/** Existing context and draft copy; shared generic labels remain in the host. */
export const GOALS_CONTEXT_EN: Record<string, string> = {
  "记录中的负责人": "Recorded owner",
  "完整范围、资料和需求覆盖": "Full scope, inputs, and requirements",
  "未设置目标值": "No target value",
  "通过条件：": "Pass when: ",
  "尚未记录范围": "Scope is not recorded yet",
  "尚未记录非目标": "Non-goals are not recorded yet",
  "暂无额外约束": "No extra constraints",
  "需要的输入": "Required inputs",
  "暂无前置输入": "No required inputs",
  "承诺的输出": "Promised outputs",
  "尚未记录输出": "Outputs are not recorded yet",
  "暂无资料绑定": "No bound materials",
  "包含范围 ": "In scope ",
  "明确不做 ": "Out of scope ",
  "条件 ID ": "Criterion ID ",
  "可选，留空自动生成": "optional, generated if empty",
  "方向还比较抽象，需要继续找到可独立交付的结果。": "The direction is still broad. Keep finding independently deliverable results.",
  "范围、输入与输出尚未填写": "Scope, inputs, and outputs are still blank",
  "还有 {count} 项未写": "{count} fields still blank",
  "Goal 名称": "Goal name",
  "怎样算通过": "What counts as pass",
  "承诺输出 ": "Promised outputs ",
  "本次修改原因": "Why this change",
  "这条 Goal 现在拆到什么程度？": "How far is this Goal split now?",
  "需要的输入 ": "Required inputs ",
  "明确这次做什么、不做什么。": "What this work includes and excludes.",
  "未完成的前置事项会阻止这条 Goal 开始。": "Incomplete prerequisites prevent this Goal from starting.",
  "完成后会得到什么": "What you will get when it is done",
  "还没有写清预期结果。": "The intended result has not been explained yet.",
  "还没有写清为什么要做。": "Why this work matters has not been explained yet.",
  "还没有写清实际使用方式。": "How this works in practice has not been explained yet.",
  "补全目标、范围和完成标准；保存后仍要经过确认才能开始。": "Complete the goal, scope, and definition of done. Saving does not start the work.",
  "这条 Goal 还没说清楚": "This Goal is not clear enough yet",
  "方案已经整理好": "The proposal is ready",
  "查看方案并决定": "Review and decide",
  "还需要补全：{gaps}。保存只会更新说明；确认后才能开始。": "Still needed: {gaps}. Saving only updates the description; approval is required before work can start.",
  "查看完成标准": "View definition of done",
  "修改目标说明和完成标准": "Edit the goal and definition of done",
  "完成标准详情": "Definition of done details",
  "每一条都要写清检查什么、怎样算通过，以及需要什么依据。": "For each item, state what to check, what passes, and what evidence is needed.",
  "添加完成标准": "Add completion criterion",
  "记录什么情况会影响推进或完成，以及准备怎样处理。": "Record what could affect progress or completion and how you plan to handle it.",
  "说明这项工作会读写哪些区域，以及影响现在是否仍然存在。": "State which areas this work reads or changes and whether the impact is still active.",
  "设置执行和检查规则": "Set execution and review rules",
  "每一条都应该能明确判断是否达到。": "Each item should have a clear yes-or-no result.",
  "达到下面的结果就算通过：": "This passes when: ",
  "还没有写清怎样才算完成。先补上可判断的完成标准，才能开始工作。": "The definition of done is missing. Add criteria that can be clearly checked before work starts.",
  "父 Goal 如何完成": "How the parent Goal completes",
  "还没有写清这次会做什么。": "What is included has not been explained yet.",
  "还没有写清这次不做什么。": "What is excluded has not been explained yet.",
  "还没有写清完成后会交付什么。": "The deliverables have not been explained yet.",
  "查看开始前需要的内容和必须遵守的限制": "View prerequisites and constraints",
  "开始前需要": "Needed before starting",
  "没有额外输入要求。": "No additional inputs are required.",
  "没有额外约束。": "No additional constraints.",
  "开始前要先完成": "Complete these first",
  "开始前不需要等待其他 Goal。": "No other Goal must finish before this one starts.",
  "已经完成，不再挡住这条 Goal。": "Completed and no longer blocking this Goal.",
  "已经拆出一部分": "Partly broken down",
  "已经有部分可以开始，但拆分工作还没有结束。": "Some work can start, but the breakdown is not finished.",
  "可以独立完成": "Can be completed independently",
  "这条 Goal 可以独立推进、独立交付，并有自己的完成标准。": "This Goal can be worked on and delivered independently, with its own definition of done.",
  "由子 Goal 共同完成": "Completed by child Goals",
  "实际运转方式": "How it works in practice",
  "目标上下文": "Goal context",
  "先扫一眼结构，再展开现在需要阅读或修改的部分。": "Scan the structure, then expand the section you need to read or change.",
  "结果、原因和实际运转方式": "Outcome, rationale, and how the Goal works in practice",
  "完成标准、工作边界、子 Goal 和前置事项": "Completion criteria, boundaries, child Goals, and prerequisites",
  "本 Goal 按当前 Contract 已满足": "This Goal satisfies its current Contract",
  "这只表示当前 Goal 自己的承诺和完成条件已满足，不自动等于父 Goal 的完整能力已经实现。": "This only means this Goal's own commitments and criteria are satisfied; it does not automatically mean the parent Goal's full capability exists.",
  "未记录父子 Contract 覆盖（历史数据）；现有完成状态不会因此被自动改写。": "No parent-child Contract coverage was recorded for this historical item; its current completion state will not be rewritten automatically.",
  "父子 Contract 覆盖": "Parent-child Contract coverage",
  "对父 Goal 的贡献": "Contribution to parent Goals",
  "这条历史父 Goal 未记录父子 Contract 覆盖；当前子 Goal 的完成不会被解释成父级完整能力。": "This historical parent Goal has no recorded Contract coverage; completing this child Goal is not treated as proof of the parent's full capability.",
  "仍需父级集成": "Parent integration required",
  "Contract 覆盖边界": "Contract coverage boundary",
  "区分当前 Goal 自己满足了什么，以及它是否覆盖父级承诺。": "Distinguish what this Goal satisfies from whether it covers its parent commitments.",
};
