/** Existing Goal create/trash/restore copy. Shared chrome remains in Workbench. */
export const GOALS_DIALOGS_EN: Record<string, string> = {
  "正在保存…": "Saving…",
  "要得到的结果 ": "The result you want ",
  "它属于哪个更大的 Goal？ ": "Which larger Goal does it belong to? ",
  "开始前必须等哪些 Goal 完成？ ": "Which Goals must finish before this can start? ",
  "恢复到 Goal Tree": "Restore to the Goal Tree",
  "恢复不会创建新 Goal，也不会自动启动 Runtime": "Restore does not create a new Goal and does not start a Runtime",
  "请先确认这条 Goal 和本次操作原因。": "Confirm this Goal and the reason for this action.",
  "未选择 Goal": "No Goal selected",
  "该操作可恢复：Goal 历史会保留，当前仍生效的关联关系会暂时停止。若这条 Goal 仍有未结束的历史活动记录，系统不会改动它，而会指出还挡着的记录。": "This can be undone. Goal history is kept, and currently active relations pause. If this Goal still has unfinished historical activity, Molis Work will not change it and will show which records still block the move.",
  "说明为什么暂时不再保留这条 Goal": "Say why this Goal should leave the everyday list for now",
  "例如 GOAL-AUTHORING": "For example GOAL-AUTHORING",
  "一句话说明要完成什么": "One sentence for what should be finished",
  "完成后，用户或系统获得什么可观察结果": "What observable result the user or system gets when it is done",
  "这个问题为什么值得现在解决": "Why this problem is worth solving now",
  "每行一条，可稍后补": "one per line, can be filled later",
  "例如：可以创建 Goal，并在左侧 Tree 中立即看到": "For example: a Goal can be created and appears in the left tree immediately",
  "它属于哪个更大的 Goal？": "Which larger Goal does it belong to?",
  "表示“它是这个 Goal 的一部分”，只决定 Tree 中放在哪里，不要求上级 Goal 先完成。": "This means “it is part of that Goal”. It only decides tree placement. The parent does not have to finish first.",
  "所属上级 Goal": "Parent Goal",
  "作为独立 Goal，不指定上级": "Stand-alone Goal, no parent",
  "开始前必须等哪些 Goal 完成？": "Which Goals must finish before this can start?",
  "只有确实要等对方完成后才能收尾时才选择。普通笔记和准备仍可先做。": "Choose this only when the other result is actually required before closing. Ordinary notes and preparation can still happen first.",
  "创建 Goal": "Create Goal",
  "请确认这条 Goal 和本次操作原因。": "Confirm this Goal and the reason for this action.",
  "请确认把这条 Goal 恢复到日常 Goal Tree。": "Confirm restoring this Goal to the everyday Goal Tree.",
  "恢复不会创建新 Goal，也不会自动启动 Runtime。系统只会恢复两端都不在回收站的关联关系；其余关系会保留为待处理事实。": "Restore does not create a new Goal and does not start a Runtime. Only relations whose both ends are out of trash are restored. The rest stay as pending facts.",
  "说明为什么现在要恢复这条 Goal": "Say why this Goal should come back now",
  "历史 Claim：": "Historical Claims: ",
  "历史 Run：": "Historical Runs: ",
  "现在无法移入回收站：这条 Goal 仍有未结束的历史活动记录。": "It cannot go to trash now: this Goal still has unfinished historical activity.",
  "这些历史活动结束后才能移入回收站。": "Those historical records must finish before it can go to trash.",
  "请说明本次操作原因。": "Give a reason for this action.",
  "Molis Work 返回了无法识别的回收站状态": "Molis Work returned an unrecognized trash state",
  "操作失败": "The action failed",
  "操作失败，请检查后重试": "The action failed. Check it and try again",
  "用简单语言说明实际使用方式和边界": "Explain the practical flow and boundaries in plain language",
  "先记录你的想法，再补全目标说明。规划可选。": "Record your idea first, then complete the goal description. Planning is optional.",
  "Goal 应描述一项有限、可验收、最终能完成的改变。": "A Goal should describe one finite, acceptable change that can ultimately be completed.",
  "能力稳定后，用普通报告记录反复出现的结果；发现问题再开有限的改进 Goal，不必把原 Goal 一直留着。": "After the capability is stable, record recurring results with ordinary reports. If a problem appears, open a finite improvement Goal instead of leaving the original unfinished.",
  "它会怎样运转 ": "How it works ",
};
