/** Existing Goal document copy; user content is never translated. */
export const GOALS_DOCUMENT_EN: Record<string, string> = {
  "回收站是空的": "Trash is empty",
  "移入回收站的 Goal 可以在这里恢复；日常 Goal Tree 不会被它们干扰。": "Goals in trash can be restored here. They will not clutter the everyday Goal Tree.",
  "还没有归档 Goal": "No archived Goal yet",
  "已完成的 Goal 可以在正文顶部手动归档，历史事实不会被删除。": "A finished Goal can be archived from the top of its document. Historical facts are not deleted.",
  "无法设为当前 Goal": "Could not set it as the current Goal",
  "已设为当前 Goal；Runtime 的执行状态没有改变": "Set as the current Goal. Runtime execution did not change",
  "关闭 {title}": "Close {title}",
  "至少保留一个打开的 Goal": "Keep at least one Goal open",
  "完成这一个决定后，页面会直接显示新的下一步。": "After this decision, the page will immediately show the new next step.",
  "满足这里列出的恢复条件后，状态会自动重新计算。": "The status will be recalculated automatically when these recovery conditions are met.",
  "从主按钮继续；已有 Run、Evidence 和 Review 都会保留。": "Continue from the primary action; existing runs, evidence, and reviews are preserved.",
  "这条 Goal 当前最需要记住的事实。": "The facts that matter most for this Goal right now.",
  "当前 Goal": "Current Goal",
  "要得到的结果：": "The result you want: ",
  "为什么做：": "Why do it: ",
  "事情如何运转：": "How it works: ",
  "当前产品聚焦 Goal；不表示 Runtime 正在执行": "This is the Board’s current focus. It does not mean a Runtime is executing it",
  "设为 Board 当前聚焦；不会领取或启动 Runtime 执行": "Set as the Board’s current focus. This does not claim or start a Runtime",
  "设为当前 Goal": "Set as current Goal",
  "Goal 的内容和完整历史都已保留。": "The Goal’s content and full history are kept.",
  "移入时仍生效的关联关系会临时停止；恢复时，只有两端都不在回收站的关系才会安全恢复。": "Active relations pause when it enters trash. On restore, only relations whose both ends are out of trash come back safely.",
  "确认恢复后，这条 Goal 会回到原来的日常列表；如果有关联仍不能安全恢复，系统会保留它们为待处理事实。": "After you confirm, this Goal returns to the everyday list. Relations that cannot be restored safely stay as pending facts.",
  "恢复这个 Goal": "Restore this Goal",
  "Goal 详情": "Goal details",
  "这些条件决定这条 Goal 是否真的完成。": "These conditions determine whether this Goal is actually complete.",
  "还没有可以判断完成的条件。": "There are no completion criteria to evaluate yet.",
  "补全完成标准后，执行和复核才有共同依据。": "Add completion criteria so execution and review share the same standard.",
  "查看全部 {count} 条要求": "View all {count} requirements",
  "查看完整要求与边界": "View full requirements and scope",
  "这条 Goal 已从日常列表移除，但内容和历史仍然保留。": "This Goal is removed from the active list, but its content and history are preserved.",
  "可以这样处理：": "How to resolve it: ",
  "归档 Goal": "Archive Goal",
  "归档这条已完成的 Goal": "Archive this completed Goal",
  "正在载入完整记录…": "Loading complete records…",
  "Goal 工作模式": "Goal work mode",
  "打开“上下文”时载入。": "Loaded when you open Context.",
  "打开“进展”时载入。": "Loaded when you open Progress.",
  "打开“关系”时载入。": "Loaded when you open Relationships.",
  "Goal 正文响应不完整": "The Goal document response is incomplete",
  "载入 Goal…": "Loading Goal…",
  "无法读取这条 Goal 正文": "Could not read this Goal document",
  "无法读取这条 Goal 的完整记录": "Could not read this Goal's complete records",
  "Goal 记录响应不完整": "The Goal records response is incomplete",
  "无法载入完整记录": "Could not load complete records",
  "无法读取更早的 Goal 记录": "Could not read earlier Goal records",
  "Goal 事件响应不完整": "The Goal event response is incomplete",
  "无法载入更早记录": "Could not load earlier records",
  "正在载入 Goal…": "Loading Goal…",
  "无法读取这个 Goal 区域": "Could not read this Goal section",
  "Goal 区域响应不完整": "The Goal section response is incomplete",
  "无法载入这个 Goal 区域": "Could not load this Goal section",
  "{message}，点击重试": "{message}. Select Retry to try again.",
  "继续已取消的目标": "Continue this cancelled Goal",
  "原完成事实和来源会保留。明确继续后开启新一轮工作。": "The original completion facts and sources stay. After an explicit continue, a new round of work starts.",
  "原完成事实保留，并开启新一轮工作。": "The original completion facts stay, and a new round of work starts.",
  "原 Goal 标准": "Original Goal standard",
  "这里保留目标已保存的原验收标准；当前结果以上方状态为准。": "This keeps the Goal’s saved original acceptance criteria. Current results follow the status above.",
  "标准编号": "Criterion ID",
  "判断方式": "Decision method",
  "目标值": "Target",
  "所需证据": "Required evidence",
  "未指定": "Not specified",
  "等待你确认的方案": "Proposals waiting for your decision",
};
