/** Existing momentum copy; user Goal titles are never translated. */
export const GOALS_MOMENTUM_EN: Record<string, string> = {
  "正在载入推进态势…": "Loading Goal momentum…",
  "无法载入推进态势": "Could not load Goal momentum",
  "推进态势响应不完整": "The Goal momentum response is incomplete",
  "打开 Goal": "Open Goal",
  "Goal 推进态势": "Goal Momentum",
  "先看推进是否流动，再决定现在做什么": "See whether work is moving, then decide what to do now",
  "时间变化、完整依赖拓扑和行动顺序共用同一份 Molis Work 事实。": "Cadence, the complete dependency topology, and action order use the same Molis Work facts.",
  "推进节奏": "Momentum cadence",
  "由子 Goal 推进": "Driven by child Goals",
  "停滞": "Stalled",
  "{title} 仍影响 {count} 个未完成下游。": "{title} still affects {count} unfinished downstream Goals.",
  "当前没有形成明显下游瓶颈的 Goal。": "No Goal currently forms a clear downstream bottleneck.",
  "停滞多于最近完成，推进节奏正在变慢。": "More Goals are stalled than recently completed, so momentum is slowing.",
  "最近完成多于启动，项目正在收口。": "Recent completions outnumber starts, so the project is converging.",
  "推进保持流动，下一步优先处理高影响节点。": "Work is moving; prioritize the highest-impact node next.",
  "近 {days} 天 Goal 推进事件": "Goal momentum events in the last {days} days",
  "{count} 个 Goal 历史不足，未计入停滞；所有数字均来自当前项目事件事实。": "{count} Goals lack enough history and are excluded from stalled counts; every number comes from current project events.",
  "所有数字均来自当前项目事件事实；停滞只统计历史足够的 Goal。": "Every number comes from current project events; stalled counts include only Goals with sufficient history.",
  "完整 Goal 依赖拓扑": "Complete Goal dependency topology",
  "{goals} 个 Goal · {edges} 条 depends_on · 从提供者向消费者展开": "{goals} Goals · {edges} depends_on edges · provider to consumer",
  "拓扑显示范围": "Topology scope",
  "全部 {count}": "All {count}",
  "未完成 {count}": "Unfinished {count}",
  "拓扑缩放": "Topology zoom",
  "无前置 / 基础输入": "No prerequisites / foundations",
  "第 {level} 层消费": "Consumption level {level}",
  "depends_on：前置提供者 → 消费者": "depends_on: prerequisite provider → consumer",
  "当前选择的一阶依赖": "Direct dependencies of the current selection",
  "分组带表达 part_of": "Bands represent part_of",
  "完成节点保留并弱化；瓶颈只是一种状态": "Completed nodes stay visible but muted; bottleneck is a state, not a filter",
  "排序只使用阻塞、推进阶段、前置与下游影响": "Order uses only blockers, execution stage, prerequisites, and downstream impact",
  "拓扑层级": "Topology level",
  "下游影响": "Downstream impact",
  "可触达 {count} 个未完成下游": "Can reach {count} unfinished downstream Goals",
  "仍在等待：{providers}": "Still waiting for: {providers}",
  "没有未满足前置": "No unmet prerequisites",
  "近 7 天有可追溯推进活动": "Has traceable activity in the last 7 days",
  "近 7 天没有可追溯推进活动": "No traceable activity in the last 7 days",
  "历史不足，不能判断是否停滞": "Not enough history to determine whether this Goal is stalled",
  "已进入执行或验收后段": "In the later execution or review stage",
  "近 7 天没有推进活动": "No momentum activity in the last 7 days",
  "当前还不能直接开始": "Cannot start directly yet",
  "影响 {count} 个未完成下游": "Affects {count} unfinished downstream Goals",
  "没有未完成下游": "No unfinished downstream Goals",
  "影响 {count} 个下游": "Affects {count} downstream Goals",
  "近 7 天停滞": "Stalled for 7 days",
  "{count} 个 Goal": "{count} Goals",
  "发现 {count} 处关系完整性问题；相关节点已保留并使用确定性降级布局。": "Found {count} relationship integrity issues; affected nodes remain visible with a deterministic fallback layout.",
  "还没有可分析的 Goal": "No Goals to analyze yet",
  "创建 Goal 并建立 depends_on 后，这里会显示完整推进拓扑和行动顺序。": "Create Goals and add depends_on relationships to see the complete momentum topology and action order here.",
  "打开推进态势时载入": "Loaded when you open Goal momentum",
  "可缩放、拖动或使用键盘浏览的完整 Goal 依赖拓扑": "Complete Goal dependency topology. Zoom, drag, or use the keyboard to explore it.",
};
