import type { PlanningMethodPack, GoalsPlanningProject, GoalsPlanningPrimitives } from "./planning-ui-model.js";
import { createPlanningPresentation } from "./planning-presentation.js";
export function createPlanningEditRenderer(primitives: GoalsPlanningPrimitives) {
    const { translate: L, escapeHtml, icon } = primitives;
    const { friendlyPlanningDependencyHint, friendlyPlanningDependencyStatement } = createPlanningPresentation(primitives);
    function renderPlanningSimpleRows(name: string, values: readonly string[], placeholder: string): string { const rows = values.length ? values : [""]; return `<div class="planning-row-list" data-planning-row-list="${name}">${rows.map((value) => `<div class="planning-edit-row" data-planning-row><input name="${name}" value="${escapeHtml(value)}" placeholder="${escapeHtml(placeholder)}"><button class="mw-btn mw-btn--ghost mw-btn--icon-only planning-remove-row" type="button" data-remove-planning-row aria-label="${L("删除这一项")}">${icon("trash")}</button></div>`).join("")}</div><button class="mw-btn mw-btn--secondary planning-add-row" type="button" data-add-planning-row="${name}">${icon("plus")}${L("添加一项")}</button>`; }
    function renderPlanningEditForm(method: PlanningMethodPack | null, saveScope: "personal" | "project", project: GoalsPlanningProject | null, apiEndpoint: string, returnHref: string): string {
        const methodId = method?.method_id ?? `custom-method-${Date.now().toString(36)}`;
        const coverage = method?.required_coverage.length ? method.required_coverage : [{ area: "", label: "", question: "" }];
        const dependencies = method?.dependency_rules.length ? method.dependency_rules : [{ rule_id: "", statement: "", direction_hint: "" }];
        return `<div class="planning-save-context">${icon(saveScope === "project" ? "folder" : "user")}<div><strong>${saveScope === "project" ? L("保存到项目「{name}」", { name: project?.display_name ?? L("当前项目") }) : L("保存到我的方法库")}</strong><p>${saveScope === "project" ? L("这个版本只影响当前项目；全局模板和其他项目不会改变。") : L("这里不设置项目。保存后，这套方法可以在各项目的工作规划中使用。")}</p></div></div><form class="planning-edit-form" data-planning-edit-form data-save-scope="${saveScope}" data-api-endpoint="${apiEndpoint}" data-return-href="${returnHref}"><div class="planning-edit-fields"><input type="hidden" name="method_id" value="${escapeHtml(methodId)}">
  <section class="planning-edit-section"><header><h2>${L("方法说明")}</h2><p>${L("先说清这套方法适合什么工作，以及它会带来什么规划结果。")}</p></header><div class="planning-edit-grid"><label>${L("方法名称")}<input name="name" required value="${escapeHtml(method?.name ?? "")}" placeholder="${L("例如：SaaS 功能发布")}"></label><label>${L("适合哪些工作")}<input name="applies_to" value="${escapeHtml(method?.applies_to.join(", ") ?? "")}" placeholder="${L("例如：新功能、系统改造、版本发布；用逗号分隔")}"></label></div><label>${L("一句话说明这套方法")}<textarea name="summary" rows="2" required placeholder="${L("例如：从用户结果反推实现、验证与发布依赖。")}">${escapeHtml(method?.summary ?? "")}</textarea></label></section>
  <section class="planning-edit-section planning-method-body"><header><h2>${L("Runtime 方法正文")}</h2><p>${L("像维护一段 Skill 一样，直接告诉 Runtime 应该怎么思考、怎么拆、如何判断依赖、怎样检查完成，以及需求变化后如何调整。")}</p></header><label>${L("完整方法说明")}<textarea name="instructions" rows="10" required placeholder="${L("写清适用边界、规划顺序、依赖方向、完成检查、常见误拆和需求变化处理。")}">${escapeHtml(method?.instructions ?? "")}</textarea><small>${L("Runtime 会在创建或调整 Goal Tree 前完整阅读这里；普通执行阶段不会反复加载。")}</small></label></section>
  <p class="planning-form-note">${L("规划路径、拆分问题和依赖判断各填写至少一项；完成与纠偏及高级设置可选。")}</p>
  <details class="planning-edit-section form-disclosure"><summary>${L("规划路径")}</summary><header><p>${L("把 Runtime 应该依次想清楚的阶段列出来。它们是规划顺序，不是强制串行的任务。")}</p></header>${renderPlanningSimpleRows("steps", method?.steps ?? [], L("例如：确认用户结果和边界"))}</details>
  <details class="planning-edit-section form-disclosure"><summary>${L("拆分时必须回答")}</summary><header><p>${L("每一项由“检查主题”和一个清晰问题组成；系统会自动处理内部标识。")}</p></header><div class="planning-row-list" data-planning-row-list="coverage">${coverage.map((rule) => `<div class="planning-edit-row planning-edit-row--structured" data-planning-row data-coverage-row><label>${L("检查主题")}<input name="coverage_label" value="${escapeHtml(rule.label)}" placeholder="${L("例如：最终结果")}"></label><label>${L("Runtime 必须回答的问题")}<textarea name="coverage_question" placeholder="${L("例如：最终交付什么、由谁使用？")}">${escapeHtml(rule.question)}</textarea></label><button class="mw-btn mw-btn--ghost mw-btn--icon-only planning-remove-row" type="button" data-remove-planning-row aria-label="${L("删除这一项")}">${icon("trash")}</button></div>`).join("")}</div><button class="mw-btn mw-btn--secondary planning-add-row" type="button" data-add-planning-row="coverage">${icon("plus")}${L("添加一个问题")}</button></details>
  <details class="planning-edit-section form-disclosure"><summary>${L("依赖判断")}</summary><header><p>${L("写清什么时候需要建立依赖，以及谁必须先完成。不要把时间上的先后误当成产出依赖。")}</p></header><div class="planning-row-list" data-planning-row-list="dependencies">${dependencies.map((rule) => `<div class="planning-edit-row planning-edit-row--structured" data-planning-row data-dependency-row><label>${L("什么时候建立依赖")}<textarea name="dependency_statement" placeholder="${L("例如：下游需要消费上游的可验收结果")}">${escapeHtml(friendlyPlanningDependencyStatement(rule.statement))}</textarea></label><label>${L("谁必须先完成")}<textarea name="dependency_direction" placeholder="${L("例如：先完成提供结果的 Goal，再开始使用它的 Goal")}">${escapeHtml(friendlyPlanningDependencyHint(rule.direction_hint))}</textarea></label><button class="mw-btn mw-btn--ghost mw-btn--icon-only planning-remove-row" type="button" data-remove-planning-row aria-label="${L("删除这一项")}">${icon("trash")}</button></div>`).join("")}</div><button class="mw-btn mw-btn--secondary planning-add-row" type="button" data-add-planning-row="dependencies">${icon("plus")}${L("添加一条依赖判断")}</button></details>
  <details class="planning-edit-section form-disclosure"><summary>${L("完成与纠偏")}</summary><header><p>${L("分别写清完成证据、收口检查和 Runtime 应避免的误拆。")}</p></header><div class="planning-edit-grid"><div><label>${L("完成前要看到的证据")}</label>${renderPlanningSimpleRows("evidence_requirements", method?.evidence_requirements ?? [], L("例如：端到端主路径的验证记录"))}</div><div><label>${L("收口前检查")}</label>${renderPlanningSimpleRows("completion_checks", method?.completion_checks ?? [], L("例如：依赖方向可以由产出消费关系解释"))}</div></div><div><label>${L("提醒 Runtime 避免什么")}</label>${renderPlanningSimpleRows("failure_modes", method?.failure_modes ?? [], L("例如：按页面或文件夹机械拆 Goal"))}</div></details>
  <details class="planning-advanced"><summary><span>${L("高级设置")}</span>${icon("chevron-down")}</summary><div class="planning-advanced-body"><div class="planning-edit-grid"><label>${L("方法类型")}<select name="kind"><option value="custom"${method?.kind === "custom" || !method ? " selected" : ""}>${L("自定义")}</option><option value="work_type"${method?.kind === "work_type" ? " selected" : ""}>${L("工作类型")}</option><option value="domain"${method?.kind === "domain" ? " selected" : ""}>${L("专业领域")}</option><option value="industry"${method?.kind === "industry" ? " selected" : ""}>${L("行业方法")}</option><option value="overlay"${method?.kind === "overlay" ? " selected" : ""}>${L("场景叠加层")}</option><option value="meta"${method?.kind === "meta" ? " selected" : ""}>${L("元方法")}</option></select><small>${L("只用于方法库分类。")}</small></label><label>${L("参考成熟度")}<input name="confidence" type="number" min="0" max="1" step="0.05" value="${method?.confidence ?? 0.8}" required><small>${L("0 到 1；不确定时保持 0.8。")}</small></label></div><label>${L("领域标签")}<input name="domain_tags" value="${escapeHtml(method?.domain_tags.join(", ") ?? "")}" placeholder="${L("用逗号分隔")}"></label><label>${L("可追溯来源")}<textarea name="source_refs" placeholder="${L("每行一个来源")}">${escapeHtml(method?.source_refs.join("\n") ?? "")}</textarea></label></div></details><label class="planning-enabled"><input name="enabled" type="checkbox"${method?.enabled === false ? "" : " checked"}><span>${L("保存后启用这套方法")}</span></label></div><p class="planning-form-error" data-planning-method-error role="alert" hidden></p><footer class="planning-edit-footer"><a class="mw-btn mw-btn--secondary" href="${returnHref}">${L("取消")}</a><button class="mw-btn mw-btn--primary" type="submit">${saveScope === "project" ? L("保存项目方法") : L("保存到我的方法库")}</button></footer></form>`;
    }
    return renderPlanningEditForm;
}
