import type { PlanningMethodPack, GoalsPlanningProject, GoalsPlanningPrimitives } from "./planning-ui-model.js";
import { createPlanningPresentation } from "./planning-presentation.js";
import { PLANNING_SETTINGS_CLIENT_SCRIPT } from "./planning-client.js";
export function createPlanningLibraryRenderer(primitives: GoalsPlanningPrimitives) {
    const { translate: L, icon, withDesktopQuery, renderPage } = primitives;
    const { planningSettingsHref, renderPlanningMethodCards } = createPlanningPresentation(primitives);
    return function renderLibrary(methods: readonly PlanningMethodPack[], contextProject: GoalsPlanningProject | null = null, desktopShell = false): string {
        const pagePath = planningSettingsHref("/settings/planning", contextProject, desktopShell);
        const returnHref = contextProject ? (desktopShell ? withDesktopQuery(`/projects/${encodeURIComponent(contextProject.project_id)}`) : `/projects/${encodeURIComponent(contextProject.project_id)}`) : (desktopShell ? withDesktopQuery("/") : "/");
        const cards = renderPlanningMethodCards(methods, "/settings/planning", contextProject, desktopShell);
        const newHref = planningSettingsHref("/settings/planning/new", contextProject, desktopShell);
        return renderPage({ title: L("规划方法"), heading: contextProject?.display_name ?? L("规划方法"), subtitle: L("规划方法库"), returnHref, pagePath,
            body: `<section class="planning-catalog"><header class="planning-page-header"><div><h1>${L("规划方法")}</h1><p>${L("这里维护 Runtime 拆分 Goal、判断依赖和检查完成证据时使用的方法。方法本身不属于某个项目；项目如何使用它，请到 Goals 列表的「工作规划」中设置。")}</p></div><a class="mw-btn mw-btn--primary" href="${newHref}">${icon("plus")}${L("新建我的方法")}</a></header><div class="planning-library-tools"><nav class="mw-toggle-group planning-filters" data-slot="toggle-group" aria-label="${L("筛选规划方法")}"><button class="mw-toggle is-current" type="button" data-planning-filter="all" aria-pressed="true">${L("全部")}</button><button class="mw-toggle" type="button" data-planning-filter="work_type" aria-pressed="false">${L("工作类型")}</button><button class="mw-toggle" type="button" data-planning-filter="domain" aria-pressed="false">${L("专业领域")}</button><button class="mw-toggle" type="button" data-planning-filter="industry" aria-pressed="false">${L("行业方法")}</button><button class="mw-toggle" type="button" data-planning-filter="overlay" aria-pressed="false">${L("场景叠加层")}</button><button class="mw-toggle" type="button" data-planning-filter="mine" aria-pressed="false">${L("我的方法")}</button></nav></div><div class="settings-body"><div class="planning-library-note">${icon("book")}<div><strong>${L("先选方法，再决定是否调整")}</strong><p>${L("点击卡片查看完整规划路径。系统模板不会被直接修改；需要调整时会创建你的个人版本。")}</p></div></div><div class="planning-card-grid">${cards}<p class="planning-filter-empty" data-planning-filter-empty hidden>${L("这个分类里还没有方法。")}</p></div></div></section>`, clientScript: PLANNING_SETTINGS_CLIENT_SCRIPT, requiresControl: false, documentComment: "<!-- THESIS: Planning methods are a browsable library, never a settings spreadsheet. OWN-WORLD: Quiet graphite surfaces, mineral-blue focus, information-rich method cards. STORY: scan the library, open one method, understand it, then decide whether to create a personal version. FIRST VIEWPORT: stable settings rail, concise library introduction, three-column method grid. FORM: established Operate settings extension. FINISH: unreviewed and undocumented is unfinished; this build ends with the finish review, the verdict, and DESIGN.md. -->" });
    };
}
