/** Existing Planning-specific copy; shared labels remain in the host catalog. */
export const GOALS_PLANNING_EN: Record<string, string> = {
  "搜索规划方法": "Search planning methods",
  "选择项目共同采用的方法。它们将用于拆分目标、检查依赖和确认完成依据。": "Choose shared methods for breaking down goals, checking dependencies, and verifying completion.",
  "这些方法共同生效。Runtime 还会根据具体 Goal 补充相关方法。": "These methods apply together. Runtime adds relevant methods for each Goal.",
  "从左侧列表点开方法，再加入这个项目。尚未添加时，Runtime 仍会按每个 Goal 的具体工作选择相关方法。": "Open a method from the list on the left, then add it to this project. Until then, Runtime selects relevant methods for each Goal.",
  "方法正文": "Method",
  "没有匹配的方法，试试其他关键词或分类。": "No matching methods. Try another search or category.",
  "方法目录": "Method directory",
  "方法列表": "Method list",

    "完成前要看到的证据": "Evidence required before completion",
    "例如：SaaS 功能发布": "For example: SaaS feature release",
    "例如：从用户结果反推实现、验证与发布依赖。": "For example: Work backward from user outcomes to implementation, verification, and release dependencies.",
    "例如：新功能、系统改造、版本发布；用逗号分隔": "For example: new feature, system change, release; separate with commas",
    "提醒 Runtime 避免什么": "What the Runtime should avoid",
    "0 到 1；不确定时保持 0.8。": "From 0 to 1; keep 0.8 if you are unsure.",
    "{steps} 个规划阶段 · {checks} 个必答问题": "{steps} planning stages · {checks} required questions",
    "这里维护 Runtime 拆分 Goal、判断依赖和检查完成证据时使用的方法。方法本身不属于某个项目；项目如何使用它，请到 Goals 列表的「工作规划」中设置。": "Maintain the methods runtimes use to decompose Goals, decide dependencies, and check completion evidence. Methods do not belong to a project; set project use from Work planning in the Goals list.",
    "先选方法，再决定是否调整": "Choose a method before adapting it",
    "点击卡片查看完整规划路径。系统模板不会被直接修改；需要调整时会创建你的个人版本。": "Open a card to see the full planning path. System templates are never edited directly; adapting one creates your personal version.",
    "这个分类里还没有方法。": "There are no methods in this category yet.",
    "Runtime 方法说明": "Runtime method instructions",
    "这是 Runtime 在拆分或调整 Goal Tree 前完整阅读的方法正文。": "The Runtime reads this complete method before decomposing or adjusting a Goal Tree.",
    "查看用于检索与检查的结构化摘要": "View structured discovery and validation summary",
    "Runtime 方法正文": "Runtime method body",
    "像维护一段 Skill 一样，直接告诉 Runtime 应该怎么思考、怎么拆、如何判断依赖、怎样检查完成，以及需求变化后如何调整。": "Write this like a Skill: tell the Runtime how to reason, decompose work, judge dependencies, verify completion, and respond to requirement changes.",
    "写清适用边界、规划顺序、依赖方向、完成检查、常见误拆和需求变化处理。": "Describe applicability, planning order, dependency direction, completion checks, common mistakes, and requirement-change handling.",
    "Runtime 会在创建或调整 Goal Tree 前完整阅读这里；普通执行阶段不会反复加载。": "The Runtime reads this in full before creating or adjusting a Goal Tree; ordinary execution does not reload it repeatedly.",
    "Runtime 会按这个思考顺序组织 Goal，但不会把它机械地当成串行任务清单。": "The Runtime uses this reasoning order to organize Goals, not as a mechanically serial task list.",
    "拆分时必须回答": "Questions decomposition must answer",
    "这些问题必须在 Goal Tree 中得到明确答案、负责人或后续处理位置。": "Each question needs a clear answer, owner, or follow-up location in the Goal Tree.",
    "只有下游真的需要消费上游结果时才建立依赖；以下规则帮助 Runtime 判断先后顺序。": "Create a dependency only when downstream work truly consumes an upstream result. These rules help the Runtime decide order.",
    "Runtime 会用证据收口工作，并避开这些常见误拆。": "The Runtime uses evidence to close work and avoid these common decomposition mistakes.",
    "没有额外证据要求": "No additional evidence required",
    "没有额外检查项": "No additional checks",
    "保存到项目「{name}」": "Save to project “{name}”",
    "保存到我的方法库": "Save to my method library",
    "这个版本只影响当前项目；全局模板和其他项目不会改变。": "This version affects only the current project. Global templates and other projects stay unchanged.",
    "这里不设置项目。保存后，这套方法可以在各项目的工作规划中使用。": "Projects are not configured here. After saving, this method can be used from each project's Work planning.",
    "先说清这套方法适合什么工作，以及它会带来什么规划结果。": "State what work this method fits and what planning result it should produce.",
    "一句话说明这套方法": "Describe this method in one sentence",
    "把 Runtime 应该依次想清楚的阶段列出来。它们是规划顺序，不是强制串行的任务。": "List the stages the Runtime should reason through. They are a planning order, not mandatory serial tasks.",
    "例如：确认用户结果和边界": "For example: confirm the user outcome and boundaries",
    "每一项由“检查主题”和一个清晰问题组成；系统会自动处理内部标识。": "Each item has a check topic and a clear question. Molis Work handles internal identifiers automatically.",
    "例如：最终结果": "For example: final outcome",
    "Runtime 必须回答的问题": "Question the Runtime must answer",
    "例如：最终交付什么、由谁使用？": "For example: what is delivered, and who will use it?",
    "写清什么时候需要建立依赖，以及谁必须先完成。不要把时间上的先后误当成产出依赖。": "State when a dependency is needed and who must finish first. Do not confuse chronological order with result consumption.",
    "什么时候建立依赖": "When to create a dependency",
    "例如：下游需要消费上游的可验收结果": "For example: downstream work consumes an accepted upstream result",
    "例如：先完成提供结果的 Goal，再开始使用它的 Goal": "For example: finish the result-providing Goal before starting the Goal that uses it",
    "添加一条依赖判断": "Add a dependency rule",
    "分别写清完成证据、收口检查和 Runtime 应避免的误拆。": "Define completion evidence, closing checks, and decomposition mistakes the Runtime should avoid.",
    "例如：端到端主路径的验证记录": "For example: validation record for the end-to-end primary path",
    "例如：依赖方向可以由产出消费关系解释": "For example: dependency direction is explained by result consumption",
    "例如：按页面或文件夹机械拆 Goal": "For example: mechanically splitting Goals by page or folder",
    "保存后启用这套方法": "Enable this method after saving",
    "只用于方法库分类。": "Used only to organize the method library.",
    "创建「{name}」的个人版本": "Create my version of “{name}”",
    "编辑「{name}」": "Edit “{name}”",
    "版本 {version}": "Version {version}",
    "系统模板不会被修改；保存后会生成你自己的版本。": "The system template stays unchanged. Saving creates your own version.",
    "按用户能理解的方式维护规划路径、必答问题和依赖判断。": "Maintain the planning path, required questions, and dependency rules in user-facing language.",
    "{steps} 个阶段 · {checks} 个问题": "{steps} stages · {checks} questions",
    "浏览完整方法库": "Browse full method library",
    "为项目「{name}」组合多套规划方法。它们会共同检查同一棵 Goal Tree，不会被机械拆成串行步骤。": "Combine multiple planning methods for project “{name}”. They review the same Goal Tree together instead of becoming a mechanical sequence of tasks.",
    "当前组合是规划下限，不是方法上限。Runtime 必须完整使用这组方法，并根据当前 Goal 的实际工作补充其他相关方法。": "The current composition is the planning floor, not the method ceiling. The Runtime must use every method in it and add other methods that materially apply to the current Goal.",
    "{count} 套方法共同生效": "{count} methods work together",
    "{count} 个覆盖项": "{count} coverage checks",
    "{count} 条依赖规则": "{count} dependency rules",
    "{count} 项完成检查": "{count} completion checks",
    "尚未建立项目规划组合": "No project planning composition yet",
    "Runtime 会先检查每个 Goal 的实际工作、专业领域、交付方式和风险，再选用所有相关方法；不预设类型或数量。你也可以把项目长期需要的方法加入组合，作为之后规划的共同基础。": "The Runtime first examines each Goal's actual work, professional domains, delivery model, and risks, then selects every relevant method without assuming a type or count. You can also add methods the project repeatedly needs as a shared planning foundation.",
    "可以继续加入多套互补方法。加入后会建立该项目的独立版本，原方法和其他项目不变。": "Add as many complementary methods as the project needs. Each addition creates a project-specific version without changing the original method or other projects.",
    "这个分类里还没有可加入的方法。": "There are no methods to add in this category.",
    "这些项目方法仍然保留，但不会参与当前组合；打开后可以重新启用。": "These project methods are preserved but do not participate in the current composition. Open one to enable it again.",
};
