/** English copy owned by the Goals work-rules surfaces. Shared shell labels remain in Workbench. */
export const GOALS_POLICY_EN: Record<string, string> = {

  "当前使用系统默认": "Using system defaults",
  "保存项目默认规则": "Save project rules",

  "项目默认工作规则保存失败": "Could not save the project default work rules",
  "项目默认工作规则保存失败，请检查输入后重试": "Could not save the project default work rules. Check the input and try again",
  "项目工作规则": "Project work rules",
  "设置这个项目里所有 Goal 共同遵守的最低要求。单个 Goal 可以增加要求，但不能降低这里的规则。": "Set the minimum requirements shared by every Goal in this project. Individual Goals can add requirements but cannot weaken these rules.",
  "这些规则什么时候生效": "When these rules take effect",
  "Goal 可以增加要求": "A Goal can add requirements",
  "项目工作规则已保存": "Project work rules saved",
  "完成前还需要哪些检查": "Checks still required before completion",
  "最后需要你确认结果。": "You need to approve the final result.",
  "不需要你的最终确认。": "Your final approval is not required.",
  "当前 Goal 额外规则": "Extra rules for this Goal",
  "已保存 · ": "Saved · ",
  "尚未单独设置，当前沿用项目默认": "Not set separately; using the project default",
  "尚未单独设置，当前使用系统默认": "Not set separately; using the system default",
  "已设置 Goal 规则": "Goal rules are set",
  "已设置项目基线": "Project baseline is set",
  "完全继承": "Fully inherited",
  "系统默认": "System default",
  "下面是当前 Goal 保存的完整规则。项目默认仍是最低门槛，不能被这里削弱。": "These are the full rules saved on this Goal. The project default remains the floor and cannot be weakened here.",
  "字段先展示继承后的当前值；只有修改并保存，才会建立这条 Goal 的单独规则。": "Fields first show the inherited current values. A Goal-specific rule is created only after you edit and save.",
  "这组规则是所有 Goal 的共同最低门槛；当前 Goal 只能在它之上增加要求。": "These rules are the shared minimum for every Goal. This Goal can only add requirements on top.",
  "当前仍使用系统默认。保存后，这组规则会成为整个项目的共同最低门槛。": "The system default is still in use. After you save, these rules become the project-wide minimum.",
  "01 · 项目默认": "01 · Project default",
  "使用系统默认": "Using system default",
  "02 · 当前 Goal": "02 · This Goal",
  "完全继承项目": "Fully inherited from the project",
  "最终生效门槛": "Effective bar",
  "用户最终确认": "Your final confirmation",
  "变更说明": "Change note",
  "旧规则会标记为已替换，历史仍保留。": "The old rule is marked replaced. History is kept.",
  "项目基线已设置": "Project baseline is set",
  "已增加单独规则": "Extra Goal rules are set",
  "用户拥有最终确认权": "You have the final confirmation",
  "当前最终生效规则": "Effective rules now",
  "上次修改原因": "Reason for the last change",
  "工作规则会进入完整记录，请说明为什么现在需要调整。": "Rule changes are kept in the full record. Explain why this adjustment is needed now.",
  "例如：这个 Goal 涉及用户数据，需要独立检查和最终确认": "For example: this Goal handles user data and needs an independent review and final approval",
  "项目默认和当前 Goal 的额外要求已经合并，实际会按下面的结果执行。": "The project defaults and this Goal's extra requirements are merged into the effective rules below.",
  "无需用户最终确认": "No final user approval required",
  "工作规则继承关系": "Work rule inheritance",
  "项目默认规则在项目设置中维护": "Project defaults are maintained in project settings",
  "这里显示合并后的结果；当前 Goal 只能增加自己的要求。": "This shows the merged result. The current Goal can only add requirements.",
  "打开项目设置": "Open project settings",
  "为当前 Goal 增加要求": "Add requirements for this Goal",
  "只作用于当前 Goal；可以继续增加要求，但不能削弱项目共同规则。": "Applies only to this Goal. You can add more requirements, but cannot weaken the project-wide rules.",
  "当前完全沿用项目规则；只有需要更严格时才在这里增加要求。": "This Goal currently follows the project rules completely. Add requirements here only when it needs stricter controls.",
  "项目共同规则已要求，当前 Goal 不能关闭": "Required by the project-wide rules and cannot be turned off for this Goal",
  "项目默认工作规则已保存": "Project default work rules saved",
  "工作规则保存失败": "Could not save the work rules",
  "工作规则保存失败，请检查输入后重试": "Could not save the work rules. Check the input and try again",
  "完成要求": "Completion requirement",
  "收尾时是否需要你确认结果。": "Whether you confirm the result before the Goal closes.",
  "所有 Goal 的共同基线；修改后影响之后的收尾。": "The baseline for every Goal; a change applies to closures from now on.",
  "保存后会与项目默认合并，在这条 Goal 收尾时检查。": "Once saved, this is merged with the project default and checked when this Goal closes.",
  "这些规则在 Goal 收尾时检查。": "These rules are checked when a Goal closes.",
  "最终生效：用户确认“{human}”。": "In effect: user confirmation \"{human}\".",
  "这个项目的共同规则已更新：用户确认“{human}”。之后收尾的 Goal 会采用这条规则。": "The project's rule was updated: user confirmation \"{human}\". Goals closed from now on follow it.",
};
