/** English copy owned by the Goals work-rules surfaces. Shared shell labels remain in Workbench. */
export const GOALS_POLICY_EN: Record<string, string> = {
  "由其他执行者检查结果与依据": "Other executors check the results and evidence",
  "独立复核人数": "Independent reviewers",
  "主动寻找遗漏、反例和错误假设": "Look for omissions, counterexamples, and incorrect assumptions",
  "反例检查人数": "Adversarial reviewers",

  "当前使用系统默认": "Using system defaults",
  "执行工具是否需要声明遵守当前目标、边界和完成标准。": "Whether tools must declare that they follow the current goal, scope, and completion criteria.",
  "设置能力要求、领取时长和独立检查人数。": "Set required capabilities, claim duration, and independent checks.",
  "说明这次调整的原因，保存后会保留在版本记录中。": "Explain this change. The reason will be kept in the version history.",
  "这些规则只约束之后开始或重新领取的工作。": "These rules apply to work started or claimed again after saving.",
  "保存项目默认规则": "Save project rules",

  "请说明为什么要调整项目默认规则。": "Explain why the project default rules need to change.",
  "独立复核人数需要是 0 或正整数。": "The independent reviewer count must be zero or a positive integer.",
  "反例检查人数需要是 0 或正整数。": "The counterexample reviewer count must be zero or a positive integer.",
  "一次领取时长需要是正整数秒数。": "The claim duration must be a positive whole number of seconds.",
  "项目默认工作规则保存失败": "Could not save the project default work rules",
  "项目默认工作规则保存失败，请检查输入后重试": "Could not save the project default work rules. Check the input and try again",
  "项目工作规则": "Project work rules",
  "设置这个项目里所有 Goal 共同遵守的最低要求。单个 Goal 可以增加要求，但不能降低这里的规则。": "Set the minimum requirements shared by every Goal in this project. Individual Goals can add requirements but cannot weaken these rules.",
  "这些规则什么时候生效": "When these rules take effect",
  "它们只约束之后开始或重新领取的工作，不会改写 Goal 内容，也不会自动启动任何执行工具。": "They apply to work that starts or is reclaimed later. They do not rewrite Goal content or start any execution tool.",
  "项目先定共同底线": "Set the project baseline",
  "例如必须自检，或完成前需要你确认": "For example, require self-verification or your approval before completion",
  "Goal 可以增加要求": "A Goal can add requirements",
  "涉及特殊风险时，可再要求额外检查": "Add extra reviews when a Goal carries special risks",
  "合并后执行": "Apply the merged rules",
  "最终按两边更严格的要求工作": "The stricter requirement from either side wins",
  "每次保存都会替换当前项目默认规则，但旧版本和修改原因会继续保留在事件记录中。": "Each save replaces the current project defaults, while older versions and change reasons remain in the event history.",
  "项目工作规则已保存": "Project work rules saved",
  "这个项目的共同规则已更新：按 Goal 工作“{mode}”，执行者自检“{self}”，用户确认“{human}”。之后开始或重新领取的 Goal 会采用这些规则。": "The shared project rules were updated: Goal-based work is “{mode}”, owner self-check is “{self}”, and user approval is “{human}”. Goals started or reclaimed later will use these rules.",
  "完成前还需要哪些检查": "Checks still required before completion",
  "推进者需要先检查自己的结果。": "The person doing the work must check their own result.",
  "不要求推进者额外自检。": "No additional self-check is required.",
  "还需要 {count} 次独立检查。": "{count} independent check(s) are still required.",
  "不要求额外的独立检查。": "No additional independent check is required.",
  "最后需要你确认结果。": "You need to approve the final result.",
  "不需要你的最终确认。": "Your final approval is not required.",
  "约 {hours} 小时": "About {hours} hours",
  "约 {minutes} 分钟": "About {minutes} minutes",
  "当前 Goal 额外规则": "Extra rules for this Goal",
  "所有 Goal 的共同基线；修改后影响后续新的领取与 Review。": "The shared baseline for every Goal. Changes affect later claims and Reviews.",
  "已保存 · ": "Saved · ",
  "尚未单独设置，当前沿用项目默认": "Not set separately; using the project default",
  "尚未单独设置，当前使用系统默认": "Not set separately; using the system default",
  "已设置 Goal 规则": "Goal rules are set",
  "已设置项目基线": "Project baseline is set",
  "完全继承": "Fully inherited",
  "系统默认": "System default",
  "下面是当前 Goal 保存的完整规则。项目默认仍是最低门槛，不能被这里削弱。": "These are the full rules saved on this Goal. The project default remains the floor and cannot be weakened here.",
  "字段先展示继承后的当前值；只有修改并保存，才会建立这条 Goal 的单独规则。": "Fields first show the inherited current values. A Goal-specific rule is created only after you edit and save.",
  "这组规则是所有 Goal 的共同最低门槛；当前 Goal 只能在它之上增加要求。": "These rules are the shared minimum for every Goal. This Goal can only add requirements on top.",
  "当前仍使用系统默认。保存后，这组规则会成为整个项目的共同最低门槛。": "The system default is still in use. After you save, these rules become the project-wide minimum.",
  "提交前必须验证": "Must verify before submitting",
  "不设自检门槛": "No self-check gate",
  "不限制能力标签": "No capability tags required",
  "01 · 项目默认": "01 · Project default",
  "使用系统默认": "Using system default",
  "02 · 当前 Goal": "02 · This Goal",
  "完全继承项目": "Fully inherited from the project",
  "最终生效门槛": "Effective bar",
  "执行者自我验证": "Executor self-check",
  "用户最终确认": "Your final confirmation",
  "变更说明": "Change note",
  "旧规则会标记为已替换，历史仍保留。": "The old rule is marked replaced. History is kept.",
  "保存后会与项目默认合并，并立即成为这条 Goal 的领取门槛。": "After save it merges with the project default and immediately becomes this Goal’s claim bar.",
  "项目基线已设置": "Project baseline is set",
  "已增加单独规则": "Extra Goal rules are set",
  "用户拥有最终确认权": "You have the final confirmation",
  "当前最终生效规则": "Effective rules now",
  "上次修改原因": "Reason for the last change",
  "开始与完成要求": "Start and completion requirements",
  "先设置最常用的三项：如何按 Goal 工作、是否自检、是否需要你最终确认。": "Start with the three common choices: Goal-scoped work, self-verification, and final user approval.",
  "执行工具是否必须按 Goal 工作": "Must the execution tool work within the Goal?",
  "按 Goal 工作时，执行工具会遵守当前目标、边界和完成标准。": "When working within a Goal, the execution tool follows its objective, boundaries, and completion criteria.",
  "高级执行与检查规则": "Advanced execution and review rules",
  "只有需要指定能力、领取时长或额外检查人数时才修改": "Change these only when you need specific capabilities, claim duration, or extra reviewers",
  "执行工具需要的能力": "Capabilities required from the execution tool",
  "一次领取最长多久": "Maximum claim duration",
  "工作规则会进入完整记录，请说明为什么现在需要调整。": "Rule changes are kept in the full record. Explain why this adjustment is needed now.",
  "例如：这个 Goal 涉及用户数据，需要独立检查和最终确认": "For example: this Goal handles user data and needs an independent review and final approval",
  "项目默认和当前 Goal 的额外要求已经合并，实际会按下面的结果执行。": "The project defaults and this Goal's extra requirements are merged into the effective rules below.",
  "按 Goal 工作": "Goal-scoped work",
  "独立检查": "Independent review",
  "无需用户最终确认": "No final user approval required",
  "一次领取最长": "Maximum claim duration",
  "需要的能力": "Required capabilities",
  "执行工具必须全部声明": "The execution tool must declare all of them",
  "工作规则继承关系": "Work rule inheritance",
  "项目默认规则在项目设置中维护": "Project defaults are maintained in project settings",
  "这里显示合并后的结果；当前 Goal 只能增加自己的要求。": "This shows the merged result. The current Goal can only add requirements.",
  "打开项目设置": "Open project settings",
  "到期后其他执行工具可以重新领取": "Other execution tools can claim it after expiry",
  "不要求": "Not required",
  "建议使用": "Recommended",
  "必须使用": "Required",
  "为当前 Goal 增加要求": "Add requirements for this Goal",
  "只作用于当前 Goal；可以继续增加要求，但不能削弱项目共同规则。": "Applies only to this Goal. You can add more requirements, but cannot weaken the project-wide rules.",
  "当前完全沿用项目规则；只有需要更严格时才在这里增加要求。": "This Goal currently follows the project rules completely. Add requirements here only when it needs stricter controls.",
  "低于项目共同规则，不能选择": "Below the project-wide rule and cannot be selected",
  "项目共同规则已要求，当前 Goal 不能关闭": "Required by the project-wide rules and cannot be turned off for this Goal",
  "项目共同规则至少要求 {count} 人": "Project-wide rules require at least {count} reviewer(s)",
  "项目已要求：{list}。这里只填写当前 Goal 额外需要的能力。": "The project already requires: {list}. Enter only the additional capabilities this Goal needs.",
  "这里只填写当前 Goal 额外需要的能力；没有可以留空。": "Enter only the additional capabilities this Goal needs; leave blank if there are none.",
  "所有能力都满足后才能开始；用逗号分隔。": "Work can start only when every capability is available. Separate them with commas.",
  "例如：浏览器操作、图像处理、数据分析": "For example: browser operation, image processing, data analysis",
  "项目最长允许 {seconds} 秒；当前 Goal 只能缩短": "The project allows at most {seconds} seconds; this Goal can only shorten it",
  "项目默认工作规则已保存": "Project default work rules saved",
  "工作规则保存失败": "Could not save the work rules",
  "工作规则保存失败，请检查输入后重试": "Could not save the work rules. Check the input and try again",
  "最终生效：按 Goal 工作“{mode}”，推进者自检“{self}”，用户确认“{human}”。": "Effective result: Goal-based work is “{mode}”, owner self-check is “{self}”, and user approval is “{human}”.",
  "{label}不能低于项目共同规则要求的 {value}。": "{label} cannot be lower than the project-wide requirement of {value}.",
  "{label}不能超过项目共同规则允许的 {value} 秒。": "{label} cannot exceed the project-wide limit of {value} seconds.",
};
