/** Existing native and historical proposal/decision copy; composed into the shared locale catalog. */
export const GOALS_PROPOSAL_EN: Record<string, string> = {
  "Runtime": "Runtime",
  "未记录": "Not recorded",
  "补充说明": "Notes",
  "可选": "optional",
  "复查：": "Revisit: ",
  "不阻塞": "Does not block",
  "已确认": "Confirmed",
  "建议": "Suggested",
  "Contract 输出": "Contract output",
  "代码引用": "Code reference",
  "测试依赖": "Test dependency",
  "业务顺序": "Business order",
  "等待决定": "Waiting for a decision",
  "已应用": "Applied",
  "已拒绝": "Rejected",
  "解除依赖": "Remove dependency",
  "新增依赖": "Add dependency",
  "未说明": "Not stated",
  "保留 Runtime 的依据和用户决定，后续事实变化时可以重新检查。": "Keeps the Runtime’s basis and your decision so later fact changes can be rechecked.",
  "拒绝关系调整不会删除已经纳入的 Goal。": "Rejecting a relation change does not delete a Goal already taken in.",
  "拒绝后现有依赖保持不变；确认后才会新增或解除依赖。": "If you reject it, current dependencies stay. They change only after you confirm.",
  "用户回答": "Your answer",
  "代码事实": "Code fact",
  "文档事实": "Document fact",
  "Runtime 推断": "Runtime inference",
  "未填写": "Not filled in",
  "当前": "Current",
  "提案": "Proposed",
  "需要自检": "Self-check required",
  "不要求自检": "No self-check required",
  "access 未记录": "access not recorded",
  "未说明原因": "Reason not stated",
  "要得到的结果": "The result you want",
  "依赖提案记录 ": "Dependency proposal history ",
  "目标名称": "Goal title",
  "新增": "Add",
  "决定提交失败": "Could not submit the decision",
  "请填写决定理由或修改意见": "Give a decision reason or revision note",
  "必填": "Required",
  "正在保存…": "Saving…",
  "需要": "Required",
  "不需要": "Not required",
  "为什么现在做": "Why do it now",
  "决定理由或修改意见": "Decision reason or revision note",
  "未记录验收条件": "No acceptance criteria recorded",
  "确认时说明判断依据；退回时写清需要修改的内容": "When confirming, say what the judgment is based on. When sending back, say what needs to change.",
  "说明为什么确认或拒绝这次关系变化": "Say why you confirm or reject this relation change",
  "说明为什么纳入；或写清退回后需要怎样调整": "Say why to take it in, or what should change if you send it back",
  "已按下方问题预填，可以直接采用，也可以改写": "Prefilled from the issues below; submit as-is or rewrite",
  "你现在需要做：点击“退回修正”。退回理由已按下方问题预填，可以直接提交，也可以改写。": "What to do now: select “Return for correction.” The return reason is prefilled from the issues below; submit it as-is or rewrite it.",
};
