/** Existing Goal relation copy; exact wording and interpolation are preserved. */
export const GOALS_RELATION_EN: Record<string, string> = {
  "只改变 Goal Tree 层级，不要求上级先完成": "Changes tree placement only; the parent does not have to finish first",
  "依赖 / 被依赖": "Depends on / depended on by",
  "左侧 Goal 必须等待右侧 Goal 完成，才具备收尾所需输入。普通笔记和准备仍可先做。": "The left Goal must wait for the right Goal to finish before it has the inputs needed to close. Ordinary notes and preparation can still happen first.",
  "两项工作无法同时成立，或会相互干扰": "The two pieces of work cannot both stand, or they interfere with each other",
  "左侧 Goal 用来降低右侧风险或负面影响": "The left Goal reduces the right-hand risk or downside",
  "左侧 Goal 在右侧结果上继续增加能力": "The left Goal adds capability on top of the right Goal’s result",
  "左侧 Goal 将取代右侧 Goal": "The left Goal will replace the right Goal",
  "左侧 Goal 修正右侧的错误或偏差": "The left Goal corrects an error or drift on the right",
  "左侧 Goal 使右侧事实或结果不再有效": "The left Goal makes the right-hand fact or result no longer valid",
  "左侧 Goal 从右侧旧实现或旧结构迁移而来": "The left Goal migrates from the right-hand older implementation",
  "说明为什么这条关系不再成立；历史记录会保留": "Say why this relation no longer holds. The history stays.",
  "暂无关系": "No relations yet",
  "上游": "Upstream",
  "这个 Goal 开始前需要什么": "What must exist before this Goal can start",
  "下游": "Downstream",
  "哪些 Goal 等待或包含它": "Which Goals wait on it or contain it",
  "其他关联": "Other links",
  "扩展、替代、修正或风险关系": "Extension, replacement, correction, or risk links",
  "已解除关系": "Removed relations",
  "条，保留方向与变更原因": "kept, with direction and reason",
  "还没有可关联的其他 Goal": "There is no other Goal to link yet",
  "先新建另一个 Goal，再回来建立层级、依赖或语义关系。": "Create another Goal first, then come back to add hierarchy, dependency, or meaning.",
  "维护关系": "Maintain relations",
  "新增关系，或在上方解除已有关系": "Add a relation, or remove one above",
  "另一个 Goal": "the other Goal",
  "提交后直接生效并写入事件历史；不会创建或启动 Runtime。": "It takes effect immediately and is written to the event ledger. No Runtime is created or started.",
  "建立关系": "Create relation",
  "关系预览：新 Goal 将作为独立 Goal 出现在 Tree 中。": "Preview: the new Goal will appear in the tree on its own.",
  "关系预览：当前没有执行前置，Goal 可以独立推进。": "Preview: there is no execution prerequisite. The Goal can move on its own.",
  "关系预览：新 Goal → 属于 → 「{name}」。这是目录层级，不需要等待它完成。": "Preview: new Goal → part of → “{name}”. This is tree placement and does not wait for it to finish.",
  "关系预览：新 Goal → 依赖 → {names}；这些 Goal 完成前，新 Goal 还不能收尾。普通笔记和准备仍可先做。": "Preview: new Goal → depends on → {names}. The new Goal cannot close until those finish. Ordinary notes and preparation can still happen first.",
  "关系方向和原因会进入事件历史": "Direction and reason enter the event history",
  "关系建立失败": "Could not create the relation",
  "关系解除失败": "Could not remove the relation",
  "请选择关系类型": "Choose a relationship type",
  "当前 Goal → {type} → {name}": "Current Goal → {type} → {name}",
  "{name} → {type} → 当前 Goal": "{name} → {type} → Current Goal",
  "你正在直接修改 Goal 关系": "You are directly editing Goal relationships",
  "保存后立即生效并进入历史。执行工具提出的关系变化仍会先进入": "Changes made here take effect immediately and are recorded. Relationship changes proposed by execution tools still go to ",
  "Inbox": "Inbox",
  "，由你确认后才生效。": " and take effect only after you confirm them.",
  "这条关系表示什么": "What does this relationship mean?",
  "当前 Goal 开始前需要它完成": "The current Goal needs it to finish first",
  "当前 Goal 属于它": "The current Goal is part of it",
  "它开始前需要当前 Goal 完成": "It needs the current Goal to finish first",
  "它属于当前 Goal": "It is part of the current Goal",
  "其他关系": "Another relationship",
  "另一个 Goal 完成前，当前 Goal 还不能收尾。普通笔记和准备仍可先做。": "The current Goal cannot close until the other Goal is done. Ordinary notes and preparation can still happen first.",
  "为什么需要这条关系": "Why is this relationship needed?",
  "写清两条 Goal 为什么需要这样关联，方便之后判断关系是否仍然成立": "Explain why these Goals need this relationship so it can be reassessed later",
  "查看准确方向和关系类型": "View exact direction and relationship type",
  "只有上面的常用选项不适用时才需要修改": "Change these only when the common choices above do not fit",
  "当前 Goal → 另一个 Goal": "Current Goal → other Goal",
  "另一个 Goal → 当前 Goal": "Other Goal → current Goal",
  "准确关系类型": "Exact relationship type",
  "当前 Goal 的关系": "the current Goal relationship",
  "关系已建立": "Relationship created",
  "已建立：{relation}。准确方向和建立原因已进入完整记录。": "Created: {relation}. The exact direction and reason are saved in the full record.",
  "关系建立失败，请检查目标、方向和原因": "Could not create the relationship. Check the Goal, direction, and reason.",
  "请填写解除原因。说明这条关系为什么不再成立。": "Explain why this relationship no longer applies.",
  "关系已解除": "Relationship removed",
  "与「{goal}」的关系已停止生效；原方向和解除原因仍保留在完整记录中。": "The relationship with “{goal}” is no longer active. Its original direction and removal reason remain in the full record.",
  "关系解除失败，请检查解除原因后重试": "Could not remove the relationship. Check the reason and try again.",
};
