/** Existing Risk/Impact copy; wording and interpolation remain unchanged. */
export const GOALS_SAFETY_EN: Record<string, string> = {
  "为什么现在记录": "Why record this now?",
  "说明这项风险为什么需要现在进入 Goal 记录": "Explain why this risk needs to be added to the Goal now",
  "保存后会回到当前 Goal，并保留在完整记录中。": "After saving, you will return to the current Goal and the entry will remain in its full record.",
  "保存后会参与并行工作冲突判断。": "After saving, it will be used to detect conflicts between concurrent work.",
  "只有必须由你接受或拒绝的风险才会出现在待决定中。": "Only risks that require your acceptance or rejection appear in Decisions.",
  "缓解": "mitigates",
  "规避": "Avoid",
  "阻止领取": "Blocks claiming",
  "触发后失效": "Invalidates when triggered",
  "当前不再使 Goal 失效；若此前触发，关联 Goal 必须重新验证。": "It no longer invalidates the Goal. If it triggered earlier, linked Goals must be revalidated.",
  "当前状态不再施加领取或完成门禁。": "The current state no longer gates claiming or completion.",
  "当前会阻止所有关联 Goal 被标记为完成。": "It currently blocks every linked Goal from being marked done.",
  "这是一条持续观察的事实，不直接阻塞领取或完成。": "This is a watched fact. It does not directly block claiming or completion.",
  "这是历史事实。当前可以记录事实、查看要求，或阅读原始历史。": "This is a historical fact. You can record facts, inspect current requirements, or read the original history.",
  "受影响 Goal": "Affected Goals",
  "按名称或 ID 筛选": "Filter by name or ID",
  "发生概率": "Likelihood",
  "低 / 中 / 高，或量化概率": "Low / medium / high, or a numeric chance",
  "受影响区域": "Affected surfaces",
  "概率 / 影响": "Likelihood / impact",
  "当前影响": "Current effect",
  "当前 Goal 会写入该区域；其他写入会冲突，读取方必须固定输入快照。": "The current Goal writes this surface. Other writes conflict, and readers must pin an input snapshot.",
  "当前 Goal 只读取该区域，并已固定输入快照，可与写入方并行推进。": "The current Goal only reads this surface and has pinned an input snapshot, so it can proceed in parallel with writers.",
  "为什么需要更新影响区域、访问方式或状态": "Why the surface, access, or state needs to change",
  "风险": "Risks",
  "受影响区域 ": "Affected surfaces ",
  "筛选{label}的受影响 Goal": "Filter affected Goals for {label}",
  "{count} 个已选择 · 至少选择一个": "{count} selected · pick at least one",
  "{count} 项": "{count} items",
  "{count} 项生效": "{count} active",
  "{count} 项历史": "{count} in history",
  "条 · 仍可查看原事实和停用原因": "kept · original facts and deactivation reason remain readable",
  "记录影响范围": "Record affected areas",
  "影响范围": "Affected areas",
  "什么时候重新判断": "When to reassess",
  "风险已发生，所有关联 Goal 立即失效。": "The risk has occurred, so every linked Goal is invalidated immediately.",
  "风险仍待处理；一旦标记为已经发生，所有关联 Goal 会失效。": "The risk remains pending. If it is marked as occurred, every linked Goal will be invalidated.",
  "为什么需要更新这项风险或它关联的 Goal": "Explain why this risk or its linked Goals need to be updated",
  "去待决定处理这个风险": "Handle this risk in Decisions",
  "用一句话写清可能出现的问题": "Describe the possible problem in one sentence",
  "会造成什么影响": "What impact would it have?",
  "例如：无法按时完成、结果不可信或会影响其他 Goal": "For example: a delay, an unreliable result, or an impact on another Goal",
  "什么时候算已经发生": "How will you know it has happened?",
  "写一个可以观察到的触发条件": "Describe an observable trigger",
  "例如：方案确认后、开始执行前或某个结果出现时": "For example: after the approach is confirmed, before work starts, or when a specific result appears",
  "补充判断、处理与责任": "Triggers, treatment, and ownership",
  "保存前还需要说明触发与复查条件，并选择负责人和它是否阻塞 Goal": "Before saving, define the trigger and reassessment conditions, assign an owner, and set whether it blocks a Goal",
  "谁负责持续关注或处理": "Who will monitor or handle it?",
  "可以是流程、文档、系统、团队或代码区域": "A workflow, document, system, team, or code area",
  "新风险": "New risk",
  "处理方式 / 对 Goal 的影响": "Treatment / effect on the Goal",
  "这是一条只读记录；请到“目标与要求 → 风险”修改当前事实。": "This record is read-only. Edit it under Goal and requirements → Risks.",
  "修改风险信息": "Edit risk details",
  "修改风险事实不会同时改变处理状态。": "Editing risk details does not change its treatment status.",
  "保存风险信息": "Save risk details",
  "会影响哪里": "What will be affected?",
  "可以是流程、文档、系统、团队、数据或代码区域": "A workflow, document, system, team, dataset, or code area",
  "为什么会影响这里": "Why will this area be affected?",
  "说明这条 Goal 会在这里做什么，以及为什么需要记录": "Explain what this Goal will do here and why it needs to be recorded",
  "补充影响方式": "How it will be affected",
  "保存前需要明确会读取、修改、决策还是独占": "Before saving, specify whether this Goal reads, changes, decides, or exclusively controls it",
  "会怎么影响": "How will it be affected?",
  "这条记录是否已确认": "Has this record been confirmed?",
  "固定的输入版本 ": "Pinned input version ",
  "可选；只读取时可用文件版本或事实引用固定输入": "Optional. For read-only work, pin the input with a file version or fact reference",
  "例如 commit://abc123、文档版本或 Goal 引用": "For example commit://abc123, a document version, or a Goal reference",
  "这是一条只读记录；请到“目标与要求 → 影响范围”修改当前事实。": "This record is read-only. Edit it under Goal and requirements → Impact scope.",
  "修改影响范围": "Edit impact scope",
  "修改会进入变更历史；已停用记录不会原地恢复。": "Changes are recorded in history. An inactive record cannot be reactivated in place.",
  "保存影响范围": "Save impact scope",
  "记录可能影响推进或完成的情况，并说明什么时候需要重新判断。": "Record conditions that may affect progress or completion, and when to reassess them.",
  "当前没有已记录的风险。只有确实需要观察、处理或阻止完成的情况才需要添加。": "No risks are recorded. Add one only when something truly needs monitoring, treatment, or a completion gate.",
  "记录风险": "Record a risk",
  "先写清可能发生什么，再设置它如何影响 Goal": "Describe what might happen, then set how it affects the Goal",
  "为什么现在需要记录这项风险": "Why does this risk need to be recorded now?",
  "新风险默认处于“开放”状态。": "A new risk starts in the open state.",
  "说明这条 Goal 会读取、修改或决定哪些区域，以及是否会和其他工作冲突。": "Record what this Goal reads, changes, or decides, and whether that conflicts with other work.",
  "当前没有已记录的影响范围。需要协调多人、多 Goal 或共享资源时再添加。": "No impact scope is recorded. Add one when people, Goals, or shared resources need coordination.",
  "说明影响哪里、会做什么以及为什么": "Describe what is affected, what will happen there, and why",
  "已确认的影响范围会参与并行工作冲突判断。": "Confirmed impact scopes are used to detect conflicts between concurrent work.",
  "接受风险": "Accept risk",
  "当前会阻止新的执行工具领取所有关联 Goal。": "This currently prevents new execution tools from claiming any linked Goal.",
  "例如：先限制导入范围，让用户逐条确认，再允许同步到其他执行工具": "For example: limit imports first, let the user confirm each item, then allow syncing to other execution tools",
  "这条记录只作为历史保留，不再参与工作冲突判断。": "This record remains only as history and no longer participates in work-conflict checks.",
  "这条记录尚未确认，不会阻止其他工作开始。": "This record is not confirmed and will not prevent other work from starting.",
  "当前 Goal 独占该区域；其他正在进行的 Goal 不能同时读取、修改或作出决定。": "The current Goal has exclusive use of this area. Other in-progress Goals cannot read, modify, or decide here at the same time.",
  "当前 Goal 会在该区域作出决定；其他正在进行的 Goal 如果也读取、修改或决策，会发生冲突。": "The current Goal makes decisions in this area. Other in-progress Goals conflict if they also read, modify, or decide here.",
  "当前 Goal 只读取该区域，但未固定输入版本；同一区域正在进行的修改会阻止领取。": "The current Goal only reads this area but has no fixed input version. In-progress changes to the same area prevent claiming.",
  "停用后不再参与工作冲突判断，但原记录和停用原因会保留在历史中。": "After deactivation, it no longer participates in work-conflict checks, but the original record and reason remain in history.",
  "说明这条影响范围为什么不再有效": "Explain why this impact scope is no longer valid",
  "未记录解决依据（历史数据）；这条状态不会被自动改写。": "No resolution basis was recorded for this historical item; its state will not be rewritten automatically.",
  "没有已知剩余缺口": "No known residual gaps",
  "请至少选择一条受影响的 Goal": "Select at least one affected Goal",
  "风险记录失败，请检查输入后重试": "Could not record the risk. Check the input and try again",
  "风险更新失败，请检查输入后重试": "Could not update the risk. Check the input and try again",
  "影响范围记录失败": "Could not record the impact scope",
  "影响范围记录失败，请检查输入后重试": "Could not record the impact scope. Check the input and try again",
  "影响范围更新失败": "Could not update the impact scope",
  "影响范围更新失败，请检查输入后重试": "Could not update the impact scope. Check the input and try again",
  "已记录风险「{description}」。它现在保持待处理；需要确认处理结果时，请到待决定。": "Risk “{description}” was recorded and remains pending. Use Decisions when its outcome needs confirmation.",
  "已更新风险「{description}」。这次修改没有改变它的处理结果。": "Risk “{description}” was updated. Its handling outcome did not change.",
  "已记录「{surface}」。它已绑定当前 Goal，并按保存的确认状态参与工作冲突判断。": "Recorded “{surface}”. It is linked to the current Goal and participates in work-conflict checks according to its saved confirmation state.",
  "已更新「{surface}」。旧值和修改说明已进入完整记录。": "Updated “{surface}”. The previous values and change note are saved in the full record.",
  "请填写停用原因。说明这条影响范围为什么不再有效。": "Explain why this impact scope is no longer valid.",
  "「{surface}」不再参与工作冲突判断；原记录和停用原因仍会保留。": "“{surface}” no longer participates in work-conflict checks. Its original record and deactivation reason remain available.",
  "影响范围停用失败，请检查停用原因后重试": "Could not deactivate the impact scope. Check the reason and try again.",
};
