/** Existing Goal state, action and factors copy; shared labels stay in the host catalog. */
export const GOALS_STATUS_EN: Record<string, string> = {
  "重新核对目标覆盖": "Recheck Goal coverage",
  "处理待确认事项": "Review pending decisions",
  "接受或拒绝风险": "Accept or reject risk",
  "下一步已经明确：{action}": "Next: {action}",
  "工作已经开始，当前进度和结果会继续保留": "Work is in progress; its progress and results are preserved.",
  "Runtime 能做的部分已经结束，现在轮到你决定": "The Runtime has finished its part. It is now your decision.",
  "正在等待前置结果，满足后会自动继续计算": "Waiting for prerequisite results; the status will update automatically when they are ready.",
  "当前没有安全的继续动作，请先处理状态异常": "There is no safe next action yet. Resolve the status issue first.",
  "{title} 已满足当前要求": "{title} meets the current requirements",
  "Runtime 能完成的检查已经结束，现在只剩你本人操作、判断或确认的完成标准。": "Runtime-checkable review is complete. Only the criteria that require your own action, judgment, or confirmation remain.",
  "完成真实操作并提交验收决定": "Complete the real action and submit your acceptance decision",
  "在待决定中提交你的判断；如果完成标准要求验收依据，也一并登记真实操作结果。": "Open this Goal to submit your judgment. If the criterion requires acceptance evidence, record the real result there as well.",
  "等待子 Goal": "Waiting for child Goals",
  "这条 Goal 还只是草稿，现在不能开始执行。": "This Goal is still a draft and cannot be started yet.",
  "补全并确认这条 Goal": "Complete and approve this Goal",
  "说明想要的结果、工作范围和怎样才算完成。": "Describe the intended result, scope, and what done means.",
  "现有子 Goal 都完成了，但父 Goal 仍标记为尚未拆完，所以不会自动完成。": "The current child Goals are complete, but this parent is still marked as not fully decomposed, so it will not complete automatically.",
  "确认当前拆分是否完整": "Confirm whether the decomposition is complete",
  "如果这些子 Goal 已覆盖整个目标，就确认由它们共同完成；否则继续补充遗漏的子 Goal。": "If these child Goals cover the whole parent, confirm that they jointly complete it. Otherwise, add the missing child Goals.",
  "方案已经整理好，采用前仍保留原草稿，暂时不能开始。": "The proposal is ready. The original draft remains unchanged until you approve it, so work cannot start yet.",
  "查看并决定这份方案": "Review and decide on this proposal",
  "在待决定中查看会改什么，然后选择采用或退回修改。": "Open this Goal to review what will change, then approve it or send it back for revision.",
  "这条 Goal 正在补全关键信息，还没有成为可执行工作。": "Key details are still being added, so this Goal is not executable yet.",
  "继续回答关键问题": "Answer the remaining key question",
  "补上仍会影响结果、范围或完成标准的信息。": "Add the information that still affects the result, scope, or completion criteria.",
  "缺少必要信息或决定，所以暂时不能完成目标说明。": "Required information or a decision is missing, so the goal cannot be finalized yet.",
  "先解决目标说明的卡点": "Resolve the goal clarification blocker",
  "查看被挡住的原因，再补信息或完成对应决定。": "Review the blocker, then add the missing information or make the required decision.",
  "这项工作由子 Goal 共同完成，不直接执行这个上层 Goal。": "Child Goals complete this work together; the parent Goal is not executed directly.",
  "选择一个可以开始的子 Goal": "Choose a child Goal that can start",
  "进入具体子 Goal，查看它的下一步并从那里打开终端。": "Open a specific child Goal, review its next step, and open a terminal there.",
  "目标和完成标准已经确认，现在可以开始推进。": "The goal and completion criteria are approved, so work can start.",
  "开始推进这条 Goal": "Start work on this Goal",
  "在这条 Goal 下打开终端，或让 Runtime 领取后开始工作。": "Open a terminal under this Goal, or let a Runtime claim and start it.",
  "已经有人或 Runtime 在处理这条 Goal。": "A person or Runtime is working on this Goal.",
  "继续当前工作，或查看最近结果、卡点和完成依据。": "Continue the work, or review the latest result, blockers, and completion evidence.",
  "当前有未解决的依赖、风险或决定，工作不能继续。": "An unresolved dependency, risk, or decision is blocking the work.",
  "先解除当前阻塞": "Resolve the current blocker",
  "查看具体原因，完成前置工作或处理等待你的决定。": "Review the cause, complete the prerequisite, or make the waiting decision.",
  "执行、完成依据和所需复核都已完成，不需要重新执行。": "Execution, completion evidence, and required reviews are finished; this Goal does not need to run again.",
  "让 Runtime 直接重试完成判定；不要重新领取或重复执行这条 Goal。": "Have the Runtime retry the completion check directly; do not claim or execute this Goal again.",
  "工作和复核已经完成，但仍有完成门禁没有解除。": "The work and reviews are complete, but a completion gate is still unresolved.",
  "查看具体风险或决定，按恢复条件处理后再运行完成判定；不要重新执行。": "Review the specific risk or decision, satisfy its recovery condition, and run the completion check again; do not re-execute.",
  "工作结果已经提交，但还没有完成所需检查。": "The result was submitted, but the required checks are not complete.",
  "检查结果是否达到完成标准": "Check whether the result meets the completion criteria",
  "对照完成标准和已有依据，提交通过或需要修改的结论。": "Compare the result with the criteria and evidence, then submit pass or needs changes.",
  "检查者正在判断结果是否达到完成标准。": "A reviewer is checking whether the result meets the completion criteria.",
  "等待或继续完成检查": "Wait for or complete the check",
  "查看检查进展；如果由你检查，就对照标准提交结论。": "Review the check progress. If you are the reviewer, compare the result with the criteria and submit a verdict.",
  "当前缺少检查所需的结果、依据或检查者。": "The check is missing a result, evidence, or reviewer.",
  "补齐检查需要的内容": "Provide what the check needs",
  "查看具体卡点，补交结果或依据，再重新检查。": "Review the blocker, provide the missing result or evidence, and check again.",
  "依赖、风险或目标事实发生了变化，旧结论不能直接沿用。": "A dependency, risk, or goal fact changed, so the earlier conclusion cannot be reused as-is.",
  "重新确认这条 Goal 仍然成立": "Check that this Goal still holds",
  "检查变化后的目标、依赖、风险和已有依据。": "Review the changed goal, dependencies, risks, and existing evidence.",
  "当前正在核对变化是否影响这条 Goal 和已有结果。": "The current check is determining whether changes affect this Goal or its existing result.",
  "完成变化后的核对": "Complete the change review",
  "提交新的核对依据，说明这条 Goal 是否仍然有效。": "Submit updated evidence and state whether this Goal is still valid.",
  "缺少核对变化所需的信息、依赖结果或风险处理。": "Information, a dependency result, or risk treatment needed for the new check is missing.",
  "补齐重新确认需要的内容": "Provide what the new check needs",
  "查看具体卡点，先补信息或处理关联事项。": "Review the blocker, then provide the missing information or handle the related item.",
  "新的事实已经让这条 Goal 或已有结果失效。": "New facts have invalidated this Goal or its existing result.",
  "查看失效原因并决定后续处理": "Review why it became invalid and choose what to do next",
  "确认发生了什么，再创建替代工作或恢复成立条件。": "Confirm what changed, then create replacement work or restore the required conditions.",
  "用户已经确认由另一条 Goal 接替这项工作；旧 Contract 和历史仍保留，但不再允许 Runtime 领取。": "The user confirmed that another Goal takes over this work. The old Contract and history remain, but Runtime can no longer claim it.",
  "转到替代 Goal 继续": "Continue with the replacement Goal",
  "查看 Goal 关系中的替代方并推进新版；只有用户撤销替代关系后，旧 Goal 才会重新开放。": "Open the replacement shown in Goal relations and continue with the new version. The old Goal reopens only after the user removes the replacement relation.",
  "完成标准和所需检查已经满足。": "The completion criteria and required checks have been met.",
  "查看结果或归档这条 Goal": "View the result or archive this Goal",
  "确认结果不再需要日常关注后，可以把它归档。": "Archive it when the result no longer needs day-to-day attention.",
  "按需要恢复这条 Goal": "Restore this Goal if needed",
  "确认仍要继续这项工作后，把它恢复到 Goal Tree。": "Restore it to the Goal Tree when you decide to continue the work.",
  "这条 Goal 已完成并退出日常工作列表，完整记录仍然保留。": "This Goal is complete and outside the active list; its full record is preserved.",
  "查看结果或恢复到日常列表": "View the result or restore it to the active list",
  "通常不需要操作；需要继续关注时再恢复。": "No action is usually needed. Restore it when it needs active attention again.",
  "父 Goal 已自动完成": "Parent Goal completed automatically",
  "所有子 Goal 都已完成，这条父 Goal 也已自动完成。": "All child Goals are complete, so this parent Goal completed automatically.",
  "子 Goal 完成后自动完成": "Completes automatically after its child Goals",
  "还剩 {count} 个子 Goal；全部完成后，这条父 Goal 会自动完成。": "{count} child Goal(s) remain. This parent Goal will complete automatically when all of them are done.",
  "父级 Contract 仍有覆盖缺口": "Parent Contract still has coverage gaps",
  "现有子 Goal 的完成数量不足以证明父级承诺已经实现；部分覆盖或仍需父级集成时，这条父 Goal 不会自动完成。": "The number of completed child Goals does not prove that the parent promise has been delivered. This parent Goal will not complete automatically while coverage is partial or still requires parent-level integration.",
  "现有子 Goal 已完成，父目标待确认": "Current child Goals are done; confirm the parent",
  "当前列出的子 Goal 都完成了，但拆分还没有确认结束。先确认它们是否已经覆盖整个父目标。": "All currently listed child Goals are done, but the decomposition has not been confirmed as complete. First confirm whether they cover the whole parent Goal.",
  "当前拆分尚未确认结束": "The decomposition is not confirmed complete",
  "先推进现有子 Goal；完成后仍要确认是否还有遗漏，父 Goal 不会自动完成。": "Continue the current child Goals first. Afterward, confirm whether anything is missing; the parent Goal will not complete automatically yet.",
  "父子结构需要确认": "Parent-child structure needs confirmation",
  "这条 Goal 被标记为可以独立完成，却同时包含子 Goal。先确认它应作为叶子，还是改为由子 Goal 共同完成。": "This Goal is marked as independently completable but also has child Goals. Confirm whether it should remain a leaf or be completed jointly by its child Goals.",
  "这条 Goal 有待你确认的当前事件决定。": "This Goal has a current event decision waiting for you.",
  "作出决定": "Make the decision",
  "在这条 Goal 的事件记录里提交你的判断。": "Submit your judgment in this Goal's event record.",
  "按当前约定记录事实。": "Record facts against the current agreement.",
  "记录进展": "Record progress",
  "继续记录事实、进展或决定。": "Keep recording facts, progress, or decisions.",
  "可记录，尚不可完成": "Can record; not ready to close",
  "仍有会挡住收尾的 Concern。": "A Concern still blocks closing this Goal.",
  "处理 Concern": "Handle the Concern",
  "先处理挡住收尾的事项，再按当前约定继续。": "Resolve what blocks closing, then continue against the current agreement.",
  "可记录": "Ready to record",
  "这条 Goal 可以按当前约定记录事实。": "This Goal can record facts against the current agreement.",
  "开始记录": "Start recording",
  "在这条 Goal 下记录事实或规划事件类型。": "Record facts or plan event types under this Goal.",
  "已完成": "Completed",
  "这条 Goal 已有明确完成结论。": "This Goal already has an explicit completion conclusion.",
  "查看结果或归档": "View the result or archive",
  "如需继续，打开「继续此目标」并填写原因。": "To continue, open Continue this Goal and give a reason.",
  "已取消": "Cancelled",
  "这条 Goal 已取消，不会被普通记录自动恢复。": "This Goal is cancelled and ordinary records will not reopen it.",
  "显式继续": "Resume explicitly",
  "继续前必须打开「显式继续」并填写原因。": "Before continuing, open Resume explicitly and give a reason.",
  "回收站": "Trash",
  "这条 Goal 已从日常列表移除，但内容和历史仍然保留。": "This Goal was removed from the active list; its content and history remain.",
  "正在推进": "In progress",
  "查看会影响这条 Goal 的关系、风险、范围和完成规则；需要时再修改。": "Review relationships, risks, scope, and completion rules that affect this Goal. Edit them only when needed.",
  "说明这条 Goal 属于什么、依赖什么，以及会影响哪些其他 Goal。": "See what this Goal belongs to, depends on, and which other Goals it affects.",
  "只记录确实需要观察或处理、并可能改变推进结果的情况。": "Record only conditions that need monitoring or treatment and may change the outcome.",
  "帮助多人或多个 Goal 判断哪些工作能并行，哪些会互相影响。": "Help people and Goals understand what can run in parallel and what may conflict.",
  "说明执行和完成前需要哪些检查；项目默认与当前 Goal 的额外要求会合并生效。": "Define checks required before work starts or finishes. Project defaults and Goal-specific requirements are merged.",
  "归属、依赖和对其他 Goal 的影响": "Hierarchy, dependencies, and effects on other Goals",
  "仍可能改变推进或完成结果的情况": "Conditions that may still change progress or completion",
  "并行工作之间的读取、修改和决定范围": "Read, write, and decision boundaries across parallel work",
  "执行、检查和完成前必须遵守的规则": "Rules for execution, review, and completion",
};
