/** Existing Goal state, action and factors copy; shared labels stay in the host catalog. */
export const GOALS_STATUS_EN: Record<string, string> = {
  "等待子 Goal": "Waiting for child Goals",
  "按需要恢复这条 Goal": "Restore this Goal if needed",
  "确认仍要继续这项工作后，把它恢复到 Goal Tree。": "Restore it to the Goal Tree when you decide to continue the work.",
  "这条 Goal 已完成并退出日常工作列表，完整记录仍然保留。": "This Goal is complete and outside the active list; its full record is preserved.",
  "查看结果或恢复到日常列表": "View the result or restore it to the active list",
  "通常不需要操作；需要继续关注时再恢复。": "No action is usually needed. Restore it when it needs active attention again.",
  "这条 Goal 有待你确认的当前事件决定。": "This Goal has a current event decision waiting for you.",
  "作出决定": "Make the decision",
  "在这条 Goal 的事件记录里提交你的判断。": "Submit your judgment in this Goal's event record.",
  "按当前约定记录事实。": "Record facts against the current agreement.",
  "记录进展": "Record progress",
  "继续记录事实、进展或决定。": "Keep recording facts, progress, or decisions.",
  "可记录，尚不可完成": "Can record; not ready to close",
  "仍有会挡住收尾的 Concern。": "A Concern still blocks closing this Goal.",
  "处理 Concern": "Handle the Concern",
  "先处理挡住收尾的事项，再按当前约定继续。": "Resolve what blocks closing, then continue against the current agreement.",
  "可记录": "Ready to record",
  "这条 Goal 可以按当前约定记录事实。": "This Goal can record facts against the current agreement.",
  "开始记录": "Start recording",
  "在这条 Goal 下记录事实或规划事件类型。": "Record facts or plan event types under this Goal.",
  "已完成": "Completed",
  "这条 Goal 已有明确完成结论。": "This Goal already has an explicit completion conclusion.",
  "查看结果或归档": "View the result or archive",
  "如需继续，打开「继续此目标」并填写原因。": "To continue, open Continue this Goal and give a reason.",
  "已取消": "Cancelled",
  "这条 Goal 已取消，不会被普通记录自动恢复。": "This Goal is cancelled and ordinary records will not reopen it.",
  "显式继续": "Resume explicitly",
  "继续前必须打开「显式继续」并填写原因。": "Before continuing, open Resume explicitly and give a reason.",
  "回收站": "Trash",
  "这条 Goal 已从日常列表移除，但内容和历史仍然保留。": "This Goal was removed from the active list; its content and history remain.",
  "正在推进": "In progress",
  "说明这条 Goal 属于什么、依赖什么，以及会影响哪些其他 Goal。": "See what this Goal belongs to, depends on, and which other Goals it affects.",
  "说明执行和完成前需要哪些检查；项目默认与当前 Goal 的额外要求会合并生效。": "Define checks required before work starts or finishes. Project defaults and Goal-specific requirements are merged.",
  "归属、依赖和对其他 Goal 的影响": "Hierarchy, dependencies, and effects on other Goals",
  "执行、检查和完成前必须遵守的规则": "Rules for execution, review, and completion",
  // plugins/native/goals/src/factors-ui.ts
  "查看会影响这条 Goal 的关系和完成规则；需要时再修改。": "Review the relationships and completion rules that affect this Goal. Edit them only when needed.",
};
