/** Existing Goal Tree copy; shared short labels remain in the host catalog. */
export const GOALS_TREE_EN: Record<string, string> = {
  "回收站 · Molis Work": "Trash · Molis Work",
  "已归档 Goal · Molis Work": "Archived Goals · Molis Work",
  "受阻 {count}": "{count} blocked",
  "当前没有进行中的 Goal": "No Goal is in progress",
  "可恢复；历史与关联处理记录会保留": "Recoverable; history and relation handling stay",
  "可随时恢复": "Can be restored any time",
  "在回收站内搜索": "Search in trash",
  "在已归档 Goal 中搜索": "Search archived Goals",
  "在当前 Goal Tree 内搜索": "Search this Goal Tree",
  "搜索回收站": "Search trash",
  "搜索已归档 Goal": "Search archived Goals",
  "搜索 Goal": "Search Goals",
  "目标列表": "Goal list",
  "没有符合当前筛选条件的 Goal。": "No Goal matches the current filters.",
  "清除所有筛选": "Clear all filters",
  "共 {count} 个{suffix}目标": "{count} {suffix}Goals",
  "显示 {shown} / {total} 个{suffix}目标": "Showing {shown} / {total} {suffix}Goals",
  "已选择 {count} 种状态": "{count} statuses selected",
  "筛选目标，已选择 {count} 种状态": "Filter Goals, {count} statuses selected",
  "打开依赖": "Open the dependency",
  "按状态筛选": "Filter by status",
  "可同时选择多个状态；会与关键词搜索一起生效。": "Select more than one status. Filters work together with search.",
  "Goal 状态": "Goal status",
  "当前没有可筛选的 Goal。": "There is no Goal to filter.",
  "显示全部状态": "Showing every status",
  "它还要等 {names}": "It still needs {names}",
  "已完成，不再挡住": "Done, no longer blocking",
  "查看 {count} 个前置依赖": "View {count} prerequisites",
  "{count} 个前置": "{count} prerequisites",
  "{count} 个阻塞": "{count} blocked",
  "{count} 个未完成": "{count} incomplete",
  "{done}/{total} 完成": "{done}/{total} done",
  "{done}/{total} 完成，{blocked} 个阻塞": "{done}/{total} done, {blocked} blocked",
  "返回 Goal Tree": "Return to Goal Tree",
  "查看已归档 Goal": "View archived Goals",
  "折叠全部": "Collapse all",
};
