/** Copy for the Goal canvas and integrated workspace. User titles remain untouched. */
export const GOALS_WORKSPACE_EN: Record<string, string> = {
  "Goal 信息": "Goal info",
  "更多 Goal 操作": "More Goal actions",
  "记录模板": "Record templates",
  "返回记录模板": "Back to record templates",
  "使用记录模板": "Use a record template",
  "记一笔": "Add entry",
  "随手备注": "Note",
  "同步进展": "Progress update",
  "保存想法或补充事实，不发给 AI": "Save thoughts or facts without messaging AI",
  "更新做到哪了、下一步做什么": "Update where things stand and what comes next",
  "记录或处理影响完成的问题": "Log or resolve issues affecting completion",
  "{done}/{total} 已满足": "{done}/{total} satisfied",
  "待明确": "Not defined",
  "现在做到哪了": "Where things stand",
  "保存进展": "Save progress",
  "更新 Goal 信息中的当前进展，并把这次更新留在时间线。": "Update the progress shown in Goal info and save this update to the timeline.",
  "记录需要跟进的问题，或更新已有问题的处理结果。": "Log an issue to follow up on, or update how an existing issue was handled.",
  "只在时间线留下一笔。要让 AI 继续工作，请到 Runtime 中发送指令。": "Save a note to the timeline. To continue work with AI, send instructions in Runtime.",
  "Goal 工作区": "Goal workspace",
  "工作区": "Workspace",
  "目标工作区": "Goal workspace",
  "关系画布": "Relationship canvas",
  "Goal 关系画布": "Goal relationship canvas",
  "目标关系": "Goal relationships",
  "收起 Goal，返回关系画布": "Collapse Goal and return to the canvas",
  "调整工作区和时间线宽度": "Resize workspace and timeline",
  "工作区 {left}%，时间线 {right}%": "Workspace {left}%, timeline {right}%",
  "展开 Goal：{title}": "Open Goal: {title}",
  "打开 Frame": "Open Frame",
  "打开 Frame：{title}": "Open Frame: {title}",
  "还没有写清预期结果": "Expected result has not been defined",
  "属于：{title}": "Part of: {title}",
  "{count} 个目标 · 箭头从前置成果指向后续工作": "{count} Goals · Arrows lead from prerequisites to the work that uses them",
  "部分关系不完整，已保留可读取的目标。": "Some relationships are incomplete. Available Goals are still shown.",
  "拖动空白处移动画布，方向键平移，加减键缩放": "Drag the background or use arrow keys to pan; use plus and minus to zoom",
  "还没有目标": "No Goals yet",
  "创建第一条 Goal，从想要的结果开始。": "Create your first Goal, starting with the result you want.",
  "拖动空白处 · 点击目标展开": "Drag to pan · Click a Goal to open",
  "画布缩放": "Canvas zoom",
  "适应全部目标": "Fit all Goals",
  "正在读取目标关系…": "Loading Goal relationships…",
  "无法读取目标关系，请重试。": "Could not load Goal relationships. Please retry.",
  "目标关系响应不完整，请重试。": "The Goal relationship response was incomplete. Please retry.",
  "记录设置": "Record settings",
  "返回记录设置": "Back to record settings",
  "目标与要求": "Goal and requirements",
  "添加记录": "Add record",
  "备注": "Note",
  "保存记录": "Save record",
  "保存到时间线，不会发送给 AI，也不会更改完成要求。": "Saves to the timeline. This does not send a message to AI or change completion requirements.",
  "更新进展": "Update progress",
  "记录问题": "Record an issue",
  "完成要求：{done}/{total} 当前满足": "Requirements: {done}/{total} currently supported",
  "当前要求支持情况": "Current requirement support",
  "完成要求待明确 · 不影响开始工作": "Completion requirements need clarification · Work can begin",
  "{count} 项待你确认": "{count} awaiting your decision",
  "返回工作区": "Back to workspace",
  "记录决定": "Record a decision",
  "检查并收尾": "Check and close",
  "待开始": "Not started",
  "待继续": "Ready to continue",
  "继续工作": "Continue work",
  "开始工作": "Start work",
  "处理问题": "Resolve issues",
  "摘要待更新": "Summary needs an update",
  "打开终端开始工作，或添加一条记录。": "Open a terminal to work, or add a record.",
  "问题与风险": "Issues and risks",
  "已有问题": "Existing issues",
  "接受风险前需要一条覆盖该范围的用户决定。": "Accepting a risk requires a user decision covering its scope.",
  "请说明影响哪项要求、哪条事件或哪个动作。": "Specify the affected requirement, event, or action.",
  "保存问题": "Save issue",
  "问题范围": "Issue scope",
  "当前没有待处理问题。": "No issues currently need attention.",
  "接受这些风险": "Accept these risks",
  "驳回这些问题": "Reject these issues",
  "问题待处理": "Issue needs attention",
  "问题已解决": "Issue resolved",
  "风险已接受": "Risk accepted",
  "问题判断已撤销": "Issue finding overturned",
  "待你决定": "Needs your decision",
  "已处理": "Handled",
  "重试读取事件": "Retry loading event",
  "无法读取更早记录，请重试。": "Could not load earlier records. Please retry.",
};
