export const IMAGES_EN: Record<string, string> = {
  "图片": "Images",
  "新建图片": "New image",
  "生成记录": "Generation history",
  "刷新": "Refresh",
  "这里会留下当前项目的图片与生成记录。": "Images and generation history for this project will appear here.",
  "返回生成记录": "Back to generation history",
  "管理服务": "Manage services",
  "把想法变成图片": "Turn an idea into an image",
  "选择生图服务，写下画面、风格和细节。": "Choose an image service and describe the scene, style, and details.",
  "先连接一个生图服务。密钥加密保存在这台电脑，配置可跨项目使用。": "Connect an image service first. Keys are encrypted on this computer, and connections are shared across projects.",
  "连接生图服务": "Connect an image service",
  "生图服务与模型": "Service and model",
  "描述你想要的图片": "Describe your image",
  "例如：清晨的书桌，一杯咖啡和翻开的书，阳光从左侧照入，胶片摄影，暖色调。": "For example: A desk at dawn, coffee and an open book, sunlight from the left, film photography, warm tones.",
  "图片尺寸（可选）": "Image size (optional)",
  "留空使用厂商默认，如 1024x1024 或 2K": "Provider default if empty, e.g. 1024x1024 or 2K",
  "可用尺寸由所选服务与模型决定。": "Supported sizes depend on the selected service and model.",
  "宽高比（可选）": "Aspect ratio (optional)",
  "留空使用厂商默认，如 1:1 或 16:9": "Provider default if empty, e.g. 1:1 or 16:9",
  "点击生成将调用所选服务，费用由该厂商按实际用量收取。": "Generating an image calls the selected provider, which may charge for usage.",
  "生成图片": "Generate image",
  "请先选择一个项目，再生成图片。": "Select a project before generating an image.",
  "生成结果": "Generation result",
  "管理生图服务": "Manage image services",
  "关闭": "Close",
  "服务配置在这台电脑共享。兼容接入需要厂商支持下列协议。": "Connections are shared on this computer. Custom services must support one of these API formats.",
  "已保存的服务": "Saved services",
  "添加服务": "Add service",
  "编辑服务": "Edit service",
  "服务模板": "Service preset",
  "自定义兼容服务": "Custom compatible service",
  "服务名称": "Service name",
  "API 协议": "API format",
  "API 基址": "API base URL",
  "模型名称": "Model name",
  "输入密钥；本地无鉴权服务可留空": "Enter a key; leave empty for local services without authentication",
  "密钥只写入本机加密存储，不会出现在历史记录中。": "Keys are kept in encrypted local storage and never included in generation history.",
  "添加另一服务": "Add another service",
  "保存服务": "Save service",
  "生成中": "Generating",
  "已生成": "Generated",
  "生成失败": "Generation failed",
  "已停止本机等待": "Local waiting stopped",
  "已中断": "Interrupted",
  "图片服务请求失败": "Image service request failed",
  "正在提交…": "Submitting…",
  "使用这个提示词": "Reuse this prompt",
  "正在等待服务生成图片，可以离开此页后再回来查看。": "Waiting for the service to generate an image. You can leave this page and return later.",
  "本机已停止等待，远端请求可能仍在生成和计费。": "Local waiting has stopped. The provider may still process and charge for the request.",
  "上次生成因本机服务重启而中断。没有自动重新调用厂商。": "The local service restarted and interrupted this request. It was not automatically submitted again.",
  "服务没有返回图片。请检查连接、模型与提示词。": "The service returned no image. Check the connection, model, and prompt.",
  "停止本机等待不能保证厂商停止处理或计费。": "Stopping local waiting does not guarantee the provider stops processing or charging.",
  "正在停止…": "Stopping…",
  "停止本机等待": "Stop local waiting",
  "可以复用提示词，调整服务配置后再次生成。再次生成会发起新的请求。": "Reuse the prompt and adjust the connection to try again. Generating again submits a new request.",
  "图片暂时无法读取，请刷新记录后重试。": "The image could not be loaded. Refresh the history and try again.",
  "下载图片": "Download image",
  "宽高比": "Aspect ratio",
  "图片尺寸": "Image size",
  "无法读取生成记录": "Could not load generation history",
  "可点击刷新重试。": "Use Refresh to try again.",
  "暂时无法更新进度，恢复连接后会继续读取。": "Progress is temporarily unavailable. Updates will resume when the connection recovers.",
  "修改 API 基址或协议后，请重新填写密钥。": "Re-enter the key after changing the API base URL or format.",
  "已保存密钥。留空保留现有密钥。": "A key is saved. Leave empty to keep it.",
  "正在保存…": "Saving…",
  "服务已保存。可以开始生成图片。": "Service saved. You can now generate an image.",
  "保存服务失败": "Could not save service",
  "提交结果未确认。再次点击生成会复用同一请求，避免重复创建任务。": "Submission was not confirmed. Generating again reuses the same request to avoid creating a duplicate job.",
  "连接生图 API，生成、预览和下载图片。": "Connect an image API to generate, preview, and download images.",
};
