/** Work-owned terminal strings. Workbench composes them into its existing locale runtime. */
export const WORK_EN: Record<string, string> = {
  "推进这个 Goal": "Advance this Goal",
  "复制命令": "Copy command",
  "命令已复制到剪贴板": "Command copied to the clipboard",
  "填入不发送": "Fill without sending",
  "重新打开": "Reopen",
  "添加终端": "Add terminal",
  "关闭终端": "Close terminal",
  "收起终端": "Collapse terminal",
  "展开终端": "Expand terminal",
  "未安装": "Not installed",
  "需要先安装 CLI": "Install the CLI first",
  "以下 CLI 未安装：{list}。安装后刷新页面即可使用。": "These CLIs are not installed: {list}. Install them, then refresh the page to use them.",
  "自定义命令": "Custom command",
  "终端已退出": "Terminal exited",
  "终端已退出（退出码 {code}）": "Terminal exited (exit code {code})",
  "终端进程已退出": "Terminal process exited",
  "退出码": "Exit code",
  "进程在启动后立即退出，常见原因：命令未安装、不在 PATH 中或工作目录不存在。": "The process exited immediately after starting. Common causes: the command is not installed, missing from PATH, or the working directory does not exist.",
  "没有终端。点右上角「添加终端」在这个 Goal 上打开 TUI。": "No terminal yet. Use Add terminal in the top-right to open a TUI on this Goal.",
  "还没有终端": "No terminal yet",
  "点右上角「添加终端」，在这个 Goal 上打开常用 Runtime 或自定义命令。": "Use Add terminal in the top-right to open a common Runtime or a custom command on this Goal.",
  "请选择要打开的 TUI": "Choose a TUI to open",
  "在这个 Goal 上打开终端": "Open a terminal on this Goal",
  "标签只属于当前 Goal。打开不会自动发送或领取。": "This tab belongs only to the current Goal. Opening it does not send a prompt or claim the work.",
  "参数": "Arguments",
  "工作目录": "Working directory",
  "继续会话 ID": "Resume session ID",
  "继续会话 ID（可选）": "Resume session ID (optional)",
  "终端面板": "Terminal pane",
  "调整终端宽度": "Resize terminal",
  "调整终端宽度，双击收起": "Resize the terminal. Double-click to collapse",
  "打开项目后，Goal 右侧可以添加终端": "After opening a project, add a terminal to the right of the Goal",
  "打开项目后，Goal 详情右侧会出现终端栏。点「添加终端」即可在当前 Goal 上打开 TUI。": "After you open a project, a terminal pane appears on the right of the Goal. Use Add terminal to open a TUI on the current Goal.",
  "打开失败": "Could not open",
  "桌面终端通道不可用，请从 Molis Work App 打开。": "The desktop terminal channel is unavailable. Open this page from the Molis Work App.",
  "正在启动终端…": "Starting terminal…",
  "正在连接终端…": "Connecting to the terminal…",
  "正在重新连接终端…": "Reconnecting to the terminal…",
  "终端已连接": "Terminal connected",
  "已回到正在运行的终端": "Reconnected to the running terminal",
  "终端进程已不在，可重新打开": "The terminal process is gone. You can reopen it.",
  "打开终端需要先把这个项目关联到一个工作目录": "Associate this project with a working directory before opening a terminal",
  "终端": "Terminal",
  "终端通道连接失败": "Could not connect to the terminal",
  "终端通道已断开": "The terminal connection dropped",
  "本地终端通道校验失败": "Local terminal channel check failed",
  "初始化提示已填入 Terminal": "The setup prompt was filled into the Terminal",
  "初始化提示已填入，检查后再发送。": "The setup prompt is filled in. Review it before sending.",
  "正在打开初始化终端…": "Opening the setup terminal…",
  "终端没有成功打开；你可以从右上角再次选择 Runtime。": "The terminal did not open. You can choose a Runtime again from the top-right.",
  "可查看": "Available",
  "路径正常": "Path is valid",
  "路径缺失": "Path is missing",
  "关联冲突": "Association conflict",
  "原生内容": "Native content",
  "Molis Work 记录": "Molis Work record",
  "不可读取": "Unreadable",
  "未选择当前 Goal": "No current Goal selected",
  "执行与内容": "Execution and content",
  "新建 Session": "New Session",
  "搜索标题、ID、Goal": "Search title, ID, or Goal",
  "搜索 Sessions": "Search Sessions",
  "筛选": "Filter",
  "全部 Runtime": "All Runtimes",
  "全部内容": "All content",
  "最早更新": "Oldest first",
  "标题 A–Z": "Title A–Z",
  "Sessions 列表": "Sessions list",
  "没有匹配结果": "No matching results",
  "这个项目还没有 Session": "This project has no Session yet",
  "共": "Total",
  "条": "items",
  "按需读取最近执行": "Load recent execution on demand",
  "读取 Molis Work 执行记录": "Read Molis Work execution records",
  "Molis Work 会分页读取原 Runtime 的最近摘要，并合并本地 TUI 记录；超大历史不会整条载入。": "Molis Work paginates recent summaries from the original Runtime and merges local TUI records. Large histories are not loaded in full.",
  "只读取 Molis Work 已持久化并能证明的 TUI 与执行事实。": "Only TUI and execution facts that Molis Work has persisted and can prove are read.",
  "读取内容": "Load content",
  "这个 Runtime 不能读取 Session 内容": "This Runtime cannot read Session content",
  "Molis Work 只显示已确认的 Session ID、项目、Goal 和工作目录，不猜测执行过程。": "Molis Work only shows confirmed Session ID, project, Goal, and workspace. It does not guess the execution process.",
  "历史关联": "Previously linked",
  "还没有 Goal 关系": "No Goal relationship yet",
  "可以在关系管理中选择当前 Goal。": "Choose the current Goal in relationship management.",
  "最近更新 {time}": "Updated {time}",
  "这个 Runtime 不能原生加载这条 Session，可使用 Handoff 创建新 Session": "This Runtime cannot natively load this Session. Use Handoff to create a new one.",
  "加载原 Session": "Load original Session",
  "请先为 Session 选择当前 Goal": "Choose a current Goal for this Session first",
  "创建 Handoff": "Create Handoff",
  "Molis Work 执行记录": "Molis Work execution records",
  "执行内容": "Execution content",
  "当前适配器没有内容读取能力。": "The current adapter cannot read content.",
  "按时间查看最近的用户、Runtime 与工具记录。": "Browse recent user, Runtime, and tool records in time order.",
  "搜索本次执行": "Search this execution",
  "搜索当前 Session 内容": "Search current Session content",
  "筛选执行事件": "Filter execution events",
  "全部事件": "All events",
  "工具与审批": "Tools and approvals",
  "当前内容中没有匹配结果。": "No matching results in the current content.",
  "Session 上下文": "Session context",
  "续跑使用这些已确认事实。": "Resume uses these confirmed facts.",
  "管理关系": "Manage relationships",
  "未选择": "Not selected",
  "去 Goals": "Go to Goals",
  "内容来源": "Content source",
  "关联历史": "Link history",
  "{count} 次": "{count} times",
  "身份与能力边界": "Identity and capability boundary",
  "只负责 PTY 所有权": "Owns PTY only",
  "只用于弱能力兼容": "Used only for weaker-capability compatibility",
  "恢复记录": "Restore record",
  "归档记录": "Archive record",
  "这个项目还没有已知运行位置。": "This project has no known run location yet.",
  "Session 的运行位置": "Where this Session runs",
  "不关联工作目录": "No linked workspace",
  "运行时不绑定本地路径": "No local path is bound at runtime",
  "选择工作目录": "Choose a workspace",
  "仍可创建 Session，之后再补充关系": "You can still create the Session and add the relationship later",
  "选择其他目录": "Choose another directory",
  "输入这台电脑上的绝对路径": "Enter an absolute path on this computer",
  "其他目录": "Other directory",
  "关联已有 Session": "Link existing Session",
  "从当前项目启动一条新的 Runtime Session。": "Start a new Runtime Session from the current project.",
  "创建新的 Runtime Session": "Create a new Runtime Session",
  "暂不关联 Goal": "Do not link a Goal yet",
  "Session 标题": "Session title",
  "可选；留空使用 Goal 或 Runtime 标题": "Optional; leave blank to use the Goal or Runtime title",
  "Runtime 原生 Session ID": "Native Runtime Session ID",
  "输入 ID，或先同步可发现记录": "Enter an ID, or sync discoverable records first",
  "同步可发现记录": "Sync discoverable records",
  "确认使用以上 Goal、Runtime 和工作目录启动新 Session。": "Confirm starting a new Session with the Goal, Runtime, and workspace above.",
  "启动 Session": "Start Session",
  "管理 Session 关系": "Manage Session relationships",
  "每条 Session 同时只有一个 Project 和一个当前 Goal。": "Each Session has one Project and one current Goal at a time.",
  "当前 Project": "Current Project",
  "目标 Project": "Target Project",
  "移出当前 Project": "Remove from current Project",
  "不设置当前 Goal": "Do not set a current Goal",
  "留空表示解除工作目录关系": "Leave empty to unlink the workspace",
  "切换 Goal 会保留旧 Goal 历史；转移或移出 Project 会清空当前 Goal。": "Switching Goal keeps the old Goal in history. Moving or removing the Project clears the current Goal.",
  "确认只更新这条 Session 的关系。": "Confirm updating only this Session's relationships.",
  "保存关系": "Save relationships",
  "创建 Goal Handoff": "Create Goal Handoff",
  "先审阅交接内容，再创建一条全新的目标 Session。": "Review the handoff content, then create a brand-new target Session.",
  "Handoff 目标": "Handoff target",
  "来源 Session": "Source Session",
  "目标 Runtime": "Target Runtime",
  "目标工作目录": "Target workspace",
  "可选；请输入绝对路径": "Optional; enter an absolute path",
  "确认使用上面的 Runtime、Project、Goal 和工作目录创建新 Session，并发送右侧内容。": "Confirm creating a new Session with the Runtime, Project, Goal, and workspace above, and send the content on the right.",
  "取消这次 Handoff": "Cancel this Handoff",
  "交接内容": "Handoff content",
  "内容由当前 Goal Contract 与最小 Session 上下文生成，可以直接修改。": "Generated from the current Goal Contract and the smallest Session context. You can edit it.",
  "草稿": "Draft",
  "可编辑的 Handoff package": "Editable Handoff package",
  "正在生成 Handoff package...": "Generating Handoff package…",
  "稍后继续": "Continue later",
  "保存草稿": "Save draft",
  "创建并发送": "Create and send",
  "归档 Session 记录": "Archive Session record",
  "只整理 Molis Work 记录，不删除或关闭 Runtime 原生内容。": "This only organizes the Molis Work record. It does not delete or close native Runtime content.",
  "影响": "Impact",
  "执行内容、运行位置与续跑": "Execution content, run location, and resume",
  "请输入这台电脑上的绝对路径": "Enter an absolute path on this computer",
  "把一条已存在的 Runtime Session 收入当前项目。": "Bring an existing Runtime Session into the current project.",
  "关联已有 Runtime Session": "Link an existing Runtime Session",
  "改为启动新 Session": "Switch to starting a new Session",
  "确认只为已有 Session 写入当前 Project、Goal 和工作目录关系。": "Confirm writing only the current Project, Goal, and workspace relationships for this existing Session.",
  "会请求所选 Runtime 创建一条新的原生 Session；不会自动发送消息。": "The selected Runtime will be asked to create a new native Session. No message is sent automatically.",
  "这个 Runtime 没有原生创建接口，将建立 Molis Work 托管记录，不伪装成已启动 Runtime。": "This Runtime has no native create interface. Molis Work will create a hosted record and will not pretend a Runtime has started.",
  "可以先同步 Runtime 元数据；只有提交后才会关联当前 Project。": "You can sync Runtime metadata first. It is linked to the current Project only after you submit.",
  "这个 Runtime 不支持发现列表，请粘贴原生 Session ID；Molis Work 不读取正文。": "This Runtime does not support a discovery list. Paste a native Session ID. Molis Work does not read the body.",
  "关联 Session": "Link Session",
  "这个 Runtime 不支持 Session 列表发现，请直接输入原生 Session ID。": "This Runtime does not support Session list discovery. Enter a native Session ID directly.",
  "正在同步 Session 元数据；不会读取正文。": "Syncing Session metadata. The body is not read.",
  "未命名 Session": "Untitled Session",
  "已同步 {count} 条元数据。选择或输入 Session ID 后再确认加入。": "Synced {count} metadata records. Choose or enter a Session ID, then confirm.",
  "Runtime 当前没有返回可发现的 Session。": "The Runtime returned no discoverable Sessions.",
  "正在创建并登记 Session...": "Creating and registering the Session…",
  "正在关联这条 Session...": "Linking this Session…",
  "切换或清空当前 Goal 会把旧 Goal 保留为历史。": "Switching or clearing the current Goal keeps the old Goal in history.",
  "转移到另一个 Project 时会清空当前 Goal，并保留原 Goal 历史。": "Moving to another Project clears the current Goal and keeps the previous Goal history.",
  "移出当前 Project 后，这条 Session 会从本目录消失；原 Runtime 内容不会删除。": "After leaving the current Project, this Session disappears from this directory. Native Runtime content is not deleted.",
  "正在保存这条 Session 的关系...": "Saving this Session's relationships…",
  "恢复 Session 记录": "Restore Session record",
  "从默认活跃记录中整理为已归档；仍可筛选和恢复。": "Move it from the default active list to archived. You can still filter and restore it.",
  "恢复为可查看记录；所有关系和历史保持不变。": "Restore it as an available record. Relationships and history stay unchanged.",
  "确认只归档 Molis Work 记录，不删除 Runtime 内容。": "Confirm archiving only the Molis Work record. Runtime content is not deleted.",
  "确认恢复这条 Molis Work Session 记录。": "Confirm restoring this Molis Work Session record.",
  "正在归档记录...": "Archiving the record…",
  "正在恢复记录...": "Restoring the record…",
  "Runtime 原生": "Runtime native",
  "Molis Work TUI · 部分终端记录": "Molis Work TUI · partial terminal records",
  "时间未知": "Unknown time",
  "Runtime 内容读取失败": "Could not read Runtime content",
  "还没有可显示的执行内容": "No execution content to show yet",
  "这个 Runtime 没有内容读取能力，Molis Work 也还没有持久化的 TUI 记录。": "This Runtime cannot read content, and Molis Work has no persisted TUI records yet.",
  "Session 身份与关系已经保留，产生执行记录后会显示在这里。": "Session identity and relationships are kept. Execution records will appear here after they exist.",
  "为保证稳定性，这里显示最近 {count} 轮的摘要；更早记录仍保留在原 Runtime。": "To stay stable, this shows summaries of the latest {count} turns. Earlier records remain in the original Runtime.",
  "已安全读取这条 Session 的 {count} 轮摘要；大体积工具输出会由原 Runtime 收拢。": "Safely read {count} turn summaries from this Session. Large tool output stays with the original Runtime.",
  "退出码 {code}": "Exit code {code}",
  "已批准": "Approved",
  "已拒绝": "Denied",
  "已结束": "Ended",
  "执行事件": "Execution event",
  "查看变更": "View changes",
  "展开输出": "Expand output",
  "查看详情": "View details",
  "没有附加输出。": "No additional output.",
  "正在读取执行内容": "Reading execution content",
  "正在联系原 Runtime，并加载 Molis Work 已保存的 TUI 记录。": "Contacting the original Runtime and loading TUI records Molis Work already saved.",
  "Session 内容读取失败": "Could not read Session content",
  "内容读取失败": "Could not read content",
  "正在请求原 Runtime 加载这条 Session...": "Asking the original Runtime to load this Session…",
  "Runtime 加载失败": "Runtime failed to load",
  "原 Runtime 已加载这条 Session，可以继续执行。": "The original Runtime loaded this Session. You can continue.",
  "选择当前 Goal": "Choose current Goal",
  "先选择当前 Goal": "Choose a current Goal first",
  "没有当前 Goal 时不能创建 Handoff，也不能把这条记录当作可续跑的执行。": "Without a current Goal, this Session cannot create a Handoff or be treated as a resumable run.",
  "Session 续跑": "Session continuation",
  "全部": "All",
  "对话": "Conversation",
  "工具": "Tools",
  "状态": "Status",
  "产物": "Artifacts",
  "更多": "More",
  "关系": "Relations",
  "关闭关系": "Close relations",
  "Session 关系": "Session relations",
  "{message} 可以使用“创建 Handoff”交给新的目标 Session。": "{message} You can use Create Handoff to hand it to a new target Session.",
  "Session 操作失败，请重试": "The Session action failed. Try again.",
  "发送中": "Sending",
  "等待重试": "Waiting to retry",
  "已发送": "Sent",
  "目标 Session 已经创建。可以修改交接正文并重试，但目标 Runtime 和工作目录不会再改变。": "The target Session already exists. You can edit the handoff text and retry, but the target Runtime and workspace will not change again.",
  "会创建一条新的原生 Session，并把右侧内容作为第一条消息发送；不会加载来源 Runtime 的原生身份。": "A new native Session will be created, and the content on the right will be sent as the first message. The source Runtime's native identity is not loaded.",
  "这个 Runtime 没有原生 Handoff Adapter。Molis Work 会创建托管 Session 并保存交接内容，不伪装成原生送达。": "This Runtime has no native Handoff adapter. Molis Work will create a hosted Session and save the handoff content. It will not pretend native delivery happened.",
  "重试发送": "Retry send",
  "不能重试": "Cannot retry",
  "正在生成": "Generating",
  "正在读取当前 Goal Contract 和最小 Session 上下文...": "Reading the current Goal Contract and the smallest Session context…",
  "另一条发送请求仍在执行。Molis Work 已锁定这份 package，完成或租约过期后再刷新。": "Another send request is still running. Molis Work has locked this package. Refresh after it finishes or the lease expires.",
  "上次失败不能安全重试。请取消这次 Handoff 后重新创建。": "The last failure cannot be retried safely. Cancel this Handoff and create it again.",
  "已恢复上次未发送的 package。修改后可保存或继续发送。": "Restored the last unsent package. You can edit it, save, or continue sending.",
  "package 已生成但尚未发送。请审阅目标组合和正文。": "The package is generated but not sent. Review the target combination and the text.",
  "生成失败": "Generation failed",
  "正在保存草稿...": "Saving draft…",
  "草稿已保存在本机；尚未创建或联系目标 Runtime。": "Draft saved on this device. The target Runtime has not been created or contacted.",
  "这次 Handoff 已取消，没有创建目标 Session。": "This Handoff was cancelled. No target Session was created.",
  "正在把修改后的 package 补发到已经创建的目标 Session...": "Resending the edited package to the target Session that already exists…",
  "正在创建新的目标 Session 并发送 package...": "Creating a new target Session and sending the package…",
  "目标 Runtime 没有完成 Handoff，package 已保留。": "The target Runtime did not finish the Handoff. The package is kept.",
  "新原生 Session 已创建，Handoff 已作为第一条消息发送。": "A new native Session was created, and the Handoff was sent as the first message.",
  "新的 Molis Work 托管 Session 已创建；package 已保存为可读取内容。": "A new Molis Work-hosted Session was created. The package was saved as readable content.",
};
