/** Artifact application copy; Workbench supplies the request locale. */
export const ARTIFACT_EN: Record<string, string> = {
  "此项目未启用该插件": "This plugin is not enabled for this project",
  "Coding 固定变更": "Coding saved changes",
  "Coding 执行报告": "Coding execution reports",
  "在 Coding 打开原报告与会话": "Open the original report and task in Coding",
  "在 Coding 查看固定变更并返回原任务": "Read saved changes and return to the original task in Coding",
  "这是保存时的文本审查，包含未执行提案；不代表当前文件状态或目标验收。": "These saved text reviews include proposals that were not applied. They do not represent current files or Goal acceptance.",
  "输入结果": "Input result",
  "产出结果": "Output result",
  "关联结果": "Linked results",
  "明确关联的 Artifact 版本；查看不会改变 Goal 或 Evidence。": "Explicitly linked Artifact versions. Viewing them does not change Goals or Evidence.",
  "关联的版本不可用或不存在。引用仍然保留，不会替换成最新版本。": "The linked version is unavailable or missing. Its reference is retained; the latest version will not be substituted.",
  "没有兼容插件。可打开这个版本查看信息或导出本地副本。": "No compatible plugin. Open this version to inspect its information or export a local copy.",
  "插件发布的结果与版本": "Results and versions published by plugins",
  "还没有 Artifact": "No Artifacts yet",
  "Goal 交付": "Goal delivery",
  "Feed 捕获": "Feed capture",
  "Artifact 版本": "Artifact versions",
  "内容不可用": "Content unavailable",
  "找不到这个 Artifact 版本": "Artifact version not found",
  "选择一个结果版本": "Choose a result version",
  "它可能属于其他项目，或这个版本尚未发布。请返回列表选择；不会自动替换成最新版本。": "It may belong to another project, or this version has not been published. Return to the list to choose a version; the latest version will not be substituted.",
  "返回 Artifact 列表": "Back to Artifact list",
  "返回项目目录": "Back to project directory",
  "这个版本的内容不可用；引用和来源信息仍然保留。": "This version's content is unavailable. Its reference and source information are retained.",
  "这个版本已归档，保留历史信息，不作为可消费的新结果。": "This version is archived. Its history is retained, but it is not offered as a consumable new result.",
  "没有兼容插件。当前可查看版本信息和原始 JSON，或导出本地副本。": "No compatible plugin. You can inspect version information and raw JSON, or export a local copy.",
  "没有兼容插件。当前可查看版本信息和内容引用，或导出本地副本。": "No compatible plugin. You can inspect version information and the content reference, or export a local copy.",
  "已有兼容的类型声明；具体操作由消费插件提供。": "A compatible type is declared. The consuming plugin provides the actual operations.",
  "结果类型": "Result type",
  "来源插件": "Source plugin",
  "已共享到 Team Project": "Shared with Team Project",
  "发布时间": "Published",
  "查看这个版本": "View this version",
  "导出这个版本": "Export this version",
  "仅下载本地副本，不会发布或共享。": "Downloads a local copy only. Nothing is published or shared.",
  "精确版本引用": "Exact version reference",
  "查看原始 JSON（非业务预览）": "View raw JSON (not an application preview)",
  "内容引用": "Content reference",
  "这里只保留定位信息，不保证当前文件仍对应这个版本；读取和校验由消费插件处理。": "This is a locator only. The current file may no longer match this version; the consuming plugin handles reading and validation.",
  "查看原始元数据": "View raw metadata",
  "Artifact version 必须是正整数": "Artifact version must be a positive integer",
  "Artifact ID 编码无效": "Invalid Artifact ID encoding",
  "当前项目中找不到这个 Artifact 版本": "This Artifact version was not found in the current project",
  "引用这个版本": "Cite this version",
  "导入文档": "Import document",
  "项目成果与导入的文档会保存在这里。可以先导入文档，或推进 Goal 后提交成果。": "Project results and imported documents are saved here. Import a document, or work on a Goal and submit its result.",
  "这是导入时保存的文档版本；原文后续修改不会自动同步。": "This is the document version saved at import. Later changes to the source are not synced automatically.",
  "打开来源文档": "Open source document",
  "文档正文": "Document content",
  "导入说明": "Import notes",
  "把外部文档保存为当前项目的 Artifact。保留本次读取的正文和来源；原文后续修改不会自动同步。": "Save an external document as an Artifact in this project. Its content and source are captured at import; later changes to the original are not synced automatically.",
  "文档来源": "Document source",
  "飞书": "Feishu",
  "本地文件": "Local file",
  "请先在 Notion 中将这个页面共享给已配置的集成。": "First share this page with the configured integration in Notion.",
  "支持飞书文档和知识库链接；连接器需要拥有该文档的读取权限。": "Supports Feishu document and wiki links. The connector needs permission to read the document.",
  "支持 Lark 文档和知识库链接；连接器需要拥有该文档的读取权限。": "Supports Lark document and wiki links. The connector needs permission to read the document.",
  "连接器需要拥有这份 Google 文档的读取权限。": "The connector needs permission to read this Google document.",
  "可从其他文档工具导出 Markdown、纯文本或 HTML，再选择文件导入。": "Export Markdown, plain text, or HTML from another document tool, then select the file to import.",
  "凭据已配置，导入时验证文档访问权限。": "Credentials are configured. Document access is checked during import.",
  "尚未配置此连接器。请先配置凭据，再返回这里导入。": "This connector is not configured. Set up its credentials, then return here to import.",
  "配置连接器": "Configure connector",
  "文档链接": "Document URL",
  "选择文件": "Choose file",
  "支持 UTF-8 编码的 Markdown、纯文本和 HTML，单个文件不超过 2 MB。不支持 PDF、DOCX 或 ZIP；请先从原工具导出支持的格式。": "Supports UTF-8 Markdown, plain text, and HTML files up to 2 MB each. PDF, DOCX, and ZIP are not supported; export a supported format from the original tool first.",
  "标题（可选）": "Title (optional)",
  "留空则使用文件名": "Leave blank to use the filename",
  "正在读取文档并保存 Artifact…": "Reading the document and saving the Artifact…",
  "重试导入": "Retry import",
  "导入失败。请检查链接、文档权限和连接器配置后重试。": "Import failed. Check the URL, document permissions, and connector settings, then retry.",
  "无法连接到本地服务。请检查服务状态后重试。": "Could not connect to the local service. Check its status, then retry.",
  "读取文档超时。你可以重试；同一次导入不会重复创建版本。": "Reading the document timed out. You can retry; the same import will not create a duplicate version.",
  "请先选择一个文件。": "Choose a file first.",
  "仅支持 .md、.markdown、.txt、.html 和 .htm 文件；不支持 PDF、DOCX 或 ZIP。": "Only .md, .markdown, .txt, .html, and .htm files are supported. PDF, DOCX, and ZIP are not supported.",
  "文件不能超过 2 MB。": "The file must not exceed 2 MB.",
  "无法读取文件。请将文件保存为 UTF-8 编码后重试。": "Could not read the file. Save it as UTF-8, then retry.",
  "请输入文档的 HTTPS 链接。": "Enter the document's HTTPS URL.",
  "文档已导入": "Document imported",
  "内容未变化，已保留现有版本": "Content unchanged; the existing version is retained",
  "服务返回的版本信息不完整。请重试以获取导入结果。": "The service returned incomplete version information. Retry to retrieve the import result.",
  "继续导入": "Import another document",
  "请输入文档链接": "Enter the document URL",
  "请选择支持的文档来源": "Choose a supported document source",
  "没有读到可导入的正文；请检查文档内容与访问权限": "No content could be imported. Check the document content and access permissions",
  "文档正文超过 2 MB，请拆分后导入": "The document content exceeds 2 MB. Split it into smaller documents before importing",
  "请选择一个文档文件": "Choose a document file",
  "文件名无效": "Invalid filename",
  "支持 Markdown、TXT 和 HTML；请先在文档工具中导出这些格式": "Markdown, TXT, and HTML are supported. Export one of these formats from your document tool first",
  "文件必须是 UTF-8 文本": "The file must contain UTF-8 text",
  "文件超过 2 MB，请拆分后导入": "The file exceeds 2 MB. Split it into smaller files before importing",
  "文件包含二进制内容，请使用 UTF-8 文本导出": "The file contains binary content. Export it as UTF-8 text",
  "文档标题无效": "Invalid document title",
  "HTML 已提取为文本快照，复杂排版、图片和附件未导入；原始 HTML 保存在版本数据中。": "HTML was converted to a text snapshot. Complex formatting, images, and attachments were not imported; the original HTML is saved in the version data.",
  "无法读取这个 HTML 文件，请改用 Markdown 或 TXT 导出": "Could not read this HTML file. Export it as Markdown or TXT instead",
  "无法读取连接器凭据，请在连接器设置中重新连接": "Could not read the connector credentials. Reconnect in connector settings",
  "请先在连接器设置中连接所选文档工具，并授予文档读取权限": "Connect the selected document tool in connector settings and grant document read access first",
  "导入请求过大，文件不能超过 2 MB": "The import request is too large. Files must not exceed 2 MB",
  "导入请求必须是有效的 UTF-8 JSON 对象": "The import request must be a valid UTF-8 JSON object",
  "导入请求已中断，请重新尝试": "The import request was interrupted. Please retry",
  "请输入完整的文档 HTTPS 链接。": "Enter the full HTTPS URL of the document.",
  "文档链接必须使用 HTTPS，且不能包含账号、密码或自定义端口。": "Document URLs must use HTTPS and must not contain a username, password, or custom port.",
  "链接与所选数据源不匹配，或不是支持的文档。请使用 Notion 页面、飞书/Lark 新版文档或 Google Docs 链接。": "The URL does not match the selected source or is not a supported document. Use a Notion page, a Feishu/Lark docx document, or a Google Docs URL.",
  "连接凭据已失效，请到设置重新连接数据源。": "The connection credentials have expired or are invalid. Reconnect the source in settings.",
  "当前连接没有读取该文档的权限。请检查只读权限，并将文档共享给连接的应用。": "This connection cannot read the document. Check its read permissions and share the document with the connected app.",
  "找不到该文档，或当前连接无权读取。请检查链接和文档共享设置。": "The document was not found or this connection cannot access it. Check the URL and document sharing settings.",
  "数据源请求过于频繁，请稍后重试。": "The source is receiving too many requests. Try again later.",
  "数据源暂时无法提供文档，请稍后重试。": "The source cannot provide the document right now. Try again later.",
  "文档超过 2 MB 导入上限，请拆分后导入。": "The document exceeds the 2 MB import limit. Split it into smaller documents before importing.",
  "读取文档超时，请稍后重试。": "Reading the document timed out. Try again later.",
  "读取文档失败，请检查网络后重试。": "Could not read the document. Check your network connection and retry.",
  "数据源没有返回有效文档数据，请稍后重试。": "The source did not return valid document data. Try again later.",
  "应用没有读取该文档或知识库的权限。请检查开放平台的文档只读权限及文档共享设置。": "The app cannot read this document or wiki. Check its document read permissions in the developer console and the document sharing settings.",
  "找不到该文档，或应用无权读取。请检查文档链接及共享设置。": "The document was not found or the app cannot access it. Check the document URL and sharing settings.",
  "数据源拒绝读取文档，请检查应用权限、文档共享设置后重试。": "The source denied access to the document. Check app permissions and document sharing settings, then retry.",
  "Notion 页面不存在或已移入回收站。": "The Notion page does not exist or is in the trash.",
  "Notion 没有返回有效页面正文。": "Notion did not return valid page content.",
  "Notion 返回的正文不完整，可能包含无权读取的子页面或超过读取上限。请修复共享权限或拆分文档后重试。": "Notion returned incomplete content. Some subpages may be inaccessible, or the document may exceed the read limit. Update sharing permissions or split the document, then retry.",
  "导入为当前正文快照；评论、权限、子页面和附件文件不会一并导入。": "Imported a snapshot of the current content. Comments, permissions, subpages, and attached files are not included.",
  "Notion 正文含暂不支持的块；原位置保留占位标记，请在原文核对。": "The Notion content contains unsupported blocks. Placeholders are retained in their original positions; check them in the source document.",
  "请在设置中以 app_id:app_secret 格式连接该数据源的自建应用。": "Connect this source's custom app in settings using the app_id:app_secret format.",
  "应用凭据无法换取访问令牌，请检查所选数据源和应用凭据。": "Could not obtain an access token with these app credentials. Check the selected source and app credentials.",
  "该知识库节点不是新版文档，暂不支持直接导入。请导出为 Markdown、文本或 HTML 后导入。": "This wiki node is not a docx document and cannot be imported directly. Export it as Markdown, text, or HTML first.",
  "知识库没有返回有效的文档标识。": "The wiki did not return a valid document identifier.",
  "数据源没有返回有效的文档信息。": "The source did not return valid document information.",
  "数据源没有返回有效的文档正文。": "The source did not return valid document content.",
  "导入为纯文本快照；原文的排版、图片、附件、评论及嵌入内容不会一并导入。": "Imported a plain text snapshot. The original formatting, images, attachments, comments, and embedded content are not included.",
  "此链接不是 Google Docs 文档。请导出为 Markdown、文本或 HTML 后导入。": "This URL does not point to a Google Docs document. Export it as Markdown, text, or HTML first.",
  "文档所有者禁止下载该文档，无法导入正文。": "The document owner has disabled downloads, so its content cannot be imported.",
  "导入为纯文本快照；原文的排版、图片、附件和评论不会一并导入。Google Drive 连接需具备 drive.readonly 或 drive.file 读取权限。": "Imported a plain text snapshot. The original formatting, images, attachments, and comments are not included. The Google Drive connection requires drive.readonly or drive.file access.",
  "请先在设置中连接所选数据源。": "Connect the selected source in settings first.",
  "当前环境无法读取在线文档。": "This environment cannot read online documents.",
  "文档没有可导入的正文。请确认文档内容和当前应用的读取权限。": "The document has no content that can be imported. Check its content and the current app's read permissions.",
};
