/** Artifact application copy; Workbench supplies the request locale. */
export const ARTIFACT_EN: Record<string, string> = {
  "输入结果": "Input result",
  "产出结果": "Output result",
  "关联结果": "Linked results",
  "明确关联的 Artifact 版本；查看不会改变 Goal 或 Evidence。": "Explicitly linked Artifact versions. Viewing them does not change Goals or Evidence.",
  "关联的版本不可用或不存在。引用仍然保留，不会替换成最新版本。": "The linked version is unavailable or missing. Its reference is retained; the latest version will not be substituted.",
  "没有兼容插件。可打开这个版本查看信息或导出本地副本。": "No compatible plugin. Open this version to inspect its information or export a local copy.",
  "插件发布的结果与版本": "Results and versions published by plugins",
  "还没有 Artifact": "No Artifacts yet",
  "Artifact 版本": "Artifact versions",
  "内容不可用": "Content unavailable",
  "找不到这个 Artifact 版本": "Artifact version not found",
  "选择一个结果版本": "Choose a result version",
  "它可能属于其他项目，或这个版本尚未发布。请返回列表选择；不会自动替换成最新版本。": "It may belong to another project, or this version has not been published. Return to the list to choose a version; the latest version will not be substituted.",
  "返回 Artifact 列表": "Back to Artifact list",
  "返回项目目录": "Back to project directory",
  "这个版本的内容不可用；引用和来源信息仍然保留。": "This version's content is unavailable. Its reference and source information are retained.",
  "这个版本已归档，保留历史信息，不作为可消费的新结果。": "This version is archived. Its history is retained, but it is not offered as a consumable new result.",
  "没有兼容插件。当前可查看版本信息和原始 JSON，或导出本地副本。": "No compatible plugin. You can inspect version information and raw JSON, or export a local copy.",
  "没有兼容插件。当前可查看版本信息和内容引用，或导出本地副本。": "No compatible plugin. You can inspect version information and the content reference, or export a local copy.",
  "已有兼容的类型声明；具体操作由消费插件提供。": "A compatible type is declared. The consuming plugin provides the actual operations.",
  "结果类型": "Result type",
  "来源插件": "Source plugin",
  "已共享到 Team Project": "Shared with Team Project",
  "发布时间": "Published",
  "查看这个版本": "View this version",
  "导出这个版本": "Export this version",
  "仅下载本地副本，不会发布或共享。": "Downloads a local copy only. Nothing is published or shared.",
  "精确版本引用": "Exact version reference",
  "查看原始 JSON（非业务预览）": "View raw JSON (not an application preview)",
  "内容引用": "Content reference",
  "这里只保留定位信息，不保证当前文件仍对应这个版本；读取和校验由消费插件处理。": "This is a locator only. The current file may no longer match this version; the consuming plugin handles reading and validation.",
  "查看原始元数据": "View raw metadata",
  "Artifact version 必须是正整数": "Artifact version must be a positive integer",
  "Artifact ID 编码无效": "Invalid Artifact ID encoding",
  "当前项目中找不到这个 Artifact 版本": "This Artifact version was not found in the current project",
};
