/** Schedule application copy; Workbench supplies the request locale. */
export const SCHEDULE_EN: Record<string, string> = {
  "结果待核对": "Review the outcome",
  "已完成": "Completed",
  "等待执行": "Waiting to run",
  "正在执行": "Running",
  "执行成功": "Succeeded",
  "执行失败": "Failed",
  "结果未知": "Outcome unknown",
  "已跳过": "Skipped",
  "原闹钟已不存在": "Original alarm is missing",
  "跳过本次并继续": "Skip this occurrence and continue",
  "重试本次": "Retry this occurrence",
  "原闹钟或功能已不存在，请保留历史并新建定时。": "The original alarm or operation is missing. Keep the history and create a new schedule.",
  "执行功能": "Operation",
  "每隔 24 小时": "Every 24 hours",
  "每隔 7 天": "Every 7 days",
  "原输入": "Original input",
  "刷新任务与安装": "Refresh task and installation",
  "尚未执行": "Not run yet",
  "已确认重试": "Retry confirmed",
  "已确认跳过": "Skip confirmed",
  "无法恢复的旧执行记录": "Legacy records that cannot be restored",
  "原功能定义已丢失，这些记录仅供核对，不会自动执行。": "The original operation definition is missing. These records are kept for review and will not run automatically.",
  "核对定时操作": "Review scheduled operation",
  "确认决定": "Confirm decision",
  "任务状态已改变，请返回列表重新选择。": "The task has changed. Return to the list and choose again.",
  "上次可能已经产生费用或外部修改。确认重试会再次运行同一输入，可能重复这些结果；请先核对外部记录。": "The previous call may already have incurred costs or made external changes. Retrying runs the same input again and may duplicate those effects. Check the external records first.",
  "跳过最早的一次未知结果，不再运行这次调用。其他未知结果仍需核对；处理完后按原间隔继续，一次性任务到此结束。": "Skip the earliest unknown occurrence without running it again. Review any remaining unknown outcomes. Then continue at the original interval; a one-time task ends here.",
  "将原功能和输入交给当前安装。未派出的记录会等待新的唤醒，之后保留原固定间隔。此确认会允许插件代码运行。": "Assign the original operation and input to the current installation. Undispatched work waits for a fresh wakeup, then keeps the original interval. This confirmation allows plugin code to run.",
  "无法恢复定时操作": "Could not restore the scheduled operation",
  "待确认归属": "Confirm plugin ownership",
  "确认归属并恢复": "Review and restore",
  "刷新当前安装": "Refresh current installation",
  "原安装身份无法确认。请核对提醒内容与当前插件后再恢复。": "The original installation cannot be verified. Review the reminder and the current plugin before restoring it.",
  "请先安装并启用对应插件，再刷新查看当前安装。": "Install and enable the corresponding plugin, then refresh to review it.",
  "恢复这条提醒": "Restore this reminder",
  "交给当前安装：": "Assign to this installation: ",
  "保留原提醒时间。已过期的提醒会补提醒一次，之后仍按原间隔提醒。此操作不会运行插件代码。": "Keep the original schedule. An overdue reminder is delivered once, then repeats at the original interval. This does not run plugin code.",
  "确认恢复": "Confirm restoration",
  "这条提醒已恢复或已不存在，请返回列表查看。": "This reminder has been restored or no longer exists. Return to the list to check.",
  "无法恢复提醒": "Could not restore the reminder",
  "无法更新定时任务列表": "Could not refresh scheduled tasks",
  "正在创建…": "Creating…",
  "还没有定时任务": "No scheduled tasks yet",
  "新建一条之后，到点会在它自己的对话里跑一轮只读 Agent。其他插件登记的闹钟也会出现在这里。": "Create one and a read-only agent will run in that task’s own chat when it is due. Alarms registered by other plugins also appear here.",
  "选择一条定时任务": "Select a scheduled task",
  "新建定时任务": "New scheduled task",
  "到点后会在这条任务自己的对话里跑一轮，不会进现有 Coding 会话。": "When due, it runs a round in this task’s own chat, not an existing Coding session.",
  "标题": "Title",
  "例如：每天早上汇总未读": "e.g. Morning unread summary",
  "说明": "Instructions",
  "到点后 Agent 会读这段说明，然后在这条对话里回复。": "At the due time the agent reads this and replies in this chat.",
  "默认只读。要改文件会进现有审核队列。": "Read-only by default. Writes still go through the existing review queue.",
  "每天": "Every day at",
  "按这台电脑的本地时间。本地服务没开时闹钟不响。": "Uses this computer’s local time. The alarm only fires while the local service is running.",
  "重要更新时在列表标出来": "Mark the list when an update is important",
  "关闭": "Close",
  "取消": "Cancel",
  "创建": "Create",
  "无法创建定时任务": "Could not create the scheduled task",
  "其他插件的闹钟": "Alarms from other plugins",
  "有更新": "Updated",
  "尚未排期": "Not scheduled yet",
  "每天 {time}": "Daily {time}",
  "Agent": "Agent",
  "系统": "System",
  "重要": "Important",
  "已启用": "Enabled",
  "已暂停": "Paused",
  "下次": "Next",
  "上次": "Last",
  "暂停": "Pause",
  "恢复": "Resume",
  "单次": "Once",
  "每隔 {seconds} 秒": "Every {seconds}s",
  "返回定时任务列表": "Back to scheduled tasks",
  "闹钟": "Alarm",
  "执行接口": "Execute API",
  "对象钥匙": "Object key",
  "重复": "Repeat",
  "这次叫醒": "Last wake",
  "还没有叫醒过": "Not woken yet",
  "叫醒成功": "Woke successfully",
  "叫醒失败": "Wake failed",
  "执行方不可用": "Owner unavailable",
  "无法更新定时任务": "Could not update the scheduled job",
  "到点跑自己的对话任务，也叫醒其他插件的闹钟。": "Runs its own chat tasks when due, and wakes alarms other plugins registered.",
};
