/** Schedule application copy; Workbench supplies the request locale. */
export const SCHEDULE_EN: Record<string, string> = {
  "还没有定时任务": "No scheduled jobs yet",
  "其他插件登记之后，到点会叫醒它们自己的执行接口。这里只负责闹钟。": "After other plugins register a job, Schedule wakes their own execute API on time. This surface is only the alarm.",
  "选择一条定时任务": "Select a scheduled job",
  "已启用": "Enabled",
  "已暂停": "Paused",
  "下次": "Next",
  "上次": "Last",
  "暂停": "Pause",
  "恢复": "Resume",
  "单次": "Once",
  "每隔 {seconds} 秒": "Every {seconds}s",
  "返回定时任务列表": "Back to scheduled jobs",
  "闹钟": "Alarm",
  "执行接口": "Execute API",
  "对象钥匙": "Object key",
  "重复": "Repeat",
  "这次叫醒": "Last wake",
  "还没有叫醒过": "Not woken yet",
  "叫醒成功": "Woke successfully",
  "叫醒失败": "Wake failed",
  "执行方不可用": "Owner unavailable",
  "无法更新定时任务": "Could not update the scheduled job",
  "到点叫醒其他插件，自己不执行。": "Wakes other plugins on time and does not run the work itself.",
};
