/** Schedule application copy; Workbench supplies the request locale. */
export const SCHEDULE_EN: Record<string, string> = {
  "还没有定时任务": "No scheduled tasks yet",
  "新建一条之后，到点会在它自己的对话里跑一轮只读 Agent。其他插件登记的闹钟也会出现在这里。": "Create one and a read-only agent will run in that task’s own chat when it is due. Alarms registered by other plugins also appear here.",
  "选择一条定时任务": "Select a scheduled task",
  "新建定时任务": "New scheduled task",
  "到点后会在这条任务自己的对话里跑一轮，不会进现有 Coding 会话。": "When due, it runs a round in this task’s own chat, not an existing Coding session.",
  "标题": "Title",
  "例如：每天早上汇总未读": "e.g. Morning unread summary",
  "说明": "Instructions",
  "到点后 Agent 会读这段说明，然后在这条对话里回复。": "At the due time the agent reads this and replies in this chat.",
  "默认只读。要改文件会进现有审核队列。": "Read-only by default. Writes still go through the existing review queue.",
  "每天": "Every day at",
  "按这台电脑的本地时间。本地服务没开时闹钟不响。": "Uses this computer’s local time. The alarm only fires while the local service is running.",
  "重要更新时在列表标出来": "Mark the list when an update is important",
  "关闭": "Close",
  "取消": "Cancel",
  "创建": "Create",
  "无法创建定时任务": "Could not create the scheduled task",
  "其他插件的闹钟": "Alarms from other plugins",
  "有更新": "Updated",
  "尚未排期": "Not scheduled yet",
  "每天 {time}": "Daily {time}",
  "Agent": "Agent",
  "系统": "System",
  "重要": "Important",
  "已启用": "Enabled",
  "已暂停": "Paused",
  "下次": "Next",
  "上次": "Last",
  "暂停": "Pause",
  "恢复": "Resume",
  "单次": "Once",
  "每隔 {seconds} 秒": "Every {seconds}s",
  "返回定时任务列表": "Back to scheduled tasks",
  "闹钟": "Alarm",
  "执行接口": "Execute API",
  "对象钥匙": "Object key",
  "重复": "Repeat",
  "这次叫醒": "Last wake",
  "还没有叫醒过": "Not woken yet",
  "叫醒成功": "Woke successfully",
  "叫醒失败": "Wake failed",
  "执行方不可用": "Owner unavailable",
  "无法更新定时任务": "Could not update the scheduled job",
  "到点跑自己的对话任务，也叫醒其他插件的闹钟。": "Runs its own chat tasks when due, and wakes alarms other plugins registered.",
};
