import assert from "node:assert/strict";
import test from "node:test";
import { openMolisWorkProjectCatalog } from "@molis-ai/molis-work-app-desktop";
import { createLocalFeedApplication, createLocalFeedSourceService, DEMO_BOARD_ID, GoalProjectApplication } from "@molis-ai/molis-work-app-local-host";
import { openGoalBrowser } from "./fixtures/goal-browser.js";

test("Kanban routes wheel by pointer and axis without switching axes at column boundaries", { timeout: 60_000 }, async t => {
  const b = await openGoalBrowser(t); if (!b) return;
  const { command, sessionId, navigate, origin, click, evaluate, waitFor } = b;
  const app = new GoalProjectApplication(b.store);
  for (let i = 0; i < 16; i++) app.goalEvents.createIntent({ board_id: DEMO_BOARD_ID, title: `待处理工作 ${i + 1}`, outcome: "验证列内滚动仍可阅读完整任务", actor_id: "scroll-test", actor_kind: "user", idempotency_key: `scroll-${i}` });
  await command("Emulation.setDeviceMetricsOverride", { width: 1440, height: 720, deviceScaleFactor: 1, mobile: false }, sessionId);
  await navigate(() => command("Page.navigate", { url: origin + "/" }, sessionId));
  await click('[data-plugin-id="goals"]');
  await waitFor("document.querySelector('[data-goal-momentum]')?.dataset.loaded==='true'");
  await click('[data-board-view-tab="kanban"]');
  await waitFor("document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView==='kanban'");
  await waitFor("[...document.querySelectorAll('[data-kanban-cards]')].some(x=>x.scrollHeight>x.clientHeight+80)");
  const actual = await evaluate<string>(`[...document.querySelectorAll('[data-kanban-cards]')].find(x=>x.scrollHeight>x.clientHeight+80)?.closest('[data-kanban-column]')?.dataset.kanbanColumn`);
  assert.ok(actual, "real created goals overflow a column");
  const cards = `[data-kanban-column="${actual}"] [data-kanban-cards]`;
  const wheel = async (selector: string, dx: number, dy: number, modifiers = 0, inset = { x: 30, y: 20 }) => {
    const point = await evaluate<{x:number;y:number}>(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return {x:r.x+Math.min(${inset.x},Math.max(8,r.width/2)),y:r.y+Math.min(${inset.y},Math.max(8,r.height/2))}})()`);
    await command("Input.dispatchMouseEvent", { type: "mouseWheel", ...point, deltaX: dx, deltaY: dy, modifiers }, sessionId);
  };
  const left = () => evaluate<number>("document.querySelector('[data-goal-kanban]').scrollLeft");
  const start = await left();
  await wheel(cards, 0, 180);
  await waitFor(`document.querySelector('${cards}').scrollTop>80`);
  assert.equal(await left(), start, "vertical wheel reads the pointed column");
  await evaluate(`document.querySelector('${cards}').scrollTop=99999`);
  const bottom = await evaluate<number>(`document.querySelector('${cards}').scrollTop`);
  await wheel(cards, 0, 180);
  assert.equal(await left(), start, "column bottom never turns vertical wheel into horizontal movement");
  assert.equal(await evaluate(`document.querySelector('${cards}').scrollTop`), bottom);
  assert.equal(await evaluate("getComputedStyle(document.querySelector('.goal-kanban-board')).flexDirection"), "row");
  await command("Emulation.setDeviceMetricsOverride", { width: 390, height: 844, deviceScaleFactor: 1, mobile: true }, sessionId);
  await waitFor("getComputedStyle(document.querySelector('.goal-kanban-board')).flexDirection==='column'");
  const stacked = await evaluate<{ sw: number; cw: number; sh: number; ch: number }>("(() => { const el = document.querySelector('[data-goal-kanban]'); return { sw: el.scrollWidth, cw: el.clientWidth, sh: el.scrollHeight, ch: el.clientHeight }; })()");
  assert.ok(stacked.sw <= stacked.cw + 1, "stacked kanban does not scroll sideways");
  assert.ok(stacked.sh > stacked.ch + 40, "stacked kanban reads vertically");
  await evaluate("document.querySelector('[data-goal-kanban]').scrollTop=0");
  await wheel(".goal-kanban-board", 0, 220, 0, { x: 40, y: 80 });
  await waitFor("document.querySelector('[data-goal-kanban]').scrollTop>40");
  assert.equal(await evaluate("document.scrollingElement.scrollTop"), 0);
  assert.equal(await evaluate("document.scrollingElement.scrollHeight <= innerHeight + 1"), true);
});

test("Frame picker adds a persistent reference in place; current tab, directory and form focus agree", { timeout: 60_000 }, async t => {
  const b = await openGoalBrowser(t, true); if (!b) return;
  const { command, sessionId, navigate, origin, click, evaluate, waitFor, projectId, reloadPage } = b;
  const catalog = await openMolisWorkProjectCatalog({homeDirectory:b.homeDirectory});
  catalog.addProjectPlugin({project_id:projectId!,plugin_id:"feed",actor_id:"attention-test"}); catalog.close();
  const app = new GoalProjectApplication(b.store);
  const goal = app.goalEvents.createIntent({board_id:DEMO_BOARD_ID,title:"整理设计反馈",outcome:"明确下一轮体验改动",actor_id:"attention-test",actor_kind:"user",idempotency_key:"attention-intent"}).goal;
  const source = createLocalFeedSourceService(b.store.db, DEMO_BOARD_ID).register({kind:"web_query",query:"设计反馈"}).source;
  const feed = createLocalFeedApplication(b.store.db);
  const item = feed.ingestItem({source,externalId:"attention-reference",title:"核对键盘焦点",summary:"需要保留当前输入位置",body:"需要保留当前输入位置",occurredAt:new Date().toISOString(),attention:false}).item;
  const before = b.store.snapshot(DEMO_BOARD_ID);
  await command("Emulation.setDeviceMetricsOverride",{width:1280,height:800,deviceScaleFactor:1,mobile:false},sessionId);
  await navigate(()=>command("Page.navigate",{url:`${origin}/projects/${projectId}/`},sessionId));
  await click('[data-plugin-id="goals"]');
  await click(`.tree-node[data-select-goal="${goal.goal_id}"]`);
  await evaluate(`document.querySelector('.tree-node[data-select-goal="${goal.goal_id}"]').dispatchEvent(new MouseEvent('click', {bubbles:true, cancelable:true, view:window, detail:2}))`);
  await waitFor(`document.querySelector('[data-frame-goal-title]')?.textContent==='整理设计反馈'`);
  assert.match(await evaluate<string>("document.title"), /整理设计反馈/);
  assert.equal(await evaluate(`document.querySelector('.tree-node[data-select-goal="${goal.goal_id}"]').classList.contains('is-selected')`),true);
  await waitFor(`document.querySelector('[data-titlebar-tabs] .tab-item[data-item-id="${goal.goal_id}"]')`);
  assert.equal(await evaluate(`document.querySelector('[data-titlebar-tabs] .tab-item[data-item-id="${goal.goal_id}"]').getBoundingClientRect().height>0`),true);
  await command("Emulation.setDeviceMetricsOverride",{width:390,height:844,deviceScaleFactor:1,mobile:false},sessionId);
  await click('[data-frame-empty] [data-frame-add-content]');
  await waitFor("document.querySelector('[data-frame-picker]').open");
  const assertPickerTargets = async () => {
    await evaluate("Promise.all(document.querySelector('[data-frame-picker]').getAnimations({subtree:true}).map(animation=>animation.finished.catch(()=>{})))");
    const targets = await evaluate<{name:string;height:number}[]>(`[...document.querySelectorAll('.frame-picker-tools input,.frame-picker-tools select,.frame-picker footer button,[data-frame-add-content]')].filter(x=>x.getClientRects().length).map(x=>({name:x.getAttribute('aria-label')||x.textContent||x.tagName,height:x.getBoundingClientRect().height}))`);
    for (const target of targets) assert.ok(target.height>=44, `${target.name} has a 44px interactive height, got ${target.height}`);
    assert.equal(await evaluate("document.scrollingElement.scrollHeight<=innerHeight+1"),true);
  };
  await assertPickerTargets();
  await command("Emulation.setDeviceMetricsOverride",{width:1280,height:800,deviceScaleFactor:1,mobile:false},sessionId);
  await command("Emulation.setTouchEmulationEnabled",{enabled:true,maxTouchPoints:1},sessionId);
  assert.equal(await evaluate("matchMedia('(pointer: coarse)').matches"),true);
  await assertPickerTargets();
  await command("Emulation.setTouchEmulationEnabled",{enabled:false},sessionId);
  assert.equal(await evaluate("document.activeElement.hasAttribute('data-frame-picker-search')"),true);
  await command("Input.insertText",{text:"不存在的内容"},sessionId);
  assert.match(await evaluate<string>("document.querySelector('[data-frame-picker-list]').textContent"),/没有匹配/);
  await evaluate("document.querySelector('[data-frame-picker-search]').value='核对键盘';document.querySelector('[data-frame-picker-search]').dispatchEvent(new Event('input',{bubbles:true}))");
  await click(`[data-frame-picker-asset="feed:${item.item_id}"]`);
  assert.equal(await evaluate("document.querySelector('[data-frame-picker]').open"),false);
  assert.equal(await evaluate("document.querySelector('[data-frame-block]').textContent.includes('核对键盘焦点')"),true);
  await reloadPage();
  await waitFor("document.querySelector('[data-frame-block]')?.textContent.includes('核对键盘焦点')");
  await click('.frame-goal-actions [data-frame-add-content]');
  assert.equal(await evaluate(`document.querySelector('[data-frame-picker-asset="feed:${item.item_id}"]').disabled`),true);
  await command("Input.dispatchKeyEvent",{type:"keyDown",key:"Escape",code:"Escape",windowsVirtualKeyCode:27},sessionId);
  await waitFor("!document.querySelector('[data-frame-picker]').open");
  await click('[data-frame-goal-work]');
  await waitFor(`document.querySelector('[data-goal-event-document]')?.dataset.goalView==='${goal.goal_id}' && !document.querySelector('[data-goal-node-workspace]').hidden`);
  assert.equal(await evaluate("document.querySelector('[data-event-sheet]').hidden"),true, "history begins collapsed");
  assert.match(await evaluate<string>("document.querySelector('[data-current-summary]').textContent"),/还没有明确完成要求/);
  await click('[data-record-menu] > summary');
  await click('[data-record-menu] [data-event-form-open="note"]');
  await waitFor("document.activeElement.closest('[data-event-form=note]') && document.activeElement.tagName==='TEXTAREA'");
  await command("Input.insertText",{text:"焦点应留在输入框"},sessionId);
  assert.equal(await evaluate("document.querySelector('[data-event-form=note] textarea').value"),"焦点应留在输入框");
  await click('[data-event-form=note] footer [data-event-back]');
  assert.equal(await evaluate("document.querySelector('[data-event-form=note]').hidden"),true);
  await waitFor(`document.querySelector('[data-tui-pane]')?.dataset.goalId==='${goal.goal_id}' && document.querySelector('[data-tui-pane]')?.dataset.tuiParentReadOnly!=='true' && !document.querySelector('[data-goal-work-main]')?.hasAttribute('inert')`);
  await evaluate("document.querySelector('[data-tui-empty-add]').click()");
  await waitFor("document.querySelector('[data-tui-menu]')?.classList.contains('is-open') && document.activeElement.matches('[data-tui-kind]')");
  await click('[data-tui-menu-cancel]');
  assert.equal(await evaluate("document.activeElement.matches('[data-tui-empty-add]')"),true);
  await click('[data-plugin-id="goals"]');
  await waitFor("document.body.dataset.desktopSurface==='goal' && document.querySelector('[data-goal-momentum]')?.dataset.loaded==='true'");
  await evaluate(`document.querySelector('[data-momentum-node][data-goal-id="${goal.goal_id}"] [data-graph-frame]').click()`);
  await waitFor("!document.querySelector('[data-goal-frame-surface]').hidden");
  assert.equal(await evaluate("document.querySelector('[data-frame-goal-title]').textContent"),"整理设计反馈", "explicit Frame entry overrides the saved work view");
  assert.deepEqual(b.store.snapshot(DEMO_BOARD_ID).goals,before.goals);
  assert.deepEqual(b.store.snapshot(DEMO_BOARD_ID).runs,before.runs);
});
