import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from 'node:http';
import {once} from 'node:events';
import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
import {handleCasebookHttp} from '../apps/local-host/src/casebook/http.js';
import {MolisWorkCasebookClient} from '../apps/local-host/src/casebook/client.js';
import {createCasebookUserActionSigner,createCasebookUserActionVerifier} from '../apps/local-host/src/casebook/user-action.js';
import {randomBytes} from 'node:crypto';
import {configureGoalEventsCapability,setGoalEventAgreementCapability} from '@molis-ai/molis-work-plugin-goals';
import {createMolisWorkLocalHost,molisWorkHostProjectReference} from '../apps/local-host/src/project-host.js';
import {MolisWorkCasebookIntegration} from '../apps/local-host/src/casebook/integration.js';
import {initializeBoardCapability,createGoalIntentCapability,readGoalEventStateCapability,submitGoalEventClosureCapability,goalTreeCapabilities,requestGoalDecisionCapability,recordGoalUserDecisionCapability,hostEventDecisionAuthority} from '@molis-ai/molis-work-plugin-goals';
const purpose='casebook.operation-receipts.v1' as any;
test('101 unmet requirements preserve the closure result with explicitly truncated reasons',async t=>{
 const f=await fixture(t);await f.auth('join');await f.create('many');
 await f.client.invoke(configureGoalEventsCapability,{board_id:'board',goal_id:'many',actor_id:'u',idempotency_key:'configure-many',expected_version:0,types:[{type_id:'note',version:1,name:'记录',purpose:'记事实',semantic_family:'progress',fields:[{field_id:'body',name:'正文',purpose:'记录',format:'longtext',required:true}]}]});
 let state=await f.client.invoke(readGoalEventStateCapability,{board_id:'board',goal_id:'many'});
 await f.client.invoke(setGoalEventAgreementCapability,{board_id:'board',goal_id:'many',actor_id:'u',idempotency_key:'agree-many',outcome:'完成全部要求',expected_config_version:state.config.version,expected_agreement_version:state.agreement.version,new_requirements:Array.from({length:101},(_,i)=>({requirement_id:`need-${i}`,statement:`真实未满足要求 ${i}`,bound_type_id:'note'}))});
 state=await f.client.invoke(readGoalEventStateCapability,{board_id:'board',goal_id:'many'});
 const result=await f.client.invoke(submitGoalEventClosureCapability,{board_id:'board',goal_id:'many',actor_id:'u',idempotency_key:'close-many',kind:'complete',reason:'尝试关闭',result:'结果尚不足以证明全部要求',expected_config_version:state.config.version,expected_agreement_version:state.agreement.version});
 assert.equal(result.recorded,true);assert.equal(result.completion_applied,false);assert.equal(result.unmet_reasons.length,101,JSON.stringify([...new Set(result.unmet_reasons.map(r=>r.code))]));
 const batch=await f.read(),closure=batch.receipts.filter((r:any)=>r.capability.endsWith('.close'));
 assert.equal(closure.length,2);assert.equal(closure[1].phase,'result');assert.equal(closure[1].saved.recorded,true);assert.equal(closure[1].saved.completion_applied,false);
 assert.equal(closure[1].guidance.reasons.length,100);assert.equal(closure[1].guidance.reasons_truncated,true);assert.equal(closure[0].guidance.reasons_truncated,false);
 assert.deepEqual(closure[1].guidance.reasons.map((r:any)=>r.code),result.unmet_reasons.slice(0,100).map(r=>r.code));
 assert.equal(batch.coverage.incomplete_operations,0);assert.equal(batch.coverage.unpersisted_failures,0);
});
async function fixture(t:test.TestContext){
 const dir=mkdtempSync(join(tmpdir(),'casebook-receipts-'));const host=createMolisWorkLocalHost();
 const ref=molisWorkHostProjectReference({databasePath:join(dir,'test.db'),boardId:'board'});const client=host.client(ref);
 await client.invoke(initializeBoardCapability,{board_id:'board',title:'隔离',actor_id:'u',idempotency_key:'init'});
 const proof={secret:randomBytes(32).toString('hex'),audience:'isolated-receipts'};const sign=createCasebookUserActionSigner(proof),verify=createCasebookUserActionVerifier(proof);
 const api=new MolisWorkCasebookIntegration({client,verifyUserAction:verify});
 const request=(action:string,key=action,p=purpose)=>{const intent={project_ref:'board',purpose:p,action,actor_ref:'u',user_confirmed:true,idempotency_key:key} as any;return{...intent,user_action_ref:sign(intent)};};
 const auth=(action:string,key=action,p=purpose)=>api.setInteractionAuthorization(request(action,key,p));
 const read=async()=>{const a=await api.readInteractionAuthorization({project_ref:'board',purpose}) as any;return (api as any).readOperationReceipts({project_ref:'board',schema_version:'1.0.0',authorization_epoch:a.authorization_epoch,after_cursor:0,limit:100});};
 const create=(id:string)=>client.invoke(createGoalIntentCapability,{board_id:'board',goal_id:id,title:'机密文本',actor_id:'u',idempotency_key:id});
 t.after(async()=>{await host.close();rmSync(dir,{recursive:true,force:true});});return{host,ref,client,api,auth,read,create,request,verify};
}
test('new receipts require independent consent and share only explicit operation identity with v2',async t=>{
 const f=await fixture(t);await f.auth('join','legacy','casebook.interaction-review.v1');await f.create('before');
 assert.equal(((await f.api.readInteractionAuthorization({project_ref:'board',purpose})) as any).state,'not_joined');
 await f.auth('join');await f.create('g');const batch=await f.read();assert.equal(batch.receipts.length,2);
 const a=await f.api.readInteractionAuthorization({project_ref:'board',purpose:'casebook.interaction-review.v1'}) as any;
 const old=await f.api.readInteractionFacts({project_ref:'board',schema_version:'2.0.0',authorization_epoch:a.authorization_epoch,after_cursor:0,limit:100});
 assert.equal(batch.receipts[0].operation_id,old.facts[2].operation_id);
 assert.notEqual(batch.receipts[0].selection.goal_ref,old.facts[2].selection.goal_ref);
 assert.equal(batch.receipts[1].saved.goal_ref,batch.receipts[0].selection.goal_ref);
 assert.equal(JSON.stringify(batch).includes('机密'),false);
 await f.auth('pause');await f.create('paused');await assert.rejects(f.read(),{code:'not_authorized'});
 await f.auth('resume');assert.equal((await f.read()).receipts.length,2);
 await f.auth('remove');await f.auth('join','rejoin');assert.equal((await f.read()).receipts.length,0);
});
test('standalone client archive exports independent receipt schemas and no owner storage dependency',async t=>{
 const directory=mkdtempSync(join(tmpdir(),'casebook-client-artifact-'));t.after(()=>rmSync(directory,{recursive:true,force:true}));
 const result=JSON.parse(execFileSync(process.execPath,['scripts/build-casebook-client.mjs',directory],{encoding:'utf8',env:{...process.env,npm_config_cache:join(directory,'cache')}}));
 execFileSync('tar',['-xzf',result.archive,'-C',directory]);
 const pkg=JSON.parse(readFileSync(join(directory,'package/package.json'),'utf8'));assert.equal(pkg.exports['./operation-receipts-schema'],'./operation-receipts.schema.json');
 const client=await import(join(directory,'package/client.js'));assert.equal(typeof client.MolisWorkCasebookClient.prototype.readOperationReceipts,'function');
 assert.equal(client.RECEIPTS_PURPOSE,'casebook.operation-receipts.v1');
 assert.equal(readFileSync(join(directory,'package/client.js'),'utf8').includes('node:fs'),false);
});
test('network diagnostics never open unresolved project; signed scoped HTTP reads validate new receipts',async t=>{
 const f=await fixture(t);const token='isolated-service-token-000000000000000000';
 const server=createServer((req,res)=>{void handleCasebookHttp(req,res,new URL(req.url!,'http://localhost'),{grants:[{token,project_ref:'board'}],verifyUserAction:f.verify},f.host,async()=>({kind:'board',options:{databasePath:f.ref.storage_key,boardId:'board'}} as any));});
 server.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>new Promise<void>(r=>server.close(()=>r())));
 const address=server.address() as any;const client=new MolisWorkCasebookClient({baseUrl:`http://127.0.0.1:${address.port}`,token,projectRef:'board'});
 await f.host.closeProject(f.ref);
 const diagnostics=await (client as any).readConnectionDiagnostics({project_ref:'board'});assert.equal(diagnostics.project_state,'not_open');assert.equal(diagnostics.historical_record,false);assert.equal(f.host.status().projects.length,0);
 assert.equal(JSON.stringify(diagnostics).includes(f.ref.storage_key),false);
 await f.host.restoreExistingProject(f.ref);await client.setInteractionAuthorization(f.request('join','http'));
 await f.create('http');const auth=await client.readInteractionAuthorization({project_ref:'board',purpose});
 const batch=await (client as any).readOperationReceipts({project_ref:'board',schema_version:'1.0.0',authorization_epoch:auth.authorization_epoch,after_cursor:0,limit:100});assert.equal(batch.receipts.length,2);
 const bad=new MolisWorkCasebookClient({baseUrl:`http://127.0.0.1:${address.port}`,token:'bad0000000000000000000000000000000000',projectRef:'board'});await assert.rejects((bad as any).readConnectionDiagnostics({project_ref:'board'}),{code:'not_authorized'});
});
test('actual API refusal, decision scope/options, proposal attempt and replay produce bounded receipts',async t=>{
 const f=await fixture(t);await f.auth('join');await f.create('g');
 const state=await f.client.invoke(readGoalEventStateCapability,{board_id:'board',goal_id:'g'});
 await f.client.invoke(submitGoalEventClosureCapability,{board_id:'board',goal_id:'g',actor_id:'u',idempotency_key:'close',kind:'complete',reason:'机密',expected_config_version:state.config.version,expected_agreement_version:state.agreement.version});
 const decision=await f.client.invoke(requestGoalDecisionCapability,{board_id:'board',goal_id:'g',actor_id:'u',idempotency_key:'decision',question:'机密问题',options:[{option_id:'yes',label:'秘密选项',impact:'执行'},{option_id:'no',label:'拒绝',impact:'不执行'}],purpose:'action',scope:{action:'deploy'}});
 await assert.rejects(f.client.invoke(goalTreeCapabilities.submitGoalTreeProposal,[{board_id:'board',actor_id:'u',idempotency_key:'bad-proposal',summary:'机密',items:[]}])) ;
 await f.create('g');const batch=await f.read();
 const close=batch.receipts.find((r:any)=>r.capability.endsWith('.close')&&r.phase==='result');assert.equal(close.saved.recorded,true);assert.equal(close.saved.completion_applied,false);assert.ok(close.guidance.reasons.length);
 const d=batch.receipts.find((r:any)=>r.capability.endsWith('.decision-request')&&r.phase==='result');assert.equal(d.guidance.decision_options.length,decision.decision_request.options.length);assert.ok(d.decision.scope.action_ref);
 const proposal=batch.receipts.filter((r:any)=>r.capability.endsWith('submit-goal-tree-proposal'));assert.equal(proposal.length,2);assert.equal(proposal[1].outcome,'threw');assert.equal(proposal[1].guidance.reasons[0].code,'goal_tree_proposal.items_required');
 assert.equal(batch.receipts.at(-1).replayed,true);assert.equal(JSON.stringify(batch).includes('机密'),false);
 await f.host.closeProject(f.ref);await f.host.restoreExistingProject(f.ref);assert.deepEqual((await f.read()).receipts,batch.receipts);
});
test('receipts reject forged scope, changed payload, invalid cursors and late results after removal',async t=>{
 const f=await fixture(t);await assert.rejects(f.api.setInteractionAuthorization({...f.request('join'),actor_ref:'forged'}),{code:'not_authorized'});
 await f.auth('join');await f.create('g');const batch=await f.read(),query={project_ref:'board',schema_version:'1.0.0',authorization_epoch:batch.authorization_epoch,after_cursor:0,limit:100};
 await assert.rejects(f.api.readOperationReceipts({...query,after_cursor:99} as any),{code:'cursor_gap'});
 await assert.rejects(f.api.readOperationReceipts({...query,schema_version:'2.0.0'} as any),{code:'unsupported_schema_version'});
 await assert.rejects(f.api.readOperationReceipts({...query,secret:'extra'} as any),{code:'unknown_field'});
 await f.host.withProject(f.ref,r=>r.store.db.prepare("UPDATE casebook_interaction_facts SET body=json_set(body,'$.outcome','threw') WHERE id=?").run(batch.receipts[0].receipt_id));
 await assert.rejects(f.read(),{code:'source_projection_invalid'});
 await f.auth('remove');await f.auth('join','new-epoch');
 const appended=await f.host.withProject(f.ref,r=>{const {seq,source_digest,...receipt}=batch.receipts[1];return r.interactionObserver!.receipts.journal.appendReceipt(batch.authorization_epoch,receipt);});assert.equal(appended,null);assert.equal((await f.read()).receipts.length,0);
});
test('stored decision comparison belongs to its commitment version; proposal success retains native versions',async t=>{
 const f=await fixture(t);await f.auth('join');await f.create('g');
 const decision=await f.client.invoke(recordGoalUserDecisionCapability,{board_id:'board',goal_id:'g',idempotency_key:'decide',authority:hostEventDecisionAuthority('web','board','u','decision-authority'),conclusion:'机密批准',effects:[{kind:'authorize_action',action:'ship'}],scope:{action:'ship'}});
 const batch=await f.read();const d=batch.receipts.at(-1).decision;
 assert.equal(d.config_version,decision.decision.config_version);assert.equal(d.agreement_version,decision.decision.agreement_version);assert.match(d.commitment_comparison,/^[a-f0-9]{64}$/);
 const submitted=await f.client.invoke(goalTreeCapabilities.submitGoalTreeProposal,[{board_id:'board',actor_id:'u',idempotency_key:'proposal',summary:'机密',items:[{item_id:'new',kind:'goal',operation:'create',payload:{title:'机密子目标',outcome:'结果',goal_id:'child'},source_refs:['runtime'],reason:'需要',confidence:0.9}]}]);
 const confirmed=await f.client.invoke(goalTreeCapabilities.decideGoalTreeProposal,[{board_id:'board',proposal_id:submitted.proposal.proposal_id,authority:{...hostEventDecisionAuthority('web','board','u','proposal-authority'),whole_confirmation_prompted:true},confirm_all_pending:true,reason:'同意',idempotency_key:'confirm'}]);
 const after=await f.read(),last=after.receipts.at(-1);assert.ok(last.saved.proposal_ref);assert.equal(last.saved.proposal_version,confirmed.proposal.version);assert.equal(last.saved.proposal_state,confirmed.proposal.state);assert.equal(last.saved.applied_item_refs.length,1);assert.equal(JSON.stringify(after).includes('机密'),false);
});
