import assert from "node:assert/strict";
import test from "node:test";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { execFileSync } from "node:child_process";
import { openGoalBrowser } from "./fixtures/goal-browser.js";

test("Coding tools open real stages, preserve session tabs and read fixed workspace content", { timeout: 90000 }, async t => {
  const b = await openGoalBrowser(t, "seeded"); if (!b) return;
  const { click, evaluate, waitFor, command, sessionId } = b;
  const prefix = `${b.origin}/projects/${b.projectId}`;
  const workspace = join(b.homeDirectory, "coding-fixture");
  await mkdir(join(workspace, "nested"), { recursive: true });
  await writeFile(join(workspace, "note.txt"), "first\n中文🙂\n");
  await writeFile(join(workspace, "nested", "empty.txt"), "");
  const git = (...args: string[]) => execFileSync("git", args, { cwd: workspace, stdio: "pipe" });
  git("init", "-b", "main"); git("config", "user.name", "Fixture"); git("config", "user.email", "fixture@example.invalid");
  git("add", "."); git("commit", "-m", "initial");
  const fill = (selector: string, value: string) => evaluate(`(()=>{const node=document.querySelector(${JSON.stringify(selector)});node.value=${JSON.stringify(value)};node.dispatchEvent(new Event('input',{bubbles:true}));})()`);
  const open = async (plugin: string) => {
    await click(`[data-plugin-strip] [data-plugin-id="${plugin}"]`);
    await waitFor(`document.querySelector('[data-work-surface="${plugin}"]').getBoundingClientRect().width > 100 && !document.querySelector('[data-work-surface="${plugin}"]').hidden`);
  };
  const files = '[data-companion="files"]';
  const coding = '[data-coding-workbench]';
  const capture = async (name: string) => {
    const directory = join(process.cwd(), ".tmp/coding-component-board-v2"); await mkdir(directory, { recursive: true });
    const shot = await command<{ data: string }>("Page.captureScreenshot", { format: "png" }, sessionId);
    await writeFile(join(directory, `${name}.png`), Buffer.from(shot.data, "base64"));
  };
  await command("Emulation.setDeviceMetricsOverride", { width: 1360, height: 900, deviceScaleFactor: 1, mobile: false }, sessionId);
  await command("Page.addScriptToEvaluateOnNewDocument", { source: "window.codingTestErrors=[];addEventListener('error',e=>codingTestErrors.push(e.message));addEventListener('unhandledrejection',e=>codingTestErrors.push(String(e.reason)));" }, sessionId);
  await b.navigate(() => command("Page.navigate", { url: b.origin + "/__ui/catalog" }, sessionId));
  const boardFrame = await evaluate(`(()=>{const h=document.querySelector('.mw-catalog-shell .mw-frame__header'),title=h.querySelector('h2');return {padding:getComputedStyle(h).padding,font:getComputedStyle(title).fontSize,weight:getComputedStyle(title).fontWeight};})()`);
  await b.navigate(() => command("Page.navigate", { url: prefix + "/" }, sessionId));
  await open("workspace");
  await waitFor("document.querySelector('[data-workspace-status]').textContent.includes('还没有')");
  await fill('[data-workspace-add] [name="path"]', workspace);
  await click('[data-workspace-add] [name="confirmed"]');
  await click('[data-workspace-add] button[type="submit"]');
  await waitFor("document.querySelector('[data-workspace-add-status]').textContent.includes('目录已关联')");
  assert.ok(await evaluate<number>("document.querySelector('[data-workspace-add] button[type=submit]').getBoundingClientRect().height") <= 48, 'inline form controls do not stretch to fill the stage');
  await capture("workspace-desktop");
  await open("files");
  await waitFor(`document.querySelector('${files} [data-files-tree] [title="note.txt"]')`);
  await click(`${files} [data-files-tree] [title="nested"]`);
  await waitFor(`document.querySelector('${files} [data-files-tree] [title="nested/empty.txt"]')`);
  await click(`${files} [data-files-tree] [title="nested/empty.txt"]`);
  await waitFor(`document.querySelector('${files} [data-files-notice]').textContent.includes('空的')`);
  assert.equal(await evaluate(`document.querySelector('${files} [data-files-capture="before"]').disabled`), false);
  await click(`${files} [data-files-tree] [title="note.txt"]`);
  await waitFor(`document.querySelector('${files} [data-files-text]').value === 'first\\n中文🙂\\n'`);
  await click(`${files} [data-files-capture="before"]`);
  await waitFor(`!document.querySelector('${files} [data-files-capture="before"]').disabled`);
  await writeFile(join(workspace, "note.txt"), "second\n中文🙂\n");
  await click(`${files} [data-files-tree] [title="note.txt"]`);
  await waitFor(`document.querySelector('${files} [data-files-text]').value.startsWith('second')`);
  await click(`${files} [data-files-capture="after"]`);
  await waitFor(`document.querySelector('${files} [data-files-diff] [data-phase="ready"]')`);
  await capture("files-desktop");
  await command("Network.enable", {}, sessionId);
  await command("Network.setBlockedURLs", { urls: [prefix + "/api/plugins/io.molis.work.files/open"] }, sessionId);
  await click(`${files} [data-files-tree] [title="note.txt"]`);
  await waitFor(`document.querySelector('${files} [data-files-notice]').textContent.includes('fetch')`);
  assert.equal(await evaluate(`document.querySelector('${files} [data-files-text]').hidden && document.querySelector('${files} [data-files-copy]').disabled`), true);
  assert.equal(await evaluate(`document.querySelector('${files} [data-files-reload]').disabled`), false, 'failed reads expose a working retry');
  await command("Network.setBlockedURLs", { urls: [] }, sessionId);
  await click(`${files} [data-files-reload]`);
  await waitFor(`!document.querySelector('${files} [data-files-text]').hidden && document.querySelector('${files} [data-files-text]').value.startsWith('second')`);
  await open("diff");
  await waitFor("document.querySelector('[data-companion=" + '"diff"' + "] [data-phase=ready]')");
  await capture("diff-desktop");
  await open("text-stats");
  await waitFor("document.querySelector('[data-companion=" + '"text-stats"' + "] [data-phase=ready]')");
  await capture("stats-desktop");
  await writeFile(join(workspace, "note.txt"), "staged\n中文🙂\n");
  git("add", "note.txt");
  await writeFile(join(workspace, "note.txt"), "second\n中文🙂\n");
  await command("Network.setBlockedURLs", { urls: [prefix + "/api/plugins/io.molis.work.workspace/state"] }, sessionId);
  await open("git");
  await waitFor("document.querySelector('[data-companion=git] [data-git-status]').textContent.includes('fetch')");
  await command("Network.setBlockedURLs", { urls: [] }, sessionId);
  await click('[data-companion="git"] [data-git-refresh]');
  await waitFor("document.querySelector('[data-companion=" + '"git"' + "] [data-git-list] button')");
  await click('[data-companion="git"] [data-git-list] button');
  await waitFor("document.querySelector('[data-companion=" + '"git"' + "] [data-git-diff] [data-phase=ready]')");
  assert.equal(await evaluate("document.querySelectorAll('[data-companion=git] [data-git-list] .is-selected').length"), 1);
  await click('[data-companion="git"] [data-git-list] section:last-child button');
  await waitFor("document.querySelector('[data-companion=git] [data-git-scope]').textContent.includes('未暂存')");
  assert.equal(await evaluate("document.querySelectorAll('[data-companion=git] [data-git-list] .is-selected').length"), 1, "same path on two Git sides has only one selected row");
  await capture("git-desktop");

  await open("coding");
  await click(`${coding} [data-coding-face="files"]`);
  await waitFor(`document.querySelector('${coding} [data-files-tree] [title="note.txt"]')`);
  await click(`${coding} [data-files-tree] [title="note.txt"]`);
  await waitFor(`!document.querySelector('${coding} [data-files-text]').hidden && document.querySelector('${coding} [data-files-text]').value.startsWith('second')`);
  assert.equal(await evaluate(`document.querySelector('${coding} [data-files-text]').getBoundingClientRect().width > 100`), true, "embedded file reads are visible before a Coding session exists");
  await click(`${coding} [data-coding-face="sessions"]`);
  await click(`${coding} [data-coding-new]`);
  await waitFor(`!document.querySelector('${coding} [data-coding-task]').disabled`);
  await waitFor(`document.querySelector('${coding} [data-coding-prompt]')`);
  await capture("coding-welcome-desktop");
  await click(`${coding} [data-coding-prompt][data-coding-prompt-intent="discuss"]`);
  await waitFor(`document.querySelector('${coding} [data-coding-task]').value.includes('主要模块')`);
  assert.equal(await evaluate(`document.querySelector('${coding} [data-coding-intent]').value`), "discuss", "a starter also picks the way the round runs");
  assert.equal(await evaluate(`document.querySelector('${coding} [data-coding-prompt]').disabled`), true, "examples never overwrite an existing draft");
  await fill(`${coding} [data-coding-task]`, "first session draft");
  await click(`${coding} [data-coding-new]`);
  await waitFor(`document.querySelector('${coding} [data-coding-sessions]').querySelectorAll('[data-coding-session]').length === 2 && document.querySelector('${coding} [data-coding-task]').value === ''`);
  await fill(`${coding} [data-coding-task]`, "second session draft");
  const sessions = await evaluate<string[]>(`[...document.querySelectorAll('${coding} [data-coding-session]')].map(node=>node.dataset.codingSession)`);
  const current = await evaluate<string>(`document.querySelector('${coding} [data-coding-session][aria-current=true]').dataset.codingSession`);
  const first = sessions.find(id => id !== current)!;
  // Select through the actual tab system, rather than the directory's direct select handler.
  // Tabs store semantic ownership in persisted UI state, not a duplicated DOM id scheme.
  const state = await evaluate<any>(`JSON.parse(localStorage.getItem('molis-work-tab-workspace:${b.projectId}'))`);
  const tabs = state.panes.flatMap((pane: any) => pane.tabs);
  const firstTab = tabs.find((tab: any) => tab.itemId === first);
  const secondTab = tabs.find((tab: any) => tab.itemId === current);
  await click(`[data-tab-id="${firstTab.id}"]`);
  await waitFor(`document.querySelector('${coding} [data-coding-task]').value === 'first session draft'`);
  await click(`[data-tab-id="${secondTab.id}"]`);
  await waitFor(`document.querySelector('${coding} [data-coding-task]').value === 'second session draft'`);
  await click(`${coding} [data-coding-new]`);
  await waitFor(`document.querySelectorAll('${coding} [data-coding-session]').length === 3 && document.querySelector('${coding} [data-coding-task]').value === ''`);
  const untouched = await evaluate<string>(`document.querySelector('${coding} [data-coding-session][aria-current=true]').dataset.codingSession`);
  await click(`${coding} [data-coding-new]`);
  await waitFor(`!document.querySelector('${coding} [data-coding-new]').disabled`);
  assert.equal(await evaluate(`document.querySelectorAll('${coding} [data-coding-session]').length`), 3, "an untouched new session is reused instead of piling up");
  assert.equal(await evaluate(`document.querySelector('${coding} [data-coding-session][aria-current=true]').dataset.codingSession`), untouched);
  assert.deepEqual(await evaluate(`(()=>{const h=document.querySelector('${coding} .coding-dialogue-head'),title=h.querySelector('[data-coding-title]');return {padding:getComputedStyle(h).padding,font:getComputedStyle(title).fontSize,weight:getComputedStyle(title).fontWeight};})()`), boardFrame, 'real Coding heading matches the component board, not just its class names');
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('${coding} [data-coding-tools]')).display`), 'none', 'empty results do not consume a permanent column');
  await click(`${coding} [data-coding-results-open]`);
  assert.notEqual(await evaluate(`getComputedStyle(document.querySelector('${coding} [data-coding-tools]')).display`), 'none');
  await click(`${coding} [data-coding-results-close]`);
  assert.equal(await evaluate(`document.querySelector('${coding} [data-coding-directory]').getBoundingClientRect().left < 70`), true, 'embedded directory does not open an empty second host directory');
  await capture("coding-desktop");
  await open("coding");
  await waitFor(`document.querySelector('${coding}').dataset.codingDetail === 'false'`);
  await click(`[data-tab-id="${secondTab.id}"]`);
  await waitFor(`document.querySelector('${coding} [data-coding-task]').value === 'second session draft'`);
  await b.reloadPage();
  await waitFor(`document.querySelector('${coding} [data-coding-task]').value === 'second session draft'`);
  assert.equal(await evaluate(`document.querySelector('${coding} [data-coding-send]').disabled`), true, "no model cannot execute a run");
  const sessionsResponse = await fetch(`${prefix}/api/plugins/io.molis.work.coding/state`);
  const sessionState = await sessionsResponse.json();
  assert.equal(sessionState.sessions.length, 3, "two drafted sessions plus one reused untouched session: opening and restoring never creates extra sessions");
  for (const row of sessionState.sessions) {
    const detail = await (await fetch(`${prefix}/api/plugins/io.molis.work.coding/sessions/${row.session_id}`)).json();
    assert.equal(detail.runs.length, 0, "opening and typing do not launch a model");
  }
  await command("Emulation.setDeviceMetricsOverride", { width: 390, height: 780, deviceScaleFactor: 1, mobile: false }, sessionId);
  await evaluate(`document.querySelector('${coding} [data-coding-send]').scrollIntoView({block:'nearest'})`);
  const sendBottom = await evaluate<number>(`document.querySelector('${coding} [data-coding-send]').getBoundingClientRect().bottom`);
  assert.ok(sendBottom <= 780, "send remains reachable on a narrow screen");
  assert.equal(await evaluate(`document.querySelectorAll('${coding} .coding-composer-context .mw-btn svg').length`), 4, 'updating context labels preserves shared icons');
  // Session settings and context sources live behind the composer's "+" so the bar stays about the task.
  assert.equal(await evaluate(`document.querySelector('${coding} [data-coding-attach-menu]').hidden`), true);
  await click(`${coding} [data-coding-attach-toggle]`);
  await click(`${coding} [data-coding-context-toggle]`);
  assert.equal(await evaluate(`document.querySelector('${coding} [data-coding-attach-menu]').hidden`), true, "choosing an item closes the menu");
  assert.equal(await evaluate(`document.querySelector('${coding} [data-coding-rename]').getBoundingClientRect().height > 0`), true, 'compact session settings retain rename');
  await click(`${coding} [data-coding-attach-toggle]`);
  await click(`${coding} [data-coding-context-toggle]`);
  await capture("coding-mobile");
  await click(`${coding} [data-coding-results-open]`);
  await click(`[data-tab-id="${firstTab.id}"]`);
  await waitFor(`document.querySelector('${coding}').dataset.codingResults === 'false' && document.querySelector('${coding} [data-coding-task]').value === 'first session draft'`);
  await click(`${coding} [data-coding-results-open]`);
  await click(`${coding} [data-coding-results-close]`);
  await click(`${coding} [data-coding-directory-back]`);
  await click(`${coding} [data-coding-session]`);
  await waitFor(`document.querySelector('${coding}').dataset.codingDetail === 'true'`);
  await click('[data-directory-show]');
  await open("files");
  await waitFor(`document.querySelector('${files} [data-files-tree] [title="note.txt"]')`);
  await click(`${files} [data-files-tree] [title="note.txt"]`);
  await waitFor(`!document.querySelector('${files} [data-files-text]').hidden`);
  await evaluate("localStorage.setItem('molis-work:theme','dark');dispatchEvent(new StorageEvent('storage',{key:'molis-work:theme',newValue:'dark'}))");
  await capture("files-mobile-dark");
  await click(`${files} [data-files-close]`);
  assert.equal(await evaluate(`document.activeElement?.getAttribute('title')`), 'note.txt', 'return restores the originating file row');
  await command("Emulation.setEmulatedMedia", { features: [{ name: "prefers-reduced-motion", value: "reduce" }] }, sessionId);
  await click(`${files} [data-files-tree] [title="note.txt"]`);
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('${files} [data-files-results]')).animationName`), 'none');
  await click(`${files} [data-files-close]`);
  assert.equal(await evaluate(`document.querySelector('${files} [data-files-tree]').getBoundingClientRect().width > 100`), true);
  assert.equal(await evaluate("document.scrollingElement.scrollWidth <= innerWidth"), true);
  await click('[data-directory-show]');
  await open('git');
  await waitFor("!document.querySelector('[data-companion=git] [data-git-history]').disabled");
  await click('[data-companion=git] [data-git-history]');
  assert.equal(await evaluate("document.activeElement.hasAttribute('data-git-close')"), true);
  assert.equal(await evaluate("document.querySelector('[data-companion=git] [data-git-results]').getAttribute('aria-busy')"), 'false');
  await click('[data-companion=git] [data-git-close]');
  assert.equal(await evaluate("document.activeElement.hasAttribute('data-git-history')"), true);
  await click('[data-companion=git] [data-git-reopen]');
  await waitFor("document.querySelector('[data-companion=git] [data-git-diff] [data-phase=ready]')");
  assert.equal(await evaluate("document.activeElement.hasAttribute('data-git-close')"), true);
  await capture('git-mobile-dark');
  await click('[data-directory-show]');
  await open('workspace');
  await waitFor("!document.querySelector('[data-workspace-refresh]').disabled");
  await capture('workspace-mobile-dark');
  assert.equal(await evaluate("document.scrollingElement.scrollWidth <= innerWidth"), true);
  await command("Emulation.setDeviceMetricsOverride", { width: 1024, height: 600, deviceScaleFactor: 1, mobile: false }, sessionId);
  await click(`[data-tab-id="${secondTab.id}"]`);
  await waitFor(`document.querySelector('${coding}').dataset.codingDetail === 'true'`);
  await capture('coding-compact-dark');
  assert.equal(await evaluate("document.scrollingElement.scrollWidth <= innerWidth"), true);
  assert.deepEqual(await evaluate("window.codingTestErrors"), []);
});
