import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdir, writeFile } from 'node:fs/promises';
import { openMolisWorkProjectCatalog } from '@molis-ai/molis-work-app-desktop';
import { openGoalBrowser } from './fixtures/goal-browser.js';

test('icon tabs pin, restore, expose keyboard and touch actions and keep fixed dimensions', {timeout:90000}, async t => {
  const b = await openGoalBrowser(t, true); if (!b) return;
  const {command, sessionId, evaluate, click, waitFor, navigate, origin, projectId} = b;
  const catalog = await openMolisWorkProjectCatalog({homeDirectory:b.homeDirectory});
  for (const plugin_id of ['feed','sessions'] as const) catalog.addProjectPlugin({project_id:projectId!,plugin_id,actor_id:'icon-tabs'});
  catalog.close();
  await command('Emulation.setDeviceMetricsOverride', {width:1440,height:900,deviceScaleFactor:1,mobile:false}, sessionId);
  await navigate(() => command('Page.navigate',{url:`${origin}/projects/${projectId}/`},sessionId));
  await waitFor("document.querySelector('.tab-item[data-tab-kind=home][aria-current]')");
  const homeId = await evaluate<string>("document.querySelector('.tab-item').dataset.tabId");
  await click('.tab-item-trigger');
  await command('Input.dispatchKeyEvent', {type:'keyDown',key:'F10',code:'F10',windowsVirtualKeyCode:121,modifiers:8},sessionId);
  await waitFor("document.querySelector('[data-workspace-tab-menu]').matches(':popover-open')");
  await click('[data-tab-menu-action=pin]');
  assert.equal(await evaluate("document.querySelector('.tab-item').dataset.pinned"),'true');
  assert.equal(await evaluate("document.querySelector('.tab-item [data-tab-close]')"), null);
  await click('[data-titlebar-tabs] [data-tab-add]');
  assert.equal(await evaluate("Boolean(document.querySelector('[data-tab-menu-action=open-artifacts]'))"),false);
  await click('[data-tab-menu-action=open-goals]');
  await waitFor("document.body.dataset.desktopSurface==='goal'");
  await click('.tree-node[data-select-goal=CORE]');
  await waitFor("document.querySelector('[data-goal-frame-surface]')?.dataset.frameGoal==='CORE'");
  const coreId=await evaluate<string>("document.querySelector('.tab-item[aria-current]').dataset.tabId");
  const coreSelector=`[data-tab-id="${coreId}"]`;
  const before=await evaluate<number>(`document.querySelector('${coreSelector}').getBoundingClientRect().width`);
  await click('[data-titlebar-tabs] [data-tab-add]');
  await click('[data-tab-menu-action=open-feed]');
  assert.equal(await evaluate(`document.querySelector('${coreSelector}').getBoundingClientRect().width`),before);
  // Real right click, then Escape returns keyboard focus without changing the active Feed.
  const point=await evaluate<{x:number,y:number}>(`(async()=>{const el=document.querySelector('${coreSelector}');el.scrollIntoView({block:'nearest',inline:'nearest',behavior:'instant'});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const r=el.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);
  for(const type of ['mousePressed','mouseReleased']) await command('Input.dispatchMouseEvent',{type,...point,button:'right',clickCount:1},sessionId);
  await waitFor("document.querySelector('[data-workspace-tab-menu]').matches(':popover-open')");
  await command('Input.dispatchKeyEvent',{type:'keyDown',key:'End',windowsVirtualKeyCode:35},sessionId);
  assert.equal(await evaluate("document.activeElement.dataset.tabMenuAction"),'close');
  await command('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',windowsVirtualKeyCode:27},sessionId);
  assert.equal(await evaluate("document.activeElement.closest('[data-tab-id]')?.dataset.tabId"),coreId);
  assert.equal(await evaluate("document.querySelector('.tab-item[aria-current]').dataset.plugin"),'feed');
  await click('[data-titlebar-tabs] [data-tab-add]'); await click('[data-tab-menu-action=pin]');
  await click('[data-titlebar-tabs] [data-tab-add]'); await click('[data-tab-menu-action=open-sessions]');
  await click(coreSelector+' .tab-item-trigger');
  assert.equal(await evaluate("document.querySelectorAll('.tab-item[data-pinned]').length"),2);
  await navigate(()=>command('Page.reload',{},sessionId));
  await waitFor("document.querySelectorAll('.tab-item[data-pinned]').length===2 && document.querySelector('[data-goal-frame-surface]')?.dataset.frameGoal==='CORE'");
  assert.equal(await evaluate("document.querySelector('.tab-item').dataset.tabId"),homeId);
  const dir='.impeccable/review/icon-tabs';await mkdir(dir,{recursive:true});
  const shot=async(name:string)=>{ await evaluate("new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))).then(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))))"); const result=await command<{data:string}>('Page.captureScreenshot',{format:'png'},sessionId);await writeFile(`${dir}/${name}.png`,Buffer.from(result.data,'base64')); };
  await shot('desktop-light');
  await command('Emulation.setEmulatedMedia',{features:[{name:'prefers-color-scheme',value:'dark'}]},sessionId);await shot('desktop-dark');
  await command('Emulation.setDeviceMetricsOverride',{width:390,height:640,deviceScaleFactor:1,mobile:true},sessionId);
  await waitFor('innerWidth===390');
  await shot('mobile-before-actions');
  await click(`[data-tab-id="${homeId}"] .tab-item-trigger`);
  assert.equal(await evaluate(`document.querySelector('[data-tab-id="${homeId}"]').getBoundingClientRect().width`),44);
  await click('[data-titlebar-tabs] [data-tab-add]');
  await click('[data-tab-menu-action=pin]');
  assert.equal(await evaluate(`document.querySelector('[data-tab-id="${homeId}"]').hasAttribute('data-pinned')`),false);
  await click('[data-titlebar-tabs] [data-tab-add]'); await shot('mobile-menu-dark');
  assert.equal(await evaluate("document.documentElement.scrollWidth<=innerWidth && document.documentElement.scrollHeight<=innerHeight"),true);
  await command('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',windowsVirtualKeyCode:27},sessionId);
  await click(coreSelector+' .tab-item-trigger');await shot('mobile-dark');
  assert.equal(await evaluate(`(()=>{const tab=document.querySelector('${coreSelector}').getBoundingClientRect(),area=document.querySelector('[data-titlebar-tabs] [data-tab-scroll]').getBoundingClientRect();return tab.left>=area.left-1 && tab.right<=area.right+1})()`),true);
  await command('Emulation.setEmulatedMedia',{features:[{name:'prefers-color-scheme',value:'light'},{name:'prefers-reduced-motion',value:'reduce'}]},sessionId);await shot('mobile-light');
  await click('[data-titlebar-tabs] [data-tab-add]');
  assert.equal(await evaluate("getComputedStyle(document.querySelector('[data-workspace-tab-menu]')).animationName"),'none');
  await click('[data-tab-menu-action=close]');
  assert.equal(await evaluate(`Boolean(document.querySelector('${coreSelector}'))`),false);
});
