import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdtemp, mkdir, writeFile, rm, chmod } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { createMolisWorkWebServer } from "../apps/desktop/launchers/web/server.js";
import { GIT_CLIENT_FACTORY_SCRIPT } from "@molis-ai/molis-work-plugin-git";
const exec = promisify(execFile);

test("Git formal routes select the current grant, publish exact staged/worktree diffs and retain fixed history across restart", async () => {
  new Function("return (" + GIT_CLIENT_FACTORY_SCRIPT + ")");
  const root = await mkdtemp(path.join(tmpdir(), "git-product-")), directory = path.join(root, "repo"); await mkdir(directory);
  const git = (...args: string[]) => exec("git", args, { cwd: directory });
  const token = "git-product-control-token-0123456789abcdef";
  let server: ReturnType<typeof createMolisWorkWebServer>, origin = "";
  async function start() { server = createMolisWorkWebServer({ homeDirectory: root, controlToken: token }); await new Promise<void>(resolve => server.listen(0, "127.0.0.1", resolve)); const address = server.address(); assert.ok(address && typeof address === "object"); origin = `http://127.0.0.1:${address.port}`; }
  const close = () => new Promise<void>(resolve => server.close(() => resolve()));
  async function request(url: string, method = "GET", body?: unknown, authorized = true) {
    const response = await fetch(origin + url, { method, headers: { origin, "content-type": "application/json", "x-molis-work-idempotency-key": randomUUID(), ...(authorized ? { "x-molis-work-control-token": token } : {}) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
    return { status: response.status, body: await response.json() };
  }
  try {
    await git("init", "-b", "main"); await git("config", "user.name", "Fixture"); await git("config", "user.email", "fixture@example.invalid");
    await writeFile(path.join(directory, "note"), "base\n"); await git("add", "."); await git("commit", "-m", "base");
    await git("config", "core.filemode", "true");
    await chmod(path.join(directory, "note"), 0o755);
    await writeFile(path.join(directory, "note"), "staged\n"); await git("add", "."); await writeFile(path.join(directory, "note"), "working\n");
    await chmod(path.join(directory, "note"), 0o644);
    await start(); const projects: string[] = [];
    for (const display_name of ["Git A", "Git B"]) { const created = await request("/api/settings/projects", "POST", { display_name, user_confirmed: true }); assert.equal(created.status, 201); projects.push(created.body.project.project_id); await request(`/api/settings/projects/${projects.at(-1)}/plugins`, "POST", { plugin_id: "coding" }); }
    const api = (plugin: string, suffix: string, project = projects[0]) => `/projects/${project}/api/plugins/io.molis.work.${plugin}${suffix}`;
    assert.equal((await request(`/projects/${projects[0]}/api/workspaces`, "POST", { workspace_path: directory, user_confirmed: true })).status, 201);
    const ws = (await request(api("workspace", "/state"))).body.workspaces[0].workspace_id;
    await request(api("workspace", "/select"), "POST", { workspace_id: ws });
    const state = await request(api("git", "/state")); assert.equal(state.status, 200, JSON.stringify(state));
    assert.equal(state.body.view.phase, "ready"); assert.equal(state.body.view.staged.length, 1); assert.equal(state.body.view.changes.length, 1);
    assert.ok(!JSON.stringify(state.body).includes(directory));
    const input = { workspace_id: ws, path: ["note"], side: "index" };
    assert.equal((await request(api("git", "/diff"), "POST", input, false)).status, 403);
    assert.equal((await request(api("git", "/diff", projects[1]), "POST", input)).status, 400);
    assert.equal((await request(api("git", "/diff"), "POST", { ...input, path: ["..", "elsewhere"] })).status, 400);
    const staged = await request(api("git", "/diff"), "POST", input); assert.equal(staged.status, 200, JSON.stringify(staged));
    assert.equal(staged.body.result.before, "base\n"); assert.equal(staged.body.result.after, "staged\n");
    const fixedPath = (ref: any) => "/state?artifact_id=" + encodeURIComponent(ref.artifact_id) + "&version=" + ref.version;
    const fixed = staged.body.selected.reference, stagedView = await request(api("diff", fixedPath(fixed)));
    assert.equal(stagedView.status, 200); assert.equal(stagedView.body.view.group, "git-change-set"); assert.match(stagedView.body.html, /staged/);
    assert.match(stagedView.body.html, /新增执行权限/);
    assert.equal((await request(api("diff", fixedPath(fixed), projects[1]))).status, 400);
    const working = await request(api("git", "/diff"), "POST", { ...input, side: "worktree" });
    assert.equal(working.body.result.before, "staged\n"); assert.equal(working.body.result.after, "working\n");
    assert.match((await request(api("diff", fixedPath(working.body.selected.reference)))).body.html, /移除执行权限/);
    await writeFile(path.join(directory, "note"), "newer\n");
    assert.deepEqual((await request(api("diff", fixedPath(fixed)))).body, stagedView.body, "new reads and disk edits cannot mutate a fixed diff");
    await close(); await start();
    assert.deepEqual((await request(api("git", "/state"))).body.selected, working.body.selected);
    assert.deepEqual((await request(api("diff", fixedPath(fixed)))).body, stagedView.body);
    const reviews = (suffix: string, project = projects[0]) => `/projects/${project}/api/agent/reviews${suffix}`;
    const prepare = async (action: "stage" | "unstage") => {
      const selected = await request(api("git", "/diff"), "POST", { ...input, side: action === "stage" ? "worktree" : "index" });
      assert.equal(selected.body.result.outcome, "diff", JSON.stringify(selected));
      const prepared = await request(api("git", "/prepare-index"), "POST", { ...input, action, revision: selected.body.result.revision, operation_id: randomUUID() });
      assert.equal(prepared.status, 200, JSON.stringify(prepared)); return prepared.body.review_id;
    };
    const decide = (review_id: string, decision = "approve") => request(reviews("/decide"), "POST", { review_id, decision });
    const staleReview = await prepare("stage");
    assert.equal((await git("show", ":note")).stdout, "staged\n", "preparation must not stage anything");
    assert.equal((await request(reviews("/recovery"), "POST", { review_id: staleReview, action: "refresh" }, false)).status, 403);
    assert.equal((await request(reviews("/recovery?review_id=" + encodeURIComponent(staleReview), projects[1]))).status, 404);
    const observation = await request(reviews("/recovery?review_id=" + encodeURIComponent(staleReview)));
    assert.equal(observation.status, 200, JSON.stringify(observation));
    assert.equal(observation.body.view.observation.matches_before, true); assert.equal(observation.body.view.can_confirm_not_happened, false, "active wait cannot be resolved as not happened");
    assert.equal((await request(reviews("/recovery"), "POST", { review_id: staleReview, action: "not-happened", confirmed: true, revision: observation.body.view.observation.revision, reason: "cannot confirm an active wait" })).status, 409);
    const saveResult = (review_id: string, extra = {}) => request(api("git", "/results"), "POST", { workspace_id: ws, review_id, ...extra });
    assert.equal((await saveResult(staleReview)).status, 400, "pending is not a fixed execution result");
    assert.equal((await request(api("git", "/results"))).body.results.length, 0);
    const pendingRows = await request(reviews("?workspace_id=" + ws));
    assert.equal(pendingRows.body.reviews.length, 1); assert.equal(pendingRows.body.reviews[0].request.run, null); assert.match(pendingRows.body.html, /操作后的暂存内容/);
    assert.equal((await request(reviews("/decide", projects[1]), "POST", { review_id: staleReview, decision: "approve" })).status, 404);
    assert.equal((await request(reviews("?session_id=unrelated"))).body.reviews.length, 0);
    await writeFile(path.join(directory, "note"), "changed after review\n");
    const staleResult = await decide(staleReview); assert.equal(staleResult.status, 200); assert.equal(staleResult.body.receipt.effect_settled, false); assert.match(staleResult.body.receipt.effect_error, /改变/);
    assert.equal((await git("show", ":note")).stdout, "staged\n");
    const lockedReview = await prepare("stage");
    const indexLock = path.join(directory, ".git", "index.lock");
    await writeFile(indexLock, "another Git operation");
    const lockedResult = await decide(lockedReview);
    assert.equal(lockedResult.body.receipt.effect_settled, false);
    assert.match(lockedResult.body.receipt.effect_error, /其他操作使用/);
    await rm(indexLock);
    const rejected = await prepare("stage"); assert.equal((await decide(rejected, "reject")).body.receipt.status, "rejected");
    assert.equal((await git("show", ":note")).stdout, "staged\n");
    const approved = await prepare("stage"); const applied = await decide(approved);
    assert.equal(applied.status, 200, JSON.stringify(applied)); assert.equal(applied.body.receipt.effect_settled, true, JSON.stringify(applied));
    assert.equal((await git("show", ":note")).stdout, "changed after review\n");
    assert.equal((await decide(approved)).status, 409, "one decision cannot stage twice");
    assert.equal((await request(api("git", "/results"), "POST", { workspace_id: ws, review_id: approved }, false)).status, 403);
    assert.equal((await request(api("git", "/results", projects[1]), "POST", { workspace_id: ws, review_id: approved })).status, 400);
    const savedResult = await saveResult(approved, { outcome: "failed", summary: "forged", result: { outcome: "denied" } });
    assert.equal(savedResult.status, 200, JSON.stringify(savedResult));
    assert.equal(savedResult.body.result.outcome, "succeeded"); assert.equal(savedResult.body.result.review.review_id, approved);
    assert.deepEqual(savedResult.body.result.review.paths, ["note"]); assert.equal(savedResult.body.result.review.decided_by, "web-user");
    assert.deepEqual((await saveResult(approved)).body, savedResult.body, "retry reuses the fixed version");
    const savedFailure = await saveResult(staleReview); assert.equal(savedFailure.body.result.outcome, "failed"); assert.equal(savedFailure.body.result.review.failure_reason, staleResult.body.receipt.effect_error);
    assert.notDeepEqual(savedFailure.body.reference, savedResult.body.reference);
    const concurrent = await Promise.all([saveResult(rejected), saveResult(rejected)]);
    assert.equal(concurrent[0].status, 200); assert.deepEqual(concurrent[0].body, concurrent[1].body);
    assert.equal(concurrent[0].body.result.outcome, "denied");
    assert.equal((await git("show", ":note")).stdout, "changed after review\n", "saving results never executes Git");
    const createdSession = await request(api("coding", "/sessions"), "POST", { title: "Git 固定反馈", runtime_id: "prologue" });
    assert.equal(createdSession.status, 200, JSON.stringify(createdSession));
    const codingSession = createdSession.body.session.session_id;
    const materialsPath = `/sessions/${codingSession}/materials`;
    const currentChoices = (await request(api("coding", materialsPath))).body.materials;
    assert.ok(currentChoices.some((item: any) => item.reference.artifact_id === savedResult.body.reference.artifact_id && item.reference.version === concurrent[0].body.reference.version), "the formal graph exposes the latest Git result to Coding");
    const refs = [fixed, savedFailure.body.reference];
    assert.equal((await request(api("coding", `/sessions/${codingSession}`), "PATCH", { materials: refs, draft: "按固定差异反馈" })).status, 200);
    const choices = (await request(api("coding", materialsPath))).body.materials;
    const fixedDiff = choices.find((item: any) => item.reference.artifact_id === fixed.artifact_id && item.reference.version === fixed.version);
    const fixedFailure = choices.find((item: any) => item.reference.artifact_id === savedFailure.body.reference.artifact_id && item.reference.version === savedFailure.body.reference.version);
    assert.ok(fixedDiff && !fixedDiff.error, JSON.stringify(fixedDiff)); assert.match(fixedDiff.text, /base\n/); assert.match(fixedDiff.text, /staged\n/); assert.match(fixedDiff.text, /100755/);
    assert.ok(fixedFailure && !fixedFailure.error, JSON.stringify(fixedFailure)); assert.ok(fixedFailure.text.includes(staleResult.body.receipt.effect_error));
    const interrupted = await prepare("unstage"); await close(); await start();
    assert.deepEqual((await request(api("coding", `/sessions/${codingSession}`))).body.materials, refs);
    const restoredChoices = (await request(api("coding", materialsPath))).body.materials;
    assert.deepEqual(restoredChoices.find((item: any) => item.reference.artifact_id === fixed.artifact_id && item.reference.version === fixed.version), fixedDiff);
    assert.deepEqual(restoredChoices.find((item: any) => item.reference.artifact_id === savedFailure.body.reference.artifact_id && item.reference.version === savedFailure.body.reference.version), fixedFailure);
    assert.deepEqual((await saveResult(approved)).body, savedResult.body, "fixed result survives restart and another output publication");
    const restoredResults = (await request(api("git", "/results"))).body.results;
    assert.deepEqual(restoredResults.find((item: any) => item.result.review.review_id === approved).saved, savedResult.body);
    const history = (await request(reviews("?workspace_id=" + ws))).body.reviews;
    assert.equal(history.find((row: any) => row.request.review_id === staleReview).receipt.effect_error, staleResult.body.receipt.effect_error, "restart preserves the original refusal reason, not only its failed classification");
    assert.equal(history.find((row: any) => row.request.review_id === lockedReview).receipt.effect_error, lockedResult.body.receipt.effect_error, "restart also preserves a failure reported by the dispatched operation");
    assert.equal((await decide(lockedReview)).status, 409, "restoring diagnostic text never grants permission to retry");
    assert.ok(history.every((row: any) => !("failure_reason" in row.receipt)), "private diagnostic storage is projected only through the existing receipt contract");
    assert.equal(history.find((row: any) => row.request.review_id === approved).receipt.effect_settled, true);
    assert.equal(history.find((row: any) => row.request.review_id === interrupted).receipt.status, "cancelled");
    assert.equal((await decide(interrupted)).status, 409);
    assert.equal((await git("show", ":note")).stdout, "changed after review\n", "restart never dispatches an old approval waiter");
    const undo = await prepare("unstage"); assert.equal((await decide(undo)).body.receipt.effect_settled, true);
    assert.equal((await git("show", ":note")).stdout, "base\n"); assert.equal((await git("diff", "--numstat")).stdout.trim().length > 0, true, "unstaging preserves disk edits");
    const authorizationChanged = await prepare("stage");
    await request(`/projects/${projects[0]}/api/workspaces/${ws}/unlink`, "POST", { user_confirmed: true });
    assert.equal((await decide(authorizationChanged)).body.receipt.effect_settled, false);
    assert.equal((await git("show", ":note")).stdout, "base\n");
    assert.equal((await saveResult(approved)).status, 400, "unlinking prevents further result publication");
    const revoked = await request(api("git", "/diff"), "POST", input);
    assert.equal(revoked.body.result.outcome, "denied");
  } finally { if (server!) await close(); await rm(root, { recursive: true, force: true }); }
});
