import assert from "node:assert/strict";
import test from "node:test";
import { mkdir, writeFile } from "node:fs/promises";
import { DEMO_BOARD_ID, GoalProjectApplication } from "@molis-ai/molis-work-app-local-host";
import { openGoalBrowser } from "./fixtures/goal-browser.js";

const captures = new URL("../.impeccable/review/", import.meta.url);

test("Goal workspace keeps details in a sidebar rail; camera and draft survive reopen", { timeout: 90_000 }, async t => {
  const browser = await openGoalBrowser(t);
  if (!browser) return;
  const { store, origin, command, sessionId, evaluate, waitFor, click, navigate, reloadPage } = browser;
  const app = new GoalProjectApplication(store);
  const created = app.goalEvents.createIntent({ board_id: DEMO_BOARD_ID, title: "完成首次内部试用", outcome: "新用户能创建目标、连接终端，并读回真实工作结果。", actor_id: "web-user", actor_kind: "user", idempotency_key: "canvas-intent" });
  const goalId = created.goal.goal_id;
  app.goalEvents.configure({ board_id: DEMO_BOARD_ID, goal_id: goalId, actor_id: "web-user", actor_kind: "user", expected_version: 0, idempotency_key: "canvas-config", types: [{ type_id: "delivery", version: 1, name: "成果", purpose: "保存可检查的结果", semantic_family: "delivery", fields: [{ field_id: "body", name: "结果", purpose: "实际结果与证据", format: "longtext", required: true }] }] });
  app.goalEvents.report({ board_id: DEMO_BOARD_ID, goal_id: goalId, actor_id: "codex", actor_kind: "runtime", idempotency_key: "canvas-report", events: [{ type_id: "delivery", type_version: 1, title: "创建与连接流程已接通", fields: { body: "已在隔离测试项目中创建 Goal，并通过正式接口读回。下一步验证终端与时间线同时使用。" } }] });
  const before = store.snapshot(DEMO_BOARD_ID);
  await mkdir(captures, { recursive: true });
  const screenshot = async (name: string) => {
    const { data } = await command<{ data: string }>("Page.captureScreenshot", { format: "png", captureBeyondViewport: false }, sessionId);
    await writeFile(new URL("production-" + name + ".png", captures), Buffer.from(data, "base64"));
  };
  const rect = (selector: string) => evaluate<{ x: number; y: number; width: number; height: number }>("(()=>{const r=document.querySelector(" + JSON.stringify(selector) + ").getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}})()");
  const key = async (key: string, code: number) => {
    await command("Input.dispatchKeyEvent", { type: "keyDown", key, windowsVirtualKeyCode: code, ...(key === "Enter" ? { text: "\r", unmodifiedText: "\r" } : {}) }, sessionId);
    await command("Input.dispatchKeyEvent", { type: "keyUp", key, windowsVirtualKeyCode: code }, sessionId);
  };
  await command("Page.addScriptToEvaluateOnNewDocument", { source: "window.__canvasErrors=[];addEventListener('error', e=>window.__canvasErrors.push(e.message));addEventListener('unhandledrejection', e=>window.__canvasErrors.push(String(e.reason)));" }, sessionId);
  await command("Emulation.setDeviceMetricsOverride", { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false }, sessionId);
  await command("Emulation.setEmulatedMedia", { features: [{ name: "prefers-reduced-motion", value: "reduce" }] }, sessionId);
  await navigate(() => command("Page.navigate", { url: origin + "/" }, sessionId));
  await waitFor("document.body.dataset.desktopSurface === 'home'");
  await screenshot("home-light");
  await click('[data-plugin-strip] [data-plugin-id="goals"]');
  await waitFor("document.querySelector('[data-goal-momentum]')?.dataset.loaded === 'true'");
  await click("[data-board-view-tab=canvas]");
  await waitFor("document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView === 'canvas'");
  const camera = () => evaluate("JSON.stringify(document.querySelector('[data-graph-stage]').dataset)");
  await click('[data-graph-zoom="in"]');
  const beforeOpen = await camera();
  await waitFor("Boolean(document.querySelector(" + JSON.stringify('[data-graph-node][data-goal-id="' + goalId + '"] [data-graph-open]') + "))");
  await evaluate("document.querySelector(" + JSON.stringify('[data-graph-node][data-goal-id="' + goalId + '"] [data-graph-open]') + ").click()");
  await waitFor("!document.querySelector('[data-goal-node-workspace]').hidden && document.querySelector('[data-goal-node-workspace]').dataset.expandedGoal === " + JSON.stringify(goalId));
  await waitFor("document.querySelector('[data-event-timeline] [data-timeline-item]')");
  await waitFor("document.querySelector('[data-goal-node-workspace]')?.dataset.detailsOpen === 'true' && document.querySelector('[data-goal-details-aside]')?.getBoundingClientRect().width > 280");
  const stage = await rect("[data-plugin-stage]"), frame = await rect("[data-goal-node-workspace]"), terminal = await rect("[data-tui-pane]"), info = await rect("[data-goal-details-aside]");
  assert.ok(Math.abs(frame.x - stage.x) < 2 && Math.abs(stage.width - frame.width) < 2);
  assert.equal(await evaluate("document.querySelector('.goal-node-toolbar [data-goal-details-toggle]')"), null);
  assert.equal(await evaluate("Boolean(document.querySelector('[data-goal-details-aside] [data-goal-details-toggle]'))"), true);
  assert.ok(info.width >= 280 && info.width <= 330 && terminal.x + terminal.width <= info.x + 2);
  assert.ok(terminal.height > 700 && terminal.y >= frame.y);
  assert.equal(await evaluate("document.querySelector('[data-goal-work-mode=conversation]').disabled"), true);
  await screenshot("goal-light");
  await evaluate("window.__terminal=document.querySelector('[data-tui-terminal]')");
  // The frame header is not a draggable graph node.
  const expandedCamera = await camera();
  await command("Input.dispatchMouseEvent", { type: "mousePressed", x: frame.x + 120, y: frame.y + 18, button: "left", clickCount: 1 }, sessionId);
  await command("Input.dispatchMouseEvent", { type: "mouseMoved", x: frame.x + 220, y: frame.y + 100, button: "left", buttons: 1 }, sessionId);
  await command("Input.dispatchMouseEvent", { type: "mouseReleased", x: frame.x + 220, y: frame.y + 100, button: "left", clickCount: 1 }, sessionId);
  assert.deepEqual(await rect("[data-goal-node-workspace]"), frame);
  assert.equal(await camera(), expandedCamera);
  await click('[data-goal-details-toggle]');
  assert.equal(await evaluate("document.querySelector('[data-document-pane]').hidden"), true);
  assert.ok((await rect("[data-goal-details-aside]")).width <= 40, "Collapsed details keep a slim rail");
  assert.ok((await rect("[data-tui-pane]")).width >= terminal.width - 1);
  await reloadPage();
  await waitFor("document.querySelector('[data-goal-node-workspace]').dataset.detailsOpen === 'false'");
  await click('[data-goal-details-toggle]');
  await click('[data-record-menu] > summary');
  await click('[data-record-menu] [data-event-form-open="note"]');
  await evaluate("(()=>{const input=document.querySelector('[data-event-form=note] textarea');input.value='保留在本地输入框里的备注';input.dispatchEvent(new Event('input',{bubbles:true}));})()");
  await click('[data-goal-collapse]');
  assert.equal(await camera(), beforeOpen);
  await evaluate("document.querySelector(" + JSON.stringify('[data-graph-node][data-goal-id="' + goalId + '"] [data-graph-open]') + ").click()");
  await waitFor("!document.querySelector('[data-goal-node-workspace]').hidden && document.querySelector('[data-goal-node-workspace]')?.dataset.detailsOpen === 'true' && document.querySelector('[data-event-form=note] footer [data-event-back]')?.getBoundingClientRect().width > 0");
  assert.equal(await evaluate("document.querySelector('[data-event-form=note] textarea').value"), "保留在本地输入框里的备注");
  assert.equal(await evaluate("document.querySelector('[data-goal-work-main]').inert"), true);
  await click('[data-event-form=note] footer [data-event-back]');
  assert.deepEqual(store.snapshot(DEMO_BOARD_ID).goals, before.goals);
  assert.deepEqual(store.snapshot(DEMO_BOARD_ID).runs, before.runs);
  await evaluate("localStorage.setItem('molis-work:theme','dark');window.dispatchEvent(new StorageEvent('storage',{key:'molis-work:theme',newValue:'dark'}))");
  await waitFor("document.documentElement.dataset.resolvedTheme === 'dark'");
  await screenshot("goal-dark");
  await command("Emulation.setDeviceMetricsOverride", { width: 800, height: 1000, deviceScaleFactor: 1, mobile: false }, sessionId);
  await waitFor("document.querySelector('[data-goal-work-main]').inert");
  const overlay = await rect('[data-document-pane]'), mediumTerminal = await rect('[data-tui-pane]');
  assert.ok(overlay.x < mediumTerminal.x + mediumTerminal.width, "Narrow details overlay the work area");
  const description = '.goal-info-actions [data-event-reader="description"]';
  await click(description);
  await waitFor("document.activeElement.hasAttribute('data-reader-title')");
  await key("Tab", 9);
  assert.equal(await evaluate("Boolean(document.activeElement.closest('[inert]'))"), false);
  await screenshot("reader-800");
  await click('.detail-toolbar [data-event-back]');
  await click('[data-goal-details-toggle]');
  await waitFor("!document.querySelector('[data-goal-work-main]').inert");
  await screenshot("goal-800");
  await command("Emulation.setDeviceMetricsOverride", { width: 390, height: 844, deviceScaleFactor: 1, mobile: true }, sessionId);
  await waitFor("document.querySelector('[data-goal-node-workspace]').getBoundingClientRect().width < 390");
  await screenshot("goal-mobile");
  assert.equal(await evaluate("document.documentElement.scrollWidth <= innerWidth"), true);
  await click('[data-goal-details-toggle]');
  await click(description);
  await waitFor("document.activeElement.hasAttribute('data-reader-title')");
  await screenshot("reader-mobile");
  await click('.detail-toolbar [data-event-back]');
  assert.deepEqual(await evaluate("window.__canvasErrors"), []);
});
