import assert from "node:assert/strict";
import test from "node:test";
import { DEMO_BOARD_ID } from "@molis-ai/molis-work-app-local-host";
import { openGoalBrowser } from "./fixtures/goal-browser.js";

test("canvas retries graph loading, pans without bounds, drags compact nodes without changing dependencies, and restores its view", { timeout: 60_000 }, async (t) => {
  const browser = await openGoalBrowser(t);
  if (!browser) return;
  const { store, origin, before, sessionId, command, evaluate, waitFor, click, reloadPage, navigate } = browser;
  await command("Network.enable", {}, sessionId);
  await command("Emulation.setDeviceMetricsOverride", { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false }, sessionId);
  await command("Network.setBlockedURLs", { urls: [origin + "/api/board/momentum*"] }, sessionId);
  await navigate(() => command("Page.navigate", { url: origin + "/" }, sessionId));
  await click('[data-plugin-id="goals"]');
  await click("[data-board-view-tab=canvas]");
  await waitFor("document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView === 'canvas'");
  await waitFor("document.querySelector('[data-retry-goal-momentum]')?.hidden === false && !document.querySelector('[data-goal-momentum]').hasAttribute('aria-busy')");
  assert.deepEqual(store.snapshot(DEMO_BOARD_ID).runs, before.runs);
  await command("Network.setBlockedURLs", { urls: [] }, sessionId);
  await click("[data-retry-goal-momentum]");
  await waitFor("document.querySelector('[data-goal-momentum]')?.dataset.loaded === 'true'");
  const count = before.goals.filter(goal => !goal.archived_at && !goal.trashed_at).length;
  assert.equal(await evaluate("document.querySelectorAll('[data-momentum-node]').length"), count);
  const edge = '[data-graph-edge][data-edge-from="CORE"][data-edge-to="INTERFACES"] path';
  await waitFor("document.querySelector(" + JSON.stringify(edge) + ")?.getAttribute('d')?.startsWith('M ')");
  const coords = () => evaluate<{ x: number; y: number; z: number }>("(()=>{const s=document.querySelector('[data-graph-stage]');return {x:Number(s.dataset.cameraX),y:Number(s.dataset.cameraY),z:Number(s.dataset.graphScale)}})()");
  const start = await coords();
  await command("Input.dispatchMouseEvent", { type: "mouseWheel", x: 1350, y: 500, deltaX: -1200, deltaY: 2300 }, sessionId);
  await waitFor("Number(document.querySelector('[data-graph-stage]').dataset.cameraX) > " + (start.x + 1000));
  const panned = await coords();
  assert.ok(panned.y < start.y - 2000, "world movement is not clamped to positive scroll bounds");
  await click('[data-graph-zoom="fit"]');
  const node = '[data-momentum-node][data-goal-id="INTERFACES"]';
  const point = await evaluate<{ x: number; y: number }>("(()=>{const r=document.querySelector(" + JSON.stringify(node) + ").getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()");
  const oldEdge = await evaluate("document.querySelector(" + JSON.stringify(edge) + ").getAttribute('d')");
  const oldPosition = await evaluate("document.querySelector(" + JSON.stringify(node) + ").style.transform");
  await command("Input.dispatchMouseEvent", { type: "mousePressed", ...point, button: "left", clickCount: 1 }, sessionId);
  await command("Input.dispatchMouseEvent", { type: "mouseMoved", x: point.x + 80, y: point.y - 35, button: "left", buttons: 1 }, sessionId);
  await command("Input.dispatchMouseEvent", { type: "mouseReleased", x: point.x + 80, y: point.y - 35, button: "left", clickCount: 1 }, sessionId);
  await waitFor("document.querySelector(" + JSON.stringify(node) + ").style.transform !== " + JSON.stringify(oldPosition));
  assert.notEqual(await evaluate("document.querySelector(" + JSON.stringify(edge) + ").getAttribute('d')"), oldEdge);
  assert.equal(await evaluate("document.querySelector('[data-goal-node-workspace]').hidden"), true, "dragging must not also open a Goal");
  const moved = await evaluate("document.querySelector(" + JSON.stringify(node) + ").style.transform");
  await reloadPage();
  await waitFor("document.querySelector('[data-goal-momentum]')?.dataset.loaded === 'true'");
  assert.equal(await evaluate("document.querySelector(" + JSON.stringify(node) + ").style.transform"), moved);
  await click(node + " [data-graph-open]");
  await waitFor("document.querySelector('[data-goal-node-workspace]').dataset.expandedGoal === 'INTERFACES'");
  assert.equal(await evaluate("location.pathname"), "/goals/INTERFACES");
  const after = store.snapshot(DEMO_BOARD_ID);
  assert.deepEqual(after.goals, before.goals);
  assert.deepEqual(after.relations, before.relations);
  assert.deepEqual(after.runs, before.runs);
});
