import assert from "node:assert/strict";
import { readFileSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import test from "node:test";
import Database from "better-sqlite3";
import { GoalsQueryService, GoalsRepository, migrateProjectGuidance, migrateProjectGuidanceRevisions, migrateRiskTreatmentPlan } from "@molis-ai/molis-work-module-goals";
import { LocalProjectDatabase } from "@molis-ai/molis-work-app-local-host";
import { GoalProjectApplication } from "@molis-ai/molis-work-app-local-host";

import { materializeGoalEventV35Fixture } from "./goal-event-v35-fixture.js";

// Captured from the production initializer before GW6 changes, not regenerated by the new schema.
const baseline: Array<{ type: string; name: string; tbl_name: string; sql: string }> = JSON.parse(
  readFileSync(new URL("./fixtures/goals-storage-before-gw6.json", import.meta.url), "utf8"),
);
const at = "2026-08-10T01:02:03.000Z";
const query = (store: LocalProjectDatabase) => new GoalsQueryService(new GoalsRepository(store.db));
const schema = (table: string) => baseline.find(row => row.type === "table" && row.name === table)!.sql;

// One intended difference: the V3 requirement ledger (coverage_items) was removed with the V3 import (2026-10-04).
test("fresh Goals tables, indexes, defaults and constraints match the pre-GW6 schema, without the V3 requirement ledger", () => {
  const store = new LocalProjectDatabase(":memory:");
  try {
    const expected = baseline.filter(row => row.tbl_name !== "coverage_items");
    const tables = new Set(baseline.map(row => row.tbl_name));
    const actual = (store.db.prepare("SELECT type, name, tbl_name, sql FROM sqlite_master WHERE sql IS NOT NULL ORDER BY type, name").all() as typeof baseline)
      .filter(row => tables.has(row.tbl_name)).map(row => ({ ...row, sql: row.sql.replace(/\s+/g, " ").trim() }));
    assert.deepEqual(actual, expected);
    assert.equal(store.db.prepare("SELECT 1 FROM sqlite_master WHERE name = 'coverage_items'").get(), undefined);
  } finally { store.close(); }
});

for (const migration of [15, 25, 26]) test(`migration ${migration} rolls back its real schema/data changes and retries without duplicate history`, () => {
  const db = new Database(":memory:");
  try {
    db.exec("CREATE TABLE schema_migrations(migration_id INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)");
    db.exec("CREATE TABLE boards(board_id TEXT PRIMARY KEY)");
    db.prepare("INSERT INTO boards VALUES (?)").run("old-project");
    if (migration === 15) db.exec(schema("risks").replace("treatment_plan TEXT NOT NULL DEFAULT '', ", ""));
    if (migration === 26) {
      let old = schema("project_guidance_entries");
      for (const field of ["revision INTEGER NOT NULL DEFAULT 1, ", "active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)), ",
        "updated_by TEXT NOT NULL, ", "updated_at TEXT NOT NULL, "]) old = old.replace(field, "");
      db.exec(old);
      db.prepare(`INSERT INTO project_guidance_entries(guidance_id, board_id, position, kind, content, content_hash,
        source_refs_json, created_by, confirmation_summary, reason, created_at) VALUES(?, ?, 1, 'context', ?, 'historical-content-id', '[]', 'original-user', 'confirmed', 'keep history', ?)`)
        .run("old-guidance", "old-project", "保留原项目说明", at);
    }
    db.exec(`CREATE TRIGGER reject_marker BEFORE INSERT ON schema_migrations WHEN NEW.migration_id = ${migration}
      BEGIN SELECT RAISE(ABORT, 'injected migration failure'); END`);
    const run = () => migration === 15 ? migrateRiskTreatmentPlan(db) : migration === 25 ? migrateProjectGuidance(db) : migrateProjectGuidanceRevisions(db);
    assert.throws(run, /injected migration failure/);
    assert.equal(db.prepare("SELECT * FROM schema_migrations").all().length, 0);
    if (migration === 15) assert.equal((db.pragma("table_info(risks)") as Array<{ name: string }>).some(c => c.name === "treatment_plan"), false);
    if (migration === 25) assert.equal(db.prepare("SELECT 1 FROM sqlite_master WHERE name='project_guidance_entries'").get(), undefined);
    if (migration === 26) {
      assert.equal((db.pragma("table_info(project_guidance_entries)") as Array<{ name: string }>).some(c => c.name === "revision"), false);
      assert.equal(db.prepare("SELECT content FROM project_guidance_entries").pluck().get(), "保留原项目说明");
      assert.equal(db.prepare("SELECT 1 FROM sqlite_master WHERE name='project_guidance_revisions'").get(), undefined);
    }
    db.exec("DROP TRIGGER reject_marker"); run();
    assert.equal(db.prepare("SELECT migration_id FROM schema_migrations").pluck().get(), migration);
    if (migration === 15) assert.ok((db.pragma("table_info(risks)") as Array<{ name: string }>).some(c => c.name === "treatment_plan"));
    if (migration === 25) assert.ok(db.prepare("SELECT 1 FROM sqlite_master WHERE name='project_guidance_entries'").get());
    if (migration === 26) {
      assert.deepEqual(db.prepare("SELECT revision, active, updated_by, updated_at, content FROM project_guidance_entries").get(),
        { revision: 1, active: 1, updated_by: "original-user", updated_at: at, content: "保留原项目说明" });
      assert.deepEqual(db.prepare("SELECT revision_id, revision, changed_by, created_at, content FROM project_guidance_revisions").get(),
        { revision_id: "migration:old-guidance:1", revision: 1, changed_by: "original-user", created_at: at, content: "保留原项目说明" });
      run();
      assert.equal(db.prepare("SELECT COUNT(*) FROM project_guidance_revisions").pluck().get(), 1);
    }
  } finally { db.close(); }
});


test("Host migration 30 rolls back Goals and Execution together, then preserves original revisions across reopen", () => {
  const { directory, path } = materializeGoalEventV35Fixture("approved");
  // This historical dump predates the product rename; never use the current demo identity.
  const historicalBoardId = "goalboard-v1-demo";
  let store = new LocalProjectDatabase(path);
  try {
    const c = new GoalProjectApplication(store);
    store.db.prepare(`
      INSERT INTO policy_bindings (
        policy_binding_id, board_id, goal_id, scope, policy_json, state, created_by, reason, created_at
      ) VALUES (?, ?, NULL, 'project_default', ?, 'active', 'original-user', '历史规则', ?)
    `).run("historical-policy", historicalBoardId, JSON.stringify({ goal_mode: "preferred", required_capabilities: ["testing"] }), at);
    c.goals.commands.addProjectGuidance({ board_id: historicalBoardId, actor_id: "original-user", kind: "quality_bar",
      content: "历史说明与作者不能丢失", reason: "保留历史", confirmation_summary: "确认", user_confirmed: true, idempotency_key: "historical-guidance" });
    const demoBefore = store.snapshot(historicalBoardId);
    const acceptedBefore = demoBefore.goals.find(goal => goal.goal_id === "CORE");
    assert.ok(acceptedBefore);
    assert.equal(acceptedBefore.definition_state, "accepted");
    assert.equal(acceptedBefore.accepted_by, "demo-user");
    assert.ok(acceptedBefore.accepted_at);
    const guidanceBefore = query(store).readProjectGuidance(historicalBoardId);
    // Independent pre-migration schema: captured old DDL with the later revision column removed.
    store.db.pragma("foreign_keys = OFF");
    const rows = store.db.prepare("SELECT * FROM goals").all() as Array<Record<string, unknown>>;
    store.db.exec("DROP TABLE goal_contract_revisions; DROP TABLE coverage_contract_revisions; DROP TABLE goals;");
    store.db.exec(schema("goals").replace("current_contract_revision INTEGER NOT NULL DEFAULT 1, ", ""));
    for (const row of rows) {
      delete row.current_contract_revision;
      const keys = Object.keys(row);
      store.db.prepare(`INSERT INTO goals (${keys.join(',')}) VALUES (${keys.map(() => '?').join(',')})`).run(...Object.values(row));
    }
    store.db.exec("DELETE FROM schema_migrations WHERE migration_id=30");
    store.db.exec("ALTER TABLE claims DROP COLUMN contract_revision");
    store.db.exec("CREATE TRIGGER reject_30 BEFORE INSERT ON schema_migrations WHEN NEW.migration_id=30 BEGIN SELECT RAISE(ABORT, 'migration30 failure'); END");
    store.close();
    const failure = spawnSync(process.execPath, ["--import", "tsx", "--input-type=module", "-e",
      `import {LocalProjectDatabase} from '@molis-ai/molis-work-app-local-host'; try {new LocalProjectDatabase(process.argv[1]); process.exitCode=1} catch(e) {if(!String(e).includes('migration30 failure')) throw e}`, path], { encoding: "utf8" });
    assert.equal(failure.status, 0, failure.stderr);
    const raw = new Database(path);
    try {
      for (const table of ["goals", "claims"]) assert.equal((raw.pragma(`table_info(${table})`) as Array<{ name: string }>).some(r => r.name === (table === "goals" ? "current_contract_revision" : "contract_revision")), false);
      assert.equal(raw.prepare("SELECT 1 FROM sqlite_master WHERE name='goal_contract_revisions'").get(), undefined);
      assert.equal(raw.prepare("SELECT 1 FROM schema_migrations WHERE migration_id=30").get(), undefined);
      raw.exec("DROP TRIGGER reject_30");
    } finally { raw.close(); }
    store = new LocalProjectDatabase(path);
    const demoAfter = store.snapshot(historicalBoardId);
    for (const key of ["goals", "relations", "risks", "policy_bindings"] as const) assert.deepEqual(demoAfter[key], demoBefore[key], key);
    assert.deepEqual(query(store).readProjectGuidance(historicalBoardId), guidanceBefore);
    const acceptedRevision = demoAfter.goal_contract_revisions.find(row => row.goal_id === "CORE");
    assert.ok(acceptedRevision);
    assert.equal(acceptedRevision.changed_by, acceptedBefore.accepted_by);
    assert.equal(acceptedRevision.created_at, acceptedBefore.accepted_at);
    assert.deepEqual(acceptedRevision.contract.acceptance_criteria,
      acceptedBefore.acceptance_criteria.map(({ criterion_id: _id, goal_id: _goal, ...criterion }) => criterion));
    store.close(); store = new LocalProjectDatabase(path);
    assert.deepEqual(query(store).readProjectGuidance(historicalBoardId), guidanceBefore);
  } finally { if (store.db.open) store.close(); rmSync(directory, { recursive: true, force: true }); }
});

