import assert from 'node:assert/strict';
import test from 'node:test';
import { openMolisWorkProjectCatalog } from '@molis-ai/molis-work-app-desktop';
import { DEMO_BOARD_ID } from '@molis-ai/molis-work-app-local-host';
import { openGoalBrowser } from './fixtures/goal-browser.js';

test('Relation HTTP validates direction/type/project scope and replays writes without duplicate history',{timeout:30000},async t=>{
  const b=await openGoalBrowser(t,true);if(!b)return;
  const catalog=await openMolisWorkProjectCatalog({homeDirectory:b.homeDirectory});
  const other=await catalog.createProject({display_name:'其他隔离项目',actor_id:'test'});catalog.close();
  const prefix=`/projects/${b.projectId}`;
  await b.navigate(()=>b.command('Page.navigate',{url:b.origin+prefix+'/'},b.sessionId));
  const post=(path:string,body:unknown,key:string)=>b.evaluate<{status:number,body:any}>(`(async()=>{const r=await fetch(${JSON.stringify(path)},{method:'POST',headers:{...globalThis.molisWorkControlHeaders(),'x-molis-work-idempotency-key':${JSON.stringify(key)}},body:JSON.stringify(${JSON.stringify(body)})});return {status:r.status,body:await r.json()}})()`);
  const payload={direction:'incoming',target_goal_id:'PLATFORM',type:'extends',reason:'独立关系HTTP验收'};
  const count=b.store.snapshot(DEMO_BOARD_ID).relations.length;
  for(const invalid of [{...payload,type:'unknown'},{...payload,direction:'unknown'},{...payload,reason:''}])assert.equal((await post(prefix+'/api/goals/CORE/relations',invalid,'invalid-payload')).status,400);
  assert.equal((await post(`/projects/${other.project_id}/api/goals/CORE/relations`,payload,'wrong-project')).status,400);
  assert.equal(b.store.snapshot(DEMO_BOARD_ID).relations.length,count);
  const unauthorized=await b.evaluate<number>(`fetch('${prefix}/api/goals/CORE/relations',{method:'POST',body:'{}'}).then(r=>r.status)`);
  assert.equal(unauthorized,403);
  const first=await post(prefix+'/api/goals/CORE/relations',payload,'create-relation');
  assert.equal(first.status,200,JSON.stringify(first.body));
  const retry=await post(prefix+'/api/goals/CORE/relations',payload,'create-relation');
  assert.equal(retry.body.replayed,true,JSON.stringify(retry));assert.equal(retry.body.relation_id,first.body.relation_id);
  assert.equal(b.store.snapshot(DEMO_BOARD_ID).relations.length,count+1);
  const path=prefix+'/api/relations/'+first.body.relation_id+'/deactivate';
  const deactivated=await post(path,{reason:'验收完毕解除'},'remove-relation');assert.equal(deactivated.status,200);
  assert.equal((await post(path,{reason:'验收完毕解除'},'remove-relation')).body.replayed,true);
  assert.equal(b.store.snapshot(DEMO_BOARD_ID).relations.find(r=>r.relation_id===first.body.relation_id)?.state,'inactive');
  const history=b.store.readEventsDescending(DEMO_BOARD_ID).filter(e=>e.object_id===first.body.relation_id);
  assert.equal(history.filter(e=>e.type==='relation.added').length,1);assert.equal(history.filter(e=>e.type==='relation.deactivated').length,1);
});
