import { buildMolisWorkWebView } from "@molis-ai/molis-work-app-local-host";
import assert from "node:assert/strict";
import { readFileSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import test from "node:test";
import Database from "better-sqlite3";
import { GoalsQueryService, GoalsRepository, migrateProjectGuidance, migrateProjectGuidanceRevisions, migrateRiskTreatmentPlan } from "@molis-ai/molis-work-module-goals";
import { LocalProjectDatabase } from "@molis-ai/molis-work-app-local-host";
import { GoalProjectApplication } from "@molis-ai/molis-work-app-local-host";
import { importV3Board } from "@molis-ai/molis-work-app-local-host";

import { DEMO_BOARD_ID } from "@molis-ai/molis-work-app-local-host";
import { materializeGoalEventV35Fixture } from "./goal-event-v35-fixture.js";

// Captured from the production initializer before GW6 changes, not regenerated by the new schema.
const baseline: Array<{ type: string; name: string; tbl_name: string; sql: string }> = JSON.parse(
  readFileSync(new URL("./fixtures/goals-storage-before-gw6.json", import.meta.url), "utf8"),
);
const at = "2026-08-10T01:02:03.000Z";
const query = (store: LocalProjectDatabase) => new GoalsQueryService(new GoalsRepository(store.db));
const schema = (table: string) => baseline.find(row => row.type === "table" && row.name === table)!.sql;

test("fresh Goals tables, indexes, defaults and constraints match the pre-GW6 schema", () => {
  const store = new LocalProjectDatabase(":memory:");
  try {
    const tables = new Set(baseline.map(row => row.tbl_name));
    const actual = (store.db.prepare("SELECT type, name, tbl_name, sql FROM sqlite_master WHERE sql IS NOT NULL ORDER BY type, name").all() as typeof baseline)
      .filter(row => tables.has(row.tbl_name)).map(row => ({ ...row, sql: row.sql.replace(/\s+/g, " ").trim() }));
    assert.deepEqual(actual, baseline);
  } finally { store.close(); }
});

for (const migration of [15, 25, 26]) test(`migration ${migration} rolls back its real schema/data changes and retries without duplicate history`, () => {
  const db = new Database(":memory:");
  try {
    db.exec("CREATE TABLE schema_migrations(migration_id INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)");
    db.exec("CREATE TABLE boards(board_id TEXT PRIMARY KEY)");
    db.prepare("INSERT INTO boards VALUES (?)").run("old-project");
    if (migration === 15) db.exec(schema("risks").replace("treatment_plan TEXT NOT NULL DEFAULT '', ", ""));
    if (migration === 26) {
      let old = schema("project_guidance_entries");
      for (const field of ["revision INTEGER NOT NULL DEFAULT 1, ", "active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)), ",
        "updated_by TEXT NOT NULL, ", "updated_at TEXT NOT NULL, "]) old = old.replace(field, "");
      db.exec(old);
      db.prepare(`INSERT INTO project_guidance_entries(guidance_id, board_id, position, kind, content, content_hash,
        source_refs_json, created_by, confirmation_summary, reason, created_at) VALUES(?, ?, 1, 'context', ?, 'historical-content-id', '[]', 'original-user', 'confirmed', 'keep history', ?)`)
        .run("old-guidance", "old-project", "保留原项目说明", at);
    }
    db.exec(`CREATE TRIGGER reject_marker BEFORE INSERT ON schema_migrations WHEN NEW.migration_id = ${migration}
      BEGIN SELECT RAISE(ABORT, 'injected migration failure'); END`);
    const run = () => migration === 15 ? migrateRiskTreatmentPlan(db) : migration === 25 ? migrateProjectGuidance(db) : migrateProjectGuidanceRevisions(db);
    assert.throws(run, /injected migration failure/);
    assert.equal(db.prepare("SELECT * FROM schema_migrations").all().length, 0);
    if (migration === 15) assert.equal((db.pragma("table_info(risks)") as Array<{ name: string }>).some(c => c.name === "treatment_plan"), false);
    if (migration === 25) assert.equal(db.prepare("SELECT 1 FROM sqlite_master WHERE name='project_guidance_entries'").get(), undefined);
    if (migration === 26) {
      assert.equal((db.pragma("table_info(project_guidance_entries)") as Array<{ name: string }>).some(c => c.name === "revision"), false);
      assert.equal(db.prepare("SELECT content FROM project_guidance_entries").pluck().get(), "保留原项目说明");
      assert.equal(db.prepare("SELECT 1 FROM sqlite_master WHERE name='project_guidance_revisions'").get(), undefined);
    }
    db.exec("DROP TRIGGER reject_marker"); run();
    assert.equal(db.prepare("SELECT migration_id FROM schema_migrations").pluck().get(), migration);
    if (migration === 15) assert.ok((db.pragma("table_info(risks)") as Array<{ name: string }>).some(c => c.name === "treatment_plan"));
    if (migration === 25) assert.ok(db.prepare("SELECT 1 FROM sqlite_master WHERE name='project_guidance_entries'").get());
    if (migration === 26) {
      assert.deepEqual(db.prepare("SELECT revision, active, updated_by, updated_at, content FROM project_guidance_entries").get(),
        { revision: 1, active: 1, updated_by: "original-user", updated_at: at, content: "保留原项目说明" });
      assert.deepEqual(db.prepare("SELECT revision_id, revision, changed_by, created_at, content FROM project_guidance_revisions").get(),
        { revision_id: "migration:old-guidance:1", revision: 1, changed_by: "original-user", created_at: at, content: "保留原项目说明" });
      run();
      assert.equal(db.prepare("SELECT COUNT(*) FROM project_guidance_revisions").pluck().get(), 1);
    }
  } finally { db.close(); }
});

const legacy = {
  schema_version: "3.0", goal_id: "old", meta: { title: "导入后的项目", source: { seed: "迁移" } }, root_goal: { constraints: ["无损"] },
  goals: [{ id: "child", parent: null, one_liner: "保留旧目标", covers: ["a"], inputs: ["原输入"], outputs: ["原输出"] }],
  coverage_ledger: [
    { id: "z", requirement: "以后处理", status: "later", owner_goal: null, entry_condition: "下一版本" },
    { id: "a", requirement: "保留覆盖记录", status: "now", owner_goal: "child", reason: "原理由" },
    { id: "b", requirement: "不做", status: "out", owner_goal: null },
    { id: "c", requirement: "尚未分配", status: "now", owner_goal: null },
  ],
};

test("real V3 import and Web Query preserve all coverage dispositions, ordering, isolation and rollback", () => {
  const store = new LocalProjectDatabase(":memory:");
  try {
    const c = new GoalProjectApplication(store);
    importV3Board(store, c, legacy, { target_board_id: "imported", actor_id: "user", idempotency_key: "v3" });
    const rows = query(store).listLegacyCoverage("imported");
    assert.deepEqual(rows.map(r => [r.requirement_id, r.disposition, r.blocking, r.owner_goal_id]), [
      ["imported:v3:a", "covered", false, "imported:v3:child"], ["imported:v3:b", "out", false, null],
      ["imported:v3:c", "unresolved", true, null], ["imported:v3:z", "deferred", false, null],
    ]);
    assert.equal(rows[0]!.reason, "原理由"); assert.equal(rows[3]!.revisit_condition, "下一版本");
    assert.deepEqual(buildMolisWorkWebView(store, c, { boardId: "imported" }).coverage, rows);
    assert.deepEqual(query(store).listLegacyCoverage("other"), []);
    assert.equal(query(store).getGoal("imported", "imported:v3:child")!.definition_state, "draft");
    c.initializeBoard({ board_id: "other", title: "other", actor_id: "user", idempotency_key: "other" });
    assert.throws(() => c.goals.commands.importLegacyCoverage("other", [{ ...rows[0]!, requirement_id: "foreign" }]), /Goal 不存在/);
    assert.deepEqual(query(store).listLegacyCoverage("other"), []);
    const broken = { ...legacy, coverage_ledger: [...legacy.coverage_ledger, legacy.coverage_ledger[0]!] };
    assert.throws(() => importV3Board(store, c, broken, { target_board_id: "failed", actor_id: "user", idempotency_key: "broken" }), /UNIQUE/);
    assert.equal(query(store).getBoard("failed"), null);
    assert.deepEqual(query(store).listLegacyCoverage("failed"), []);
    assert.equal(store.db.prepare("SELECT COUNT(*) FROM events WHERE board_id='failed'").pluck().get(), 0);
  } finally { store.close(); }
});

test("V3 import adopts migration event ownership so notes work immediately and after reopen", () => {
  const directory = mkdtempSync(join(tmpdir(), "molis-work-v3-event-import-"));
  const databasePath = join(directory, "import.db");
  let store = new LocalProjectDatabase(databasePath);
  try {
    const tree = {
      ...legacy,
      goals: [
        { id: "root", parent: null, one_liner: "父目标", covers: [], inputs: ["根输入"], outputs: ["根输出"] },
        { id: "child", parent: "root", one_liner: "子目标", covers: ["a"], inputs: ["原输入"], outputs: ["原输出"] },
      ],
    };
    let app = new GoalProjectApplication(store);
    importV3Board(store, app, tree, { target_board_id: "imported", actor_id: "user", idempotency_key: "v3" });
    const childId = "imported:v3:child";
    const child = query(store).getGoal("imported", childId)!;
    assert.equal(child.title, "子目标");
    assert.equal(child.outcome, "子目标");
    assert.deepEqual(child.required_inputs, ["原输入"]);
    assert.deepEqual(child.promised_outputs, ["原输出"]);
    assert.deepEqual(child.constraints, ["无损"]);
    assert.equal(child.decomposition_state, "abstract");
    assert.equal(child.acceptance_criteria.length, 0);
    assert.equal(store.snapshot("imported").relations[0]?.type, "part_of");
    assert.equal(query(store).listLegacyCoverage("imported")[0]?.disposition, "covered");
    assert.equal(app.goalEvents.isEventStateOwner("imported", childId), true);
    const state = app.goalEvents.readState("imported", childId);
    assert.equal(state.work_status, "open");
    assert.equal(state.can_record, true);
    assert.equal(state.intent.source_kind, "migration");
    assert.deepEqual(state.requirements, []);
    const note = app.goalEvents.recordNote({
      board_id: "imported", goal_id: childId, actor_id: "user", actor_kind: "user",
      body: "导入后即可记录", idempotency_key: "import-note",
    });
    assert.equal(note.recorded, true);
    store.close();
    store = new LocalProjectDatabase(databasePath);
    app = new GoalProjectApplication(store);
    assert.equal(app.goalEvents.readState("imported", childId).work_status, "open");
    const replay = app.goalEvents.recordNote({
      board_id: "imported", goal_id: childId, actor_id: "user", actor_kind: "user",
      body: "导入后即可记录", idempotency_key: "import-note",
    });
    assert.equal(replay.replayed, true);
    const afterRestart = app.goalEvents.recordNote({
      board_id: "imported", goal_id: childId, actor_id: "user", actor_kind: "user",
      body: "重启后仍可记录", idempotency_key: "import-note-2",
    });
    assert.equal(afterRestart.recorded, true);
    assert.throws(
      () => importV3Board(store, app, tree, { target_board_id: "imported", actor_id: "user", idempotency_key: "v3-again" }),
      /不会覆盖/,
    );
  } finally {
    if (store.db.open) store.close();
    rmSync(directory, { recursive: true, force: true });
  }
});

test("Host migration 30 rolls back Goals and Execution together, then preserves original revisions across reopen", () => {
  const { directory, path } = materializeGoalEventV35Fixture("approved");
  let store = new LocalProjectDatabase(path);
  try {
    const c = new GoalProjectApplication(store);
    store.db.prepare(`
      INSERT INTO policy_bindings (
        policy_binding_id, board_id, goal_id, scope, policy_json, state, created_by, reason, created_at
      ) VALUES (?, ?, NULL, 'project_default', ?, 'active', 'original-user', '历史规则', ?)
    `).run("historical-policy", DEMO_BOARD_ID, JSON.stringify({ goal_mode: "preferred", required_capabilities: ["testing"] }), at);
    c.goals.commands.addProjectGuidance({ board_id: DEMO_BOARD_ID, actor_id: "original-user", kind: "quality_bar",
      content: "历史说明与作者不能丢失", reason: "保留历史", confirmation_summary: "确认", user_confirmed: true, idempotency_key: "historical-guidance" });
    const demoBefore = store.snapshot(DEMO_BOARD_ID);
    const acceptedBefore = demoBefore.goals.find(goal => goal.goal_id === "CORE");
    assert.ok(acceptedBefore);
    assert.equal(acceptedBefore.definition_state, "accepted");
    assert.equal(acceptedBefore.accepted_by, "demo-user");
    assert.ok(acceptedBefore.accepted_at);
    const guidanceBefore = query(store).readProjectGuidance(DEMO_BOARD_ID);
    importV3Board(store, c, legacy, { target_board_id: "imported", actor_id: "user", idempotency_key: "v3" });
    const before = store.snapshot("imported");
    // Independent pre-migration schema: captured old DDL with the later revision column removed.
    store.db.pragma("foreign_keys = OFF");
    const rows = store.db.prepare("SELECT * FROM goals").all() as Array<Record<string, unknown>>;
    store.db.exec("DROP TABLE goal_contract_revisions; DROP TABLE coverage_contract_revisions; DROP TABLE goals;");
    store.db.exec(schema("goals").replace("current_contract_revision INTEGER NOT NULL DEFAULT 1, ", ""));
    for (const row of rows) {
      delete row.current_contract_revision;
      const keys = Object.keys(row);
      store.db.prepare(`INSERT INTO goals (${keys.join(',')}) VALUES (${keys.map(() => '?').join(',')})`).run(...Object.values(row));
    }
    store.db.exec("DELETE FROM schema_migrations WHERE migration_id=30");
    store.db.exec("ALTER TABLE claims DROP COLUMN contract_revision");
    store.db.exec("CREATE TRIGGER reject_30 BEFORE INSERT ON schema_migrations WHEN NEW.migration_id=30 BEGIN SELECT RAISE(ABORT, 'migration30 failure'); END");
    store.close();
    const failure = spawnSync(process.execPath, ["--import", "tsx", "--input-type=module", "-e",
      `import {LocalProjectDatabase} from '@molis-ai/molis-work-app-local-host'; try {new LocalProjectDatabase(process.argv[1]); process.exitCode=1} catch(e) {if(!String(e).includes('migration30 failure')) throw e}`, path], { encoding: "utf8" });
    assert.equal(failure.status, 0, failure.stderr);
    const raw = new Database(path);
    try {
      for (const table of ["goals", "claims"]) assert.equal((raw.pragma(`table_info(${table})`) as Array<{ name: string }>).some(r => r.name === (table === "goals" ? "current_contract_revision" : "contract_revision")), false);
      assert.equal(raw.prepare("SELECT 1 FROM sqlite_master WHERE name='goal_contract_revisions'").get(), undefined);
      assert.equal(raw.prepare("SELECT 1 FROM schema_migrations WHERE migration_id=30").get(), undefined);
      raw.exec("DROP TRIGGER reject_30");
    } finally { raw.close(); }
    store = new LocalProjectDatabase(path);
    const after = store.snapshot("imported");
    assert.deepEqual(after.goals, before.goals);
    assert.deepEqual(after.relations, before.relations);
    const demoAfter = store.snapshot(DEMO_BOARD_ID);
    for (const key of ["goals", "relations", "risks", "policy_bindings"] as const) assert.deepEqual(demoAfter[key], demoBefore[key], key);
    assert.deepEqual(query(store).readProjectGuidance(DEMO_BOARD_ID), guidanceBefore);
    const acceptedRevision = demoAfter.goal_contract_revisions.find(row => row.goal_id === "CORE");
    assert.ok(acceptedRevision);
    assert.equal(acceptedRevision.changed_by, acceptedBefore.accepted_by);
    assert.equal(acceptedRevision.created_at, acceptedBefore.accepted_at);
    assert.deepEqual(acceptedRevision.contract.acceptance_criteria,
      acceptedBefore.acceptance_criteria.map(({ criterion_id: _id, goal_id: _goal, ...criterion }) => criterion));
    const revision = after.goal_contract_revisions[0]!;
    assert.equal(revision.revision, 1);
    assert.equal(revision.changed_by, "migration");
    assert.equal(revision.created_at, before.goals[0]!.created_at);
    const c2 = new GoalProjectApplication(store);
    const viewBefore = buildMolisWorkWebView(store, c2, { boardId: "imported" }).coverage;
    store.close(); store = new LocalProjectDatabase(path);
    assert.deepEqual(store.snapshot("imported").goal_contract_revisions, after.goal_contract_revisions);
    assert.deepEqual(query(store).listLegacyCoverage("imported"), viewBefore);
    assert.deepEqual(query(store).readProjectGuidance(DEMO_BOARD_ID), guidanceBefore);
  } finally { if (store.db.open) store.close(); rmSync(directory, { recursive: true, force: true }); }
});

test("V3 final audit failure rolls back the entire import and permits the same request after repair", () => {
  const store = new LocalProjectDatabase(":memory:");
  try {
    const coordinator = new GoalProjectApplication(store);
    store.db.exec("CREATE TRIGGER reject_v3_import BEFORE INSERT ON events WHEN NEW.type = 'v3.imported' BEGIN SELECT RAISE(ABORT, 'v3 final audit failed'); END");
    const tree = { ...legacy, goals: [{ ...legacy.goals[0]!, id: "root", parent: null }, { ...legacy.goals[0]!, parent: "root" }] };
    const request = { target_board_id: "atomic-v3", actor_id: "user", idempotency_key: "atomic-import" };
    assert.throws(() => importV3Board(store, coordinator, tree, request), /v3 final audit failed/);
    assert.equal(query(store).getBoard(request.target_board_id), null);
    for (const table of ["goals", "goal_relations", "coverage_items", "events", "idempotency_records"]) {
      assert.equal(store.db.prepare(`SELECT COUNT(*) FROM ${table} WHERE board_id = ?`).pluck().get(request.target_board_id), 0, table);
    }
    store.db.exec("DROP TRIGGER reject_v3_import");
    const report = importV3Board(store, coordinator, tree, request);
    const snapshot = store.snapshot(request.target_board_id);
    assert.equal(snapshot.goals.length, 2);
    assert.equal(snapshot.relations.length, 1);
    assert.equal(query(store).listLegacyCoverage(request.target_board_id).length, 4);
    assert.equal(query(store).getBoard(request.target_board_id)!.active_goal_id, "atomic-v3:v3:root");
    const event = store.db.prepare("SELECT seq, payload_json FROM events WHERE board_id = ? AND type = 'v3.imported'").all(request.target_board_id) as Array<{ seq: number; payload_json: string }>;
    assert.equal(event.length, 1);
    assert.equal(report.observed_event_cursor, event[0]!.seq);
    assert.deepEqual(JSON.parse(event[0]!.payload_json), { legacy_goal_id: legacy.goal_id, legacy_schema_version: "3.0" });
    assert.throws(() => importV3Board(store, coordinator, tree, request), /目标 Board 已存在/);
    assert.deepEqual(store.snapshot(request.target_board_id), snapshot);
  } finally { store.close(); }
});

test("V3 import with no Goals retains a null active pointer and one final import event", () => {
  const store = new LocalProjectDatabase(":memory:");
  try {
    const coordinator = new GoalProjectApplication(store);
    const report = importV3Board(store, coordinator, { ...legacy, goals: [], coverage_ledger: [] }, {
      target_board_id: "empty-v3", actor_id: "user", idempotency_key: "empty-import",
    });
    assert.deepEqual(report.goal_id_map, {});
    assert.equal(query(store).getBoard("empty-v3")!.active_goal_id, null);
    assert.deepEqual(store.snapshot("empty-v3").goals, []);
    assert.equal(store.db.prepare("SELECT COUNT(*) FROM events WHERE board_id = ? AND type = 'v3.imported'").pluck().get("empty-v3"), 1);
  } finally { store.close(); }
});
