import assert from "node:assert/strict";
import test from "node:test";
import { DEMO_BOARD_ID } from "@molis-ai/molis-work-app-local-host";
import { openGoalBrowser } from "./fixtures/goal-browser.js";

test("Goal kanban sits beside the canvas, opens the workspace, and remembers the board view", { timeout: 90_000 }, async (t) => {
  const browser = await openGoalBrowser(t);
  if (!browser) return;
  const { command, sessionId, evaluate, waitFor, navigate, click, reloadPage, origin, store, before } = browser;
  const tap = (selector: string) => evaluate("document.querySelector(" + JSON.stringify(selector) + ").click()");
  await command("Emulation.setDeviceMetricsOverride", { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false }, sessionId);
  await command("Emulation.setEmulatedMedia", { features: [{ name: "prefers-reduced-motion", value: "reduce" }] }, sessionId);
  await navigate(() => command("Page.navigate", { url: origin + "/" }, sessionId));
  await waitFor("document.body.dataset.desktopSurface === 'home'");
  await click('[data-plugin-strip] [data-plugin-id="goals"]');
  await waitFor("document.querySelector('[data-goal-momentum]')?.dataset.loaded === 'true' && document.querySelector('.tab-item[data-tab-kind=mother][aria-current]') && document.querySelector('[data-container-tabs]')?.hidden");
  const goalId = await evaluate<string>("document.querySelector('[data-select-goal]').dataset.selectGoal");
  assert.equal(await evaluate("document.querySelectorAll('[data-kanban-column]').length"), 6);
  assert.doesNotMatch(await evaluate<string>("document.querySelector('[data-goal-kanban]')?.textContent || ''"), /从想要的结果开始|创建第一条 Goal|Click a card/);
  await tap("[data-board-view-tab=kanban]");
  await waitFor("document.querySelector('[data-board-view-tab=kanban][aria-current=\"page\"]') && document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView === 'kanban'");
  assert.equal(await evaluate("getComputedStyle(document.querySelector('[data-goal-kanban]')).display !== 'none'"), true);
  assert.equal(await evaluate("getComputedStyle(document.querySelector('[data-goal-momentum]')).display === 'none'"), true);
  assert.equal(await evaluate("document.querySelector('[data-kanban-card][data-goal-id=\"" + goalId + "\"]') != null"), true);
  await click('[data-kanban-card][data-goal-id="' + goalId + '"]');
  await waitFor("document.querySelector('[data-goal-node-workspace]')?.dataset.expandedGoal === " + JSON.stringify(goalId));
  assert.equal(await evaluate("document.querySelector('[data-board-view-tab=kanban][aria-current=\"page\"]') != null"), true);
  assert.equal(await evaluate("document.querySelector('[data-container-tab=\"" + goalId + "\"]')"), null);
  await tap("[data-goal-collapse]");
  await waitFor("document.querySelector('[data-goal-node-workspace]').hidden");
  assert.equal(await evaluate("document.querySelector('[data-board-view-tab=kanban][aria-current=\"page\"]') != null"), true);
  await click('.tree-node[data-select-goal="' + goalId + '"]');
  await waitFor("document.querySelector('.tab-item[data-tab-kind=item][aria-current]') && document.querySelector('[data-goal-node-workspace]')?.dataset.expandedGoal === " + JSON.stringify(goalId));
  assert.equal(await evaluate("document.querySelector('[data-container-tab=\"" + goalId + "\"]')"), null);
  await tap("[data-goal-collapse]");
  await waitFor("document.querySelector('[data-board-view-tab=kanban][aria-current=\"page\"]') && document.querySelector('[data-goal-node-workspace]').hidden");
  await tap("[data-board-view-tab=canvas]");
  await waitFor("document.querySelector('[data-board-view-tab=canvas][aria-current=\"page\"]') && document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView === 'canvas'");
  await evaluate("document.querySelector('[data-graph-node][data-goal-id=\"" + goalId + "\"] [data-graph-frame]').click()");
  await waitFor("document.querySelector('[data-container-tab=\"" + goalId + "\"][aria-current=\"page\"]')");
  await click('.tree-node[data-select-goal="' + goalId + '"]');
  await waitFor("document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView === 'canvas' && document.querySelector('[data-board-view-tab=canvas][aria-current=\"page\"]') && document.querySelector('[data-goal-node-workspace]').hidden && document.querySelector('.tree-node[data-select-goal=\"" + goalId + "\"]')?.classList.contains('is-selected') && document.querySelector('[data-container-tab=\"" + goalId + "\"]') && !document.querySelector('.tab-item[data-tab-kind=item][aria-current]')");
  await evaluate("document.querySelector('[data-graph-node][data-goal-id=\"" + goalId + "\"] [data-graph-frame]').click()");
  await waitFor("document.querySelector('[data-container-tab=\"" + goalId + "\"][aria-current=\"page\"]')");
  await tap("[data-container-tab=kanban]");
  await waitFor("document.querySelector('[data-container-tab=kanban][aria-current=\"page\"]')");
  await tap('[data-container-tab="' + goalId + '"]');
  await waitFor("document.querySelector('[data-container-tab=\"" + goalId + "\"][aria-current=\"page\"]')");
  await tap('[data-container-tab-close="' + goalId + '"]');
  await waitFor("document.querySelector('[data-board-view-tab=kanban][aria-current=\"page\"]') && document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView === 'kanban'");
  await click('[data-plugin-strip] [data-plugin-id="sessions"]');
  await waitFor("document.body.dataset.desktopSurface === 'sessions'");
  await click('[data-plugin-strip] [data-plugin-id="goals"]');
  await waitFor("document.body.dataset.desktopSurface === 'goal' && document.querySelector('[data-board-view-tab=kanban][aria-current=\"page\"]') && document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView === 'kanban'");
  await reloadPage();
  await waitFor("document.body.dataset.desktopSurface === 'home' || document.body.dataset.desktopSurface === 'goal'");
  if (await evaluate("document.body.dataset.desktopSurface") !== "goal") {
    await click('[data-plugin-strip] [data-plugin-id="goals"]');
  }
  await waitFor("document.querySelector('[data-board-view-tab=kanban][aria-current=\"page\"]') && document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView === 'kanban'");
  await command("Emulation.setDeviceMetricsOverride", { width: 390, height: 844, deviceScaleFactor: 2, mobile: true }, sessionId);
  const overflow = await evaluate<{ board: number; shell: number }>("(() => { const board = document.querySelector('[data-goal-kanban] .goal-kanban-board'); const shell = document.querySelector('[data-goal-kanban]'); return { board: board?.scrollWidth || 0, shell: shell?.clientWidth || 0 }; })()");
  assert.ok(overflow.board > overflow.shell, "narrow kanban stays a horizontal board");
  assert.deepEqual(store.snapshot(DEMO_BOARD_ID).goals, before.goals);
});
