import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { LocalProjectDatabase } from "@molis-ai/molis-work-app-local-host";

// Captured from the production initializer before GW6 changes, not regenerated by the new schema.
const baseline: Array<{ type: string; name: string; tbl_name: string; sql: string }> = JSON.parse(
  readFileSync(new URL("./fixtures/goals-storage-before-gw6.json", import.meta.url), "utf8"),
);

// One intended difference: the V3 requirement ledger (coverage_items) was removed with the V3 import (2026-10-04).
test("fresh Goals tables, indexes, defaults and constraints match the pre-GW6 schema, without the V3 requirement ledger", () => {
  const store = new LocalProjectDatabase(":memory:");
  try {
    const expected = baseline.filter(row => row.tbl_name !== "coverage_items");
    const tables = new Set(baseline.map(row => row.tbl_name));
    const actual = (store.db.prepare("SELECT type, name, tbl_name, sql FROM sqlite_master WHERE sql IS NOT NULL ORDER BY type, name").all() as typeof baseline)
      .filter(row => tables.has(row.tbl_name)).map(row => ({ ...row, sql: row.sql.replace(/\s+/g, " ").trim() }));
    assert.deepEqual(actual, expected);
    assert.equal(store.db.prepare("SELECT 1 FROM sqlite_master WHERE name = 'coverage_items'").get(), undefined);
  } finally { store.close(); }
});
