import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { PlanningMethodPack } from "@molis-ai/molis-work-contracts/modules/goals";
import { DEMO_BOARD_ID } from "@molis-ai/molis-work-app-local-host";
import { openGoalBrowser } from "./fixtures/goal-browser.js";

test("Planning browser copies a template, recovers failed saves and adopts an independent project version", { timeout: 60_000 }, async t => {
  const browser = await openGoalBrowser(t, true);
  if (!browser) return;
  const { origin, projectId, store, before, command, sessionId, evaluate, waitFor, click, reloadPage, navigate } = browser;
  assert.ok(projectId);
  const prefix = "/projects/" + projectId;
  const globalApi = "/api/settings/planning-methods";
  const projectApi = prefix + globalApi;
  const read = async (path: string) => (await (await fetch(origin + path)).json()) as { methods: PlanningMethodPack[]; composition?: { method_pack_ids: string[] } };
  const original = await read(globalApi);
  const id = "domain-software-development";
  const template = original.methods.find(x => x.method_id === id)!;
  assert.equal(template.scope, "built_in");
  await command("Network.enable", {}, sessionId);
  await command("Emulation.setDeviceMetricsOverride", { width: 1440, height: 1100, deviceScaleFactor: 1, mobile: false }, sessionId);
  await navigate(() => command("Page.navigate", { url: origin + "/settings/planning" }, sessionId));
  await command("Page.bringToFront", {}, sessionId);
  const dom = (selector: string) => "document.querySelector(" + JSON.stringify(selector) + ")";
  await waitFor("document.readyState === 'complete' && " + dom('[data-planning-filter="mine"]'));
  await click('[data-planning-filter="mine"]');
  assert.equal(await evaluate(dom("[data-planning-filter-empty]") + ".hidden"), false);
  await click('[data-planning-filter="domain"]');
  assert.equal(await evaluate("Array.from(document.querySelectorAll('[data-planning-method]')).filter(x=>!x.hidden).every(x=>x.dataset.kind==='domain')"), true);
  await navigate(() => click('a[href="/settings/planning/' + id + '"]'));
  await waitFor("document.readyState === 'complete' && " + dom(".planning-detail"));
  await navigate(() => click(".planning-primary-action"));
  await waitFor("document.readyState === 'complete' && " + dom("[data-planning-edit-form]"));
  assert.equal(await evaluate(dom("[data-planning-edit-form]") + ".dataset.saveScope"), "personal");
  const row = '[data-planning-row-list="steps"] [data-planning-row]';
  const count = await evaluate<number>("document.querySelectorAll(" + JSON.stringify(row) + ").length");
  await click('.planning-edit-section.form-disclosure > summary');
  await click('[data-add-planning-row="steps"]');
  assert.equal(await evaluate("document.activeElement.name"), "steps");
  assert.equal(await evaluate("document.querySelectorAll(" + JSON.stringify(row) + ").length"), count + 1);
  await click(row + ":last-child [data-remove-planning-row]");
  const values = { name: 'Browser method "<safe>', summary: "Verified browser method", instructions: "Read all instructions.\nKeep the original template.",
    applies_to: "Delivery, Validation", domain_tags: "software, reliability", confidence: "0.9", source_refs: "project://requirements.md\nproject://validation.md" };
  await evaluate("(() => { const form = document.querySelector('[data-planning-edit-form]'); for (const [name,value] of Object.entries(" +
    JSON.stringify(values) + ")) { const input=form.elements.namedItem(name); input.value=value; input.dispatchEvent(new Event('input',{bubbles:true})); } return true; })()");
  const submit = '[data-planning-edit-form] button[type="submit"]';
  await command("Network.setBlockedURLs", { urls: [origin + globalApi] }, sessionId);
  await click(submit);
  await waitFor(dom("[data-planning-method-error]") + "?.hidden === false && !" + dom(submit) + ".disabled");
  assert.equal(await evaluate(dom('[name="name"]') + ".value"), values.name);
  assert.deepEqual(await read(globalApi), original);
  await command("Network.setBlockedURLs", { urls: [] }, sessionId);
  await navigate(() => click(submit));
  await waitFor("document.readyState === 'complete' && " + dom(".planning-detail"));
  const saved = (await read(globalApi)).methods.find(x => x.method_id === id)!;
  assert.equal(saved.scope, "personal");
  assert.equal(saved.version, 1);
  assert.equal(saved.name, values.name);
  assert.equal(saved.instructions, values.instructions);
  assert.equal(saved.summary, values.summary);
  assert.equal(saved.confidence, 0.9);
  assert.deepEqual(saved.applies_to, ["Delivery", "Validation"]);
  assert.deepEqual(saved.domain_tags, ["software", "reliability"]);
  assert.deepEqual(saved.source_refs, ["project://requirements.md", "project://validation.md"]);
  assert.deepEqual(saved.steps, template.steps);
  assert.deepEqual(saved.required_coverage.map(x => ({ label: x.label, question: x.question })),
    template.required_coverage.map(x => ({ label: x.label, question: x.question })));
  assert.deepEqual(saved.evidence_requirements, template.evidence_requirements);
  assert.deepEqual(saved.completion_checks, template.completion_checks);
  assert.deepEqual(saved.failure_modes, template.failure_modes);
  assert.deepEqual((await read(globalApi)).methods.filter(x => x.method_id !== id), original.methods.filter(x => x.method_id !== id));
  await reloadPage();
  assert.equal(await evaluate(dom(".planning-detail h1") + ".textContent"), values.name);
  await navigate(() => command("Page.navigate", { url: origin + prefix + "/settings/planning" }, sessionId));
  await waitFor(dom('[data-adopt-planning-method="' + id + '"]'));
  const projectBefore = await read(projectApi);
  const unconfirmed = await evaluate<{ status: number; error: string }>("(async()=>{const response=await fetch(" + JSON.stringify(projectApi + "/apply") +
    ",{method:'POST',headers:globalThis.molisWorkControlHeaders(),body:JSON.stringify({method_id:" + JSON.stringify(id) +
    "})});return {status:response.status,...await response.json()};})()");
  assert.equal(unconfirmed.status, 400);
  assert.match(unconfirmed.error, /必须由用户确认/);
  assert.deepEqual(await read(projectApi), projectBefore);
  const adopt = '[data-adopt-planning-method="' + id + '"]';
  await command("Network.setBlockedURLs", { urls: [origin + projectApi + "/apply"] }, sessionId);
  await click(adopt);
  await waitFor(dom("[data-planning-adoption-error]") + "?.hidden === false && !" + dom(adopt) + ".disabled");
  assert.deepEqual(await read(projectApi), projectBefore);
  await command("Network.setBlockedURLs", { urls: [] }, sessionId);
  await navigate(() => click(adopt));
  await waitFor("document.readyState === 'complete' && !" + dom(adopt) + " && " + dom(".planning-composition-row"));
  const adopted = (await read(projectApi)).methods.find(x => x.method_id === id)!;
  assert.equal(adopted.scope, "project");
  assert.equal(adopted.version, 1);
  assert.equal(adopted.instructions, saved.instructions);
  assert.equal(adopted.name, saved.name);
  assert.equal((await read(projectApi)).methods.filter(x => x.method_id === id).length, 1);
  await navigate(() => click('.planning-composition-row[href="' + prefix + '/settings/planning/' + id + '"]'));
  await waitFor("document.readyState === 'complete' && " + dom(".planning-detail"));
  await navigate(() => click(".planning-primary-action"));
  await waitFor("document.readyState === 'complete' && " + dom("[data-planning-edit-form]"));
  await click('[name="enabled"]');
  await navigate(() => click(submit));
  await waitFor("document.readyState === 'complete' && " + dom(".planning-detail"));
  const disabled = (await read(projectApi)).methods.find(x => x.method_id === id)!;
  assert.equal(disabled.enabled, false);
  assert.equal(disabled.version, 2);
  assert.deepEqual((await read(globalApi)).methods.find(x => x.method_id === id), saved);
  await navigate(() => click(".planning-back"));
  await waitFor(dom(".planning-inactive-section"));
  assert.equal((await read(projectApi)).composition!.method_pack_ids.includes(id), false);
  await reloadPage();
  assert.ok(await evaluate(dom(".planning-inactive-section") + "?.textContent.includes(" + JSON.stringify(values.name) + ")"));
  const after = store.snapshot(DEMO_BOARD_ID);
  assert.deepEqual(after.goals, before.goals);
  assert.deepEqual(after.relations, before.relations);
  assert.deepEqual(after.runs, before.runs);
  if (process.env.MOLIS_WORK_TEST_CAPTURE) {
    const captures = await mkdtemp(join(tmpdir(), "molis-work-gw5-planning-"));
    for (const [name, width, height] of [["desktop", 1440, 1100], ["mobile", 390, 844]] as const) {
      await command("Emulation.setDeviceMetricsOverride", { width, height, deviceScaleFactor: 1, mobile: name === "mobile" }, sessionId);
      await evaluate("window.scrollTo(0,0); new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))");
      const { data } = await command<{ data: string }>("Page.captureScreenshot", { format: "png", captureBeyondViewport: false }, sessionId);
      await writeFile(join(captures, name + ".png"), Buffer.from(data, "base64"));
    }
    t.diagnostic("Planning screenshots: " + captures);
  }
});
