import assert from "node:assert/strict";
import test from "node:test";
import { DEMO_BOARD_ID } from "@molis-ai/molis-work-app-local-host";
import { openGoalBrowser } from "./fixtures/goal-browser.js";

test("Goal kanban sits beside the canvas, opens Frame, and remembers the board view", { timeout: 90_000 }, async (t) => {
  const browser = await openGoalBrowser(t);
  if (!browser) return;
  const { command, sessionId, evaluate, waitFor, navigate, click, reloadPage, origin, store, before } = browser;
  const tap = (selector: string) => evaluate("document.querySelector(" + JSON.stringify(selector) + ").click()");
  await command("Emulation.setDeviceMetricsOverride", { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false }, sessionId);
  await command("Emulation.setEmulatedMedia", { features: [{ name: "prefers-reduced-motion", value: "reduce" }] }, sessionId);
  await navigate(() => command("Page.navigate", { url: origin + "/" }, sessionId));
  await waitFor("document.body.dataset.desktopSurface === 'home'");
  await click('[data-plugin-strip] [data-plugin-id="goals"]');
  await waitFor("document.querySelector('[data-goal-momentum]')?.dataset.loaded === 'true' && document.querySelector('.tab-item[data-tab-kind=mother][aria-current]') && document.querySelector('[data-container-tabs]')?.hidden && document.querySelector('[data-goal-stage-list] .tree-node[data-select-goal]')");
  const goalId = await evaluate<string>("document.querySelector('[data-goal-stage-list] .tree-node[data-select-goal]').dataset.selectGoal");
  assert.equal(await evaluate("document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView"), "list");
  assert.equal(await evaluate("document.querySelector('[data-directory-panel=goals] .tree-node')"), null);
  assert.equal(await evaluate("getComputedStyle(document.querySelector('[data-goal-stage-list]')).display"), "block");
  assert.equal(await evaluate("document.querySelectorAll('[data-kanban-column]').length"), 6);
  assert.doesNotMatch(await evaluate<string>("document.querySelector('[data-goal-kanban]')?.textContent || ''"), /从想要的结果开始|创建第一条 Goal|Click a card/);
  await evaluate("document.querySelector('[data-goal-stage-list] .tree-node[data-select-goal=\"" + goalId + "\"]').click()");
  await waitFor("document.querySelector('.tab-item[data-tab-kind=item][aria-current][data-item-id=\"" + goalId + "\"]') && document.querySelector('[data-goal-frame-surface]')?.dataset.frameGoal === " + JSON.stringify(goalId));
  await waitFor("Boolean(document.querySelector('[data-titlebar-tabs] .tab-item[data-tab-kind=mother] [role=tab]'))");
  await evaluate("document.querySelector('[data-titlebar-tabs] .tab-item[data-tab-kind=mother] [role=tab]').click()");
  await waitFor("document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView === 'list' && document.querySelector('[data-board-view-tab=list][aria-current=\"page\"]')");
  await tap("[data-board-view-tab=kanban]");
  await waitFor("document.querySelector('[data-board-view-tab=kanban][aria-current=\"page\"]') && document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView === 'kanban'");
  assert.equal(await evaluate("getComputedStyle(document.querySelector('[data-goal-kanban]')).display !== 'none'"), true);
  assert.equal(await evaluate("getComputedStyle(document.querySelector('[data-goal-momentum]')).display === 'none'"), true);
  assert.equal(await evaluate("getComputedStyle(document.querySelector('[data-goal-stage-list]')).display === 'none'"), true);
  const desktopFit = await evaluate<{ sw: number; cw: number }>("(() => { const el = document.querySelector('[data-goal-kanban]'); return { sw: el?.scrollWidth || 0, cw: el?.clientWidth || 0 }; })()");
  assert.ok(desktopFit.sw <= desktopFit.cw + 1, "desktop kanban fits six columns without horizontal scroll");
  assert.equal(await evaluate("document.querySelector('[data-kanban-card][data-goal-id=\"" + goalId + "\"]') != null"), true);
  await click('[data-kanban-card][data-goal-id="' + goalId + '"]');
  await waitFor("document.querySelector('[data-goal-frame-surface]')?.dataset.frameGoal === " + JSON.stringify(goalId) + " && document.querySelector('.tab-item[data-tab-kind=item][aria-current][data-item-id=\"" + goalId + "\"]')");
  await evaluate("document.querySelector('[data-titlebar-tabs] .tab-item[data-tab-kind=mother] [role=tab]').click()");
  await waitFor("document.querySelector('[data-board-view-tab=kanban][aria-current=\"page\"]') && document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView === 'kanban'");
  await tap("[data-board-view-tab=canvas]");
  await waitFor("document.querySelector('[data-board-view-tab=canvas][aria-current=\"page\"]') && document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView === 'canvas'");
  await evaluate("document.querySelector('[data-graph-node][data-goal-id=\"" + goalId + "\"]').click()");
  await waitFor("document.querySelector('[data-goal-frame-surface]')?.dataset.frameGoal === " + JSON.stringify(goalId));
  await evaluate("document.querySelector('[data-titlebar-tabs] .tab-item[data-tab-kind=mother] [role=tab]').click()");
  await waitFor("document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView === 'canvas' && document.querySelector('[data-board-view-tab=canvas][aria-current=\"page\"]') && document.querySelector('.tree-node[data-select-goal=\"" + goalId + "\"]')?.classList.contains('is-selected')");
  await evaluate("document.querySelector('[data-graph-node][data-goal-id=\"" + goalId + "\"] [data-graph-frame]').click()");
  await waitFor("document.querySelector('[data-goal-frame-surface]')?.dataset.frameGoal === " + JSON.stringify(goalId));
  await tap("[data-container-tab=kanban]");
  await waitFor("document.querySelector('[data-board-view-tab=kanban][aria-current=\"page\"]') && document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView === 'kanban'");
  await tap('[data-container-tab="' + goalId + '"]');
  await waitFor("document.querySelector('[data-goal-frame-surface]')?.dataset.frameGoal === " + JSON.stringify(goalId));
  await tap('[data-container-tab-close="' + goalId + '"]');
  await waitFor("document.querySelector('[data-board-view-tab=kanban][aria-current=\"page\"]') && document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView === 'kanban'");
  await click('[data-plugin-strip] [data-plugin-id="sessions"]');
  await waitFor("document.body.dataset.desktopSurface === 'sessions'");
  await click('[data-plugin-strip] [data-plugin-id="goals"]');
  await waitFor("document.body.dataset.desktopSurface === 'goal' && document.querySelector('[data-board-view-tab=kanban][aria-current=\"page\"]') && document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView === 'kanban'");
  await reloadPage();
  await waitFor("document.body.dataset.desktopSurface === 'home' || document.body.dataset.desktopSurface === 'goal'");
  if (await evaluate("document.body.dataset.desktopSurface") !== "goal") {
    await click('[data-plugin-strip] [data-plugin-id="goals"]');
  }
  await waitFor("document.querySelector('[data-board-view-tab=kanban][aria-current=\"page\"]') && document.querySelector('[data-goal-canvas-shell]')?.dataset.boardView === 'kanban'");
  await command("Emulation.setDeviceMetricsOverride", { width: 390, height: 844, deviceScaleFactor: 2, mobile: true }, sessionId);
  await waitFor("getComputedStyle(document.querySelector('[data-goal-kanban] .goal-kanban-board')).flexDirection === 'column'");
  const stacked = await evaluate<{ direction: string; overflowX: string; groups: number; outcome: string }>("(() => { const board = document.querySelector('[data-goal-kanban] .goal-kanban-board'); const shell = document.querySelector('[data-goal-kanban]'); const outcome = document.querySelector('.goal-kanban-card-outcome'); return { direction: getComputedStyle(board).flexDirection, overflowX: getComputedStyle(shell).overflowX, groups: document.querySelectorAll('[data-kanban-group]').length, outcome: outcome ? getComputedStyle(outcome).display : 'none' }; })()");
  assert.equal(stacked.direction, "column");
  assert.equal(stacked.groups, 6);
  assert.equal(stacked.outcome, "none");
  assert.ok(stacked.overflowX === "hidden" || stacked.overflowX === "clip", "narrow kanban stacks groups instead of scrolling sideways " + JSON.stringify(stacked));
  assert.deepEqual(store.snapshot(DEMO_BOARD_ID).goals, before.goals);
});
