import assert from "node:assert/strict";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";
import { openMolisWorkProjectCatalog } from "@molis-ai/molis-work-app-desktop";
import { createLocalFeedApplication, DEMO_BOARD_ID, GoalProjectApplication, openWorkSessionRegistry } from "@molis-ai/molis-work-app-local-host";
import { openGoalBrowser } from "./fixtures/goal-browser.js";

test("Immersive directories resize and retain compact, operable Goal, Feed and Session lists", { timeout: 90_000 }, async t => {
  const browser = await openGoalBrowser(t, "migrated");
  if (!browser) return;
  const { command, sessionId, evaluate, waitFor, navigate, click, reloadPage, origin, store, projectId, homeDirectory } = browser;
  const catalog = await openMolisWorkProjectCatalog({ homeDirectory });
  for (const plugin_id of ["feed", "sessions"] as const) catalog.addProjectPlugin({ project_id: projectId!, plugin_id, actor_id: "directory-test" });
  const other = await catalog.createProject({ display_name: "另一项目", actor_id: "directory-test" });
  catalog.close();
  new GoalProjectApplication(store).goalEvents.createIntent({ board_id: DEMO_BOARD_ID, goal_id: "long-child", parent_goal_id: "CORE", actor_id: "directory-test", actor_kind: "user", title: "迁移 Execution Claim / Run 生命周期并保留现有 Runtime 与 Goal 的完整关联", outcome: "验证多层目录中的长标题不会挤压状态标记。", idempotency_key: "long-child" });
  const before = store.snapshot(DEMO_BOARD_ID);
  const registry = await openWorkSessionRegistry({ homeDirectory });
  const session = registry.createSession({ runtime_id: "codex", project_id: projectId!, current_goal_id: "CORE", title: "完成 Molis Work 架构、代码与文档重组，保留已有项目工作过程", user_confirmed: true, actor_id: "directory-test" });
  registry.createSession({ runtime_id: "claude-code", project_id: projectId!, current_goal_id: "WEB", title: "检查目录与工作区交互", user_confirmed: true, actor_id: "directory-test" });
  registry.close();
  const page = origin + "/projects/" + projectId + "/?desktop=1";
  await command("Page.addScriptToEvaluateOnNewDocument", { source: "window.__uiErrors=[];addEventListener('error',e=>window.__uiErrors.push(e.message));" }, sessionId);
  const viewport = (width: number, height = 1000) => command("Emulation.setDeviceMetricsOverride", { width, height, deviceScaleFactor: 1, mobile: width < 600 }, sessionId);
  const key = async (value: string, code: number) => {
    await command("Input.dispatchKeyEvent", { type: "keyDown", key: value, windowsVirtualKeyCode: code }, sessionId);
    await command("Input.dispatchKeyEvent", { type: "keyUp", key: value, windowsVirtualKeyCode: code }, sessionId);
  };
  const capture = async (name: string) => {
    if (!process.env.MOLIS_WORK_DIRECTORY_CAPTURE) return;
    const directory = process.env.MOLIS_WORK_DIRECTORY_CAPTURE;
    await mkdir(directory, { recursive: true });
    const { data } = await command<{ data: string }>("Page.captureScreenshot", { format: "png", captureBeyondViewport: false }, sessionId);
    await writeFile(join(directory, name + ".png"), Buffer.from(data, "base64"));
  };
  const width = () => evaluate<number>("document.querySelector('#goal-tree-pane').getBoundingClientRect().width");
  const expectWidth = (expected: number) => waitFor("document.querySelector('#goal-tree-pane').getBoundingClientRect().width === " + expected);
  await viewport(1440);
  await command("Emulation.setEmulatedMedia", { features: [{ name: "prefers-reduced-motion", value: "reduce" }] }, sessionId);
  await navigate(() => command("Page.navigate", { url: page }, sessionId));
  await waitFor("document.querySelector('[data-directory-list-title]')?.textContent === '项目首页'");
  await click('[data-plugin-strip] [data-plugin-id="goals"]');
  await waitFor("document.querySelector('[data-directory-list-title]')?.textContent === 'Goals'");
  assert.ok(await evaluate("(()=>{const title=document.querySelector('[data-directory-list-title]'),search=document.querySelector('.tree-pane [data-global-search-open]'),region=document.querySelector('[data-directory-list-region]'),inline=document.querySelector('.desktop-goal-directory .tree-search'),tools=document.querySelector('[data-directory-panel=goals]:not([hidden]) [data-directory-list-actions]'),footer=document.querySelector('.personal-sidebar-footer'),shortcuts=document.querySelector('.directory-shortcuts');const sameRow=title&&tools&&Math.abs(title.getBoundingClientRect().top+title.getBoundingClientRect().height/2-(tools.getBoundingClientRect().top+tools.getBoundingClientRect().height/2))<8;return Boolean(title&&search&&region)&&!inline&&sameRow&&search.closest('.navigator-project-primary')&&search.getBoundingClientRect().bottom<=region.getBoundingClientRect().top+1&&getComputedStyle(region).borderTopWidth==='0px'&&getComputedStyle(footer).borderTopWidth==='0px'&&getComputedStyle(shortcuts).borderTopWidth==='0px';})()"));
  const metrics = await evaluate<{ height: number; weight: string; line: string; titleRight: number; stateLeft: number; border: string }[]>(`[...document.querySelectorAll('.tree-entry')].map(row => {
    const title = row.querySelector('strong'), state = row.querySelector('.directory-row-state');
    return { height: row.getBoundingClientRect().height, weight: getComputedStyle(title).fontWeight, line: getComputedStyle(title).whiteSpace, titleRight: title.getBoundingClientRect().right, stateLeft: state.getBoundingClientRect().left, border: getComputedStyle(state).borderWidth };
  })`);
  assert.ok(metrics.length > 10);
  for (const row of metrics) {
    assert.equal(row.height, 32, "Parent and child rows share a single-line height");
    assert.equal(row.line, "nowrap");
    assert.ok(Number(row.weight) <= 500);
    assert.ok(row.titleRight <= row.stateLeft, "Long text must not cover the status");
    assert.equal(row.border, "0px", "The label supplies its own boundary without a second enclosing box");
  }
  await capture("directory-goals-light");
  const point = await evaluate<{ x: number; y: number }>("(()=>{const r=document.querySelector('[data-tree-resizer]').getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+180};})()");
  const initial = await width();
  await command("Input.dispatchMouseEvent", { type: "mousePressed", ...point, button: "left", clickCount: 1 }, sessionId);
  await command("Input.dispatchMouseEvent", { type: "mouseMoved", x: point.x + 120, y: point.y, button: "left", buttons: 1 }, sessionId);
  await command("Input.dispatchMouseEvent", { type: "mouseReleased", x: point.x + 120, y: point.y, button: "left", clickCount: 1 }, sessionId);
  await expectWidth(initial + 120);
  assert.equal(await evaluate("JSON.parse(sessionStorage.getItem('molis-work-ui:' + JSON.parse(document.querySelector('#molis-work-data').textContent).project.project_id + ':current')).treeWidth"), initial + 120, "Pointer release persists the final width");
  await reloadPage();
  await expectWidth(initial + 120);
  await evaluate("document.querySelector('[data-tree-resizer]').focus()");
  await key("ArrowLeft", 37);
  await expectWidth(initial + 104);
  await click('[data-directory-toggle]');
  await viewport(1280);
  await click('[data-directory-show]');
  await expectWidth(initial + 104);
  await navigate(() => command("Page.navigate", { url: origin + "/projects/" + other.project_id + "/" }, sessionId));
  await expectWidth(264);
  await navigate(() => command("Page.navigate", { url: page }, sessionId));
  await expectWidth(initial + 104);
  await click('[data-plugin-strip] [data-plugin-id="goals"]');
  await evaluate("document.querySelector('[data-tree-resizer]').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}))");
  await expectWidth(264);
  await waitFor("Boolean(document.querySelector('[data-graph-node][data-goal-id=long-child] [data-graph-open]'))");
  await click('[data-graph-node][data-goal-id="long-child"] [data-graph-open]');
  await waitFor("document.querySelector('[data-goal-node-workspace]').dataset.expandedGoal==='long-child'");
  await click('[data-goal-collapse]');
  await click('[data-plugin-strip] [data-plugin-id="feed"]');
  await waitFor("document.body.dataset.desktopSurface === 'feed' && !document.querySelector('[data-feed-empty]').hidden && Boolean(document.querySelector('[data-feed-stage-directory]')) && Boolean(document.querySelector('[data-feed-task=all].is-open'))");
  assert.equal(await evaluate("document.querySelector('[data-feed-list]')?.closest('#goal-tree-pane')"), null);
  assert.equal(await evaluate("document.querySelector('[data-feed-views]')?.hidden ?? true"), true);
  assert.equal(await evaluate("getComputedStyle(document.querySelector('[data-feed-empty]')).backgroundColor"), "rgba(0, 0, 0, 0)");
  const emptyText = await evaluate<string>("document.querySelector('[data-feed-empty]').textContent");
  assert.match(emptyText, /添加任务/);
  await capture("directory-feed-empty");

  const feed = createLocalFeedApplication(store.db);
  const now = new Date().toISOString();
  const source = feed.upsertSource({ board_id: DEMO_BOARD_ID, source_id: "directory-rss", kind: "rss", definition_id: "rss", sync_kind: "manual", name: "产品观察", description: "目录验证", status: "active", enabled: true, item_count: 0, origin: "goalboard", config: {}, schedule: { mode: "manual" }, cursor: null, credential_ref: null, account_label: null, last_sync_at: null, last_outcome: null, last_error_code: null, imported_at: now, updated_at: now });
  const item = feed.ingestItem({ source, externalId: "first", title: "从首次使用观察中找到下一步值得改进的地方", summary: "完整保留消息来源和正文，再决定如何推进。", body: "这条消息用于验证在真实目录中打开和阅读内容。", occurredAt: now, attention: false });
  feed.ingestItem({ source, externalId: "second", title: "终端与目标信息应当如何配合", summary: "切换工作时保留上下文，让记录留在正确的目标里。", body: "第二条目录内容。", occurredAt: now, attention: false });
  await reloadPage();
  await waitFor("document.querySelectorAll('[data-feed-entry-id]').length===2");
  const feedRow = await evaluate<{ height: number; size: string; weight: string; titleWidth: number; columns: string }>("(()=>{const row=document.querySelector('[data-feed-entry-id]'),title=row.querySelector('strong');return {height:Math.round(row.getBoundingClientRect().height),size:getComputedStyle(title).fontSize,weight:getComputedStyle(title).fontWeight,titleWidth:Math.round(title.getBoundingClientRect().width),columns:getComputedStyle(row).gridTemplateColumns};})()");
  assert.equal(feedRow.height, 44, "Feed rows share the two-line directory height");
  assert.equal(feedRow.size, "13px");
  assert.ok(Number(feedRow.weight) <= 500);
  assert.ok(feedRow.titleWidth > 120, "Feed item titles use the row, not a leftover icon column");
  assert.doesNotMatch(feedRow.columns, /^(22px|24px)/);
  await capture("directory-feed-list");
  await evaluate("(()=>{const option=document.querySelector('[data-feed-filter-option=\"status\"][data-feed-filter-value=\"archived\"]');option?.click();})()");
  await waitFor("!document.querySelector('[data-feed-empty]').hidden");
  assert.ok(await evaluate("document.querySelector('[data-feed-clear-filters]').getClientRects().length>0"));
  await click('[data-feed-clear-filters]');
  await click('[data-feed-filter-trigger]');
  assert.ok(await evaluate("(()=>{let p=document.querySelector('[data-feed-filter-panel]').getBoundingClientRect(),r=document.querySelector('[data-work-surface=feed]').getBoundingClientRect();return p.left>=r.left&&p.right<=r.right&&p.bottom<=innerHeight;})()"));
  await capture("directory-feed-filter");
  await click('[data-feed-filter-trigger]');
  await click('[data-feed-entry-id][data-feed-item-id="' + item.item.item_id + '"]');
  await waitFor("document.body.dataset.desktopSurface === 'feed' && Boolean(document.querySelector('[data-feed-item-wrap=\"" + item.item.item_id + "\"] [data-feed-item-slot]:not([hidden])')) && (document.querySelector('[data-work-surface=feed]')?.textContent || '').includes('从首次使用观察中找到下一步值得改进的地方')");
  await click('[data-plugin-strip] [data-plugin-id="sessions"]');
  await waitFor("document.querySelectorAll('[data-operation-row=session]').length===2 && document.querySelector('[data-directory-list-title]')?.textContent === 'Sessions'");
  const sessionRow = await evaluate<{ height: number; size: string }>("(()=>{const row=document.querySelector('[data-operation-row=session]'),title=row.querySelector('strong');return {height:Math.round(row.getBoundingClientRect().height),size:getComputedStyle(title).fontSize};})()");
  assert.equal(sessionRow.height, 44, "Session rows share the two-line directory height");
  assert.equal(sessionRow.size, "13px");
  assert.ok(await evaluate("(()=>{const title=document.querySelector('[data-directory-list-title]'),tools=document.querySelector('[data-directory-panel=sessions]:not([hidden]) [data-directory-list-actions]');return title&&tools&&Math.abs(title.getBoundingClientRect().top+title.getBoundingClientRect().height/2-(tools.getBoundingClientRect().top+tools.getBoundingClientRect().height/2))<8&&!document.querySelector('[data-operation-search]');})()"));
  await capture("directory-sessions-list");
  await click('.project-record-filter-menu > summary');
  assert.ok(await evaluate("(()=>{let p=document.querySelector('.project-record-filter-menu > div').getBoundingClientRect(),r=document.querySelector('#goal-tree-pane').getBoundingClientRect();return p.left>=r.left&&p.right<=r.right&&p.width>=r.width-24;})()"));
  await capture("directory-sessions-filter");
  await evaluate("(()=>{let s=document.querySelector('[data-session-runtime-filter]');s.value='codex';s.dispatchEvent(new Event('change',{bubbles:true}));})()");
  await waitFor("document.querySelectorAll('[data-operation-row=session]:not([hidden])').length===1");
  await key("Escape", 27);
  assert.equal(await evaluate("document.querySelector('.project-record-filter-menu').open"), false);
  await click('[data-operation-select="' + session.session_id + '"]');
  await waitFor("document.body.dataset.desktopSurface === 'sessions' && !document.querySelector('[data-work-surface=sessions]').hidden");
  await command("Emulation.setEmulatedMedia", { features: [{ name: "prefers-color-scheme", value: "dark" }, { name: "prefers-reduced-motion", value: "reduce" }] }, sessionId);
  await evaluate("document.documentElement.dataset.resolvedTheme='dark'");
  assert.equal(await evaluate("getComputedStyle(document.querySelector('[data-operation-row=session] strong')).color"), "rgb(232, 233, 238)");
  await capture("directory-sessions-dark");
  await viewport(1024, 800);
  assert.ok(await evaluate("document.documentElement.scrollWidth<=innerWidth"));
  await capture("directory-1024");
  await viewport(700, 800);
  assert.ok(await evaluate("document.querySelector('[data-tree-resizer]').getClientRects().length>0"));
  await evaluate("document.querySelector('[data-tree-resizer]').focus()");
  await key("ArrowRight", 39);
  await expectWidth(280);
  await viewport(390, 844);
  await click('[data-directory-show]');
  await click('[data-plugin-strip] [data-plugin-id="goals"]');
  assert.ok(await evaluate("document.querySelector('.navigator-project').getBoundingClientRect().height===84"));
  assert.ok(await evaluate("document.querySelector('.personal-sidebar-footer').getBoundingClientRect().bottom<=innerHeight"));
  await expectWidth(264);
  assert.equal(await evaluate("document.querySelector('[data-tree-resizer]').getClientRects().length"), 0);
  assert.ok(await evaluate("document.documentElement.scrollWidth<=innerWidth"));
  await capture("directory-mobile");
  await click('[data-select-goal="long-child"]');
  await waitFor("!document.querySelector('[data-workspace]').classList.contains('is-directory-drawer-open')");
  assert.deepEqual(store.snapshot(DEMO_BOARD_ID).goals, before.goals);
  assert.deepEqual(store.snapshot(DEMO_BOARD_ID).runs, before.runs);
  assert.deepEqual(await evaluate("window.__uiErrors"), []);
});
