import assert from "node:assert/strict";
import test from "node:test";
import { DEMO_BOARD_ID, GoalProjectApplication } from "@molis-ai/molis-work-app-local-host";
import { openGoalBrowser } from "./fixtures/goal-browser.js";

test("Project navigation preserves the fixed Goal workspace, terminal instance, and camera without writing Goal facts", { timeout: 60_000 }, async (t) => {
  const browser = await openGoalBrowser(t);
  if (!browser) return;
  const { command, sessionId, evaluate, waitFor, navigate, click, origin, store, before } = browser;
  await command("Page.addScriptToEvaluateOnNewDocument", { source: "window.__uiErrors=[];addEventListener('error',e=>window.__uiErrors.push(e.message));addEventListener('unhandledrejection',e=>window.__uiErrors.push(String(e.reason)));" }, sessionId);
  await command("Emulation.setDeviceMetricsOverride", { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false }, sessionId);
  await command("Emulation.setEmulatedMedia", { features: [{ name: "prefers-reduced-motion", value: "reduce" }] }, sessionId);
  await navigate(() => command("Page.navigate", { url: origin + "/" }, sessionId));
  await waitFor("document.body.dataset.desktopSurface === 'home'");
  assert.equal(await evaluate("document.querySelector('[data-work-surface=home]').hidden"), false);
  assert.equal(await evaluate("document.querySelector('[data-goal-canvas-shell]').hidden"), true);
  assert.deepEqual(await evaluate("window.__uiErrors"), []);
  assert.equal(await evaluate("document.querySelector('#goal-tree-pane').dataset.desktopDirectory"), "root");
  await click('[data-plugin-strip] [data-plugin-id="goals"]');
  await waitFor("document.querySelector('[data-goal-momentum]')?.dataset.loaded === 'true'");
  await waitFor("document.querySelector('[data-plugin-strip] [data-plugin-id=goals]').getAttribute('aria-current') === 'page'");
  const goalId = await evaluate<string>("document.querySelector('[data-select-goal]').dataset.selectGoal");
  const camera = await evaluate("document.querySelector('[data-graph-stage]').getAttribute('style')");
  await waitFor("Boolean(document.querySelector(" + JSON.stringify('[data-graph-node][data-goal-id="' + goalId + '"] [data-graph-open]') + "))");
  await click('[data-graph-node][data-goal-id="' + goalId + '"] [data-graph-open]');
  await waitFor("document.querySelector('[data-goal-node-workspace]')?.dataset.expandedGoal === " + JSON.stringify(goalId));
  assert.equal(await evaluate("document.querySelector('[data-goal-node-workspace]').dataset.workMode"), "terminal");
  assert.equal(await evaluate("document.querySelector('[data-goal-work-mode=conversation]').disabled"), true);
  await click('[data-goal-work-mode="conversation"]');
  assert.equal(await evaluate("document.querySelector('[data-goal-node-workspace]').dataset.workMode"), "terminal");
  await evaluate("window.__terminalInstance=document.querySelector('[data-tui-terminal]')");
  await click('[data-goal-work-mode="terminal"]');
  assert.equal(await evaluate("document.querySelector('[data-tui-pane]').hidden"), false);
  await click('[data-plugin-strip] [data-plugin-id="sessions"]');
  assert.equal(await evaluate("document.body.dataset.desktopSurface"), "sessions");
  assert.equal(await evaluate("document.querySelector('[data-directory-panel=sessions]').hidden"), false);
  assert.equal(await evaluate("document.querySelector('[data-work-surface=sessions]').hidden"), false);
  await click('[data-plugin-strip] [data-plugin-id="goals"]');
  assert.equal(await evaluate("document.body.dataset.desktopSurface"), "goal");
  assert.equal(await evaluate("document.querySelector('[data-goal-node-workspace]').dataset.expandedGoal"), "");
  assert.equal(await evaluate("document.querySelector('[data-goal-node-workspace]').hidden"), true);
  await click('[data-graph-node][data-goal-id="' + goalId + '"] [data-graph-open]');
  await waitFor("document.querySelector('[data-goal-node-workspace]')?.dataset.expandedGoal === " + JSON.stringify(goalId));
  assert.equal(await evaluate("document.querySelector('[data-tui-pane]').hidden"), false);
  assert.equal(await evaluate("window.__terminalInstance===document.querySelector('[data-tui-terminal]')"), true);
  assert.equal(await evaluate("document.querySelector('[data-plugin-heading]').hidden"), false);
  assert.equal(await evaluate("document.querySelector('#goal-tree-pane').dataset.desktopDirectory"), "goals");
  assert.equal(await evaluate("document.querySelector('[data-goal-node-workspace]').hidden"), false);
  await click('[data-goal-collapse]');
  assert.equal(await evaluate("document.querySelector('[data-graph-stage]').getAttribute('style')"), camera);
  assert.deepEqual(store.snapshot(DEMO_BOARD_ID).goals, before.goals);
  assert.deepEqual(store.snapshot(DEMO_BOARD_ID).runs, before.runs);
  await command("Emulation.setDeviceMetricsOverride", { width: 390, height: 844, deviceScaleFactor: 1, mobile: true }, sessionId);
  await click('[data-directory-show]');
  await click('[data-plugin-strip] [data-plugin-id="goals"]');
  assert.equal(await evaluate("document.querySelector('[data-workspace]').classList.contains('is-directory-drawer-open')"), true);
  assert.equal(await evaluate("document.querySelector('[data-plugin-stage]').inert"), true);
  await click('[data-select-goal="' + goalId + '"]');
  await waitFor("!document.querySelector('[data-workspace]').classList.contains('is-directory-drawer-open')");
  assert.equal(await evaluate("document.documentElement.scrollWidth <= innerWidth"), true);
  assert.deepEqual(await evaluate("window.__uiErrors"), []);
});

test("Bundled market adds to the selected project and Artifact versions stay in the current workbench", { timeout: 60_000 }, async t => {
  const browser = await openGoalBrowser(t, true);
  if (!browser) return;
  const { store, projectId, command, sessionId, evaluate, waitFor, navigate, click, origin } = browser;
  const app = new GoalProjectApplication(store);
  for (const version of [1, 2]) app.artifacts.commands.registerVersion({
    board_id: DEMO_BOARD_ID, actor_id: "fixture", artifact_id: "review-note", version,
    artifact_type_id: "example.note", schema_version: 1,
    producer: { plugin_id: "example.writer", plugin_version: "1.0.0", binding_signature: "fixture" },
    content: { kind: "inline", payload: { text: version === 1 ? "Original result" : "Revised result" } }, metadata: {},
  });
  await command("Emulation.setDeviceMetricsOverride", { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false }, sessionId);
  const prefix = "/projects/" + projectId;
  await navigate(() => command("Page.navigate", { url: origin + prefix + "/" }, sessionId));
  assert.equal(await evaluate("document.querySelector('[data-plugin-strip] [data-plugin-id=artifacts]')"), null);
  assert.equal(await evaluate("document.querySelector('[data-plugin-strip] [data-plugin-id]:last-child')?.dataset.pluginId"), "market");
  assert.equal(await evaluate("document.querySelector('.personal-sidebar-footer [data-work-surface-open=market]')"), null);
  const otherId = await evaluate<string>(`(async()=>{const r=await fetch('/api/settings/projects',{method:'POST',headers:globalThis.molisWorkControlHeaders(),body:JSON.stringify({display_name:'另一个项目',user_confirmed:true})});if(!r.ok)throw new Error(await r.text());return (await r.json()).project.project_id;})()`);
  await click('[data-work-surface-open="market"]');
  await waitFor("!document.querySelector('[data-market-project]').disabled");
  await evaluate(`(()=>{const s=document.querySelector('[data-market-project]');s.value=${JSON.stringify(otherId)};s.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  await click('[data-market-add="feed"]');
  await waitFor("document.querySelector('[data-market-add=feed]').textContent === '已添加'");
  assert.equal(await evaluate("document.querySelector('[data-market-add=inbox]').textContent"), "已添加");
  const list = await evaluate<{ project_id: string; plugins: string[] }[]>("fetch('/api/settings/project-plugins').then(r=>r.json()).then(r=>r.projects)");
  assert.deepEqual(list.find(item => item.project_id === projectId)!.plugins, ["goals"]);
  assert.deepEqual(list.find(item => item.project_id === otherId)!.plugins, ["feed", "goals", "inbox"]);
  await evaluate(`(()=>{const s=document.querySelector('[data-market-project]');s.value=${JSON.stringify(projectId)};s.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  await navigate(() => click('[data-market-add="artifacts"]'));
  await waitFor("document.body.dataset.desktopSurface === 'market' && !document.querySelector('[data-market-project]').disabled");
  await evaluate("(()=>{let q=document.querySelector('[data-market-search]');q.value='Artifacts';q.dispatchEvent(new Event('input',{bubbles:true}));})()");
  assert.deepEqual(await evaluate("[...document.querySelectorAll('[data-market-plugin]:not([hidden])')].map(x=>x.dataset.marketPlugin)"), ["artifacts"]);
  await click('[data-plugin-strip] [data-plugin-id="artifacts"]');
  await waitFor("document.querySelector('[data-artifact-directory] .artifact-version-list')");
  await evaluate("window.__workbenchInstance=document.querySelector('[data-workspace]')");
  await click('[data-artifact-directory] a[href$="/versions/1"]');
  await waitFor("document.body.dataset.desktopSurface === 'artifacts' && /Original result/.test(document.querySelector('[data-artifact-detail] h1')?.textContent || '')");
  assert.equal(await evaluate("window.__workbenchInstance===document.querySelector('[data-workspace]')"), true);
  await navigate(() => command("Page.navigate", { url: origin + "/projects/" + otherId + "/" }, sessionId));
  await waitFor("document.body.dataset.desktopSurface === 'home'");
  assert.equal(await evaluate("document.querySelector('[data-plugin-strip] [data-plugin-id=artifacts]')"), null);
  assert.ok(await evaluate("Boolean(document.querySelector('[data-plugin-strip] [data-plugin-id=feed]'))"));
  assert.ok(await evaluate("Boolean(document.querySelector('[data-plugin-strip] [data-plugin-id=inbox]'))"));
  await click('[data-plugin-strip] [data-plugin-id="inbox"]');
  await waitFor("document.body.dataset.desktopSurface === 'inbox' && document.querySelector('[data-directory-panel=inbox]:not([hidden])')");
  assert.match(await evaluate<string>("document.querySelector('[data-inbox-empty]')?.textContent || ''"), /现在没有需要你介入的事项/);
  assert.equal(await evaluate("document.querySelector('[data-feed-views]')"), null);
  await click('[data-plugin-strip] [data-plugin-id="feed"]');
  await waitFor("document.body.dataset.desktopSurface === 'feed' && Boolean(document.querySelector('[data-feed-stage-directory]'))");
  assert.equal(await evaluate("document.querySelector('[data-feed-views]')"), null);
  assert.equal(await evaluate("document.querySelector('#goal-tree-pane')?.dataset.desktopDirectory"), "root");
  assert.ok(await evaluate("Boolean(document.querySelector('[data-feed-task=all]'))"));
  assert.equal(await evaluate("document.querySelector('[data-feed-list]')?.closest('#goal-tree-pane')"), null);
});

test("Project entry lands at home, while refresh preserves work and Goal links remain direct", { timeout: 60_000 }, async (t) => {
  const browser = await openGoalBrowser(t);
  if (!browser) return;
  const { command, sessionId, evaluate, waitFor, navigate, click, reloadPage, origin } = browser;
  await navigate(() => command("Page.navigate", { url: origin + "/" }, sessionId));
  await waitFor("document.body.dataset.desktopSurface === 'home'");
  await click('[data-plugin-strip] [data-plugin-id="goals"]');
  await waitFor("document.body.dataset.desktopSurface === 'goal'");
  await waitFor("document.querySelector('[data-goal-momentum]')?.dataset.loaded === 'true'");
  const goalId = await evaluate<string>("document.querySelector('[data-select-goal]').dataset.selectGoal");
  await waitFor("Boolean(document.querySelector(" + JSON.stringify('[data-graph-node][data-goal-id="' + goalId + '"] [data-graph-open]') + "))");
  await click('[data-graph-node][data-goal-id="' + goalId + '"] [data-graph-open]');
  await waitFor("!document.querySelector('[data-goal-node-workspace]').hidden");
  await reloadPage();
  await waitFor("document.body.dataset.desktopSurface === 'goal'");
  assert.equal(await evaluate("document.querySelector('[data-goal-node-workspace]').hidden"), true);
  await navigate(() => command("Page.navigate", { url: origin + "/goals/" + encodeURIComponent(goalId) }, sessionId));
  await waitFor("document.querySelector('[data-goal-node-workspace]').dataset.expandedGoal === " + JSON.stringify(goalId));
  assert.equal(await evaluate("document.querySelector('[data-goal-node-workspace]').hidden"), false);
  await click('[data-plugin-strip] [data-plugin-id="home"]');
  assert.equal(await evaluate("document.body.dataset.desktopSurface"), "home");
});
