import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test, { after } from "node:test";
import { fileURLToPath } from "node:url";

// specs/repository-anti-corruption §4.16 (W1-09): the checks for what is not TypeScript (scripts/gates/native-checks.mjs).
// Each check is broken once on a scratch repository and must go red; the clean case must pass. A check whose tool is not on
// this machine is skipped here and says so (CI runs rust and swift on macOS and shell on Linux, so none is skipped there);
// the shell plumbing (which files are handed over, the severity flag, a failing exit) is also tested against a stub
// shellcheck, so it is covered where the real one is missing. Plain node:test, no tsx: the macOS job installs nothing.
const script = fileURLToPath(new URL("../scripts/gates/native-checks.mjs", import.meta.url));
const scratchDirs = [];
const scratchRoot = mkdtempSync(path.join(tmpdir(), "molis-native-checks-"));
after(() => { rmSync(scratchRoot, { recursive: true, force: true }); });

const have = (command, args) => spawnSync(command, args, { stdio: "ignore" }).status === 0;
const haveRust = have("cargo", ["--version"]) && have("cargo", ["clippy", "--version"]) && have("rustfmt", ["--version"]);
const haveSwift = process.platform === "darwin" && have("swiftc", ["--version"]);
const haveShellcheck = have("shellcheck", ["--version"]);

const repoWith = (files) => {
  const dir = mkdtempSync(path.join(scratchRoot, "repo-"));
  scratchDirs.push(dir);
  execFileSync("git", ["init", "-q", "-b", "main"], { cwd: dir });
  for (const [file, text] of Object.entries(files)) {
    mkdirSync(path.dirname(path.join(dir, file)), { recursive: true });
    writeFileSync(path.join(dir, file), text);
  }
  execFileSync("git", ["add", "-A"], { cwd: dir });
  return dir;
};
const gate = (dir, args, env = {}) => {
  const run = spawnSync(process.execPath, [script, "--root", dir, ...args], { encoding: "utf8", env: { ...process.env, CARGO_TARGET_DIR: path.join(scratchRoot, "cargo-target"), CARGO_NET_OFFLINE: "true", ...env } });
  return { code: run.status, out: `${run.stdout}${run.stderr}` };
};

// ---- Rust -------------------------------------------------------------------------------------------------------------
const RUST_MANIFEST = [`[package]`, `name = "scratch-desktop"`, `version = "0.0.0"`, `edition = "2021"`, ``, `[[bin]]`, `name = "scratch-desktop"`, `path = "../adapters/tauri/src/main.rs"`, ``].join("\n");
const RUST_LOCK = `# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "scratch-desktop"\nversion = "0.0.0"\n`;
const CLEAN_MAIN = `fn main() {\n    println!("hi");\n}\n`;
const crate = (main, extra = {}) => repoWith({
  "apps/desktop/src-tauri/Cargo.toml": RUST_MANIFEST, "apps/desktop/src-tauri/Cargo.lock": RUST_LOCK,
  "apps/desktop/adapters/tauri/src/main.rs": main, ...extra,
});
const rust = { skip: haveRust ? false : "cargo, clippy and rustfmt are not installed here" };

test("rust: a formatted, warning-free crate passes", rust, () => {
  const run = gate(crate(CLEAN_MAIN), ["rust"]);
  assert.equal(run.code, 0, run.out);
  assert.match(run.out, /rust checks passed: 1 Rust files formatted, clippy clean/);
});
test("rust: unformatted code fails rustfmt --check", rust, () => {
  const run = gate(crate(`fn main(){println!("hi");}\n`), ["rust"]);
  assert.equal(run.code, 1, run.out);
  assert.match(run.out, /rustfmt --check found unformatted code/);
});
test("rust: a clippy lint fails", rust, () => {
  const run = gate(crate(`fn one() -> i32 {\n    return 1;\n}\n\nfn main() {\n    println!("{}", one());\n}\n`), ["rust"]);
  assert.equal(run.code, 1, run.out);
  assert.match(run.out, /cargo clippy -D warnings failed/);
  assert.match(run.out, /needless_return/);
});
test("rust: a compiler warning fails too (every warning is an error)", rust, () => {
  const run = gate(crate(`fn main() {\n    let unused = 1;\n}\n`), ["rust"]);
  assert.equal(run.code, 1, run.out);
  assert.match(run.out, /unused variable/);
});
test("rust: code in a test module that does not compile in tests fails (--all-targets)", rust, () => {
  const run = gate(crate(`fn main() {}\n\n#[cfg(test)]\nmod tests {\n    #[test]\n    fn broken() {\n        let unused = 1;\n    }\n}\n`), ["rust"]);
  assert.equal(run.code, 1, run.out);
});
test("rust: a Rust file outside apps/desktop is refused, however clean", () => {
  const run = gate(crate(CLEAN_MAIN, { "tooling/other/lib.rs": "pub fn f() {}\n" }), ["rust"]);
  assert.equal(run.code, 1, run.out);
  assert.match(run.out, /tooling\/other\/lib\.rs is Rust code outside apps\/desktop\//);
});
test("rust: a repository without Rust files has nothing to check", () => {
  const run = gate(repoWith({ "README.md": "# x\n" }), ["rust"]);
  assert.equal(run.code, 0, run.out);
  assert.match(run.out, /no Rust files/);
});

// ---- Swift ------------------------------------------------------------------------------------------------------------
const JELLY = "apps/local-host/native/materials/JellyMaterial.swift";
const swift = { skip: haveSwift ? false : "swiftc on macOS is not available here" };
const CLEAN_SWIFT = `import Foundation\n\n@main struct Tool {\n    static func main() { print("ok") }\n}\n`;

test("swift: a file that type-checks passes", swift, () => {
  const run = gate(repoWith({ [JELLY]: CLEAN_SWIFT }), ["swift"]);
  assert.equal(run.code, 0, run.out);
  assert.match(run.out, /swift checks passed/);
});
test("swift: a type error fails", swift, () => {
  const run = gate(repoWith({ [JELLY]: `import Foundation\n\n@main struct Tool {\n    static func main() { let value: Int = "text"; print(value) }\n}\n` }), ["swift"]);
  assert.equal(run.code, 1, run.out);
  assert.match(run.out, /swiftc -typecheck apps\/local-host\/native\/materials\/JellyMaterial\.swift failed/);
});
test("swift: a Swift file the checks do not know is refused (no tool needed)", () => {
  const run = gate(repoWith({ [JELLY]: CLEAN_SWIFT, "apps/local-host/native/other/New.swift": "import Foundation\n" }), ["swift"]);
  assert.equal(run.code, 1, run.out);
  assert.match(run.out, /apps\/local-host\/native\/other\/New\.swift is Swift code the checks do not know/);
});
test("swift: a repository without Swift files has nothing to check", () => {
  assert.equal(gate(repoWith({ "README.md": "# x\n" }), ["swift"]).code, 0);
});

// ---- shell ------------------------------------------------------------------------------------------------------------
// A stand-in for shellcheck that fails on a file containing BAD and logs what it was given.
const stubBin = () => {
  const dir = mkdtempSync(path.join(scratchRoot, "stub-"));
  const log = path.join(dir, "args.log");
  writeFileSync(path.join(dir, "shellcheck"), [
    "#!/bin/sh", `if [ "$1" = "--version" ]; then echo stub; exit 0; fi`, `echo "$@" > "${log}"`,
    `for f in "$@"; do case "$f" in --*) ;; *) if grep -q BAD "$f"; then echo "$f: BAD"; exit 1; fi ;; esac; done`, ""].join("\n"));
  chmodSync(path.join(dir, "shellcheck"), 0o755);
  return { dir, log };
};
const withStub = (stub) => ({ PATH: `${stub.dir}${path.delimiter}${process.env.PATH}` });

test("shell: every .sh file and every shebang script is handed to shellcheck at warning severity", () => {
  const stub = stubBin();
  const dir = repoWith({ "Start.sh": "#!/bin/bash\necho ok\n", "tools/run": "#!/usr/bin/env bash\necho ok\n", "notes.txt": "BAD but not a script\n", "data.json": "{}\n" });
  const run = gate(dir, ["shell"], withStub(stub));
  assert.equal(run.code, 0, run.out);
  const args = readFileSync(stub.log, "utf8").trim().split(/\s+/);
  assert.deepEqual(args.sort(), ["--severity=warning", "Start.sh", "tools/run"].sort());
});
test("shell: a failing script fails the run, however it is named", () => {
  const stub = stubBin();
  const dir = repoWith({ "a.sh": "#!/bin/bash\necho ok\n", "bin/tool": "#!/bin/sh\n# BAD\n" });
  const run = gate(dir, ["shell"], withStub(stub));
  assert.equal(run.code, 1, run.out);
  assert.match(run.out, /shellcheck found problems/);
  assert.match(run.out, /bin\/tool: BAD/);
});
test("shell: no shell scripts, nothing to check (and no shellcheck needed)", () => {
  const run = gate(repoWith({ "README.md": "# x\n" }), ["shell"]);
  assert.equal(run.code, 0, run.out);
  assert.match(run.out, /no shell scripts/);
});
test("shell: scripts without shellcheck installed is exit 2, never a pass", () => {
  // A PATH that has git (the run lists the tracked files with it) and nothing else, so no shellcheck.
  const onlyGit = mkdtempSync(path.join(scratchRoot, "only-git-"));
  const git = spawnSync("sh", ["-c", "command -v git"], { encoding: "utf8" }).stdout.trim();
  symlinkSync(git, path.join(onlyGit, "git"));
  const run = gate(repoWith({ "a.sh": "#!/bin/bash\necho ok\n" }), ["shell"], { PATH: onlyGit });
  assert.equal(run.code, 2, run.out);
  assert.match(run.out, /shellcheck --version did not run/);
});
const realShell = { skip: haveShellcheck ? false : "shellcheck is not installed here" };
test("shell: the real shellcheck passes a clean script", realShell, () => {
  assert.equal(gate(repoWith({ "a.sh": "#!/bin/bash\nset -euo pipefail\necho \"$1\"\n" }), ["shell"]).code, 0);
});
test("shell: the real shellcheck fails a warning (cd without a guard)", realShell, () => {
  const run = gate(repoWith({ "a.sh": "#!/bin/bash\ncd /tmp\nls\n" }), ["shell"]);
  assert.equal(run.code, 1, run.out);
  assert.match(run.out, /SC2164/);
});

// ---- Python -----------------------------------------------------------------------------------------------------------
const python = { skip: have("python3", ["-I", "--version"]) ? false : "python3 is not installed here" };
test("python: a file that parses passes", python, () => {
  const run = gate(repoWith({ "tools/worker.py": "import sys\nprint(sys.argv)\n" }), ["python"]);
  assert.equal(run.code, 0, run.out);
  assert.match(run.out, /python checks passed: 1 Python files parse/);
});
test("python: a syntax error fails, and the check writes no __pycache__", python, () => {
  const dir = repoWith({ "tools/ok.py": "x = 1\n", "tools/broken.py": "def f(:\n    pass\n" });
  const run = gate(dir, ["python"]);
  assert.equal(run.code, 1, run.out);
  assert.match(run.out, /tools\/broken\.py does not parse/);
  assert.equal(existsSync(path.join(dir, "tools/__pycache__")), false);
});
test("python: a repository without Python files has nothing to check", () => {
  assert.equal(gate(repoWith({ "README.md": "# x\n" }), ["python"]).code, 0);
});

// ---- the command line ---------------------------------------------------------------------------------------------------
test("a missing or unknown argument is exit 2", () => {
  assert.equal(spawnSync(process.execPath, [script], { encoding: "utf8" }).status, 2);
  assert.equal(spawnSync(process.execPath, [script, "ruby"], { encoding: "utf8" }).status, 2);
  assert.equal(spawnSync(process.execPath, [script, "rust", "--package"], { encoding: "utf8" }).status, 2);
});
