import assert from "node:assert/strict";
import test from "node:test";
import Database from "better-sqlite3";
import { SqlitePluginPrivateStorage } from "@molis-ai/molis-work-plugin-runtime";
import { parsePluginManifest, type PluginCapabilityClient, type PluginRouteRequest, type PluginStartContext } from "@molis-ai/molis-work-contracts/platform/plugin";
import { agentHostCapabilities as agent, type AgentRunControl, type AgentRunHandle, type AgentRunRef, type AgentRunView, type AgentSessionRef, type AgentStartRequest } from "@molis-ai/molis-work-contracts/services/agent-host";
import { projectsCapabilities } from "@molis-ai/molis-work-contracts/modules/projects";
import { BuilderWorkflow, type BuilderPorts } from "../plugins/native/plugin-builder/src/workflow.js";
import { builderManifest } from "../plugins/native/plugin-builder/src/manifest.js";
import { builderPrompts } from "../plugins/native/plugin-builder/src/roles.js";
import { builderRoutes } from "../plugins/native/plugin-builder/src/routes.js";
import { RecordStore } from "../plugins/native/plugin-builder/src/records.js";
import type { Design } from "../plugins/native/plugin-builder/src/model.js";

const config = { workspace_id: "approved-workspace", provider_id: "configured-provider", model_id: "configured-model" };
const selected: Design = {
  id: "stock-table", title: "库存记录", description: "输入数量与单价查看库存价值", journey: ["添加库存", "查看金额汇总"], acceptance: ["数量乘单价得到库存价值"],
  fields: [{ id: "name", label: "名称", type: "text", required: true }, { id: "quantity", label: "数量", type: "number", required: true }, { id: "price", label: "单价", type: "number", required: true }],
  calculations: [{ id: "value", label: "库存价值", expression: { op: "multiply", left: { op: "field", id: "quantity" }, right: { op: "field", id: "price" } } }],
  layout: "table", allowImport: true, allowExport: true,
};
// Model responses are independent fixtures, never generated by production prompts or parsers.
const designResponse = JSON.stringify({ summary: "两个库存管理方案", candidates: [
  { ...selected, rationale: "表格适合对照数量和单价" },
  { ...selected, id: "stock-cards", layout: "cards", rationale: "卡片适合逐项浏览" },
] });
const uiResponse = JSON.stringify([
  { id: "heading", kind: "heading", label: "库存" }, { id: "entry", kind: "form", label: "新增库存" },
  { id: "find", kind: "search", label: "搜索库存" }, { id: "items", kind: "collection", label: "全部库存" },
  { id: "operations", kind: "actions", label: "导入与导出" }, { id: "totals", kind: "summary", label: "价值汇总" },
]);
const behaviorResponse = JSON.stringify({ calculations: [{ id: "value", label: "库存价值", expression: {
  op: "multiply", left: { op: "field", id: "quantity" }, right: { op: "field", id: "price" },
} }], allowImport: true, allowExport: true });

function deferred<T>() {
  let resolve!: (value: T) => void;
  const promise = new Promise<T>(done => { resolve = done; });
  return { promise, resolve };
}
function gate<T>() { return { entered: deferred<void>(), result: deferred<T>() }; }
type Gate<T> = ReturnType<typeof gate<T>>;

class FakeRuntime implements PluginCapabilityClient {
  readonly calls: string[] = [];
  readonly starts: Array<{ runtime: string; request: AgentStartRequest; ref: AgentRunRef }> = [];
  readonly controls: Array<{ session: AgentSessionRef; ref: AgentRunRef; control: AgentRunControl }> = [];
  readonly views = new Map<string, AgentRunView>();
  readonly readGates: Gate<AgentRunView>[] = [];
  readonly startGates: Gate<void>[] = [];
  workspaces = [{ workspace_id: config.workspace_id, display_name: "已授权项目", canonical_path: "/approved/project", realpath_verified: true }];
  private sessionCount = 0;
  async invoke<Input, Output>(definition: { capability_id: string }, args: Input): Promise<Output> {
    this.calls.push(definition.capability_id);
    assert.ok(builderManifest.capabilities.consumes.includes(definition.capability_id), "workflow must only invoke manifest-declared capabilities");
    const input = args as unknown as unknown[];
    if (definition.capability_id === projectsCapabilities.listWorkspaces.capability_id) return structuredClone(this.workspaces) as Output;
    if (definition.capability_id === agent.listRuntimes.capability_id) return [{ runtime_id: "prologue" }] as Output;
    if (definition.capability_id === agent.createSession.capability_id) {
      assert.equal(input[0], "prologue");
      return { session_id: `session-${++this.sessionCount}`, runtime_id: "prologue" } as Output;
    }
    if (definition.capability_id === agent.startRun.capability_id) {
      const request = structuredClone(input[1]) as AgentStartRequest;
      const ref = { session_id: request.session.session_id, run_id: `run-${this.starts.length + 1}` };
      this.starts.push({ runtime: input[0] as string, request, ref });
      this.views.set(ref.run_id, this.view(ref, "running"));
      const pending = this.startGates.shift();
      if (pending) { pending.entered.resolve(); await pending.result.promise; }
      return { ref } as AgentRunHandle as Output;
    }
    if (definition.capability_id === agent.readRun.capability_id) {
      const pending = this.readGates.shift();
      if (pending) { pending.entered.resolve(); return await pending.result.promise as Output; }
      const ref = input[1] as AgentRunRef, view = this.views.get(ref.run_id);
      assert.ok(view, "readRun must reference an actual started fixture run");
      return structuredClone(view) as Output;
    }
    if (definition.capability_id === agent.controlRun.capability_id) {
      this.controls.push({ session: structuredClone(input[0]) as AgentSessionRef, ref: structuredClone(input[1]) as AgentRunRef, control: structuredClone(input[2]) as AgentRunControl });
      return undefined as Output;
    }
    throw new Error(`Unexpected fixture capability: ${definition.capability_id}`);
  }
  view(ref: AgentRunRef, phase: AgentRunView["phase"], text = ""): AgentRunView {
    return { ref, phase, turns: text ? [{ turn_id: "answer", kind: "assistant", text, at: "2026-09-23T00:00:00Z" }] : [],
      frozen: { role_id: "fixture", role_version: 1, execution: "read-only", model_id: "configured-model", prompts: [], skills: [], mcp_tools: [], host_tools: [], text_materials: [], budget: null, directory: { canonical_path: "/approved/project", realpath_verified: true } },
      activity: [], awaiting_input: [], usage: { tokens: { input: 0, output: 0 } }, started_at: "2026-09-23T00:00:00Z", ended_at: phase === "completed" ? "2026-09-23T00:00:01Z" : null,
    };
  }
  complete(runId: string, text: string) { const view = this.views.get(runId); assert.ok(view); this.views.set(runId, this.view(view.ref, "completed", text)); }
}

function fixture() {
  const db = new Database(":memory:"), runtime = new FakeRuntime();
  const baseContext = { board_id: "test-board", plugin_id: builderManifest.plugin_id, version: builderManifest.version, install_id: "test-install", requireGrant(permission: string) { assert.equal(permission, "storage:private"); } } as PluginStartContext;
  const storage = new SqlitePluginPrivateStorage(db).forPlugin(baseContext, builderManifest);
  const context: PluginStartContext = { ...baseContext, services: { storage, capabilities: runtime } as unknown as PluginStartContext["services"] };
  let models = [{ provider_id: config.provider_id, model_id: config.model_id, label: "Fixture configured model" }];
  const ports: BuilderPorts = { async ready() {}, async models() { return models; }, selectionAvailable() { return false; } };
  return { db, runtime, context, storage, ports, workflow: new BuilderWorkflow(context, ports), clearModels() { models = []; } };
}
async function uiRun(f: ReturnType<typeof fixture>) {
  let doc = f.workflow.store.create("记录库存并自动计算价值");
  doc = await f.workflow.start(doc.id, doc.revision, "design", config, "actor");
  f.runtime.complete(doc.active!.run_id!, designResponse);
  doc = await f.workflow.advance(doc.id, "actor");
  doc = await f.workflow.choose(doc.id, doc.revision, "stock-table", "manual");
  return f.workflow.resume(doc.id, doc.revision, config, "actor");
}
const routeRequest = (id: string): PluginRouteRequest => ({ method: "GET", pathname: `/builds/${id}`, params: { id }, query: {}, body: undefined, actor_id: "actor" });

test("Prologue workflow selects a candidate, persists UI parts incrementally, connects behavior and produces usable records", async () => {
  const f = fixture();
  try {
    let doc = await uiRun(f);
    assert.equal(doc.phase, "building"); assert.equal(doc.active!.stage, "ui");
    assert.equal(doc.selection!.source, "manual");
    assert.deepEqual(doc.design, selected);
    f.runtime.complete(doc.active!.run_id!, uiResponse);
    doc = await f.workflow.advance(doc.id, "actor");
    assert.deepEqual(doc.nodes.map(node => node.id), ["heading"]);
    assert.deepEqual(doc.pendingNodes.map(node => node.id), ["entry", "find", "items", "operations", "totals"]);
    assert.equal(doc.active!.stage, "behavior"); assert.equal(doc.behavior, null);
    // A page read only observes; refresh must never move a part or bump the revision.
    const read = builderRoutes(f.context, f.workflow).find(route => route.route_id === "builder.read")!;
    const beforeRead = f.workflow.require(doc.id);
    assert.equal((await read.handle(routeRequest(doc.id))).status, 200);
    assert.deepEqual(f.workflow.require(doc.id), beforeRead);
    // Recreate the workflow owner to demonstrate persisted stage/configuration recovery.
    const recovered = new BuilderWorkflow(f.context, f.ports);
    f.runtime.complete(doc.active!.run_id!, behaviorResponse);
    doc = await recovered.advance(doc.id, "actor");
    assert.equal(doc.phase, "building"); assert.equal(doc.active, null); assert.ok(doc.behavior);
    assert.deepEqual(doc.nodes.map(node => node.id), ["heading", "entry"]);
    for (let count = 0; count < 4; count += 1) doc = await recovered.advance(doc.id, "actor");
    assert.equal(doc.phase, "ready"); assert.deepEqual(doc.pendingNodes, []);
    assert.deepEqual(doc.nodes.map(node => node.id), ["heading", "entry", "find", "items", "operations", "totals"]);
    const records = new RecordStore(f.storage, `preview:${doc.id}`, doc.design!, doc.behavior!);
    assert.equal(records.save({ name: "马克杯", quantity: 4, price: 12.5 }).values.value, 50);
    assert.deepEqual(records.summary(), { count: 1, totals: { quantity: 4, price: 12.5, value: 50 } });
    assert.deepEqual(f.runtime.starts.map(start => [start.runtime, start.request.role_id]), [["prologue", "design"], ["prologue", "ui"], ["prologue", "behavior"]]);
    for (const start of f.runtime.starts) {
      assert.deepEqual(start.request.model_selection, { provider_id: "configured-provider", model_id: "configured-model" });
      assert.deepEqual(start.request.directory, { canonical_path: "/approved/project", realpath_verified: true });
      assert.equal(start.request.board_id, "test-board"); assert.equal(start.request.install_id, "test-install");
    }
    assert.deepEqual(JSON.parse(f.runtime.starts[2].request.task).design, selected);
    assert.equal((await recovered.state()).selectionAvailable, false);
  } finally { f.db.close(); }
});

test("manifest carries private storage, declared capabilities and three read-only roles with resolvable prompts", () => {
  const parsed = parsePluginManifest(builderManifest);
  assert.deepEqual(parsed.permissions.map(permission => permission.permission), ["storage:private"]);
  assert.deepEqual(parsed.agent!.roles.map(role => [role.role_id, role.execution]), [["design", "read-only"], ["ui", "read-only"], ["behavior", "read-only"]]);
  for (const role of parsed.agent!.roles) for (const id of role.prompts ?? []) assert.ok(builderPrompts.some(prompt => prompt.prompt_id === id && prompt.body.length > 0));
  assert.ok(parsed.capabilities.consumes.includes("agent.run.start.v1"));
  assert.ok(parsed.capabilities.consumes.includes("agent.run.control.v1"));
});

test("paused readRun completion cannot place UI; resume allows the original run to finish", async () => {
  const f = fixture();
  try {
    let doc = await uiRun(f); const run = doc.active!;
    const delayed = gate<AgentRunView>(); f.runtime.readGates.push(delayed);
    const advancing = f.workflow.advance(doc.id, "actor"); await delayed.entered.promise;
    doc = await f.workflow.pause(doc.id, doc.revision);
    delayed.result.resolve(f.runtime.view({ session_id: run.session_id!, run_id: run.run_id! }, "completed", uiResponse));
    await advancing;
    assert.equal(f.workflow.require(doc.id).phase, "paused");
    assert.deepEqual(f.workflow.require(doc.id).nodes, []); assert.deepEqual(f.workflow.require(doc.id).pendingNodes, []);
    assert.deepEqual(f.runtime.controls.map(control => control.control.kind), ["pause"]);
    assert.equal(f.runtime.starts.length, 2);
    doc = await f.workflow.resume(doc.id, f.workflow.require(doc.id).revision, config, "actor");
    f.runtime.complete(run.run_id!, uiResponse);
    doc = await f.workflow.advance(doc.id, "actor");
    assert.deepEqual(doc.nodes.map(node => node.id), ["heading"]);
    assert.deepEqual(f.runtime.controls.map(control => control.control.kind), ["pause", "resume"]);
  } finally { f.db.close(); }
});

test("stopped run cannot overwrite a newly resumed revision when its old read arrives late", async () => {
  const f = fixture();
  try {
    let doc = await uiRun(f); const old = doc.active!;
    const delayed = gate<AgentRunView>(); f.runtime.readGates.push(delayed);
    const advancing = f.workflow.advance(doc.id, "actor"); await delayed.entered.promise;
    doc = await f.workflow.stop(doc.id, doc.revision);
    doc = await f.workflow.resume(doc.id, doc.revision, config, "actor");
    const newer = structuredClone(doc);
    assert.notEqual(doc.active!.token, old.token);
    delayed.result.resolve(f.runtime.view({ session_id: old.session_id!, run_id: old.run_id! }, "completed", uiResponse));
    await advancing;
    assert.deepEqual(f.workflow.require(doc.id), newer, "late output must leave the entire newer persisted revision unchanged");
    assert.deepEqual(f.runtime.controls.map(control => [control.ref.run_id, control.control.kind]), [[old.run_id, "cancel"]]);
  } finally { f.db.close(); }
});

test("stop during a pending start cancels the late run handle and never reattaches it to the draft", async () => {
  const f = fixture();
  try {
    const doc = f.workflow.store.create("保留这条需求");
    const delayed = gate<void>(); f.runtime.startGates.push(delayed);
    const starting = f.workflow.start(doc.id, doc.revision, "design", config, "actor"); await delayed.entered.promise;
    const stopped = await f.workflow.stop(doc.id, f.workflow.require(doc.id).revision);
    delayed.result.resolve(); await starting;
    const recovered = new BuilderWorkflow(f.context, f.ports).require(doc.id);
    assert.equal(recovered.active, null); assert.equal(recovered.phase, "paused");
    assert.equal(recovered.brief, stopped.brief); assert.deepEqual(recovered.nodes, stopped.nodes); assert.deepEqual(recovered.messages, stopped.messages);
    assert.deepEqual(recovered.runs?.map(run => ({ session: run.session_id, run: run.run_id, phase: run.phase })), [{ session: "session-1", run: "run-1", phase: "cancel-requested" }]);
    assert.deepEqual(f.runtime.controls.map(control => [control.ref.run_id, control.control.kind]), [["run-1", "cancel"]]);
  } finally { f.db.close(); }
});

test("persisted pending UI resumes placement and starts behavior in a fresh Workflow using stored configuration", async () => {
  const f = fixture();
  try {
    let doc = f.workflow.store.create("重启后继续装配库存工具");
    // This is the durable boundary after valid UI output is saved, before the next runtime starts.
    doc = f.workflow.store.update(doc.id, doc.revision, draft => {
      draft.design = structuredClone(selected); draft.phase = "building"; draft.configuration = { ...config };
      draft.pendingNodes = JSON.parse(uiResponse); draft.active = null; draft.behavior = null;
    });
    const recovered = new BuilderWorkflow(f.context, f.ports);
    doc = await recovered.advance(doc.id, "restart-actor");
    assert.deepEqual(doc.nodes.map(node => node.id), ["heading"]);
    assert.deepEqual(doc.pendingNodes.map(node => node.id), ["entry", "find", "items", "operations", "totals"]);
    assert.equal(doc.active!.stage, "behavior"); assert.equal(doc.phase, "building");
    assert.deepEqual(f.runtime.starts.map(start => [start.runtime, start.request.role_id, start.request.model_selection]), [["prologue", "behavior", { provider_id: "configured-provider", model_id: "configured-model" }]]);
    assert.equal(f.runtime.starts[0].request.actor_id, "restart-actor");
    assert.equal(doc.runs!.at(-1)!.session_id, "session-1"); assert.equal(doc.runs!.at(-1)!.run_id, "run-1");
    f.runtime.complete(doc.active!.run_id!, behaviorResponse);
    while (doc.phase !== "ready") doc = await recovered.advance(doc.id, "restart-actor");
    assert.equal(doc.behavior!.calculations[0].id, "value");
    assert.equal(recovered.require(doc.id).runs!.at(-1)!.phase, "completed");
  } finally { f.db.close(); }
});

test("an interrupted active start is visibly failed after restart and keeps the draft for an explicit stop/retry", async () => {
  const f = fixture();
  try {
    let doc = f.workflow.store.create("运行开始时退出进程");
    doc = f.workflow.store.update(doc.id, doc.revision, draft => {
      draft.phase = "clarifying"; draft.configuration = { ...config };
      draft.active = { token: "interrupted-start", stage: "design", baseRevision: draft.revision, ...config };
      draft.runs = [{ token: "interrupted-start", stage: "design", phase: "starting", ...config }];
    });
    const recovered = new BuilderWorkflow(f.context, f.ports);
    doc = await recovered.advance(doc.id, "restart-actor");
    assert.equal(doc.phase, "failed"); assert.match(doc.error!, /启动被中断.*停止本轮/);
    assert.equal(doc.brief, "运行开始时退出进程"); assert.equal(doc.active!.token, "interrupted-start");
    assert.equal(f.runtime.starts.length, 0); assert.equal(f.runtime.calls.includes(agent.readRun.capability_id), false);
    doc = await recovered.stop(doc.id, doc.revision);
    doc = await recovered.resume(doc.id, doc.revision, config, "restart-actor");
    assert.equal(doc.active!.stage, "design"); assert.ok(doc.active!.run_id); assert.equal(doc.error, null);
  } finally { f.db.close(); }
});

test("pending UI without saved model configuration pauses visibly and can resume with an explicit selection", async () => {
  const f = fixture();
  try {
    let doc = f.workflow.store.create("旧草稿缺少模型选择");
    doc = f.workflow.store.update(doc.id, doc.revision, draft => { draft.design = structuredClone(selected); draft.phase = "building"; draft.pendingNodes = JSON.parse(uiResponse); });
    const recovered = new BuilderWorkflow(f.context, f.ports);
    doc = await recovered.advance(doc.id, "restart-actor");
    assert.equal(doc.phase, "paused"); assert.match(doc.error!, /选择工作区和模型/); assert.equal(f.runtime.starts.length, 0);
    const previousIds = doc.nodes.map(node => node.id);
    doc = await recovered.resume(doc.id, doc.revision, config, "restart-actor");
    doc = await recovered.advance(doc.id, "restart-actor");
    assert.equal(doc.active!.stage, "behavior"); assert.equal(doc.error, null);
    assert.deepEqual(doc.nodes.slice(0, previousIds.length).map(node => node.id), previousIds);
  } finally { f.db.close(); }
});

test("pause during a pending start forwards the pause to the late run handle", async () => {
  const f = fixture();
  try {
    const doc = f.workflow.store.create("暂停应当停止模型继续工作");
    const delayed = gate<void>(); f.runtime.startGates.push(delayed);
    const starting = f.workflow.start(doc.id, doc.revision, "design", config, "actor"); await delayed.entered.promise;
    await f.workflow.pause(doc.id, f.workflow.require(doc.id).revision);
    delayed.result.resolve(); await starting;
    const persisted = f.workflow.require(doc.id);
    assert.equal(persisted.phase, "paused"); assert.deepEqual(persisted.nodes, []);
    assert.deepEqual(f.runtime.controls.map(control => [control.ref.run_id, control.control.kind]), [["run-1", "pause"]], "a paused label alone must not leave the newly started model running");
  } finally { f.db.close(); }
});

test("invalid model JSON fails visibly while preserving the selected design and previously saved draft", async () => {
  const f = fixture();
  try {
    let doc = await uiRun(f);
    const before = structuredClone(doc);
    f.runtime.complete(doc.active!.run_id!, "<script>runAnything()</script>");
    doc = await f.workflow.advance(doc.id, "actor");
    assert.equal(doc.phase, "failed"); assert.match(doc.error!, /完整 JSON/); assert.equal(doc.active, null);
    assert.deepEqual(doc.design, before.design); assert.deepEqual(doc.messages, before.messages); assert.equal(doc.brief, before.brief);
    assert.deepEqual(doc.nodes, []); assert.deepEqual(doc.pendingNodes, []);
    assert.equal(f.runtime.starts.length, 2, "invalid UI must never start the behavior role");
    const snapshot = f.workflow.require(doc.id);
    await f.workflow.advance(doc.id, "actor"); assert.deepEqual(f.workflow.require(doc.id), snapshot);
  } finally { f.db.close(); }
});

test("two overlapping advances accept UI completion once and start exactly one behavior run", async () => {
  const f = fixture();
  try {
    const doc = await uiRun(f), run = doc.active!;
    const first = gate<AgentRunView>(), second = gate<AgentRunView>(); f.runtime.readGates.push(first, second);
    const advanceFirst = f.workflow.advance(doc.id, "actor"), advanceSecond = f.workflow.advance(doc.id, "actor");
    await Promise.all([first.entered.promise, second.entered.promise]);
    const completed = f.runtime.view({ session_id: run.session_id!, run_id: run.run_id! }, "completed", uiResponse);
    // Resolve the second HTTP request first, keeping behavior creation in flight.
    const behaviorStart = gate<void>(); f.runtime.startGates.push(behaviorStart);
    second.result.resolve(completed); await behaviorStart.entered.promise;
    first.result.resolve(completed); await advanceFirst;
    assert.equal(f.runtime.starts.filter(start => start.request.role_id === "behavior").length, 1);
    behaviorStart.result.resolve(); await advanceSecond;
    const saved = f.workflow.require(doc.id);
    assert.deepEqual(saved.nodes.map(node => node.id), ["heading"]);
    assert.deepEqual(saved.pendingNodes.map(node => node.id), ["entry", "find", "items", "operations", "totals"]);
    assert.equal(saved.messages.filter(message => message.text.startsWith("UI 方案已校验")).length, 1);
    assert.equal(saved.phase, "building"); assert.equal(saved.active!.stage, "behavior");
  } finally { f.db.close(); }
});

test("missing authorized workspace or configured model fails before creating a Runtime session", async () => {
  const f = fixture();
  try {
    const doc = f.workflow.store.create("需求不能丢失");
    f.runtime.workspaces[0].realpath_verified = false;
    await assert.rejects(f.workflow.start(doc.id, doc.revision, "design", config, "actor"), /已授权的工作区/);
    assert.deepEqual(f.workflow.require(doc.id), doc);
    f.runtime.workspaces[0].realpath_verified = true; f.clearModels();
    await assert.rejects(f.workflow.start(doc.id, doc.revision, "design", config, "actor"), /模型尚未配置/);
    assert.deepEqual(f.workflow.require(doc.id), doc);
    assert.equal(f.runtime.calls.filter(id => id === agent.createSession.capability_id).length, 0);
    assert.equal(f.runtime.starts.length, 0);
  } finally { f.db.close(); }
});

test('local component label and order edits remain revisioned and undo restores the complete snapshot',async()=>{
 const f=fixture();
 try{
  let doc=f.workflow.store.create('可调整零件');
  doc=f.workflow.store.update(doc.id,doc.revision,d=>{d.design=structuredClone(selected);d.nodes=JSON.parse(uiResponse);d.behavior=JSON.parse(behaviorResponse);d.phase='ready';});
  const before=structuredClone(doc.nodes);
  const binding=builderRoutes(f.context,f.workflow).find(route=>route.route_id==='builder.action')!;
  const result=await binding.handle({...routeRequest(doc.id),method:'POST',body:{action:'node',revision:doc.revision,nodeId:'find',label:'查找库存',direction:1}});
  assert.equal(result.status,200);doc=f.workflow.require(doc.id);
  assert.deepEqual(doc.nodes.map(node=>node.id),['heading','entry','items','find','operations','totals']);
  assert.equal(doc.nodes[3]!.label,'查找库存');assert.deepEqual(doc.behavior,JSON.parse(behaviorResponse));
  assert.deepEqual(f.workflow.store.undo(doc.id,doc.revision).nodes,before);
 }finally{f.db.close();}
});
