import assert from "node:assert/strict";
import test from "node:test";
import { openMolisWorkProjectCatalog } from "@molis-ai/molis-work-app-desktop";
import { createLocalFeedApplication, DEMO_BOARD_ID } from "@molis-ai/molis-work-app-local-host";
import { openGoalBrowser } from "./fixtures/goal-browser.js";

test("Goal Frame keeps the outer tabs and layout offers explicit bottom splitting", { timeout: 60_000 }, async t => {
  const b = await openGoalBrowser(t, true); if (!b) return;
  const { evaluate, waitFor, click, openGoalFrame, command, sessionId, navigate, origin, projectId } = b;
  await command("Emulation.setDeviceMetricsOverride", { width: 1440, height: 960, deviceScaleFactor: 1, mobile: false }, sessionId);
  await navigate(() => command("Page.navigate", {url: `${origin}/projects/${projectId}/`}, sessionId));
  await waitFor("document.querySelector('[data-titlebar-tabs] .tab-item')");
  await click('[data-plugin-id="goals"]');
  await openGoalFrame('.tree-node[data-select-goal="CORE"]');
  await waitFor("document.querySelector('[data-goal-frame-surface]')?.dataset.frameGoal==='CORE' && !document.querySelector('[data-goal-frame-surface]').hidden");
  assert.equal(await evaluate("document.querySelector('[data-titlebar-tabs]').getBoundingClientRect().height>0"), true);
  const core = b.store.snapshot(DEMO_BOARD_ID).goals.find(goal => goal.goal_id === "CORE")!;
  assert.equal(await evaluate<string>("document.querySelector('[data-frame-goal-title]').textContent"), core.title);
  assert.equal(await evaluate<string>("document.querySelector('[data-frame-goal-outcome]').textContent"), core.outcome);
  assert.equal(await evaluate<string>("document.querySelector('[data-frame-goal-status]').textContent"), "已完成");
  await click('[data-titlebar-tabs] [data-tab-split]');
  assert.deepEqual(await evaluate("[...document.querySelectorAll('[data-layout-split]')].map(x=>x.dataset.layoutSplit)"), ["right","bottom","left","top"]);
  await click('[data-layout-split="bottom"]');
  await waitFor("document.querySelectorAll('[data-tab-pane]').length===2 && document.querySelector('[data-direction=column]')");
  await waitFor("[...document.querySelectorAll('iframe.tab-content-frame:not([hidden])')].every(f=>f.contentDocument?.querySelector('[data-goal-frame-surface]')?.dataset.frameGoal==='CORE')");
  await evaluate("document.querySelector('iframe.tab-content-frame:not([hidden])').contentDocument.querySelector('[data-frame-goal-work]').click()");
  await waitFor("[...document.querySelectorAll('iframe.tab-content-frame:not([hidden])')].some(f=>f.contentDocument?.querySelector('[data-goal-view]')?.dataset.goalView==='CORE')");
});

test("Feed task creation is a scoped dialog with validation and persistent schedule", { timeout: 60_000 }, async t => {
  const b = await openGoalBrowser(t, true); if (!b) return;
  const { evaluate, waitFor, click, command, sessionId, navigate, origin, projectId, homeDirectory } = b;
  const catalog = await openMolisWorkProjectCatalog({homeDirectory});
  catalog.addProjectPlugin({ project_id: projectId!, plugin_id: "feed", actor_id: "interaction-test" }); catalog.close();
  await command("Emulation.setDeviceMetricsOverride", { width: 1440, height: 960, deviceScaleFactor: 1, mobile: false }, sessionId);
  await navigate(() => command("Page.navigate", {url: `${origin}/projects/${projectId}/`}, sessionId));
  await waitFor("document.querySelector('[data-titlebar-tabs] .tab-item')");
  await click('[data-plugin-id="feed"]');
  assert.equal(await evaluate("document.querySelector('[data-feed-advanced-open]')"), null);
  await click('[data-feed-add-toggle]');
  await waitFor("document.querySelector('[data-feed-sources-dialog]').open");
  assert.equal(await evaluate("document.querySelector('[data-feed-add]')"), null);
  await click('[data-feed-choose-kind="custom_rss"]');
  assert.equal(await evaluate("document.querySelector('[data-feed-source-register]').parentElement === document.querySelector('[data-feed-sources-dialog] footer [data-feed-sources-close]').parentElement"), true);
  await click('[data-feed-source-register]');
  assert.equal(await evaluate("document.querySelector('[data-feed-source-value=custom_rss]').validity.valueMissing"), true);
  await evaluate(`{
    document.querySelector('[data-feed-add-name]').value='设计观察';
    document.querySelector('[data-feed-source-value=custom_rss]').value='https://example.com/design.xml';
    document.querySelector('[data-feed-create-frequency]').value='360';
    document.querySelector('[data-feed-add-out-rule-name]').value='发布相关';
    document.querySelector('[data-feed-add-out-rule-contains]').value='launch';
  }`);
  await navigate(() => click('[data-feed-source-register]'));
  await waitFor("[...document.querySelectorAll('[data-feed-task]')].some(x=>x.textContent.includes('设计观察'))");
  const sourceId = await evaluate<string>("[...document.querySelectorAll('[data-feed-task]')].find(x=>x.textContent.includes('设计观察')).dataset.feedTask");
  await click(`[data-feed-task-config-open="${sourceId}"]`);
  assert.equal(await evaluate("document.querySelector('[data-feed-sources-dialog]').open"), true);
  assert.equal(await evaluate(`document.querySelector('[data-feed-task-config="${sourceId}"] [data-source-schedule-interval]').value`), "360");
  assert.equal(await evaluate(`document.querySelector('[data-feed-task-config="${sourceId}"] [data-source-schedule-enabled]').checked`), true);
  const saved = createLocalFeedApplication(b.store.db).getSource(DEMO_BOARD_ID, sourceId);
  assert.equal(saved.name, "设计观察");
  assert.equal(saved.schedule.mode, "interval");
  if (saved.schedule.mode === "interval") {
    assert.equal(saved.schedule.enabled, true); assert.equal(saved.schedule.interval_minutes, 360);
    assert.ok(Date.parse(saved.schedule.next_pull_at!) > Date.now());
  }
  const rules = createLocalFeedApplication(b.store.db).listOutRules(DEMO_BOARD_ID)
    .filter((rule) => rule.match.source_id === sourceId);
  assert.equal(rules.length, 1);
  assert.equal(rules[0]?.name, "发布相关");
  assert.equal(rules[0]?.match.contains, "launch");
  assert.equal(rules[0]?.match.source_id, sourceId);
  assert.match(await evaluate(`document.querySelector('[data-feed-out-rules="${sourceId}"]')?.textContent || ""`), /发布相关/);
});

test("Feed creation recovers a failed schedule without duplicating the task", { timeout: 60_000 }, async t => {
  const b = await openGoalBrowser(t, true); if (!b) return;
  const { evaluate, waitFor, click, command, sessionId, navigate, origin, projectId, homeDirectory } = b;
  const catalog = await openMolisWorkProjectCatalog({homeDirectory});
  catalog.addProjectPlugin({ project_id: projectId!, plugin_id: "feed", actor_id: "interaction-test" }); catalog.close();
  await navigate(() => command("Page.navigate", {url: `${origin}/projects/${projectId}/`}, sessionId));
  await waitFor("document.querySelector('[data-titlebar-tabs] .tab-item')");
  await click('[data-plugin-id="feed"]');
  await click('[data-feed-add-toggle]');
  await click('[data-feed-choose-kind="custom_rss"]');
  await evaluate(`{
    document.querySelector('[data-feed-add-name]').value='失败后重试';
    document.querySelector('[data-feed-source-value=custom_rss]').value='https://example.com/retry.xml';
    document.querySelector('[data-feed-create-frequency]').value='60';
    const original = window.fetch;
    let fail = true; window.sourceCreationRequests = 0;
    window.fetch = (url, options) => {
      if (options?.method === 'POST' && String(url).endsWith('/api/feed/sources')) window.sourceCreationRequests++;
      if (fail && options?.method === 'PUT' && String(url).endsWith('/schedule')) { fail = false; return Promise.resolve(new Response(JSON.stringify({error:'计划暂时无法保存'}), {status:503,headers:{'content-type':'application/json'}})); }
      return original(url, options);
    };
  }`);
  await click('[data-feed-source-register]');
  await waitFor("document.querySelector('[data-feed-add-form]').dataset.createdSourceId && document.querySelector('[data-feed-add-error]').textContent.includes('任务已创建')");
  const sourceId = await evaluate<string>("document.querySelector('[data-feed-add-form]').dataset.createdSourceId");
  assert.equal(createLocalFeedApplication(b.store.db).getSource(DEMO_BOARD_ID, sourceId).schedule.mode, "manual");
  await click('[data-feed-sources-dialog] header [data-feed-sources-close]');
  await click('[data-feed-add-toggle]');
  assert.equal(await evaluate("document.querySelector('[data-feed-source-value=custom_rss]').value"), "https://example.com/retry.xml");
  assert.equal(await evaluate("document.querySelector('[data-feed-setup-back]').hidden"), true);
  await evaluate("window.addEventListener('beforeunload',()=>sessionStorage.setItem('creationRequests',String(window.sourceCreationRequests)))");
  await navigate(() => click('[data-feed-source-register]'));
  await waitFor(`document.querySelector('[data-feed-task="${sourceId}"] summary[aria-current=page]')`);
  assert.equal(await evaluate("sessionStorage.getItem('creationRequests')"), "1");
  const saved = createLocalFeedApplication(b.store.db).getSource(DEMO_BOARD_ID, sourceId);
  assert.equal(saved.schedule.mode, "interval");
  if (saved.schedule.mode === "interval") assert.equal(saved.schedule.interval_minutes, 60);
});

test("Feed configuration cancels drafts and saves its schedule independently", { timeout: 60_000 }, async t => {
  const b = await openGoalBrowser(t, true); if (!b) return;
  const { evaluate, waitFor, click, command, sessionId, navigate, origin, projectId, homeDirectory } = b;
  const { createLocalFeedSourceService } = await import("@molis-ai/molis-work-app-local-host");
  const source = createLocalFeedSourceService(b.store.db, DEMO_BOARD_ID).register({kind:"web_query",query:"设计资料"}).source;
  const feed = createLocalFeedApplication(b.store.db);
  const catalog = await openMolisWorkProjectCatalog({homeDirectory});
  catalog.addProjectPlugin({project_id:projectId!,plugin_id:"feed",actor_id:"test"}); catalog.close();
  await navigate(() => command("Page.navigate", {url:`${origin}/projects/${projectId}/`},sessionId));
  await waitFor("document.querySelector('[data-titlebar-tabs] .tab-item')");
  await click('[data-plugin-id="feed"]');
  const panel = `[data-feed-task-config="${source.source_id}"]`;
  await click(`[data-feed-task-config-open="${source.source_id}"]`);
  await evaluate(`document.querySelector('${panel} [data-source-config-field=name]').value='丢弃的名称'`);
  await click('[data-feed-sources-dialog] footer [data-feed-sources-close]');
  assert.equal(feed.getSource(DEMO_BOARD_ID,source.source_id).name, source.name);
  await click(`[data-feed-task-config-open="${source.source_id}"]`);
  assert.equal(await evaluate(`document.querySelector('${panel} [data-source-config-field=name]').value`),source.name);
  await click(`${panel} [data-feed-plan-region] > summary`);
  await evaluate(`{const field=document.querySelector('${panel} [data-source-schedule-mode]');field.value='interval';field.dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('${panel} [data-source-schedule-interval]').value='360';}`);
  await click(`${panel} [data-source-schedule-reset]`);
  assert.equal(await evaluate(`document.querySelector('${panel} [data-source-schedule-mode]').value`),"manual");
  await evaluate(`{document.querySelector('${panel} [data-source-config-field=name]').value='保留中的名称';const field=document.querySelector('${panel} [data-source-schedule-mode]');field.value='interval';field.dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('${panel} [data-source-schedule-interval]').value='360';}`);
  await click(`${panel} [data-source-schedule-save]`);
  await waitFor(`!document.querySelector('${panel} [data-source-schedule-save]').disabled`);
  assert.equal(feed.getSource(DEMO_BOARD_ID,source.source_id).schedule.mode,"interval");
  assert.equal(feed.getSource(DEMO_BOARD_ID,source.source_id).name,source.name);
  assert.equal(await evaluate(`document.querySelector('${panel} [data-source-config-field=name]').value`),"保留中的名称");
  await click(`${panel} [data-source-schedule-enabled]`);
  await click(`${panel} [data-source-schedule-save]`);
  await waitFor(`!document.querySelector('${panel} [data-source-schedule-save]').disabled`);
  await click(`${panel} [data-source-schedule-enabled]`);
  await click(`${panel} [data-source-schedule-reset]`);
  assert.equal(await evaluate(`document.querySelector('${panel} [data-source-schedule-enabled]').checked`),false,"reset must preserve a saved paused schedule");
  await evaluate(`{const original=window.fetch; window.fetch=(url,options)=>options?.method==='PATCH'?Promise.resolve(new Response(JSON.stringify({error:'无法保存配置'}),{status:503})):original(url,options);window.restoreConfigFetch=()=>window.fetch=original;}`);
  await click('[data-feed-config-submit]');
  await waitFor(`document.querySelector('${panel} [data-source-action-status]').textContent.includes('无法保存配置')`);
  assert.equal(await evaluate(`document.querySelector('${panel} [data-source-config-field=name]').value`),"保留中的名称");
  await evaluate('window.restoreConfigFetch()');
  await navigate(()=>click('[data-feed-config-submit]'));
  assert.equal(feed.getSource(DEMO_BOARD_ID,source.source_id).name,"保留中的名称");
  const plan=feed.getSource(DEMO_BOARD_ID,source.source_id).schedule;
  assert.equal(plan.mode,"interval"); if(plan.mode==='interval') assert.equal(plan.interval_minutes,360);
});

test("Feed reader keeps one title, tracks read state, collapses and retries a failed detail", {timeout:60_000}, async t=>{
  const b=await openGoalBrowser(t,true);if(!b)return;
  const {evaluate,waitFor,click,command,sessionId,navigate,origin,projectId,homeDirectory}=b;
  const {createLocalFeedSourceService}=await import("@molis-ai/molis-work-app-local-host");
  const source=createLocalFeedSourceService(b.store.db,DEMO_BOARD_ID).register({kind:'web_query',query:'阅读测试'}).source;
  const feed=createLocalFeedApplication(b.store.db);
  const item=feed.ingestItem({source,externalId:'reader-test',title:'一次清楚的阅读',summary:'列表摘要',body:'## 核心内容\n\n阅读正文与完整来源。\n\n'+Array.from({length:30},(_,i)=>`### 检查项 ${i+1}\n\n保持标题和操作在视野内，让阅读区独立滚动。`).join('\n\n'),priority:'normal',occurredAt:'2026-09-16T00:00:00.000Z',attention:false}).item;
  const catalog=await openMolisWorkProjectCatalog({homeDirectory});catalog.addProjectPlugin({project_id:projectId!,plugin_id:'feed',actor_id:'test'});catalog.close();
  await navigate(()=>command('Page.navigate',{url:`${origin}/projects/${projectId}/`},sessionId));
  await waitFor("document.querySelector('[data-titlebar-tabs] .tab-item')");await click('[data-plugin-id=feed]');
  const row=`[data-feed-entry-id="${item.item_id}"]`;
  await waitFor(`Boolean(document.querySelector('${row}'))`);
  await evaluate(`{const original=window.fetch;let fail=true;window.fetch=(url,options)=>{if(fail&&String(url).includes('/detail?')){fail=false;return Promise.resolve(new Response('failed',{status:503}));}return original(url,options);};}`);
  await click(row);await waitFor("document.querySelector('[data-feed-stage-shell][data-expanded=true] [data-retry-feed-detail]')");
  await click('[data-feed-stage-workspace] [data-retry-feed-detail]');
  await waitFor(`document.querySelector('[data-feed-detail="${item.item_id}"] .feed-rich-content')`);
  assert.ok(feed.getFeedItem(DEMO_BOARD_ID,item.item_id).read_at);
  assert.equal(await evaluate(`document.querySelector('${row}').getAttribute('aria-expanded')`),'true');
  assert.notEqual(await evaluate(`getComputedStyle(document.querySelector('[data-feed-detail="${item.item_id}"] h1')).display`),'none');
  assert.match(await evaluate<string>(`document.querySelector('[data-feed-detail="${item.item_id}"] .feed-rich-content').textContent`),/阅读正文/);
  const headerTop=await evaluate<number>("document.querySelector('.feed-stage-toolbar').getBoundingClientRect().top");
  const bodyPoint=await evaluate<{x:number;y:number}>("(()=>{const r=document.querySelector('[data-feed-stage-workspace]').getBoundingClientRect();return {x:r.x+30,y:r.y+40}})()");
  await command('Input.dispatchMouseEvent',{type:'mouseWheel',...bodyPoint,deltaX:0,deltaY:300},sessionId);
  await waitFor("document.querySelector('[data-feed-stage-workspace]').scrollTop>100");
  assert.equal(await evaluate("document.querySelector('.feed-stage-toolbar').getBoundingClientRect().top"),headerTop,'reader scroll never moves the toolbar');
  assert.equal(await evaluate("document.scrollingElement.scrollTop"),0);
  await click(`[data-feed-entry-detail="${item.item_id}"]:not([hidden]) [data-feed-collapse]`);
  await waitFor("document.querySelector('[data-feed-stage-shell]')?.dataset.expanded !== 'true'");
  assert.equal(await evaluate(`document.querySelector('${row}').getAttribute('aria-expanded')`),'false');
  await click(row);assert.equal(await evaluate(`document.querySelector('[data-feed-detail="${item.item_id}"]').hidden`),false);
  await evaluate(`{const field=document.querySelector('[data-feed-search]');field.value='不存在的标题';field.dispatchEvent(new Event('input',{bubbles:true}));}`);
  assert.equal(await evaluate(`document.querySelector('${row}').closest('[data-feed-item-wrap]').hidden`),true);
  await evaluate("document.querySelector('[data-feed-clear-filters]').click()");
  assert.equal(await evaluate(`document.querySelector('${row}').closest('[data-feed-item-wrap]').hidden`),false);
});
