import { DEMO_BOARD_ID } from "@molis-ai/molis-work-app-local-host";
import assert from "node:assert/strict";
import test from "node:test";
import { openGoalBrowser } from "./fixtures/goal-browser.js";

test("settings serve complete category pages and restore workspace tabs and splits after navigation", { timeout: 60_000 }, async t => {
  const browser = await openGoalBrowser(t, true);
  if (!browser) return;
  const { origin, projectId, command, sessionId, evaluate, navigate, click, waitFor, reloadPage } = browser;
  const prefix = `/projects/${projectId}`;
  for (const [path, content] of [["", "data-project-rename"], ["/general", "data-project-rename"], ["/guidance", "data-guidance-form"], ["/rules", "data-policy-form"], ["/planning", "data-planning-search"]]) {
    const response = await fetch(origin + prefix + "/settings" + path);
    assert.equal(response.status, 200);
    const html = await response.text();
    assert.match(html, /<body class="settings-page project-preferences-page"/);
    assert.ok(html.includes(content));
    assert.doesNotMatch(html, /data-tab-workspace|data-plugin-strip|data-project-settings-page-root/);
  }
  const embed = await (await fetch(origin + prefix + "/settings/rules?embed=1")).text();
  assert.match(embed, /data-policy-form/);
  assert.doesNotMatch(embed, /<body/);
  await command("Emulation.setDeviceMetricsOverride", { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false }, sessionId);
  await navigate(() => command("Page.navigate", { url: origin + prefix + "/" }, sessionId));
  await click('[data-plugin-strip] [data-plugin-id="goals"]');
  await click('.tree-node[data-select-goal="CORE"]');
  await waitFor("document.querySelector('[data-goal-frame-surface]')?.dataset.frameGoal === 'CORE'");
  await evaluate("document.querySelector('[data-tab-edge=right]').click()");
  await waitFor("document.querySelectorAll('[data-tab-pane]').length === 2");
  const storageKey = "molis-work-tab-workspace:" + projectId;
  const readState = `JSON.parse(localStorage.getItem(${JSON.stringify(storageKey)}))`;
  const before = await evaluate(readState);
  // A normal category page must remain usable even if every old embed request is blocked.
  await command("Network.enable", {}, sessionId);
  await command("Network.setBlockedURLs", { urls: ["*embed=1*"] }, sessionId);
  await navigate(() => click(".navigator-project-settings"));
  await waitFor("!!document.querySelector('[data-project-rename]')");
  for (const category of ["guidance", "rules", "planning"]) {
    await navigate(() => click(`.settings-nav-body a[href$="/${category}"]`));
    assert.equal(await evaluate("document.body.dataset.settingsSection"), category);
    assert.equal(await evaluate("document.querySelectorAll('[data-tab-workspace], [data-plugin-strip]').length"), 0);
    await reloadPage();
    assert.equal(await evaluate("document.body.dataset.settingsSection"), category);
  }
  await navigate(() => evaluate("history.back()"));
  assert.equal(await evaluate("document.body.dataset.settingsSection"), "rules");
  await navigate(() => evaluate("history.forward()"));
  assert.equal(await evaluate("document.body.dataset.settingsSection"), "planning");
  await navigate(() => click(".settings-nav-back"));
  await waitFor("document.querySelectorAll('[data-tab-pane]').length === 2");
  assert.deepEqual(await evaluate(readState), before);
  // Old builds persisted settings as an exclusive workspace surface. The new build clears only that flag.
  await evaluate(`(() => { const state=${readState}; state.exclusive='project-settings'; localStorage.setItem(${JSON.stringify(storageKey)},JSON.stringify(state)); })()`);
  await reloadPage();
  await waitFor("document.querySelectorAll('[data-tab-pane]').length === 2 && !document.querySelector('[data-tab-workspace]').dataset.exclusive");
  assert.deepEqual(await evaluate(readState), before);
});

test("project settings preserve edits on failed saves, record guidance versions, and combine planning search with filters", { timeout: 60_000 }, async t => {
  const browser = await openGoalBrowser(t, true);
  if (!browser) return;
  const { origin, projectId, command, sessionId, evaluate, navigate, click, waitFor, reloadPage } = browser;
  const prefix = `/projects/${projectId}`;
  const readGuidance = async () => (await (await fetch(origin + prefix + "/api/project-guidance")).json());
  const fill = async (selector: string, value: string) => evaluate(`(() => { const field=document.querySelector(${JSON.stringify(selector)}); field.value=${JSON.stringify(value)}; field.dispatchEvent(new Event('input',{bubbles:true})); })()`);
  await command("Network.enable", {}, sessionId);
  await navigate(() => command("Page.navigate", { url: origin + prefix + "/settings/guidance" }, sessionId));
  await click('[data-guidance-kind="constraint"]');
  assert.equal(await evaluate("document.querySelector('[name=kind]').value"), "constraint");
  await fill('[name=content]', "用户数据只保存在本机。");
  await fill('[name=reason]', "明确项目的数据边界。");
  await command("Network.setBlockedURLs", { urls: [origin + prefix + "/api/project-guidance"] }, sessionId);
  await click('[data-guidance-form] button[type=submit]');
  await waitFor("!document.querySelector('[data-guidance-editor-error]').hidden");
  assert.equal(await evaluate("document.querySelector('[name=content]').value"), "用户数据只保存在本机。");
  assert.equal((await readGuidance()).entries.length, 0);
  await command("Network.setBlockedURLs", { urls: [] }, sessionId);
  await navigate(() => click('[data-guidance-form] button[type=submit]'));
  const first = await readGuidance();
  assert.equal(first.entries[0].kind, "constraint");
  assert.equal(first.entries[0].content, "用户数据只保存在本机。");
  await click("[data-guidance-edit]");
  await fill('[name=content]', "用户数据和备份只保存在本机。");
  await fill('[name=reason]', "将备份也纳入边界。");
  await navigate(() => click('[data-guidance-form] button[type=submit]'));
  const edited = await readGuidance();
  assert.equal(edited.entries[0].revision, 2);
  assert.equal(edited.entries[0].content, "用户数据和备份只保存在本机。");
  assert.equal(edited.revisions.length, 2);
  await reloadPage();
  assert.match(await evaluate<string>("document.querySelector('.guidance-entry').textContent"), /用户数据和备份只保存在本机/);
  await navigate(() => click('.settings-nav-body a[href$="/rules"]'));
  const beforeRules = browser.store.snapshot(DEMO_BOARD_ID).cursor;
  await fill('[name=reason]', "不应保存的草稿");
  await fill('[name=goal_mode]', "required");
  await click('[data-policy-cancel]');
  assert.equal(await evaluate("document.querySelector('[name=reason]').value"), "");
  assert.equal(browser.store.snapshot(DEMO_BOARD_ID).cursor, beforeRules);
  await click('[data-policy-form] button[type=submit]');
  assert.equal(await evaluate("document.activeElement.name"), "reason");
  await fill('[name=reason]', "验证项目统一工作标准。");
  await evaluate("document.querySelector('[name=goal_mode]').value='required'");
  await command("Network.setBlockedURLs", { urls: [origin + prefix + "/api/policy-bindings"] }, sessionId);
  await click('[data-policy-form] button[type=submit]');
  await waitFor("!document.querySelector('[data-policy-error]').hidden && !document.querySelector('[data-policy-form] button[type=submit]').disabled");
  assert.equal(await evaluate("document.querySelector('[name=reason]').value"), "验证项目统一工作标准。");
  await command("Network.setBlockedURLs", { urls: [] }, sessionId);
  await navigate(() => click('[data-policy-form] button[type=submit]'));
  assert.equal(await evaluate("document.querySelector('[name=goal_mode]').value"), "required");
  assert.equal(await evaluate("document.querySelector('[data-project-rules-receipt]').hidden"), false);
  await reloadPage();
  assert.equal(await evaluate("document.querySelector('[name=goal_mode]').value"), "required");
  assert.match(await evaluate<string>("document.querySelector('.settings-last-change').textContent"), /验证项目统一工作标准/);
  await navigate(() => click('.settings-nav-body a[href$="/planning"]'));
  await fill('[data-planning-search]', "软件");
  assert.ok(await evaluate<number>("document.querySelectorAll('[data-planning-method]:not([hidden])').length") > 0);
  await click('[data-planning-filter="work_type"]');
  assert.equal(await evaluate("document.querySelector('[data-planning-filter-empty]').hidden"), false);
  await click('[data-planning-filter="domain"]');
  assert.equal(await evaluate("document.querySelector('[data-planning-filter-empty]').hidden"), true);
  await fill('[data-planning-search]', "没有这个方法xyz");
  assert.equal(await evaluate("document.querySelectorAll('[data-planning-method]:not([hidden])').length"), 0);
  await fill('[data-planning-search]', "");
  assert.equal(await evaluate("Array.from(document.querySelectorAll('[data-planning-method]:not([hidden])')).every(x=>x.dataset.kind==='domain')"), true);
});
