import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdir, writeFile } from 'node:fs/promises';
import { openGoalBrowser } from './fixtures/goal-browser.js';
import { DEMO_BOARD_ID } from '@molis-ai/molis-work-app-local-host';

for (const [width, height] of [[1024, 400], [390, 500]]) {
  test(`Settings ${width}×${height}: fixed actions, cancel, failed retry and pending save`, { timeout: 60000 }, async t => {
    const b = await openGoalBrowser(t, true); if (!b) return;
    const { command, sessionId, navigate, origin, projectId, click, evaluate, waitFor } = b;
    const prefix = `${origin}/projects/${projectId}`;
    await command('Emulation.setDeviceMetricsOverride', { width, height, deviceScaleFactor: 1, mobile: false }, sessionId);
    await command('Network.enable', {}, sessionId);
    const fill = (selector: string, value: string) => evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));})()`);
    const rect = (selector: string) => evaluate<{ top: number; bottom: number }>(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return {top:r.top,bottom:r.bottom}})()`);
    const contained = async (selector: string) => {
      const r = await rect(selector);
      assert.ok(r.top >= -1 && r.bottom <= height + 1, `${selector}: ${JSON.stringify(r)}`);
      return r;
    };
    const capture = async (name: string) => {
      await evaluate('Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{})))');
      const dir = process.env.MOLIS_CONTENT_CAPTURE || '.impeccable/review/settings-viewport-v9';
      await mkdir(dir, { recursive: true });
      const png = await command<{ data: string }>('Page.captureScreenshot', { format: 'png' }, sessionId);
      await writeFile(`${dir}/${name}-${width}.png`, Buffer.from(png.data, 'base64'));
    };
    const scrollFields = async (body: string, header: string, footer: string) => {
      await evaluate("Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{})))");
      const before = [await contained(header), await contained(footer)];
      const field = await evaluate<{ x: number; y: number; ch: number; sh: number }>(`(()=>{const e=document.querySelector('${body}'),r=e.getBoundingClientRect();return {x:r.x+12,y:r.y+12,ch:e.clientHeight,sh:e.scrollHeight}})()`);
      assert.ok(field.ch >= 80 && field.sh > field.ch, 'real fields have a usable internal scroll region');
      await command('Input.dispatchMouseEvent', { type: 'mouseWheel', x: field.x, y: field.y, deltaX: 0, deltaY: 1500 }, sessionId);
      await waitFor(`document.querySelector('${body}').scrollTop > 0`);
      assert.deepEqual([await contained(header), await contained(footer)], before);
      assert.equal(await evaluate('document.scrollingElement.scrollHeight<=innerHeight+1 && document.scrollingElement.scrollTop===0'), true);
    };
    await navigate(() => command('Page.navigate', { url: prefix + '/settings/rules' }, sessionId));
    await click('[data-rules-advanced] > summary');
    const cursor = b.store.snapshot(DEMO_BOARD_ID).cursor;
    await fill('[name=reason]', '不应持久化的规则草稿');
    await fill('[name=cross_reviewers]', '3');
    await click('[data-policy-cancel]');
    assert.equal(await evaluate("document.querySelector('[name=reason]').value"), '');
    assert.equal(b.store.snapshot(DEMO_BOARD_ID).cursor, cursor);
    await click('[data-policy-form] button[type=submit]');
    assert.equal(await evaluate('document.activeElement.name'), 'reason');
    await contained('[name=reason]');
    await capture('rules-validation');
    await fill('[name=reason]', '验证低窗口里的规则保存。');
    await fill('[name=cross_reviewers]', '3');
    await command('Network.setBlockedURLs', { urls: [prefix + '/api/policy-bindings'] }, sessionId);
    await click('[data-policy-form] button[type=submit]');
    await waitFor("!document.querySelector('[data-policy-error]').hidden");
    await contained('[data-policy-error]');
    assert.match(await evaluate<string>("document.querySelector('[data-policy-error]').textContent"), /输入已保留/);
    await evaluate("document.querySelector('.settings-save-footer').scrollIntoView({block:'nearest'})");
    await contained('.settings-save-footer');
    assert.equal(await evaluate("document.querySelector('[name=reason]').value"), '验证低窗口里的规则保存。');
    await command('Network.setBlockedURLs', { urls: [] }, sessionId);
    await command('Network.emulateNetworkConditions', { offline: false, latency: 800, downloadThroughput: -1, uploadThroughput: -1 }, sessionId);
    await navigate(async () => {
      await click('[data-policy-form] button[type=submit]');
      assert.equal(await evaluate("document.querySelector('[data-policy-cancel]').disabled && document.querySelector('[name=reason]').disabled"), true);
    });
    await command('Network.emulateNetworkConditions', { offline: false, latency: 0, downloadThroughput: -1, uploadThroughput: -1 }, sessionId);
    assert.equal(await evaluate("document.querySelector('[name=cross_reviewers]').value"), '3');
    assert.ok(b.store.snapshot(DEMO_BOARD_ID).cursor > cursor);
    await b.reloadPage();
    assert.equal(await evaluate("document.querySelector('[name=cross_reviewers]').value"), '3');

    await navigate(() => command('Page.navigate', { url: prefix + '/settings/guidance' }, sessionId));
    const trigger = '[data-guidance-kind="constraint"]';
    await click(trigger);
    await waitFor("document.activeElement.name === 'content'");
    await scrollFields('.guidance-editor-body', '.guidance-editor > header', '.guidance-editor footer');
    await fill('[name=content]', '不应保存的说明草稿');
    await click('[data-guidance-editor-close]');
    assert.equal(await evaluate(`document.activeElement.matches('${trigger}')`), true);
    const guidance = async () => (await (await fetch(prefix + '/api/project-guidance')).json());
    assert.equal((await guidance()).entries.length, 0);
    await click(trigger);
    await waitFor("document.activeElement.name === 'content'");
    assert.equal(await evaluate("document.querySelector('[name=content]').value"), '');
    const content = '用户数据和备份只保存在本机。\n' + '保留原始文件，所有导出均由用户主动发起。\n'.repeat(12);
    await fill('[name=content]', content);
    await fill('[name=reason]', '明确项目的数据边界，并验证失败时草稿完整保留。');
    await command('Network.setBlockedURLs', { urls: [prefix + '/api/project-guidance'] }, sessionId);
    await click('[data-guidance-form] button[type=submit]');
    await waitFor("!document.querySelector('[data-guidance-editor-error]').hidden");
    assert.equal(await evaluate("document.querySelector('[name=content]').value"), content);
    assert.equal(await evaluate("document.querySelector('[data-guidance-editor-close]').disabled"), false);
    await contained('[data-guidance-editor-error]');
    assert.match(await evaluate<string>("document.querySelector('[data-guidance-editor-error]').textContent"), /输入已保留/);
    await contained('.guidance-editor footer');
    await capture('guidance-error');
    await evaluate("localStorage.setItem('molis-work:theme','dark');dispatchEvent(new StorageEvent('storage',{key:'molis-work:theme',newValue:'dark'}))");
    await evaluate('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
    await evaluate('Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{})))');
    await capture('guidance-error-dark');
    await command('Network.setBlockedURLs', { urls: [] }, sessionId);
    await command('Network.emulateNetworkConditions', { offline: false, latency: 800, downloadThroughput: -1, uploadThroughput: -1 }, sessionId);
    await navigate(async () => {
      await click('[data-guidance-form] button[type=submit]');
      assert.equal(await evaluate("document.querySelector('[data-guidance-form]').getAttribute('aria-busy')"), 'true');
      assert.equal(await evaluate("document.querySelector('[data-guidance-editor-close]').disabled && document.querySelector('[name=content]').disabled"), true);
      await command('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27 }, sessionId);
      await command('Input.dispatchKeyEvent', { type: 'keyUp', key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27 }, sessionId);
      assert.equal(await evaluate("document.querySelector('[data-guidance-editor]').hidden"), false);
    });
    await command('Network.emulateNetworkConditions', { offline: false, latency: 0, downloadThroughput: -1, uploadThroughput: -1 }, sessionId);
    const saved = await guidance();
    assert.equal(saved.entries.length, 1);
    assert.equal(saved.entries[0].content, content.trim());
    assert.equal(saved.entries[0].kind, 'constraint');
    assert.equal(saved.revisions.length, 1);
    await b.reloadPage();
    assert.match(await evaluate<string>("document.querySelector('.guidance-entry').textContent"), /用户数据和备份只保存在本机/);
    await click('[data-guidance-action="deactivate"]');
    await waitFor("document.activeElement.name === 'reason'");
    assert.equal(await evaluate("document.querySelector('[name=content]').disabled"), true);
    await scrollFields('.guidance-editor-body', '.guidance-editor > header', '.guidance-editor footer');
    await fill('[name=reason]', '验证说明停用后保留历史。');
    await navigate(() => click('[data-guidance-form] button[type=submit]'));
    const stopped = await guidance();
    assert.equal(stopped.entries.length, 0);
    assert.equal(stopped.inactive_entries[0].content, content.trim());
    await click('.guidance-inactive > summary');
    await click('[data-guidance-action="restore"]');
    await waitFor("document.activeElement.name === 'reason'");
    await fill('[name=reason]', '恢复已核对的说明。');
    await navigate(() => click('[data-guidance-form] button[type=submit]'));
    const restored = await guidance();
    assert.equal(restored.entries[0].content, content.trim());
    assert.equal(restored.inactive_entries.length, 0);
    assert.equal(restored.revisions.length, 3);

  });
}
