import assert from "node:assert/strict";
import test from "node:test";
import { openMolisWorkProjectCatalog } from "@molis-ai/molis-work-app-desktop";
import { openGoalBrowser } from "./fixtures/goal-browser.js";

test("Feed source navigation, independent nested panes, resize and restore", { timeout: 90_000 }, async (t) => {
  const browser = await openGoalBrowser(t, true);
  if (!browser) return;
  const { evaluate, waitFor, click, command, sessionId, navigate, origin, projectId, homeDirectory } = browser;
  const catalog = await openMolisWorkProjectCatalog({ homeDirectory });
  catalog.addProjectPlugin({ project_id: projectId!, plugin_id: "feed", actor_id: "pane-test" }); catalog.close();
  await command("Emulation.setDeviceMetricsOverride", { width: 1440, height: 960, deviceScaleFactor: 1, mobile: false }, sessionId);
  await navigate(() => command("Page.navigate", { url: `${origin}/projects/${projectId}/` }, sessionId));
  await waitFor("document.querySelector('[data-titlebar-tabs] .tab-item')");
  assert.equal(await evaluate("document.querySelector('[data-immersive-theme]') === null"), true);
  await click('[data-plugin-id="feed"]');
  await waitFor("!document.querySelector('[data-directory-panel=feed]').hidden");
  const sources = await evaluate<string[]>("[...document.querySelectorAll('[data-feed-task-toggle]')].map(x=>x.dataset.feedTaskToggle)");
  assert.ok(sources.length > 1);
  const source = sources.find(id => id.includes("rss"))!;
  await click(`[data-feed-task-toggle="${source}"]`);
  assert.equal(await evaluate("document.querySelector('[data-feed-task-title]').textContent"), "RSS · Latent Space");
  const sourceIds = await evaluate<string[]>("[...document.querySelectorAll('[data-feed-item-wrap]:not([hidden]) [data-feed-entry-id]')].map(x=>x.dataset.feedEntrySourceId)");
  assert.deepEqual(sourceIds, [source]);
  const bounds = await evaluate<number[]>("[...document.querySelectorAll('[data-feed-task-toggle]')].map(x=>x.getBoundingClientRect().top)");
  assert.equal(new Set(bounds).size, bounds.length, "source tasks must not overlap");
  const widths = await evaluate<number[]>("[...document.querySelectorAll('[data-titlebar-tabs] .tab-item')].map(x=>Math.round(x.getBoundingClientRect().width))");
  assert.equal(new Set(widths).size, 1);
  await click('[data-titlebar-tabs] [data-tab-split]');
  await click('[data-layout-split=right]');
  await waitFor("document.querySelectorAll('iframe.tab-content-frame').length === 2 && [...document.querySelectorAll('iframe.tab-content-frame')].every(f=>f.contentDocument?.querySelector('[data-feed-task-title]')?.textContent==='RSS · Latent Space')");
  assert.equal(await evaluate("document.querySelector('[data-titlebar-tabs]')?.hidden"), true);
  assert.equal(await evaluate("[...document.querySelectorAll('[data-tab-pane] [data-tab-strip]')].every(strip => !strip.hidden)"), true);
  const frameSelector = "document.querySelector('iframe.tab-content-frame').contentDocument";
  await evaluate(`{ const field = ${frameSelector}.querySelector('[data-feed-search]'); field.value = 'not found in this source'; field.dispatchEvent(new Event('input',{bubbles:true})); }`);
  assert.equal(await evaluate(`${frameSelector}.querySelector('[data-feed-result-count]').textContent`), "0 个 Item");
  assert.equal(await evaluate("[...document.querySelectorAll('iframe.tab-content-frame')][1].contentDocument.querySelector('[data-feed-result-count]').textContent"), "1 个 Item");
  await click('.tab-pane.is-focused [data-tab-split]');
  await click('[data-layout-split=bottom]');
  await waitFor("document.querySelectorAll('[data-tab-pane]').length===3 && document.querySelector('[data-direction=column]')");
  assert.equal(await evaluate(`${frameSelector}.querySelector('[data-feed-search]').value`), "not found in this source", "splitting a neighbour must preserve existing content state");
  const sash = await evaluate<{x:number;y:number}>("(()=>{const r=document.querySelector('[data-direction=row] [data-tab-sash]').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/4}})()");
  await command("Input.dispatchMouseEvent", { type: "mousePressed", ...sash, button: "left", clickCount: 1 }, sessionId);
  await command("Input.dispatchMouseEvent", { type: "mouseMoved", x: sash.x + 90, y: sash.y, button: "left", buttons: 1 }, sessionId);
  await command("Input.dispatchMouseEvent", { type: "mouseReleased", x: sash.x + 90, y: sash.y, button: "left", clickCount: 1 }, sessionId);
  const ratio = await evaluate("document.querySelector('[data-direction=row] [data-tab-sash]').getAttribute('aria-valuenow')");
  assert.notEqual(ratio, "50");
  assert.equal(await evaluate(`${frameSelector}.querySelector('[data-feed-search]').value`), "not found in this source");
  await browser.reloadPage();
  await waitFor("document.querySelectorAll('[data-tab-pane]').length===3");
  assert.equal(await evaluate("document.querySelector('[data-direction=row] [data-tab-sash]').getAttribute('aria-valuenow')"), ratio);
  await command("Emulation.setDeviceMetricsOverride", { width: 390, height: 844, deviceScaleFactor: 1, mobile: false }, sessionId);
  assert.equal(await evaluate("[...document.querySelectorAll('[data-tab-pane]')].filter(p=>p.getBoundingClientRect().width>0).length"), 1);
  await click('.tab-pane.is-focused [data-tab-split]');
  await click('[data-focus-pane]');
  assert.equal(await evaluate("document.querySelector('.tab-pane.is-focused').dataset.tabPane===document.querySelector('[data-focus-pane]').dataset.focusPane"), true);
});

test("moving a Feed tab and merging panes preserves its unfinished source form", { timeout: 90_000 }, async (t) => {
  const browser = await openGoalBrowser(t, true);
  if (!browser) return;
  const { evaluate, waitFor, click, command, sessionId, navigate, origin, projectId, homeDirectory } = browser;
  const catalog = await openMolisWorkProjectCatalog({ homeDirectory });
  catalog.addProjectPlugin({ project_id: projectId!, plugin_id: "feed", actor_id: "pane-test" }); catalog.close();
  await command("Emulation.setDeviceMetricsOverride", { width: 1440, height: 960, deviceScaleFactor: 1, mobile: false }, sessionId);
  await navigate(() => command("Page.navigate", { url: `${origin}/projects/${projectId}/` }, sessionId));
  await waitFor("document.querySelector('[data-titlebar-tabs] .tab-item')");
  await click('[data-titlebar-tabs] [data-tab-split]');
  await click('[data-layout-split=right]');
  await click('[data-plugin-id="feed"]');
  await waitFor("[...document.querySelectorAll('iframe.tab-content-frame:not([hidden])')].some(f=>f.contentDocument?.body?.dataset.desktopSurface==='feed')");
  await click('[data-directory-panel="feed"] [data-feed-add-toggle]');
  await waitFor("document.querySelector('[data-feed-sources-dialog]').open");
  await click('[data-feed-choose-kind=custom_rss]');
  await evaluate(`(() => {
    window.draftFrame = [...document.querySelectorAll('iframe.tab-content-frame:not([hidden])')].find(f=>f.contentDocument.body.dataset.desktopSurface==='feed');
    window.draftDocument = draftFrame.contentDocument;
    document.querySelector('[data-feed-add-name]').value = '未提交的观察来源';
    document.querySelector('[data-feed-add-form] [data-feed-source-value=custom_rss]').value = 'https://example.com/draft.xml';
    draftDocument.querySelector('[data-feed-search]').value='保留检索';
    document.querySelector('[data-feed-sources-dialog]').close();
    window.sourcePane = draftFrame.dataset.paneOwner;
    const target = [...document.querySelectorAll('[data-tab-pane]')].find(p=>p.dataset.tabPane!==sourcePane);
    window.targetPane = target.dataset.tabPane;
    const transfer = new DataTransfer();
    document.querySelector('[data-tab-id="'+draftFrame.dataset.paneTab+'"]').dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:transfer}));
    const r=target.getBoundingClientRect();
    target.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:transfer,clientX:r.x+r.width/2,clientY:r.y+r.height/2}));
  })()`);
  await waitFor("draftFrame.dataset.paneOwner===targetPane");
  assert.equal(await evaluate("draftFrame.contentDocument===draftDocument && draftFrame.isConnected"), true, "move must retain the actual content document");
  assert.equal(await evaluate("document.querySelector('[data-feed-add-name]').value"), "未提交的观察来源");
  await evaluate("document.querySelector('[data-tab-pane=\"'+sourcePane+'\"] [data-tab-pane-close]').click()");
  await waitFor("document.querySelectorAll('[data-tab-pane]').length===1");
  assert.equal(await evaluate("draftFrame.contentDocument===draftDocument && !draftFrame.hidden"), true, "merge must retain the surviving content document");
  await click('[data-directory-panel="feed"] [data-feed-add-toggle]');
  await click('[data-feed-choose-kind=custom_rss]');
  assert.equal(await evaluate("document.querySelector('[data-feed-add-form]').hidden"), false);
  assert.equal(await evaluate("draftDocument.querySelector('[data-feed-search]').value"), "保留检索");
  await click('[data-feed-sources-dialog] [data-feed-sources-close]');
  assert.equal(await evaluate("document.querySelector('[data-feed-add-form] [data-feed-source-value=custom_rss]').value"), "https://example.com/draft.xml");
  // Focus messages still resolve the moved frame's new owner.
  await evaluate("draftDocument.querySelector('[data-feed-search]').focus()");
  assert.equal(await evaluate("document.querySelector('.tab-pane.is-focused').dataset.tabPane===targetPane"), true);
});

test("opening a related Goal inside a pane leaves the original Goal tab intact", { timeout: 90_000 }, async (t) => {
  const browser = await openGoalBrowser(t, true);
  if (!browser) return;
  const { evaluate, waitFor, click, openGoalFrame, command, sessionId, navigate, origin, projectId } = browser;
  await command("Emulation.setDeviceMetricsOverride", { width: 1440, height: 960, deviceScaleFactor: 1, mobile: false }, sessionId);
  await navigate(() => command("Page.navigate", { url: `${origin}/projects/${projectId}/` }, sessionId));
  await waitFor("document.querySelector('[data-titlebar-tabs] .tab-item')");
  await click('[data-plugin-id="goals"]');
  await openGoalFrame('.tree-node[data-select-goal="CORE"]');
  await click('[data-frame-goal-work]');
  await waitFor("document.querySelector('[data-goal-view]')?.dataset.goalView==='CORE'");
  await click('[data-titlebar-tabs] [data-tab-split]');
  await click('[data-layout-split=right]');
  await waitFor("[...document.querySelectorAll('iframe.tab-content-frame:not([hidden])')].length===2 && [...document.querySelectorAll('iframe.tab-content-frame:not([hidden])')].every(f=>f.contentDocument?.querySelector('[data-goal-view]')?.dataset.goalView==='CORE' && f.contentDocument.querySelector('[data-goal-node-workspace]')?.hidden===false)");
  const relatedId = await evaluate<string>(`(() => {
    const paneId = document.querySelector('.tab-pane.is-focused').dataset.tabPane;
    window.originalFrame = document.querySelector('iframe[data-pane-owner="'+paneId+'"]:not([hidden])');
    window.originalDocument = originalFrame.contentDocument;
    originalDocument.querySelector('[data-frame-goal-work]').click();
    const toggle = originalDocument.querySelector('[data-goal-details-toggle]');
    if(toggle?.getAttribute('aria-expanded')==='false') toggle.click();
    originalDocument.querySelector('[data-goal-info]:not([open]) > summary')?.click();
    originalDocument.querySelector('[data-event-reader=description]').click();
    const link=originalDocument.querySelector('.event-reader .relation-row[data-select-goal]') || [...originalDocument.querySelectorAll('.relation-row[data-select-goal]')].find(x=>x.getBoundingClientRect().width);
    if (!link || !link.getBoundingClientRect().width) throw new Error('related Goal must be available in the content panel');
    link.click();
    return link.dataset.selectGoal;
  })()`);
  await waitFor(`[...document.querySelectorAll('iframe.tab-content-frame:not([hidden])')].some(f=>f.contentDocument?.querySelector('[data-goal-frame-surface]')?.dataset.frameGoal===${JSON.stringify(relatedId)})`);
  await evaluate("document.querySelector('[data-tab-id=\"'+originalFrame.dataset.paneTab+'\"] .tab-item-trigger').click()");
  await waitFor("!originalFrame.hidden");
  assert.equal(await evaluate("originalFrame.contentDocument===originalDocument"), true);
  assert.equal(await evaluate("originalDocument.querySelector('[data-goal-view]').dataset.goalView"), "CORE");
});
