export const FORM_EN: Record<string, string> = {
  "重新读取": "Reload form",
  "继续": "Continue",
  "重新读取会丢弃未保存的编辑和填写内容。继续吗？": "Reloading discards unsaved edits and answers. Continue?",
  "离开会丢弃未提交的填写内容。继续吗？": "Leaving discards unsubmitted answers. Continue?",
  "问卷已在别处修改，当前输入已保留。请复制需要保留的内容，再重新读取。": "This form changed elsewhere. Your input is preserved. Copy what you need, then reload the form.",
  "保存中": "Saving",
  "尚未保存": "Unsaved",
  "处理中": "Working",
  "已保存": "Saved",
  "恢复发布": "Resume publication",
  "上次 Artifact 发布尚未完成。恢复使用上次固定内容，后续编辑可另存一版。": "Artifact publication is incomplete. Resuming uses the previous snapshot; later edits can be published separately.",
  "题目或 AI 提示": "Question or AI prompt",
  "按题目加题": "Add this question",
  "AI 拟题加题": "Suggest and add with AI",
  "当前没有可用的文字模型，请检查模型设置和服务连接。": "No text model is available. Check model settings and service connections.",
  "历史答卷未保存题目快照；名称参考当前问卷，未知题目保留原题号。": "This older response has no question snapshot. Labels use the current form; unknown questions retain their original IDs.",
  "标记已发布": "Mark as published",
  "发布状态保存在本机，不会生成外网填写链接。": "Publication status is local; it does not create a public response link.",
  "新建问卷": "New form",
  "还没有问卷": "No forms yet",
  "先建一份，再加题目。预览里可以自己填一遍，看结果。": "Create a form, add questions, fill a preview, then check results.",
  "内容属于当前项目，保存在这台电脑。": "These stay with the current project on this computer.",
  "返回问卷列表": "Back to form list",
  "问卷": "Form",
  "编辑": "Edit",
  "预览": "Preview",
  "结果": "Results",
  "删除": "Delete",
  "存成 Artifact": "Save as Artifact",
  "再存一版": "Save another version",
  "已存成 Artifact": "Saved as an Artifact",
  "取消": "Cancel",
  "标题": "Title",
  "说明": "Description",
  "可选": "Optional",
  "题目": "Questions",
  "填空": "Text",
  "单选": "Single choice",
  "多选": "Multiple choice",
  "下拉": "Dropdown",
  "评分": "Rating",
  "日期": "Date",
  "加一题": "Add question",
  "按提示加一题": "Add a question from a prompt",
  "例如：你最常用的工具是什么": "For example: What tool do you use most?",
  "加题": "Add from prompt",
  "发布": "Publish",
  "提交": "Submit",
  "已提交": "Submitted",
  "答卷": "Response",
  "还没有题目。回到编辑加一题。": "No questions yet. Go back to Edit and add one.",
  "删选项": "Remove option",
  "JSON": "JSON",
  "草稿": "Draft",
  "已发布": "Published",
  "题": "questions",
  "必填": "Required",
  "选项": "Option",
  "加选项": "Add option",
  "上移": "Move up",
  "删题": "Remove question",
  "下移": "Move down",
  "问卷请求失败": "Form request failed",
  "保存失败": "Could not save",
  "缺少项目": "Missing project",
  "未命名问卷": "Untitled form",
  "还没有答卷": "No submissions yet",
  "份答卷": "submissions",
  "建问卷，预览填写，看结果。": "Create a form, fill a preview, then check results.",
  "删除这份问卷？答卷也会一起删掉。": "Delete this form? Submissions will be removed too.",
  "还有必填题没填": "A required question is still empty",
  "载入中…": "Loading…",
  "还没有说明": "No description yet",
};
