export const FORM_EN: Record<string, string> = {
  "新建问卷": "New form",
  "还没有问卷": "No forms yet",
  "先建一份，再加题目。预览里可以自己填一遍，看结果。": "Create a form, add questions, fill a preview, then check results.",
  "内容属于当前项目，保存在这台电脑。": "These stay with the current project on this computer.",
  "返回问卷列表": "Back to form list",
  "问卷": "Form",
  "编辑": "Edit",
  "预览": "Preview",
  "结果": "Results",
  "删除": "Delete",
  "取消": "Cancel",
  "标题": "Title",
  "说明": "Description",
  "可选": "Optional",
  "题目": "Questions",
  "填空": "Text",
  "单选": "Single choice",
  "多选": "Multiple choice",
  "下拉": "Dropdown",
  "评分": "Rating",
  "日期": "Date",
  "加一题": "Add question",
  "按提示加一题": "Add a question from a prompt",
  "例如：你最常用的工具是什么": "For example: What tool do you use most?",
  "加题": "Add from prompt",
  "发布": "Publish",
  "提交": "Submit",
  "已提交": "Submitted",
  "答卷": "Response",
  "还没有题目。回到编辑加一题。": "No questions yet. Go back to Edit and add one.",
  "删选项": "Remove option",
  "JSON": "JSON",
  "草稿": "Draft",
  "已发布": "Published",
  "题": "questions",
  "必填": "Required",
  "选项": "Option",
  "加选项": "Add option",
  "上移": "Move up",
  "下移": "Move down",
  "问卷请求失败": "Form request failed",
  "保存失败": "Could not save",
  "缺少项目": "Missing project",
  "未命名问卷": "Untitled form",
  "还没有答卷": "No submissions yet",
  "份答卷": "submissions",
  "建问卷，预览填写，看结果。": "Create a form, fill a preview, then check results.",
  "删除这份问卷？答卷也会一起删掉。": "Delete this form? Submissions will be removed too.",
  "还有必填题没填": "A required question is still empty",
  "载入中…": "Loading…",
  "还没有说明": "No description yet",
};
