export const FORM_EN: Record<string, string> = {
  "重新读取": "Reload form",
  "继续": "Continue",
  "重新读取会丢弃未保存的编辑和填写内容。继续吗？": "Reloading discards unsaved edits and answers. Continue?",
  "离开会丢弃未提交的填写内容。继续吗？": "Leaving discards unsubmitted answers. Continue?",
  "问卷已在别处修改，当前输入已保留。请复制需要保留的内容，再重新读取。": "This form changed elsewhere. Your input is preserved. Copy what you need, then reload the form.",
  "保存中": "Saving",
  "尚未保存": "Unsaved",
  "处理中": "Working",
  "已保存": "Saved",
  "恢复发布": "Resume publication",
  "上次 Artifact 发布尚未完成。恢复使用上次固定内容，后续编辑可另存一版。": "Artifact publication is incomplete. Resuming uses the previous snapshot; later edits can be published separately.",
  "题目或 AI 提示": "Question or AI prompt",
  "按题目加题": "Add this question",
  "AI 拟题加题": "Suggest and add with AI",
  "当前没有可用的文字模型，请检查模型设置和服务连接。": "No text model is available. Check model settings and service connections.",
  "历史答卷未保存题目快照；名称参考当前问卷，未知题目保留原题号。": "This older response has no question snapshot. Labels use the current form; unknown questions retain their original IDs.",
  "标记已发布": "Mark as published",
  "发布状态保存在本机，不会生成外网填写链接。": "Publication status is local; it does not create a public response link.",
  "新建问卷": "New form",
  "还没有问卷": "No forms yet",
  "先建一份，再加题目。预览里可以自己填一遍，看结果。": "Create a form, add questions, fill a preview, then check results.",
  "内容属于当前项目，保存在这台电脑。": "These stay with the current project on this computer.",
  "返回问卷列表": "Back to form list",
  "问卷": "Form",
  "编辑": "Edit",
  "预览": "Preview",
  "结果": "Results",
  "删除": "Delete",
  "存成 Artifact": "Save as Artifact",
  "再存一版": "Save another version",
  "已存成 Artifact": "Saved as an Artifact",
  "取消": "Cancel",
  "标题": "Title",
  "说明": "Description",
  "可选": "Optional",
  "题目": "Questions",
  "填空": "Text",
  "单选": "Single choice",
  "多选": "Multiple choice",
  "下拉": "Dropdown",
  "评分": "Rating",
  "日期": "Date",
  "加一题": "Add question",
  "按提示加一题": "Add a question from a prompt",
  "例如：你最常用的工具是什么": "For example: What tool do you use most?",
  "加题": "Add from prompt",
  "发布": "Publish",
  "提交": "Submit",
  "已提交": "Submitted",
  "答卷": "Response",
  "还没有题目。回到编辑加一题。": "No questions yet. Go back to Edit and add one.",
  "删选项": "Remove option",
  "JSON": "JSON",
  "草稿": "Draft",
  "已发布": "Published",
  "题": "questions",
  "必填": "Required",
  "选项": "Option",
  "加选项": "Add option",
  "上移": "Move up",
  "删题": "Remove question",
  "下移": "Move down",
  "问卷请求失败": "Form request failed",
  "保存失败": "Could not save",
  "缺少项目": "Missing project",
  "未命名问卷": "Untitled form",
  "还没有答卷": "No submissions yet",
  "份答卷": "submissions",
  "建问卷，预览填写，看结果。": "Create a form, fill a preview, then check results.",
  "删除这份问卷？答卷也会一起删掉。": "Delete this form? Submissions will be removed too.",
  "还有必填题没填": "A required question is still empty",
  "载入中…": "Loading…",
  "还没有说明": "No description yet",
  "重新开始收集": "Start collecting again",
  "开始收集": "Start collecting",
  "填写页": "Fill-in page",
  "在这台电脑上填写 · 回答只保存在这台电脑": "Filling in on this computer · answers are saved only on this computer",
  "退出填写页": "Leave fill-in page",
  "已提交，谢谢": "Submitted — thank you",
  "这是第 {count} 份答卷。可以把电脑交给下一位。": "That's response {count}. You can hand the computer to the next person.",
  "下一位填写": "Next person",
  "提交失败": "Submission failed",
  "未命名题目": "Untitled question",
  "{count} 人回答": "{count} answered",
  "{score} 分": "{score} points",
  "平均 {score} / 5": "average {score} / 5",
  "上次固定版本还没存完。恢复会使用上次的固定内容，之后的编辑可以再存一版。": "The last fixed version wasn't finished saving. Resuming uses that saved content; you can save another version of later edits.",
  "再存一个固定版本": "Save another fixed version",
  "存为固定版本": "Save as fixed version",
  "正在收集": "Collecting",
  "已停止收集": "Collection stopped",
  "未开始收集": "Not collecting yet",
  "第 {version} 版题目 · 放在这个位置的成果（Artifacts）里；不含答卷": "Question set version {version} · kept in this location's Artifacts; responses not included",
  "还没有题目，先加题再开始收集": "No questions yet. Add some before you start collecting.",
  "正在收集答卷：可以在这台电脑上打开填写页，或导出填写页文件发给别人。不会生成外网链接。": "Collecting responses: open the fill-in page on this computer, or export the fill-in page file and send it to people. No public link is created.",
  "已停止收集。已有答卷都保留；填写页不再接受提交，导入答卷文件仍然可以。": "Collection stopped. Existing responses are kept; the fill-in page no longer accepts submissions, but you can still import response files.",
  "填写页 · 发给对方在自己的浏览器里填，填完得到答卷文件发回，在“结果”里导入": "Fill-in page · send it to someone to fill in their own browser; they send back the response file, which you import under “Results”",
  "{count} 份答卷 · Excel、Numbers 可以打开": "{count} responses · opens in Excel or Numbers",
  "还没有答卷，收到答卷后再存成数据表": "No responses yet. Save as a dataset once responses arrive.",
  "{count} 份答卷做成的表 · 之后的新答卷不会自动加入": "A table of {count} responses · new responses won't be added automatically",
  "导入 {count} 份": "Imported {count}",
  "{count} 份已导入过，跳过": "{count} already imported, skipped",
  "{count} 份没有导入": "{count} not imported",
  "导入失败": "Import failed",
  "先建一份，再加题目。开始收集后，别人可以在这台电脑上填，或用导出的填写页在自己的浏览器里填。": "Create a form, then add questions. Once collecting, people can fill it in on this computer or in their own browser using the exported fill-in page.",
  "自己先填一遍；提交的会计入结果并标为试填": "Try it yourself first; your submission counts in the results, marked as a test",
  "试填": "Test fill",
  "开始在这台电脑上收集答卷；不会生成外网链接": "Start collecting responses on this computer; no public link is created",
  "整屏填写页，适合把电脑交给别人填": "Full-screen fill-in page, for handing the computer to someone",
  "打开填写页": "Open fill-in page",
  "导出": "Export",
  "填写页文件（发给别人填）": "Fill-in page file (to send to people)",
  "答卷表格（.csv）": "Responses table (.csv)",
  "把题目存成不会再变的一版，放进这个位置的成果（Artifacts）；不含答卷": "Save the questions as a version that won't change, in this location's Artifacts; responses not included",
  "停止收集": "Stop collecting",
  "收集答卷不需要网络：在这台电脑上打开填写页让别人填；或导出填写页文件发给对方，对方填完得到答卷文件发回给你，在“结果”里导入。不会生成外网链接。": "Collecting responses doesn't need a network: open the fill-in page on this computer for others to fill in, or export the fill-in page file and send it; they send back a response file that you import under “Results”. No public link is created.",
  "导入答卷文件…": "Import response files…",
  "把现有答卷做成一张可以继续编辑的数据表；之后的新答卷不会自动加入": "Turn the current responses into an editable dataset; new responses won't be added automatically",
  "存成数据表": "Save as dataset",
  "逐份答卷": "Individual responses",
  "正在这台电脑上收集": "Collecting on this computer",
  "本机填写页": "Fill-in page on this computer",
  "答卷文件": "Response files",
  "继续保存上次固定版本": "Finish saving the last fixed version",
};
