import type { ActionSchema } from "@molis-ai/molis-work-contracts/platform/actions";
export const text = { type: "string" };
export const id = { type: "string", minLength: 1, maxLength: 500 };
export const integer = { type: "integer", minimum: 0 };
export const revision = { type: "integer", minimum: 1 };
export const nullable = (schema: unknown) => ({ anyOf: [schema, { type: "null" }] });
export const array = (items: unknown) => ({ type: "array", items });
export const object = (properties: Record<string, unknown>, required = Object.keys(properties)): ActionSchema => ({ type: "object", properties, required, additionalProperties: false });
export const domain = object({ id, name: text });
export const kind = { enum: ["obsidian", "llm-wiki", "markdown"] };
export const role = { enum: ["material", "wiki", "index", "log", "attachment"] };
export const source = object({ id, name: text, kind, locator: text, domain_id: nullable(id) });
export const materialFields = { id, source_id: id, path: text, title: text, tags: array(text), aliases: array(text), domain_id: nullable(id), role, revision, hash: text, bytes: integer, updated_at: text, mime: text };
export const material = object({ ...materialFields, body: text, frontmatter: text });
export const summary = object({ ...materialFields, excerpt: text });
export const reference = object({ label: id, material_id: id, revision, title: text, path: text, body: text });
export const draftFields = { id, title: text, domain_id: nullable(id), mode: { enum: ["synthesize", "query"] }, saved_id: nullable(id), created_at: text };
export const draft = object({ ...draftFields, body: text, references: array(reference) });
export const link = object({ target: text, label: text, status: { enum: ["resolved", "missing", "ambiguous", "external", "unsafe"] }, material_id: id }, ["target", "label", "status"]);
export const detail = object({ material, outgoing: array(link), incoming: array(material), references: array(reference) });
export const file = object({ path: { ...id, maxLength: 1000 }, data: text, reason: text }, ["path"]);
export const files = { ...array(file), maxItems: 1000 };
export const entry = object({ path: text, status: { enum: ["new", "update", "unchanged", "skipped"] }, reason: text, role, bytes: integer }, ["path", "status"]);
export const preview = object({ id, source, entries: array(entry), expires_at: integer });
export const receipt = object({ id, source_id: id, added: integer, updated: integer, unchanged: integer, skipped: integer, material_ids: array(id), entries: array(entry) });
export const materialInput = { title: { ...id, pattern: "\\S" }, body: { ...text, maxLength: 2_000_000 }, domain_id: nullable(text) };
export const importFields = { kind, name: { ...id, maxLength: 200 }, source_id: id, domain_id: nullable(text) };
export const readInput = object({ id, revision }, ["id"]);
export const deleted = object({ deleted: { const: true } });
