export const COGNIA_CLIENT_FACTORY_SCRIPT = String.raw`(host) => {
  const root = document.querySelector('[data-cognia=workbench]'); if (!root) return;
  const L = host.translate, $ = s => root.querySelector(s), dialog = $('[data-cognia-dialog]'), form = $('[data-cognia-form]'), content = $('[data-cognia-dialog-content]'), submit = $('[data-cognia-submit]');
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const tx = value => esc(L(value)), button = (label, action, extra='') => '<button type="button" class="mw-btn mw-btn--ghost cognia-relation" data-cognia-action="'+action+'" '+extra+'>'+esc(label)+'</button>';
  let state = {materials:[],domains:[],sources:[],drafts:[]}, selected = new Set(), current = null, preview = null, receipt = null, draft = null, flow = '', busy = false, seq = 0, timer, returnFocus = null, listScroll = 0, listFocus = null;
  const api = async (path, body) => { const response = await fetch('/api/plugins/cognia'+path,{method:body===undefined?'GET':'POST',headers:typeof molisWorkControlHeaders==='function'?molisWorkControlHeaders():{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)}); const payload=await response.json().catch(()=>({})); if(!response.ok)throw new Error(payload.error||L('Cognia 请求失败')); return payload; };
  const notice = error => { const el=$('[data-cognia-notice]'); el.hidden=!error; el.querySelector('span').textContent=error?L(error):''; };
  const fail = error => { const el=$('[data-cognia-error]'); el.hidden=!error; el.textContent=error?L(error):''; };
  const options = (values, first) => '<option value="">'+tx(first)+'</option>'+values.map(v=>'<option value="'+esc(v.id)+'">'+esc(v.name)+'</option>').join('');
  const field = (label, inner) => '<label class="cognia-field">'+tx(label)+inner+'</label>';
  const domainSelect = () => '<select class="mw-select" name="domain_id">'+options(state.domains,'未分类')+'</select>';
  const roles = {material:'材料',wiki:'知识',index:'索引',log:'日志',attachment:'附件'};
  const statuses = {new:'新增',update:'更新',unchanged:'不变',skipped:'跳过'};
  function rows() {
    const el=$('[data-cognia-rows]');
    el.innerHTML=state.materials.length?state.materials.map(m=>'<article class="cognia-row"><input type="checkbox" class="mw-checkbox" data-cognia-select="'+esc(m.id)+'" aria-label="'+tx('选择材料')+' '+esc(m.title)+'" '+(selected.has(m.id)?'checked':'')+' '+(m.role==='attachment'?'disabled':'')+'><button type="button" class="cognia-entry" data-cognia-id="'+esc(m.id)+'"><div><strong>'+esc(m.title)+'</strong><small>'+esc(m.path)+'</small>'+(m.excerpt?'<small>'+esc(m.excerpt)+'</small>':'')+'</div><span>'+tx(roles[m.role])+'</span><span>'+esc(state.domains.find(d=>d.id===m.domain_id)?.name||L('未分类'))+'</span><span>'+esc(new Date(m.updated_at).toLocaleDateString())+'</span></button></article>').join(''):'<div class="cognia-empty"><strong>'+tx('把已有的知识带进来')+'</strong>'+tx('导入 Markdown 目录，或添加一份材料。资料保存在当前 Home，与项目无关。')+'</div>';
    $('[data-cognia-selected]').textContent=L('已选')+' '+selected.size+' / 5';
  }
  async function load() {
    const id=++seq, q=new URLSearchParams({q:$('[data-cognia-search]').value,domain_id:$('[data-cognia-domain]').value,source_id:$('[data-cognia-source]').value}); const next=await api('?'+q); if(id!==seq)return; state=next;
    for(const key of ['domain','source']) { const el=$('[data-cognia-'+key+']'), value=el.value; el.innerHTML=options(state[key==='domain'?'domains':'sources'],key==='domain'?'全部领域':'全部来源')+(key==='domain'?'<option value="unclassified">'+tx('未分类')+'</option>':''); el.value=value; }
    $('[data-cognia-model]').hidden=false;$('[data-cognia-model]').textContent=state.ai_runtime||L('尚未配置文字模型，导入、搜索和阅读仍可使用。'); rows(); notice('');
  }
  function markdown(body, outgoing=[], references=[]) {
    const plain = line => esc(line).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
    const inline = line => {
      let text='',end=0;
      const tokens = /\x60([^\x60]+)\x60|!?\[\[([^\]\n]+)\]\]|!?\[([^\]\n]*)\]\(<?([^\s)>]+)>?(?:\s+"[^"]*")?\)|\[S(\d+)\]/g;
      for(const match of line.matchAll(tokens)) {
        text+=plain(line.slice(end,match.index));end=match.index+match[0].length;
        if(match[1]!==undefined){text+='<code>'+esc(match[1])+'</code>';continue;}
        if(match[5]){const ref=references.find(r=>r.label==='S'+match[5]);text+=ref?'<button type="button" class="cognia-inline-link" data-cognia-action="reference" data-id="'+esc(ref.material_id)+'" data-revision="'+ref.revision+'">'+esc(match[0])+'</button>':esc(match[0]);continue;}
        const parts=match[2]?.split('|'),target=parts?parts[0]:match[4],label=parts?(parts[1]||parts[0]):(match[3]||target),link=outgoing.find(l=>l.target===target);
        if(link?.status==='resolved')text+='<button type="button" class="cognia-inline-link" data-cognia-action="link" data-id="'+esc(link.material_id)+'">'+esc(label)+'</button>';
        else if(link?.status==='external'&&/^(https?:|mailto:)/i.test(link.target))text+='<a href="'+esc(link.target)+'" target="_blank" rel="noopener noreferrer">'+esc(label)+'</a>';
        else text+='<span title="'+tx(link?.status==='ambiguous'?'同名链接有歧义':'未找到链接目标')+'">'+esc(match[0])+'</span>';
      }
      return text+plain(line.slice(end));
    };
    let code=false,output='',paragraph=[],list=false;
    const flush=()=>{if(paragraph.length){output+='<p>'+paragraph.map(inline).join('\n')+'</p>';paragraph=[];}if(list){output+='</ul>';list=false;}};
    for(const line of body.split(/\r?\n/)) {
      if(/^\s*(?:\x60{3,}|~{3,})/.test(line)){flush();output+=code?'</code></pre>':'<pre><code>';code=!code;continue;}
      if(code){output+=esc(line)+'\n';continue;}
      const heading=/^(#{1,6})\s+(.*)$/.exec(line), bullet=/^\s*(?:[-*+] |\d+\. )(.*)$/.exec(line);
      if(heading){flush();output+='<h'+heading[1].length+'>'+inline(heading[2])+'</h'+heading[1].length+'>';}
      else if(bullet){if(paragraph.length)flush();if(!list){output+='<ul>';list=true;}output+='<li>'+inline(bullet[1])+'</li>';}
      else if(/^>\s?/.test(line)){flush();output+='<blockquote>'+inline(line.replace(/^>\s?/,''))+'</blockquote>';}
      else if(!line.trim())flush();else{if(list)flush();paragraph.push(line);}
    }
    flush();if(code)output+='</code></pre>';return output;
  }
  const refs = references => references.length?'<section class="cognia-relations"><h3>'+tx('固定版本来源')+'</h3>'+references.map(r=>button('['+r.label+'] '+r.title+' · v'+r.revision,'reference','data-id="'+esc(r.material_id)+'" data-revision="'+r.revision+'"')).join('')+'</section>':'';
  async function openMaterial(id,revision) {
    const data=await api('/materials/'+encodeURIComponent(id)+(revision?'?revision='+revision:'')); current=data.material; if(root.dataset.expanded!=='true'){listFocus=document.activeElement;listScroll=$('[data-cognia=directory]').scrollTop;}root.dataset.expanded='true';$('[data-cognia-workspace]').hidden=false;$('[data-cognia-heading]').textContent=current.title;
    $('[data-cognia-download]').href='/api/plugins/cognia/materials/'+encodeURIComponent(id)+'/download?revision='+current.revision;
    const links=data.outgoing.map(link=>link.status==='resolved'?button(link.label,'link','data-id="'+esc(link.material_id)+'"'):link.status==='external'?'<p>'+esc(link.label)+' · <a href="'+esc(link.target)+'" target="_blank" rel="noopener noreferrer">'+esc(link.target)+'</a></p>':'<p>'+esc(link.label)+' · '+tx(link.status==='ambiguous'?'同名链接有歧义':link.status==='unsafe'?'不安全的链接':'未找到链接目标')+'</p>').join('');
    $('[data-cognia-reading]').innerHTML='<div class="cognia-provenance"><p>'+esc(state.sources.find(s=>s.id===current.source_id)?.name||'')+' / '+esc(current.path)+'</p><p>'+tx(roles[current.role])+' · v'+current.revision+' · '+esc(current.tags.map(t=>'#'+t).join(' '))+'</p></div><article class="cognia-body">'+(current.role==='attachment'?'<p>'+tx('附件已保存，可下载原文件。此处不执行或提取附件内容。')+'</p>':markdown(current.body.replace(current.frontmatter,''),data.outgoing,data.references))+'</article><details><summary>'+tx('查看原文')+'</summary><pre class="cognia-raw">'+esc(current.body)+'</pre></details>'+refs(data.references)+'<section class="cognia-relations"><h3>'+tx('出站链接')+'</h3>'+(links||'<p>'+tx('暂无链接')+'</p>')+'<h3>'+tx('反向链接')+'</h3>'+(data.incoming.map(m=>button(m.title,'link','data-id="'+esc(m.id)+'"')).join('')||'<p>'+tx('暂无链接')+'</p>')+'</section>';
    $('[data-cognia-reading]').scrollTop=0;$('[data-cognia-heading]').setAttribute('tabindex','-1');$('[data-cognia-heading]').focus();
  }
  function show(title,kind,html,label) { if(!dialog.open)returnFocus=document.activeElement;flow=kind;content.innerHTML=html;$('#cognia-dialog-title').textContent=L(title);submit.textContent=L(label);submit.hidden=false;$('[data-cognia-step]').textContent='';fail('');if(!dialog.open)dialog.showModal(); }
  const guides='<details><summary>'+tx('从其他知识工具导入')+'</summary><p class="cognia-hint">'+tx('Obsidian、Logseq 文件图：选择 Markdown 目录。Notion：导出 Markdown & CSV 并解压。Joplin：导出 Markdown + Front Matter。思源、Anytype、Bear、Apple Notes、Logseq DB：先导出 Markdown，再选导出目录。LLM Wiki 是资料整理方法，不是专有格式。')+'</p><p class="cognia-hint">'+tx('保留 Markdown 原文、目录与附件；不还原数据库关系、查询视图、块引用或动态插件。ENEX、JEX、.sy、SQLite、OneNote 等原生格式需先转换，跳过项会显示原因。')+'</p></details>';
  function showImport() { preview=null;receipt=null;show('导入知识库','import','<p class="cognia-hint">'+tx('单向复制快照，源目录不会修改。每批最多 1000 个文件、32 MB；文本 2 MB、附件 8 MB。')+'</p>'+field('格式','<select class="mw-select" name="kind"><option value="obsidian">Obsidian</option><option value="llm-wiki">LLM Wiki</option><option value="markdown">Markdown</option></select>')+field('领域',domainSelect())+field('上传来源','<select class="mw-select" name="source_id">'+options(state.sources.filter(s=>s.locator==='upload'),'新建独立来源')+'</select>')+field('选择目录','<input type="file" name="files" webkitdirectory multiple>')+field('或输入本机绝对目录路径','<input class="mw-input" name="path" placeholder="/Users/…/vault" autocomplete="off">')+guides,'预览导入');$('[data-cognia-step]').textContent=L('选择 → 预览 → 结果'); }
  function table(entries){return '<table class="cognia-preview"><thead><tr><th>'+tx('相对路径')+'</th><th>'+tx('类型')+'</th><th>'+tx('状态与原因')+'</th></tr></thead><tbody>'+entries.map(e=>'<tr><td>'+esc(e.path)+'</td><td>'+tx(roles[e.role]||'—')+'</td><td>'+tx(statuses[e.status])+(e.reason?' · '+esc(L(e.reason)):'')+'</td></tr>').join('')+'</tbody></table>';}
  function showDraft(value){draft=value;show('审阅知识草稿','review','<h3>'+esc(value.title)+'</h3><p class="cognia-hint">'+tx('这是 AI 生成的草稿，请核对正文与来源，再保存到知识库。')+'</p><article class="cognia-body">'+markdown(value.body,[],value.references)+'</article>'+refs(value.references),value.saved_id?'打开已保存资料':'保存到知识库');}
  function setBusy(on){busy=on;form.querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=on);form.setAttribute('aria-busy',String(on));}
  async function close(){if(busy)return;if(preview&&!receipt)await api('/import/cancel',{preview_id:preview.id});dialog.close();returnFocus?.focus();}
  async function uploadFiles(files){if(files.length>1000)throw new Error(L('每批最多 1000 个文件，请选择较小目录'));let total=0;const result=[];for(const file of files){const path=file.webkitRelativePath.split('/').slice(1).join('/')||file.name, isText=/\.(md|markdown|txt)$/i.test(path),supported=isText||/\.(png|jpe?g|gif|webp|avif|svg|pdf|mp3|wav|mp4|webm)$/i.test(path);let reason='';if(path.split('/').some(p=>p.startsWith('.')||['node_modules','__pycache__','cache'].includes(p)))reason='隐藏或缓存目录';else if(!supported)reason='暂不支持此文件类型';else if(file.size>(isText?2000000:8000000)||total+file.size>32000000)reason='超过文件或批次大小限制';if(reason){result.push({path,reason});continue;}total+=file.size;try{const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=16384)binary+=String.fromCharCode(...bytes.subarray(i,i+16384));result.push({path,data:btoa(binary)});}catch{result.push({path,reason:'读取失败'});}}return result;}
  form.addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const data=new FormData(form);setBusy(true);fail('');const previousLabel=submit.textContent;submit.textContent=L('正在处理…');try{
    if(flow==='import'){const path=String(data.get('path')||'').trim(),files=Array.from(form.querySelector('[name=files]').files);if(!path&&!files.length)throw new Error(L('请选择目录或填写本机路径'));const result=await api('/import/preview',{kind:data.get('kind'),domain_id:data.get('domain_id')||null,...(path?{path}:{files:await uploadFiles(files),name:files[0].webkitRelativePath.split('/')[0],source_id:data.get('source_id')||undefined})});preview=result.preview;flow='preview';content.innerHTML='<p>'+esc(preview.source.name)+' · '+esc(preview.source.locator)+'</p><p>'+tx('领域')+'：'+esc(state.domains.find(d=>d.id===preview.source.domain_id)?.name||L('未分类'))+'</p><p class="cognia-hint">'+tx('确认后导入此次预览的固定内容。相同来源和路径会更新，旧版本继续保留。')+'</p>'+table(preview.entries);submit.textContent=L('确认导入');content.dataset.importable=String(preview.entries.some(e=>e.status!=='skipped'));if(content.dataset.importable==='false')fail(L('没有可导入的内容，请查看跳过原因并选择 Markdown 导出目录。'));$('[data-cognia-step]').textContent=L('预览');}
    else if(flow==='preview'){if(content.dataset.importable==='false')throw new Error(L('没有可导入的内容，请查看跳过原因并选择 Markdown 导出目录。'));const result=await api('/import/commit',{preview_id:preview.id});receipt=result.receipt;flow='receipt';content.innerHTML='<p class="cognia-receipt">'+tx('导入完成')+'<br>'+tx('新增')+' '+receipt.added+' · '+tx('更新')+' '+receipt.updated+' · '+tx('不变')+' '+receipt.unchanged+' · '+tx('跳过')+' '+receipt.skipped+'</p>'+table(receipt.entries);submit.textContent=L('打开资料');$('[data-cognia-step]').textContent=L('结果');await load().catch(e=>fail(L('导入已完成，但列表刷新失败。关闭后可重试读取。')+' '+e.message));}
    else if(flow==='receipt'){dialog.close();if(receipt.material_ids[0])await openMaterial(receipt.material_ids[0]);else await load();}
    else if(flow==='add'){const result=await api('/materials',{title:data.get('title'),body:data.get('body'),domain_id:data.get('domain_id')||null});dialog.close();await load().catch(e=>notice(e.message));await openMaterial(result.material.id);}
    else if(flow==='domain'){await api('/domains',{name:data.get('name')});dialog.close();await load();}
    else if(flow==='ai'){const result=await api('/ai',{mode:content.dataset.mode,question:data.get('question'),domain_id:$('[data-cognia-domain]').value,material_ids:JSON.parse(content.dataset.ids||'[]')});showDraft(result.draft);await load().catch(e=>notice(e.message));}
    else if(flow==='review'){const result=draft.saved_id?{material:{id:draft.saved_id}}:await api('/drafts/'+draft.id+'/save',{});draft.saved_id=result.material.id;dialog.close();await load().catch(e=>notice(e.message));await openMaterial(result.material.id);}
  }catch(error){fail(error.message);submit.textContent=previousLabel;}finally{setBusy(false);if(submit.textContent===L('正在处理…'))submit.textContent=previousLabel;}});
  root.addEventListener('click',async event=>{const action=event.target.closest('[data-cognia-action]')?.dataset.cogniaAction,id=event.target.closest('[data-cognia-id]')?.dataset.cogniaId;try{if(id){returnFocus=event.target.closest('[data-cognia-id]');await openMaterial(id);return;}if(busy)return;const el=event.target.closest('[data-cognia-action]');if(action==='import')showImport();else if(action==='add')show('添加材料','add',field('标题','<input class="mw-input" name="title" required maxlength="500">')+field('领域',domainSelect())+field('Markdown 正文','<textarea class="mw-textarea" name="body" rows="10"></textarea>'),'保存材料');else if(action==='domain')show('新建领域','domain',field('领域名称','<input class="mw-input" name="name" required maxlength="120">'),'创建领域');else if(action==='close')await close();else if(action==='back'){root.dataset.expanded='false';$('[data-cognia-workspace]').hidden=true;$('[data-cognia=directory]').scrollTop=listScroll;if(listFocus?.isConnected&&$('[data-cognia=directory]').contains(listFocus))listFocus.focus();else root.querySelector('[data-cognia-id="'+current?.id+'"]')?.focus();current=null;}else if(action==='reload')await load();else if(action==='link'||action==='reference'){if(dialog.open)dialog.close();await openMaterial(el.dataset.id,el.dataset.revision);}else if(action==='draft'){showDraft((await api('/drafts/'+el.dataset.id)).draft);}else if(action==='drafts'){show('审阅草稿','drafts',state.drafts.length?state.drafts.map(d=>button(d.title+' · '+L(d.saved_id?'已保存':'待审阅'),'draft','data-id="'+esc(d.id)+'"')).join(''):'<p>'+tx('暂无草稿，先选材料整理或检索问答。')+'</p>','关闭');submit.hidden=true;}else if(['synthesize','synthesize-current','query'].includes(action)){const ids=action==='synthesize-current'&&current?[current.id]:[...selected];if(action!=='query'&&(!ids.length||ids.length>5))throw new Error(L('请选择 1–5 份不同材料'));show(action==='query'?'检索问答':'整理为知识','ai','<p class="cognia-hint">'+tx(action==='query'?'按问题关键词检索当前领域，最多使用 5 份相关资料。':'仅向模型发送选中材料的固定版本，最多 100,000 字符。')+'</p>'+field('问题或整理方向','<textarea class="mw-textarea" name="question" rows="3" '+(action==='query'?'required':'')+'></textarea>'),'生成草稿');content.dataset.mode=action==='query'?'query':'synthesize';content.dataset.ids=JSON.stringify(ids);}}catch(error){if(dialog.open)fail(error.message);else notice(error.message);}});
  root.addEventListener('change',event=>{if(event.target.matches('[data-cognia-select]')){const id=event.target.dataset.cogniaSelect;if(event.target.checked&&selected.size>=5){event.target.checked=false;notice(L('最多选择 5 份材料'));return;}event.target.checked?selected.add(id):selected.delete(id);$('[data-cognia-selected]').textContent=L('已选')+' '+selected.size+' / 5';}if(event.target.matches('[data-cognia-domain],[data-cognia-source]'))void load().catch(e=>notice(e.message));});
  $('[data-cognia-search]').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>void load().catch(e=>notice(e.message)),220);});dialog.addEventListener('cancel',event=>{event.preventDefault();void close().catch(e=>fail(e.message));});
  void load().catch(e=>notice(e.message));
  return { refresh:()=>load().catch(e=>notice(e.message)) };
}`;
