export const packageDescriptor = { packageName: "@molis-ai/molis-work-plugin-cognia", packagePath: "plugins/native/cognia", kind: "native-plugin", maturity: "partial", contract: "@molis-ai/molis-work-contracts/platform/plugin", ssot: "docs/SSOT-MATRIX.md", capabilities: ["cognia.ui-contribution.v1", "cognia.knowledge.v1"] } as const;
export * from "./types.js";
export * from "./content.js";
export * from "./store.js";
export * from "./ai.js";
export * from "./routes.js";
export * from "./mcp.js";
export * from "./ui.js";
export * from "./styles.js";
export * from "./client.js";
export * from "./manifest.js";
export * from "./en.js";
