export const COGNIA_STYLES = `
[data-cognia=workbench]{container-type:inline-size;position:relative;min-height:0}
.cognia-toolbar,.cognia-selection,.cognia-filters{display:flex;align-items:center;gap:8px;flex-wrap:wrap;padding:12px 20px}
.cognia-filters{padding-bottom:4px}.cognia-filters .cognia-search{position:relative;display:flex;align-items:center;flex:1 1 240px;max-width:420px;min-width:0}.cognia-filters .cognia-search svg{position:absolute;left:10px;width:14px;height:14px;color:var(--muted);pointer-events:none}.cognia-filters .cognia-search .mw-input{width:100%;padding-left:30px}.cognia-filters{flex-wrap:wrap}.cognia-filters>.mw-select-picker{flex:0 1 180px;min-width:120px}
.cognia-selection{padding-top:8px;padding-bottom:8px}.cognia-selection>[data-cognia-selected]{color:var(--muted);font-size:12px;font-variant-numeric:tabular-nums}.cognia-selection__gap{flex:1}
body.immersive-workbench .plugin-stage-shell[data-cognia=workbench][data-expanded] .cognia-list{padding:0}.plugin-stage-shell[data-cognia=workbench][data-expanded=true] .cognia-entry{grid-template-columns:minmax(0,1fr) auto}.plugin-stage-shell[data-cognia=workbench][data-expanded=true] .cognia-entry>span:nth-child(3),.plugin-stage-shell[data-cognia=workbench][data-expanded=true] .cognia-entry>span:nth-child(4){display:none}.cognia-row:has(input:checked){background:var(--nav-active)}.cognia-toolbar.plugin-stage-chrome{position:static;top:auto;left:auto;width:auto;max-width:none;height:auto;min-height:56px;flex-wrap:wrap;z-index:auto;justify-content:flex-start}.cognia-filters{padding-top:0}.cognia-search{display:flex;align-items:center;gap:8px;flex:1;min-width:180px}.cognia-search .mw-input{width:100%}.cognia-filters select{max-width:200px}.cognia-selection{padding-top:0;color:var(--muted);font-size:12px;border-bottom:1px solid var(--line)}
.cognia-model-note{color:var(--muted);padding:0 20px;font-size:12px}.cognia-row{display:flex;align-items:center;padding:0 20px;border-bottom:1px solid var(--line);gap:12px}.cognia-row>input{flex:none}.cognia-entry{border:0;background:transparent;color:var(--ink);text-align:left;display:grid;grid-template-columns:minmax(120px,1fr) minmax(70px,.35fr) minmax(70px,.35fr) auto;gap:12px;align-items:center;min-height:60px;width:100%;cursor:pointer;padding:12px 0;font:inherit}.cognia-entry:hover{background:var(--nav-hover)}.cognia-entry strong,.cognia-entry small{display:block;overflow-wrap:anywhere}.cognia-entry small,.cognia-entry>span{font-size:12px;color:var(--muted)}.cognia-entry strong{font-size:14px;font-weight:550}.cognia-empty{padding:36px 24px;color:var(--muted);line-height:1.8}.cognia-empty strong{display:block;color:var(--ink);font-size:18px;font-weight:550}
.cognia-reading{overflow:auto;min-height:0;flex:1;padding:32px max(24px,calc((100% - 72ch)/2));line-height:1.75;overflow-wrap:anywhere}.cognia-inline-link{border:0;background:none;padding:0;color:var(--accent);font:inherit;text-decoration:underline;text-underline-offset:3px;cursor:pointer}.cognia-body blockquote{margin:16px 0;padding:0 16px;border-left:1px solid var(--line-strong);color:var(--ink-soft)}.cognia-body a{color:var(--accent);text-underline-offset:3px}.cognia-provenance{font-size:12px;color:var(--muted);margin:0 0 24px}.cognia-provenance p{margin:3px 0}.cognia-body{font-size:15px;max-width:72ch;white-space:normal}.cognia-body p{white-space:pre-wrap}.cognia-body h1{font-size:28px}.cognia-body h2{font-size:22px;margin-top:1.8em}.cognia-body h3{font-size:18px;margin-top:1.6em}.cognia-body pre,.cognia-raw{white-space:pre-wrap;overflow-wrap:anywhere;background:var(--rail);padding:16px;border-radius:8px;font-size:13px}.cognia-relations{margin-top:36px;padding-top:20px;border-top:1px solid var(--line);font-size:13px}.cognia-relations h3{font-size:14px}.cognia-relation{display:block;max-width:100%;white-space:normal;overflow-wrap:anywhere;text-align:left}.cognia-notice{padding:12px 20px;color:var(--red);background:var(--paper)}
dialog.mw-dialog.cognia-dialog{width:min(680px,calc(100vw - 24px));padding:0;max-height:calc(100dvh - 32px);color:var(--ink);background:var(--paper)}.cognia-dialog form{display:flex;flex-direction:column;max-height:calc(100dvh - 36px);min-height:0}.cognia-dialog header,.cognia-dialog footer{display:flex;justify-content:space-between;align-items:center;padding:16px 20px;gap:12px;flex:none}.cognia-dialog header{border-bottom:1px solid var(--line)}.cognia-dialog h2{font-size:20px;font-weight:550;margin:0}.cognia-dialog footer{border-top:1px solid var(--line)}.cognia-dialog footer>div{display:flex;gap:8px}.cognia-dialog-scroll{padding:20px;overflow:auto;min-height:0;flex:1}.cognia-field{display:flex;flex-direction:column;gap:7px;margin:0 0 18px;font-size:13px}.cognia-field input,.cognia-field textarea,.cognia-field select{width:100%}.cognia-field textarea{min-height:180px}.cognia-hint{color:var(--muted);font-size:12px;line-height:1.7}.cognia-error{color:var(--red);margin:0;padding:12px 20px;white-space:pre-wrap}.cognia-preview{width:100%;border-collapse:collapse;font-size:12px}.cognia-preview td,.cognia-preview th{text-align:left;border-bottom:1px solid var(--line);padding:9px 4px;vertical-align:top;overflow-wrap:anywhere}.cognia-preview td:first-child{width:55%}.cognia-preview th:nth-child(2),.cognia-preview td:nth-child(2){white-space:nowrap;min-width:4ch;width:6ch}.cognia-receipt{font-size:16px;margin:0 0 20px;line-height:1.8}.cognia-dialog details{margin:16px 0}.cognia-dialog summary{cursor:pointer;font-size:13px}.cognia-dialog footer>span{font-size:12px;color:var(--muted)}
@container(max-width:700px){.plugin-stage-shell[data-cognia=workbench][data-expanded=true] .cognia-list{display:none!important}.plugin-stage-shell[data-cognia=workbench][data-expanded=true] .cognia-workspace{position:absolute!important;inset:0!important;width:100%!important;grid-column:1/-1!important;}.cognia-toolbar,.cognia-filters,.cognia-selection{padding-left:12px;padding-right:12px}.cognia-entry{grid-template-columns:minmax(120px,1fr) auto}.cognia-entry>span:nth-child(3),.cognia-entry>span:nth-child(4){display:none}.cognia-row{padding:0 12px}.cognia-reading{padding:24px 18px}.cognia-filters select{flex:1;max-width:none;min-width:0}.cognia-search{flex-basis:100%}.cognia-workspace .plugin-stage-detail-bar{flex-wrap:wrap}.cognia-workspace .plugin-stage-detail-bar h1{flex:1;min-width:80px}.cognia-workspace .plugin-stage-detail-bar .mw-btn{min-height:44px;font-size:12px}.cognia-selection .mw-btn,.cognia-toolbar .mw-btn{min-height:44px}.cognia-filters input,.cognia-filters select{font-size:16px}}
@media(max-width:700px){.cognia-dialog input,.cognia-dialog textarea,.cognia-dialog select{font-size:16px}.cognia-dialog .mw-btn{min-height:44px}.cognia-dialog header,.cognia-dialog footer,.cognia-dialog-scroll{padding:14px}.cognia-dialog footer>span{max-width:100px}.cognia-dialog h2{font-size:18px}}

.cognia-scope { margin:0; padding:0 20px 4px; font-size:12px; color:var(--muted); }
.cognia-manage { flex-basis:100%; font-size:12px; }
.cognia-manage > summary { list-style:none; width:fit-content; cursor:pointer; }
.cognia-manage > summary::-webkit-details-marker { display:none; }
.cognia-manage > div { display:flex; flex-wrap:wrap; gap:6px; padding:6px 0; }
.cognia-empty > strong { font-size:18px; font-weight:500; }
.cognia-empty > p { line-height:1.75; margin:8px 0 18px; }
.cognia-empty .mw-btn { display:inline-flex; width:auto; margin-right:6px; }
.cognia-model-settings { width:fit-content; align-self:flex-start; margin:0 20px 8px; }
`;
