export const ALCHEMIST_EN: Record<string, string> = {
  "炼金术士": "Alchemist",
  "写下方向": "Write a direction",
  "还没有方向": "No directions yet",
  "先写下一件想炼化的事。会得到三张可比较的卡，再决定留下哪一张。": "Write what you want to refine. You get three cards to compare, then decide which to keep.",
  "内容属于当前项目，保存在这台电脑。": "These stay with the current project on this computer.",
  "返回方向列表": "Back to directions",
  "方向": "Direction",
  "你想炼化的问题": "What you want to refine",
  "例如：让独立创始人在一周内判断一个工具值不值得做": "For example: help a solo founder judge in a week whether a tool is worth building",
  "炼化": "Refine",
  "演示炼化。这三张是根据你写的方向在本机拼出来的，不是市场研究。": "Demo refine. These three cards are composed on this computer from your direction. They are not market research.",
  "上一张": "Previous",
  "下一张": "Next",
  "保留": "Keep",
  "弃牌": "Discard",
  "恢复": "Restore",
  "删除方向": "Delete direction",
  "候选": "Candidate",
  "已保留": "Kept",
  "已弃牌": "Discarded",
  "给谁": "Who",
  "场景": "Scenario",
  "问题": "Problem",
  "机制": "Mechanism",
  "价值": "Value",
  "为什么可能成立": "Why it might work",
  "假设": "Assumptions",
  "未知": "Unknowns",
  "先做": "In the first slice",
  "先不做": "Out of the first slice",
  "记下决定": "Record the decision",
  "去做": "Build",
  "先放着": "Hold",
  "不做": "Drop",
  "为什么": "Why",
  "写下为什么值得或不值得做。": "Write why it is or is not worth doing.",
  "缺少项目": "Missing project",
  "炼金术士请求失败": "Alchemist request failed",
  "删掉这个方向和它的卡？": "Delete this direction and its cards?",
  "一次搜索（含最多 3 个网页提取）或一次模型请求，各计 1 次。费用由供应商收取。": "One search (including up to 3 page extractions) or one model request counts as one call. Provider charges apply.",
  "下一步或回看条件": "Next step or revisit condition",
  "下方保留上一份报告，本次研究尚未生成新结论。": "The previous report remains below. This run has no new conclusion yet.",
  "两份研究属于当前版本。根据证据和未知，选择下一步。": "Both reports cover this version. Choose a next step based on the evidence and unknowns.",
  "个人判断偏好": "Personal preferences",
  "交叉验证": "Cross-check",
  "什么会改变判断": "What would change this judgment",
  "仅本报告": "This report only",
  "仍然未知": "Still unknown",
  "从一个具体的人和场景开始，AI 会给出不同的候选机制。": "Start with a specific person and situation. AI will suggest different approaches.",
  "以后具体怎样研究或判断": "How should future research or judgment change?",
  "作用范围": "Scope",
  "你": "You",
  "你想探索的问题": "What do you want to explore?",
  "你的意见": "Your feedback",
  "使用可用模型": "Use an available model",
  "例外": "Exceptions",
  "例外（每行一条）": "Exceptions (one per line)",
  "保存": "Save",
  "保存了决定": "Decision saved",
  "保存了研究方法": "Research method saved",
  "保存偏好": "Save preference",
  "保存并炼化": "Save and refine",
  "保存来源": "Save sources",
  "保存注释": "Save annotation",
  "保留了想法": "Idea kept",
  "保留并研究": "Keep and research",
  "保留想法或生成报告后，可以选中原文添加注释。": "Keep an idea or generate a report, then select text to annotate it.",
  "修改研究设置": "Edit research settings",
  "候选想法": "Candidate ideas",
  "偏好内容": "Preference",
  "停止研究": "Stop research",
  "停用": "Disable",
  "先在正文中选中一段文字，再打开注释。": "Select a passage in the document, then open annotations.",
  "先确认研究范围、模型和调用预算，再开始。": "Confirm scope, model, and call budget before starting.",
  "全部来源": "All sources",
  "关闭": "Close",
  "决定": "Decision",
  "决策": "Decisions",
  "决策理由": "Reason",
  "历史演示记录": "Legacy demo records",
  "原始信号": "Raw signals",
  "反例": "Negative examples",
  "正例": "Positive examples",
  "反例（每行一条）": "Negative examples (one per line)",
  "反向信号": "Counter-signals",
  "反向来源": "Counter-evidence",
  "发送": "Send",
  "取消": "Cancel",
  "只作为你的偏好，不作为市场证据。": "These guide your preferences; they are not market evidence.",
  "可以探索的机会": "Opportunities to explore",
  "启用": "Active",
  "在研究报告里选择原文、添加注释，再把反馈沉淀为方法。": "Select text in a report, annotate it, and turn the feedback into a research method.",
  "失败": "Failed",
  "实现成本": "Build cost",
  "实现成本默认调用上限": "Default build-cost call limit",
  "对方向的理解": "Understanding the direction",
  "导出 JSON": "Export JSON",
  "导出 ZIP": "Export ZIP",
  "导出失败，请重试。": "Export failed. Please retry.",
  "导出已生成。": "Export ready.",
  "导出当前项目的方向、研究、决策和讨论，不含模型凭据。": "Export this project's directions, research, decisions, and discussions without model credentials.",
  "已中断": "Interrupted",
  "已保存": "Saved",
  "已停止": "Stopped",
  "已停用": "Disabled",
  "已决定": "Decided",
  "已决策": "Decided",
  "已完成": "Completed",
  "已支持": "Supported",
  "已解决": "Resolved",
  "已采集": "Collected",
  "市场空间": "Market space",
  "市场空间默认调用上限": "Default market-space call limit",
  "市场脉搏": "Market pulse",
  "市场脉搏来源": "Market pulse sources",
  "应用次数": "Times applied",
  "应用研究方法": "Applied research methods",
  "开始炼化": "Start refining",
  "开始研究": "Start research",
  "当前对象讨论与注释": "Discussion and annotations for this item",
  "当前方向": "Current direction",
  "当前集合还没有内容。新建方向，或采集一轮市场信号开始。": "This collection is empty. Start with a direction or collect market signals.",
  "待决策": "Awaiting decision",
  "待处理": "Open",
  "待验证": "To verify",
  "恢复候选": "Restore candidate",
  "想法": "Idea",
  "想法详情": "Idea details",
  "所有后续市场研究": "All future market research",
  "打开方向": "Open direction",
  "打开模型设置": "Open model settings",
  "报告不存在。": "Report not found.",
  "排队中": "Queued",
  "搜索当前集合": "Search this collection",
  "支持来源": "Supporting source",
  "收集": "Collect",
  "新建方向": "New direction",
  "方向不存在。": "Direction not found.",
  "旧版本": "Older versions",
  "暂定": "Tentative",
  "有争议": "Disputed",
  "未完成": "Incomplete",
  "未开始": "Not started",
  "未设置": "Not set",
  "本地数据": "Local data",
  "本期观察": "Observations",
  "来源缺口": "Coverage gaps",
  "来源设置": "Source settings",
  "来源设置已保存。": "Sources saved.",
  "查看决策列表": "View decisions",
  "查看已保留想法": "View kept idea",
  "查看研究": "View research",
  "查看详情": "View details",
  "标为已解决": "Mark resolved",
  "标题": "Title",
  "校准研究方法": "Calibrate research method",
  "模型与预算": "Model and budget",
  "模型凭据由 Molis Work 管理。这里只选择研究模型和调用上限。": "Molis Work manages credentials. Choose only the research model and call limits here.",
  "正例（每行一条）": "Positive examples (one per line)",
  "正在研究，可以离开此页，稍后回来查看。": "Research is running. You can leave and return later.",
  "正在读取…": "Loading…",
  "正在采集，完成后会出现在报告列表中。": "Collecting signals. The report will appear here when ready.",
  "此前的候选": "Earlier candidates",
  "没有匹配的内容。": "No matching items.",
  "注释": "Annotations",
  "活动记录": "Activity",
  "添加了判断偏好": "Preference added",
  "添加了注释": "Annotation added",
  "添加偏好": "Add preference",
  "添加判断偏好": "Add a preference",
  "炼金术集合": "Alchemist collections",
  "生成研究计划": "Create research plan",
  "留待以后": "Save for later",
  "研究中": "Exploring",
  "研究偏好": "Research preferences",
  "研究实现成本": "Research build cost",
  "研究市场空间": "Research market space",
  "研究报告": "Reports",
  "研究摘要": "Research summary",
  "研究方法": "Research methods",
  "研究未完成。已取得的材料保留，可重新确认计划再试。": "Research did not finish. Collected material is kept. Confirm a new plan to retry.",
  "研究模型": "Research model",
  "确认保存方法": "Save method",
  "确认决定": "Confirm decision",
  "确认开始研究": "Confirm research",
  "确认研究方法": "Confirm method",
  "确认研究范围": "Confirm research scope",
  "继续讨论": "Continue the discussion",
  "综合结论": "Synthesize",
  "规划": "Plan",
  "讨论": "Discuss",
  "讨论这个方向": "Discuss this direction",
  "请先在宿主设置里配置模型。": "Configure a model in host settings first.",
  "请选择研究模型。": "Choose a research model.",
  "请重新选择原文。": "Select the original passage again.",
  "调用上限": "Call limit",
  "转为方向": "Turn into a direction",
  "返回列表": "Back to list",
  "还没有可用模型。连接模型后再炼化，已写的方向不会丢失。": "No model is available. Connect a model to refine. Your direction is saved.",
  "还没有活动记录。": "No activity yet.",
  "这次炼化未完成，方向已保存。检查模型后可重新炼化。": "Refining failed. Your direction is saved. Check the model and retry.",
  "进行中": "Running",
  "适用范围": "Applies to",
  "部分完成": "Partial",
  "采集市场信号": "Collect market signals",
  "重新炼化": "Refine again",
  "重新研究": "Research again",
  "重试": "Retry",
  "需求推断": "Demand inference",
  "预算范围内只完成了部分研究。补充研究后才能正式决策。": "Only part of the research fit within the budget. Complete the research before deciding.",
  "预览变更": "Preview changes",
};
