export const LINGGUANG_EN: Record<string, string> = {
  "灵光": "Lingguang",
  "还没有灵光": "Nothing here yet",
  "想法还没想清楚时先扔进来，再决定留下或丢掉。": "Drop a thought here before it has a place, then keep or discard it.",
  "内容属于当前项目，保存在这台电脑。": "These stay with the current project on this computer.",
  "记下": "Save",
  "标题": "Title",
  "正文": "Body",
  "清空": "Clear selection",
  "丢掉": "Discard",
  "取消": "Cancel",
  "头脑风暴": "Brainstorm",
  "分发": "Send on",
  "返回灵光列表": "Back to Lingguang",
  "缺少项目": "Missing project",
  "灵光请求失败": "Lingguang request failed",
  "保存失败": "Could not save",
  "未命名灵光": "Untitled spark",
  "条": "items",
  "已选": "Selected",
  "先写下标题或正文": "Write a title or a few words first",
  "丢掉这几条？它们会离开灵光池。": "Discard these? They will leave the pool.",
  "丢掉这条？它会离开灵光池。": "Discard this? It will leave the pool.",
  "先选至少一条": "Select at least one spark",
  "先记着：": "Noted: ",
  "发送": "Send",
  "接着往下说": "Keep going",
  "这次不会写入 Inbox 或 Goal。确认后只复制正文。": "This will not write Inbox or Goal. Confirming only copies the text.",
  "复制正文": "Copy text",
  "已复制，没有写入其他系统。": "Copied. Nothing was written elsewhere.",
  "复制失败": "Could not copy",
  "这条灵光已丢掉或不存在": "This spark was discarded or no longer exists",
  "先扔进来，还没归类也没关系。": "Drop it in. It does not need a category yet.",
  "再说一点": "A little more, if you want",
  "还没有正文": "No body yet",
  "选择这条": "Select this spark",
  "收起": "Collapse",
  "Inbox": "Inbox",
  "Goal": "Goal",
  "判断规则": "Rules",
  "本地记录": "Local record",
  "分发候选": "Send-on candidates",
  "先记下还没想清楚的想法，再决定留下或丢掉。": "Capture a thought before it has a place, then keep or discard it.",
  "这条灵光是它的来源；灵光本身留着，想好了可以丢掉": "This spark is its source. The spark stays; discard it once you're sure",
  "文档里记着它来自这条灵光；灵光本身留着，想好了可以丢掉": "The page records that it came from this spark. The spark stays; discard it once you're sure",
  "做成一篇可以继续写的文档，记着它来自这条灵光；灵光本身不变": "Turn it into a page you can keep writing, noting it came from this spark; the spark stays as it is",
  "转成文档": "Turn into page",
  "在这个位置建一个 Goal，这条灵光作为它的来源": "Create a Goal here with this spark as its source",
  "建成 Goal": "Make it a Goal",
  "交给助理": "Hand to the Assistant",
  "要助理做什么？": "What should the Assistant do?",
  "只带过去，我自己发": "Just bring it; I'll send",
  "助理只拿到这条灵光和最近几句头脑风暴，不会合并整段对话；它做的修改仍会请你确认。": "The Assistant gets this spark and the last few brainstorm lines, never the whole conversation; its changes still ask you first.",
  "头脑风暴 · 最近": "Brainstorm · last",
  "句": "lines",
  "我": "Me",
};
