export const LINGGUANG_EN: Record<string, string> = {
  "灵光": "Lingguang",
  "还没有灵光": "Nothing here yet",
  "想法还没想清楚时先扔进来，再决定留下或丢掉。": "Drop a thought here before it has a place, then keep or discard it.",
  "内容属于当前项目，保存在这台电脑。": "These stay with the current project on this computer.",
  "记下": "Save",
  "标题": "Title",
  "正文": "Body",
  "清空": "Clear selection",
  "丢掉": "Discard",
  "取消": "Cancel",
  "头脑风暴": "Brainstorm",
  "分发": "Send on",
  "返回灵光列表": "Back to Lingguang",
  "缺少项目": "Missing project",
  "灵光请求失败": "Lingguang request failed",
  "保存失败": "Could not save",
  "未命名灵光": "Untitled spark",
  "条": "items",
  "已选": "Selected",
  "先写下标题或正文": "Write a title or a few words first",
  "丢掉这几条？它们会离开灵光池。": "Discard these? They will leave the pool.",
  "丢掉这条？它会离开灵光池。": "Discard this? It will leave the pool.",
  "先选至少一条": "Select at least one spark",
  "先记着：": "Noted: ",
  "发送": "Send",
  "接着往下说": "Keep going",
  "这次不会写入 Inbox 或 Goal。确认后只复制正文。": "This will not write Inbox or Goal. Confirming only copies the text.",
  "复制正文": "Copy text",
  "已复制，没有写入其他系统。": "Copied. Nothing was written elsewhere.",
  "复制失败": "Could not copy",
  "先扔进来，还没归类也没关系。": "Drop it in. It does not need a category yet.",
  "Inbox": "Inbox",
  "Goal": "Goal",
  "Functions": "Functions",
  "分发候选": "Send-on candidates",
  "先记下还没想清楚的想法，再决定留下或丢掉。": "Capture a thought before it has a place, then keep or discard it.",
};
