export const JELLY_EN: Record<string, string> = {
  "原来选择的模型已不可用，选择仍保留。请恢复连接或重新选择模型。": "Your selected model is unavailable. The selection is retained; restore its connection or choose another model.",
  "Jelly 工作区": "Jelly workspace", "日历": "Calendar", "笔记": "Notes", "灵感": "Inspiration", "回顾": "Review",
  "撤销": "Undo", "重做": "Redo", "撤销最近一次修改": "Undo the last change", "更多": "More", "管理分类": "Manage categories",
  "导出工作区": "Export workspace", "导入工作区": "Import workspace", "上一段": "Previous", "下一段": "Next", "今天": "Today", "日历视图": "Calendar view",
  "月": "Month", "周": "Week", "列表": "List", "新建事项": "New item", "搜索标题和内容": "Search titles and content", "归档": "Archive", "隐藏已完成": "Hide completed",
  "正在打开 Jelly…": "Opening Jelly…", "返回列表": "Back to list", "拆成任务": "Break into tasks", "置顶 / 取消置顶": "Pin / unpin", "导出 Markdown": "Export Markdown",
  "永久删除笔记": "Delete note permanently", "编辑事项": "Edit item", "关闭": "Close", "标题": "Title", "要做什么？": "What needs doing?", "开始日期": "Start date",
  "结束日期": "End date", "开始时间": "Start time", "结束时间": "End time", "不填时间就是全天事项；结束日期可跨天。": "Leave times empty for an all-day item. End dates may span multiple days.",
  "分类": "Category", "优先级": "Priority", "置顶": "Pin", "重复": "Repeat", "重复截止日期": "Repeat until", "修改范围": "Apply changes to", "备注": "Notes",
  "删除事项": "Delete item", "完成事项": "Complete item", "保存": "Save", "取消": "Cancel", "确定": "Confirm", "Jelly 请求失败": "Jelly request failed",
  "操作失败，请重试": "Could not complete the action. Try again.", "Jelly 尚未加载完成": "Jelly is still loading", "其他窗口已更新。你的编辑仍保留，请核对后重新保存。": "Another window changed this workspace. Your edits are preserved. Review them before saving again.",
  "全部": "All", "新建笔记": "New note", "收集灵感": "Capture inspiration", "工作区已更新": "Workspace updated", "工作区已导出": "Workspace exported",
  "合并导入前先检查数量与影响。原工作区会保留备份；重复导入不会重复创建。": "Review the counts before importing. A backup is kept and duplicate imports are skipped.", "确认导入": "Import", "导入完成": "Import complete",
  "Jelly 暂时无法打开": "Jelly could not open", "请检查本地服务后重试。": "Check the local service and try again.", "重试": "Try again",
  "没有匹配的事项": "No matching items", "这段时间还没有安排": "Nothing scheduled yet", "点“新建事项”记下任务，或切到月历选择一天。": "Add an item or select a day in the month view.",
  "一": "Mon", "二": "Tue", "三": "Wed", "四": "Thu", "五": "Fri", "六": "Sat", "日": "Sun", "在这天添加事项": "Add an item on this day",
  "任务": "Task", "日程": "Event", "无": "None", "仅这一次": "Only this occurrence", "这次及以后": "This and future occurrences", "安排笔记任务": "Schedule note task",
  "恢复事项": "Reopen item", "关联笔记": "Linked notes", "无标题": "Untitled", "移除关联": "Remove link", "关联已有笔记": "Link an existing note", "请输入标题": "Enter a title",
  "结束日期不能早于开始日期": "End date cannot be before the start date", "事项已保存": "Item saved", "将删除这次及以后的重复事项。": "This and all future occurrences will be deleted.",
  "删除这条事项？关联笔记会保留。": "Delete this item? Linked notes will remain.", "删除": "Delete", "先在笔记中新建一篇。": "Create a note first.", "事项已移动": "Item moved",
  "分类名称": "Category name", "向上": "Move up", "新分类名称": "New category name", "添加": "Add", "删除分类后，内容移到“未分类”，不会删除事项或笔记。": "Deleting a category moves its contents to Uncategorized. Items and notes are kept.",
  "完成": "Done", "项安排": "scheduled", "已完成": "completed", "待补做": "overdue", "完成比例": "complete", "重复事项按每次发生统计；跨日事项只计一次。": "Each recurrence counts separately. Multi-day items count once.",
  "这个时间段还没有完成记录。": "No completed items in this period.", "没有逾期事项。": "No overdue items.", "没有匹配的内容": "No matching content", "还没有归档内容": "Nothing archived yet",
  "留一页给正在想的事": "Make room for your thoughts", "先把灵感放在这里": "Capture an idea here", "归档的内容会在这里，可以随时恢复。": "Archived content appears here and can be restored anytime.",
  "写下想法，添加任务块，再把它安排到日历。": "Write your thoughts, add a task block and schedule it on your calendar.", "收集文字、链接或文件，保留原始内容，再整理成笔记。": "Capture text, links or files. Keep the source and turn it into notes.",
  "完成任务块": "Complete task block", "向上移动": "Move up", "删除段落": "Delete paragraph", "已安排，查看事项": "Scheduled: view item", "安排到日历": "Schedule on calendar",
  "继续写，或输入 / 选择段落格式": "Keep writing, or type / for paragraph options", "笔记格式": "Note formatting", "正文": "Text", "项目符号": "Bullets", "编号": "Numbered list",
  "引用": "Quote", "代码": "Code", "分割线": "Divider", "粗体": "Bold", "斜体": "Italic", "行内代码": "Inline code", "链接": "Link", "恢复": "Restore",
  "添加段落": "Add paragraph", "来源链接": "Source URL", "原始文件": "Source file", "原始内容": "Source content", "粘贴原文、链接摘录或突然想到的一句话。": "Paste source text, an excerpt or a thought.",
  "导入文件": "Import file", "转为笔记": "Convert to note", "提炼摘要": "Summarize", "已保存": "Saved", "正在编辑": "Editing", "正在保存": "Saving",
  "保存失败，编辑已保留": "Save failed; edits preserved", "请先完成正在输入的文字": "Finish composing the current text first", "段落格式": "Paragraph format", "一级标题": "Heading 1", "二级标题": "Heading 2", "三级标题": "Heading 3",
  "先选中一段文字，再设置格式": "Select some text before applying formatting", "链接需要以 http:// 或 https:// 开头": "Links must start with http:// or https://",
  "关联事项": "Linked items", "解除任务联动": "Unlink task", "摘要": "Summary", "写入笔记": "Write to note", "原文已修改，这份摘要来自之前的版本。": "The source changed. This summary reflects an earlier version.",
  "将删除这篇笔记并清理关联。日历中的事项会保留。": "Delete this note and its links. Calendar items will remain.", "永久删除": "Delete permanently",
  "先生成可编辑的任务计划，确认后才会写入日历。": "Preview and edit the task plan before adding it to your calendar.", "补充要求": "Instructions", "例如：按优先级拆分，每项控制在半小时内。": "For example: order by priority, with each task under 30 minutes.",
  "按原文逐行拆分，不调用模型": "Split source lines without using a model", "生成预览": "Generate preview", "只会添加勾选的任务。标题与日期可在确认前修改。": "Only checked tasks will be added. Edit titles and dates before confirming.",
  "任务标题": "Task title", "确认任务计划": "Confirm task plan", "确认并安排": "Confirm and schedule", "至少选择一项任务": "Select at least one task", "计划已确认，任务已创建": "Plan confirmed and tasks created",
  "添加链接": "Add link", "应用": "Apply", "摘要已保存，原始内容保留": "Summary saved; source content preserved", "摘要已写入笔记": "Summary written to note", "正在读取文件内容…": "Reading file content…",
  "已读取部分内容，请核对原始文件。": "Some content was extracted. Check the source file.", "文件内容已保存": "File content saved",
  "API 格式": "API format", "下载后只用于本机转写。现在下载并继续？": "The model runs locally. Download it and continue?", "个字符": "characters", "主笔记": "Primary note",
  "任务备注与完成要求": "Notes and completion criteria", "先填写来源链接": "Enter a source URL first", "先解除日历任务联动，再删除或合并这个任务块。": "Unlink this calendar task before deleting or merging the block.",
  "先解除日历任务联动，再转换这个任务块。": "Unlink this calendar task before changing its block type.", "先选择要移动的一次性事项": "Select one-time items to move first",
  "关闭此窗口会取消读取。原始灵感不会被清空。": "Closing this window cancels extraction. The original inspiration is preserved.", "其他窗口已经修改了这篇内容。可以保留当前编辑并覆盖最新版本，或载入最新版本。": "Another window changed this content. Keep your edits and replace the latest version, or load the latest version.",
  "勾选创建任务，再决定是否安排时间。标题、完成要求和时长都可以调整。": "Choose which tasks to create, then whether to schedule them. Edit titles, completion criteria and durations.", "参考笔记": "Reference note", "参考": "Reference",
  "填写服务地址和模型 ID": "Enter a service URL and model ID", "复制事项": "Duplicate item", "完成说明": "Completion notes", "导入笔记内容": "Import note content", "导出 HTML": "Export HTML",
  "将随记整理为笔记": "Turn item notes into a note", "已复制为独立事项": "Duplicated as an independent item", "恢复继承系列笔记": "Restore inherited series notes", "所选事项已移动": "Selected items moved",
  "提炼摘要或拆解时，原文会发送给所选模型。保存设置不会发送内容。": "Summarizing and planning send source content to the selected model. Saving settings does not send content.", "搬到下周": "Move to next week", "搬到下月": "Move to next month",
  "摘要与拆解模型": "Summary and planning model", "整个系列": "Entire series", "新建主笔记": "New primary note", "新灵感": "New inspiration", "日期格式应为 YYYY-MM-DD": "Use YYYY-MM-DD for dates",
  "时长需要在 15 到 720 分钟之间": "Duration must be between 15 and 720 minutes", "时长（分钟）": "Duration (minutes)", "时间格式应为 HH:MM": "Use HH:MM for times",
  "替换当前内容（默认追加到末尾）": "Replace current content (otherwise append)", "服务地址": "Service URL", "本周": "This week", "本月": "This month", "来源内容已保存": "Source content saved",
  "来源读取失败": "Could not read source", "来源读取没有返回结果": "Source extraction returned no result", "模型 ID": "Model ID", "模型设置已保存": "Model settings saved", "正在读取来源…": "Reading source…",
  "每个事项有一篇主笔记。替换主笔记会解除原主笔记关系，正文仍保留。": "Each item has one primary note. Replacing it removes the old link but keeps the note.", "清空选择": "Clear selection", "留空保留已有密钥": "Leave empty to keep the existing key",
  "移动到日期": "Move to date", "移动所选": "Move selected", "笔记内容已导入": "Note content imported", "自定义模型": "Custom model", "记录完成了什么，或留下结果链接。": "Record what was completed, or add a result link.",
  "读取已取消，原始内容保留": "Extraction canceled; source preserved", "转写需要下载本机语音模型。": "Transcription needs a local speech model download.", "载入最新版本": "Load latest version", "保留我的编辑": "Keep my edits",
  "这个时间段没有对应记录。": "No matching records in this period.", "选择一个模型，或填写自定义模型": "Select a model or configure a custom model", "选择事项": "Select item",
  "选择新建笔记，或追加到已有笔记。成功后清空此事项的旧随记，并关联为主笔记。": "Create a note or append to an existing note. The item’s old notes are cleared after success and linked as its primary note.",
  "重新读取来源": "Read source again", "随记已整理为笔记": "Item notes converted", "项已选择": "selected", "编辑版本冲突": "Editing conflict", "移动所选事项": "Move selected items", "移动": "Move",
  "保存模型设置": "Save model settings", "还没有可用模型。可以填写已有服务的地址和密钥。": "No model is available. Enter your service URL and key.", "已有模型配置；可在这里切换 Jelly 使用的模型。": "A model is configured. Choose which one Jelly should use.",
  "配置后即可提炼摘要和拆解。按原文逐行拆分无需模型。": "Configure a model to summarize and plan. Splitting source lines works without a model.", "未完成": "Open", "延期": "Overdue", "高优先级": "High priority", "分类分布": "By category",
  "永久删除灵感": "Delete inspiration permanently", "已转为笔记，原始内容保持不变。": "Converted to a note. The original content is preserved.", "打开关联笔记": "Open linked note",
  "发现一份未保存草稿。当前显示的是已保存版本。": "An unsaved draft was found. The saved version is shown.", "恢复草稿": "Recover draft", "丢弃草稿": "Discard draft", "只拆解当前选中文字": "Plan from selected text only",
  "删除原始灵感及摘要；已经写入的笔记会保留。": "Delete the inspiration and summary. Existing notes will remain.", "读取来源": "Read source", "整理内容": "Process content", "下载语音模型": "Download speech model", "下载并继续": "Download and continue",
  "正在提取内容": "Extracting content", "正在下载转写模型": "Downloading speech model", "正在转写音频": "Transcribing audio", "正在加载模型": "Loading model", "正在识别文字": "Recognizing text", "正在读取视频画面": "Reading video frames", "正在读取网页": "Reading webpage", "正在提炼内容": "Summarizing content",
  "链接块": "Link block", "原文": "Source", "页": "Page", "图片": "Image", "段落": "Paragraph", "已覆盖来源": "Source covered", "部分覆盖": "Partial coverage", "覆盖不足": "Insufficient coverage", "个来源片段": "source segments",
  "要点": "Key points", "原文摘录": "Source excerpts", "未采用的内容": "Omitted content", "查看来源片段": "View source segments", "创建任务": "Create task", "局部重拆": "Refine this task", "移除候选": "Remove candidate",
  "还有这些问题需要你确认；可以在下方补充后重新拆解。": "These questions need clarification. Add context below and regenerate the plan.", "补充背景或回答上面的问题，再重新拆解。": "Add context or answer the questions, then regenerate.",
  "重新拆解": "Regenerate plan", "重新拆解时保留字段": "Keep fields when regenerating", "完成要求": "Completion criteria", "时长": "Duration", "安排时间": "Scheduled time", "请输入任务标题": "Enter a task title", "全天": "All day", "新建全天事项": "New all-day item",
  "这份文件没有可重读的副本，请重新选择文件。": "No stored copy is available. Select the file again.", "新提取的正文与已关联笔记的原文不同。原始内容保留，请新建灵感接收这份新内容。": "The extracted text differs from the source linked to a note. The original is preserved. Create a new inspiration for the new content.", "文件不能超过 25 MB": "Files must be no larger than 25 MB",
};
