export const JELLY_STYLES = `
  [data-jelly="workbench"] { --plugin-tint: var(--plugin-schedule, var(--accent)); position: relative; }
  body.immersive-workbench .plugin-stage-shell[data-jelly="workbench"] { display: grid; grid-template-columns: minmax(0, 1fr); grid-template-rows: auto minmax(0, 1fr); }
  body.immersive-workbench .plugin-stage-shell[data-jelly="workbench"][data-expanded="true"] { grid-template-columns: minmax(220px, 27%) minmax(0, 1fr); }
  .jelly-header { grid-column: 1 / -1; display:flex; align-items:center; justify-content:space-between; min-height:48px; padding:8px 16px; gap:12px; border-bottom:1px solid var(--line); }
  .jelly-tabs,.jelly-header-actions,.jelly-toolbar,.jelly-toolbar-end,.jelly-period,.jelly-filters,.jelly-category-filters,.jelly-choice-row { display:flex; align-items:center; gap:6px; }
  .jelly-tabs { flex-wrap:wrap; }
  .jelly-tabs .mw-btn[aria-current="page"],.jelly-choice-row .mw-btn[aria-pressed="true"],.jelly-category-filters .mw-btn[aria-pressed="true"],.jelly-calendar-modes .mw-btn[aria-pressed="true"] { background:var(--nav-active); color:var(--ink); }
  .jelly-header-actions { position:relative; }
  .jelly-global-menu,.jelly-editor-menu { position:absolute; right:8px; top:100%; z-index:50; min-width:180px; }
  body.immersive-workbench [data-jelly="workbench"] > .jelly-main.plugin-stage-list { position:relative; inset:auto; width:100%; max-width:none; min-width:0; margin:0; justify-self:stretch; box-sizing:border-box; padding:16px 20px 24px; overflow:auto; grid-column:1; grid-row:2; }
  .jelly-toolbar { justify-content:space-between; margin-bottom:14px; flex-wrap:wrap; }
  .jelly-toolbar h1 { font-size:19px; font-weight:400; margin:0 8px 0 0; letter-spacing:-.02em; white-space:nowrap; }
  .jelly-period .mw-btn:has(svg) span { display:none; }
  .jelly-toolbar-end { flex-wrap:wrap; }
  .jelly-calendar-modes { display:flex; padding:2px; border:1px solid var(--hairline); border-radius:9px; background:var(--control-fill); }
  .jelly-calendar-modes .mw-btn { min-width:36px; }
  .jelly-filters { gap:10px; margin-bottom:16px; flex-wrap:wrap; }
  .jelly-search { width:220px; max-width:100%; }
  .jelly-category-filters { flex:1; flex-wrap:wrap; }
  .jelly-category-filters .mw-btn { font-size:12px; gap:5px; }
  .jelly-color { flex:none; width:7px; height:7px; border-radius:50%; background:var(--muted); }
  .jelly-color[data-tone="red"] { background:var(--red); }.jelly-color[data-tone="green"] { background:var(--green); }.jelly-color[data-tone="amber"] { background:var(--amber); }.jelly-color[data-tone="blue"] { background:var(--accent); }.jelly-color[data-tone="purple"] { background:var(--hue-violet,var(--accent)); }.jelly-color[data-tone="teal"] { background:var(--tone-hold); }
  .jelly-muted,.jelly-field-hint { color:var(--muted); font-size:12px; line-height:1.6; }
  [data-jelly="workbench"] .jelly-content { min-height:260px; width:100%; max-width:none; margin:0; }
  .jelly-month { display:grid; grid-template-columns:repeat(7,minmax(0,1fr)); border-left:1px solid var(--line); border-top:1px solid var(--line); border-radius:8px; overflow:hidden; }
  .jelly-week-label { text-align:center; color:var(--muted); font-size:11px; padding:8px; border-bottom:1px solid var(--line); border-right:1px solid var(--line); background:var(--nav-bg); }
  .jelly-day { min-height:116px; padding:6px 4px; border-right:1px solid var(--line); border-bottom:1px solid var(--line); min-width:0; transition:background var(--motion-fast) var(--ease-standard); }
  .jelly-day.is-outside { background:var(--nav-bg); }.jelly-day.is-outside .jelly-day-number { color:var(--faint); }
  .jelly-day.is-drop { background:var(--accent-soft); box-shadow:inset 0 0 0 1px var(--focus-stroke); }
  .jelly-day-head { display:flex; align-items:center; justify-content:space-between; margin-bottom:4px; }
  .jelly-day-number { display:grid; place-items:center; min-width:26px; min-height:26px; padding:0; color:var(--ink-soft); border:0; border-radius:7px; background:transparent; cursor:pointer; font-size:12px; }
  .jelly-day-number:hover { background:var(--nav-hover); }.jelly-day.is-today .jelly-day-number { color:var(--action-ink); background:var(--action); }
  .jelly-day-add { opacity:0; color:var(--muted); padding:0 4px; min-width:22px; height:24px; }.jelly-day-add span { display:none; }.jelly-day:hover .jelly-day-add,.jelly-day:focus-within .jelly-day-add { opacity:1; }
  .jelly-occurrence { display:flex; align-items:center; gap:4px; width:100%; min-width:0; margin:2px 0; padding:4px 5px; background:var(--nav-hover); border:0; border-radius:5px; color:var(--ink); text-align:left; font-size:11px; cursor:pointer; }
  .jelly-occurrence:hover { background:var(--nav-active); }.jelly-occurrence.is-done { color:var(--faint); }.jelly-occurrence.is-done .jelly-item-title { text-decoration:line-through; }
  .jelly-occurrence .jelly-item-title { white-space:nowrap; overflow:hidden; text-overflow:ellipsis; flex:1; }
  .jelly-occurrence time { color:var(--muted); font-variant-numeric:tabular-nums; font-size:10px; }.jelly-occurrence svg { width:11px; height:11px; flex:none; }
  .jelly-priority { font-size:10px; color:var(--amber); }.jelly-priority[data-priority="P0"] { color:var(--red); }
  .jelly-week { display:grid; grid-template-columns:repeat(7,minmax(100px,1fr)); min-width:700px; border-left:1px solid var(--line); border-top:1px solid var(--line); }.jelly-week .jelly-day { min-height:420px; }.jelly-week .jelly-day-head { justify-content:center; gap:8px; }.jelly-week .jelly-occurrence { min-height:40px; flex-wrap:wrap; }
  .jelly-week-timeline { display:grid; grid-template-columns:48px repeat(7,minmax(100px,1fr)); min-width:748px; border:1px solid var(--line); border-radius:7px; overflow:hidden; }.jelly-week-timeline .jelly-week-column { padding:0; border-bottom:0; border-top:0; min-height:0; }.jelly-week-column-head { height:44px; display:flex; align-items:center; justify-content:center; gap:8px; background:var(--nav-bg); border-bottom:1px solid var(--line); }.jelly-week-all-day { height:104px; overflow:auto; padding:5px; border-bottom:1px solid var(--line-strong); }.jelly-week-time { height:1056px; position:relative; background:repeating-linear-gradient(to bottom,transparent 0,transparent 43px,var(--line) 43px,var(--line) 44px); }.jelly-week-event { position:absolute; padding:1px 2px; box-sizing:border-box; overflow:hidden; }.jelly-week-event .jelly-occurrence { margin:0; height:100%; min-height:22px; align-items:flex-start; flex-wrap:wrap; line-height:1.35; background:var(--nav-active); overflow:hidden; }.jelly-week-event .jelly-item-title { white-space:normal; min-width:35px; }.jelly-week-event .jelly-occurrence time { display:block; font-size:10px; }.jelly-week-ruler { color:var(--faint); border-right:1px solid var(--line); }.jelly-week-ruler-head { display:flex; justify-content:center; align-items:center; height:148px; border-bottom:1px solid var(--line-strong); font-size:10px; }.jelly-week-hours { height:1056px; position:relative; }.jelly-week-hours span { position:absolute; right:6px; font-size:10px; font-variant-numeric:tabular-nums; transform:translateY(-50%); }.jelly-week-hours span:first-child { transform:none; }
  .jelly-agenda { max-width:64rem; }.jelly-agenda-group { margin:0 0 22px; }.jelly-agenda-group h2 { margin:0 0 8px; color:var(--muted); font-size:12px; font-weight:400; }
  .jelly-agenda-row { display:flex; align-items:center; gap:10px; border-bottom:1px solid var(--line); padding:8px 2px; }.jelly-agenda-row .jelly-occurrence { margin:0; background:none; font-size:13px; min-height:28px; padding:0; }.jelly-agenda-row .jelly-occurrence time { width:80px; font-size:12px; }.jelly-agenda-row .jelly-item-title { flex:1; }.jelly-agenda-row .mw-btn { flex:none; }
  .jelly-rows { max-width:54rem; }.jelly-row { display:flex; align-items:center; gap:12px; width:100%; padding:12px 8px; border:0; border-bottom:1px solid var(--line); background:transparent; color:var(--ink); text-align:left; cursor:pointer; }.jelly-row:hover { background:var(--nav-hover); }.jelly-row.is-selected { background:var(--nav-active); }.jelly-row-main { flex:1; min-width:0; }.jelly-row strong { display:block; font-size:14px; font-weight:400; }.jelly-row p { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; margin:4px 0 0; color:var(--muted); font-size:12px; }.jelly-row-meta { display:flex; align-items:center; gap:7px; color:var(--faint); font-size:11px; }.jelly-row-meta svg { width:13px; height:13px; }
  .jelly-empty { max-width:38ch; padding:44px 12px; color:var(--muted); font-size:13px; }.jelly-empty h2 { font-size:19px; font-weight:400; color:var(--ink); margin:12px 0 8px; }.jelly-empty svg { width:24px; height:24px; }
  body.immersive-workbench [data-jelly="workbench"] > .jelly-detail.plugin-stage-workspace { grid-column:2; grid-row:2; min-width:0; display:flex; flex-direction:column; border-left:1px solid var(--line); position:relative; }
  [data-jelly="workbench"][data-expanded="true"] .jelly-main .jelly-period,[data-jelly="workbench"][data-expanded="true"] .jelly-calendar-modes,[data-jelly="workbench"][data-expanded="true"] .jelly-category-filters { display:none; }
  [data-jelly="workbench"][data-expanded="true"] .jelly-main .jelly-search { width:100%; }.jelly-detail .plugin-stage-detail-bar { flex:none; }.jelly-save-status { color:var(--faint); font-size:11px; white-space:nowrap; }
  .jelly-document { padding:28px clamp(16px,4vw,48px) 72px; overflow:auto; flex:1; min-height:0; }.jelly-document-title { width:100%; border:0; box-shadow:none; background:transparent; color:var(--ink); padding:0; font-size:28px; font-weight:400; letter-spacing:-.03em; line-height:1.5; outline:none; }.jelly-document-meta { display:flex; gap:6px; flex-wrap:wrap; margin:8px 0 20px; }.jelly-format-bar { display:flex; flex-wrap:wrap; gap:4px; padding:8px 0; border-bottom:1px solid var(--line); margin-bottom:12px; position:sticky; top:-28px; z-index:2; background:var(--paper); }.jelly-format-bar .mw-btn { font-size:11px; min-width:28px; padding:0 7px; }
  .jelly-block { display:flex; gap:7px; align-items:flex-start; margin:4px 0; padding:0; position:relative; }.jelly-block-text { min-width:0; flex:1; width:100%; resize:none; overflow:hidden; border:0; background:transparent; color:var(--ink); font:inherit; font-size:14px; line-height:1.7; padding:3px 0; outline:none; box-shadow:none; }.jelly-block-text:focus-visible { box-shadow:0 1px 0 var(--focus-stroke); }.jelly-block[data-kind="heading1"] .jelly-block-text { font-size:25px; }.jelly-block[data-kind="heading2"] .jelly-block-text { font-size:21px; }.jelly-block[data-kind="heading3"] .jelly-block-text { font-size:17px; }.jelly-block[data-kind="quote"] { border-left:2px solid var(--line-strong); padding-left:12px; }.jelly-block[data-kind="code"] { padding:8px 12px; background:var(--nav-bg); border-radius:6px; }.jelly-block[data-kind="code"] .jelly-block-text { font-family:monospace; font-size:12px; }.jelly-block.is-completed .jelly-block-text { text-decoration:line-through; color:var(--faint); }.jelly-block-mark { flex:none; color:var(--muted); padding-top:5px; }.jelly-block .mw-checkbox { margin-top:8px; }.jelly-block-tools { display:flex; opacity:0; flex:none; padding-top:3px; }.jelly-block:focus-within .jelly-block-tools,.jelly-block:hover .jelly-block-tools { opacity:1; }.jelly-block-tools .mw-btn { padding:0 4px; height:24px; min-width:24px; }.jelly-block-tools svg { width:13px; height:13px; }.jelly-block-divider { flex:1; margin:14px 0; border:0; border-top:1px solid var(--line); }.jelly-linked-task { color:var(--accent); opacity:1; }
  .jelly-material-body { width:100%; min-height:260px; line-height:1.75; resize:vertical; }.jelly-material-tools { display:flex; flex-wrap:wrap; gap:8px; margin:12px 0; }.jelly-digest { margin:24px 0; padding:16px 0; border-top:1px solid var(--line); }.jelly-digest h2 { font-size:16px; font-weight:400; }.jelly-digest p { white-space:pre-wrap; line-height:1.7; font-size:13px; }
  .jelly-notice { position:absolute; bottom:18px; left:50%; transform:translateX(-50%); z-index:100; max-width:min(620px,calc(100% - 32px)); margin:0; padding:10px 14px; border-radius:8px; background:var(--action); color:var(--action-ink); font-size:12px; box-shadow:0 3px 16px var(--scrim); }.jelly-notice.is-error { background:var(--red); }
  .jelly-item-dialog { width:min(540px,calc(100vw - 24px)); max-height:calc(100vh - 32px); overflow:auto; }.jelly-generic-dialog { width:min(660px,calc(100vw - 24px)); max-height:calc(100vh - 32px); overflow:auto; }.jelly-dialog-form { display:flex; flex-direction:column; gap:14px; padding:20px; }.jelly-dialog-form header,.jelly-dialog-form footer { display:flex; align-items:center; justify-content:space-between; gap:10px; }.jelly-dialog-form header h2 { font-size:18px; font-weight:400; margin:0; }.jelly-dialog-form footer { border-top:1px solid var(--line); padding-top:14px; margin-top:4px; }.jelly-dialog-form footer > div { display:flex; gap:6px; }.jelly-dialog-form header > .mw-btn span { display:none; }.jelly-field { display:flex; flex-direction:column; gap:6px; font-size:12px; color:var(--muted); margin:0; padding:0; border:0; min-width:0; }.jelly-field legend { padding:0; margin-bottom:6px; }.jelly-form-grid { display:grid; grid-template-columns:1fr 1fr; gap:12px; }.jelly-check { display:flex; gap:8px; align-items:center; color:var(--ink-soft); font-size:12px; }.jelly-choice-row { flex-wrap:wrap; }.jelly-choice-row .mw-btn { min-height:28px; font-size:12px; }.jelly-until { margin-top:8px; }.jelly-field-hint { margin:-6px 0 0; }.jelly-form-error { color:var(--red); margin:0; font-size:12px; white-space:pre-wrap; }.jelly-item-relations { display:flex; flex-direction:column; gap:5px; font-size:12px; }.jelly-item-relations .mw-btn { justify-content:flex-start; }.jelly-category-row { display:flex; align-items:center; gap:8px; margin:10px 0; }.jelly-category-row .mw-input { flex:1; min-width:0; }.jelly-category-palette { display:flex; gap:4px; }.jelly-category-palette .mw-btn { padding:0 5px; min-width:24px; }.jelly-plan-action { padding:12px 0; border-bottom:1px solid var(--line); display:flex; gap:10px; align-items:flex-start; }.jelly-plan-action > div { flex:1; }.jelly-plan-action p { font-size:12px; color:var(--muted); line-height:1.6; margin:6px 0; }.jelly-plan-action .mw-input { width:100%; }.jelly-review-summary { display:flex; align-items:baseline; gap:24px; margin:22px 0; flex-wrap:wrap; }.jelly-review-summary strong { font-size:32px; font-weight:400; letter-spacing:-.04em; }.jelly-review-summary span { color:var(--muted); font-size:12px; }.jelly-progress-track { height:5px; width:100%; background:var(--line); border-radius:4px; overflow:hidden; }.jelly-progress-track > span { display:block; height:100%; background:var(--green); }.jelly-review-section { margin-top:28px; }.jelly-review-section h2 { font-size:15px; font-weight:400; }
  @media(max-width:1000px) { .jelly-header-actions .mw-btn span { display:none; }.jelly-filters { gap:6px; }.jelly-category-filters { flex-basis:100%; }.jelly-day { min-height:100px; }.jelly-occurrence time { display:none; } }
  @media(max-width:760px) { body.immersive-workbench .plugin-stage-shell[data-jelly="workbench"][data-expanded="true"] { grid-template-columns:minmax(0,1fr); } body.immersive-workbench [data-jelly="workbench"][data-expanded="true"] > .jelly-main { display:none; } body.immersive-workbench [data-jelly="workbench"] > .jelly-detail.plugin-stage-workspace { grid-column:1; border:0; } .jelly-header { padding:4px 8px; gap:4px; }.jelly-tabs { gap:0; }.jelly-tabs .mw-btn { padding:0 8px; }.jelly-tabs .mw-btn svg { display:none; }.jelly-header-actions { gap:0; }.jelly-header-actions [data-jelly-undo],.jelly-header-actions [data-jelly-redo] { display:none; } body.immersive-workbench [data-jelly="workbench"] > .jelly-main.plugin-stage-list { padding:12px 8px; }.jelly-toolbar h1 { font-size:17px; }.jelly-toolbar { gap:10px; }.jelly-toolbar-end { width:100%; justify-content:space-between; }.jelly-day { min-height:92px; padding:3px 2px; }.jelly-day-add { display:none; }.jelly-day-number { min-height:32px; }.jelly-occurrence { padding:4px 2px; font-size:10px; }.jelly-occurrence .jelly-color,.jelly-occurrence .jelly-priority { display:none; }.jelly-month { min-width:340px; }.jelly-content { overflow-x:auto; }.jelly-tabs .mw-btn,.jelly-toolbar .mw-btn,.jelly-dialog-form .mw-btn,.jelly-detail .plugin-stage-detail-bar .mw-btn { min-height:40px; }.jelly-document { padding:20px 16px 64px; }.jelly-document-title { font-size:26px; }.jelly-block-text,.jelly-material-body { font-size:16px; }.jelly-block-tools { opacity:1; }.jelly-detail .plugin-stage-detail-bar [data-jelly-archive] { display:none; }.jelly-category-row { flex-wrap:wrap; }.jelly-form-grid { gap:8px; } }
  .jelly-block-text { white-space:pre-wrap; overflow-wrap:anywhere; min-height:30px; }
  .jelly-block-text:empty::before { content:attr(data-placeholder); color:var(--faint); pointer-events:none; }
  .jelly-block-text strong { font-weight:600; }.jelly-block-text code { font-family:monospace; padding:1px 3px; background:var(--nav-bg); border-radius:3px; }.jelly-block-text a { color:var(--accent); text-decoration:underline; }
  .jelly-date-picker { position:relative; width:100%; }.jelly-date-picker .mw-calendar { display:none; position:absolute; left:0; top:calc(100% + 5px); width:268px; z-index:60; background:var(--paper); border:1px solid var(--line); box-shadow:0 5px 20px var(--scrim); }.jelly-date-picker .mw-calendar.is-open { display:block; }.jelly-date-picker .mw-calendar__header { gap:4px; }.jelly-date-picker .mw-calendar__header .mw-btn { min-width:24px; }.jelly-date-picker .mw-calendar__grid { width:100%; }
  .jelly-note-backlinks { margin-top:24px; border-top:1px solid var(--line); padding-top:12px; }
  .jelly-import-preview { max-height:240px; overflow:auto; white-space:pre-wrap; font-size:12px; line-height:1.6; padding:12px; background:var(--nav-bg); border-radius:6px; color:var(--ink-soft); }
  .jelly-draft-recovery { padding:10px 12px; margin-bottom:16px; border:1px solid var(--line-strong); border-radius:8px; font-size:12px; }.jelly-draft-recovery p { margin:0 0 6px; }.jelly-extract-progress { width:100%; accent-color:var(--accent); }
  .jelly-material-coverage { display:flex; flex-wrap:wrap; align-items:center; gap:8px; }.jelly-material-coverage p { flex-basis:100%; margin:0; }.jelly-digest h3 { font-size:13px; font-weight:400; color:var(--muted); margin:20px 0 8px; }.jelly-evidence-links { display:inline-flex; flex-wrap:wrap; gap:3px; margin-left:6px; vertical-align:middle; }.jelly-evidence-links .mw-btn { min-height:22px; font-size:10px; padding:0 5px; color:var(--accent); }.jelly-evidence-links svg { width:10px; height:10px; }.jelly-source-details { margin:14px 0; font-size:13px; }.jelly-source-details summary { cursor:pointer; padding:6px 0; }.jelly-source-details article { border-left:1px solid var(--line); padding-left:12px; margin:12px 0; }.jelly-digest blockquote { border-left:2px solid var(--line-strong); margin:12px 0; padding-left:12px; white-space:pre-wrap; font-size:13px; }
  .jelly-bulk-bar { display:flex; flex-wrap:wrap; gap:6px; align-items:center; margin:8px 0 18px; }.jelly-bulk-bar > span { margin-right:auto; }.jelly-review-tabs { display:flex; flex-wrap:wrap; gap:6px; margin:16px 0; }.jelly-review-tabs [aria-pressed="true"] { background:var(--nav-active); }
  .jelly-plan-row-tools { display:flex; gap:4px; align-items:center; margin-bottom:6px; }.jelly-plan-row-tools > span { margin-right:auto; }.jelly-plan-row-tools .mw-btn { font-size:11px; min-height:24px; }.jelly-plan-refine { display:flex; gap:8px; align-items:flex-end; margin-bottom:14px; }.jelly-plan-refine .mw-textarea { flex:1; min-width:0; }.jelly-plan-locks { font-size:11px; color:var(--muted); margin-top:10px; }.jelly-plan-locks summary { cursor:pointer; }.jelly-plan-locks .jelly-choice-row { margin-top:6px; }.jelly-plan-questions { font-size:13px; padding:12px; border:1px solid var(--line); border-radius:8px; }
  @media(pointer:coarse) { .jelly-day-add { display:inline-flex; opacity:1; min-width:30px; min-height:30px; } }
  @media(prefers-reduced-motion:reduce) { [data-jelly="workbench"] * { scroll-behavior:auto; transition:none; animation:none; } }
`;
