//! System clipboard watch. Copying text or a link anywhere on this Mac records
//! a clipboard entry; copying local files shelves the files themselves and
//! leaves the history alone. Concealed and transient types are never recorded.

use crate::shelf_http;
use tauri::AppHandle;
use objc2_app_kit::NSPasteboard;
use objc2_foundation::{ns_string, NSArray, NSString};
use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::mpsc;
use std::thread;
use std::time::Duration;

static RUNNING: AtomicBool = AtomicBool::new(false);
/// macOS may hand a background app the change count but no content. Once that
/// happens the Shelf says so instead of pretending the watch works.
static READABLE: AtomicBool = AtomicBool::new(true);

pub fn clipboard_readable() -> bool {
    READABLE.load(Ordering::Relaxed)
}

const POLL: Duration = Duration::from_millis(700);

pub fn install(app: AppHandle) {
    if RUNNING.swap(true, Ordering::SeqCst) {
        return;
    }
    // AppKit reads happen on the main thread; the shelf call that follows is
    // blocking HTTP, so it stays on this one.
    thread::spawn(move || {
        let mut seen = on_main(&app, current_change_count).unwrap_or(-1);
        loop {
            thread::sleep(POLL);
            let Some(change) = on_main(&app, current_change_count) else { continue };
            if change == seen {
                continue;
            }
            seen = change;
            let Some(Some(cargo)) = on_main(&app, read_pasteboard) else { continue };
            take(cargo);
        }
    });
}

/// Run `read` on the main thread and wait for its answer.
fn on_main<T: Send + 'static>(app: &AppHandle, read: fn() -> T) -> Option<T> {
    let (sender, receiver) = mpsc::channel();
    app.run_on_main_thread(move || {
        let _ = sender.send(read());
    })
    .ok()?;
    receiver.recv_timeout(Duration::from_secs(3)).ok()
}

struct Cargo {
    files: Vec<PathBuf>,
    text: Option<String>,
    types: Vec<String>,
}

fn take(cargo: Cargo) {
    if is_concealed(&cargo.types) {
        return;
    }
    let empty = cargo.files.is_empty()
        && cargo.text.as_deref().map(str::trim).is_none_or(str::is_empty);
    READABLE.store(!empty, Ordering::Relaxed);
    if empty {
        return;
    }
    // Files copied elsewhere go straight to materials; they never take a
    // clipboard slot, same as DropAgent.
    if !cargo.files.is_empty() {
        for path in &cargo.files {
            if let Err(error) = shelf_http::admit_file(path) {
                eprintln!("Molis Work 没能收下复制的文件：{error}");
            }
        }
        return;
    }
    let Some(text) = cargo.text.as_deref().map(str::trim).filter(|value| !value.is_empty()) else {
        return;
    };
    if let Err(error) = shelf_http::record_clip(text, &cargo.types) {
        eprintln!("Molis Work 没能记下剪贴板：{error}");
    }
}

fn is_concealed(types: &[String]) -> bool {
    types.iter().any(|value| {
        let lower = value.to_ascii_lowercase();
        lower.contains("org.nspasteboard.concealedtype")
            || lower.contains("org.nspasteboard.transienttype")
            || lower.contains("org.nspasteboard.autogeneratedtype")
    })
}

fn current_change_count() -> isize {
    let Some(board) = general_board() else { return -1 };
    unsafe { board.changeCount() }
}

fn general_board() -> Option<objc2::rc::Retained<NSPasteboard>> {
    Some(unsafe { NSPasteboard::generalPasteboard() })
}

fn read_pasteboard() -> Option<Cargo> {
    let board = general_board()?;
    let types: Vec<String> = unsafe { board.types() }
        .map(|array| array.iter().map(|item| item.to_string()).collect())
        .unwrap_or_default();
    let mut files: Vec<PathBuf> = Vec::new();
    unsafe {
        if let Some(list) = board.propertyListForType(ns_string!("NSFilenamesPboardType")) {
            if let Ok(array) = list.downcast::<NSArray>() {
                for item in array.iter() {
                    if let Some(name) = item.downcast_ref::<NSString>() {
                        let path = PathBuf::from(name.to_string());
                        if path.is_file() {
                            files.push(path);
                        }
                    }
                }
            }
        }
        if files.is_empty() {
            if let Some(url) = board.stringForType(ns_string!("public.file-url")) {
                if let Some(path) = path_from_file_url(&url.to_string()) {
                    files.push(path);
                }
            }
        }
    }
    // `stringForType:` comes back empty for some writers, so read the bytes.
    let text = unsafe {
        board
            .dataForType(ns_string!("public.utf8-plain-text"))
            .or_else(|| board.dataForType(ns_string!("NSStringPboardType")))
    }
    .map(|data| String::from_utf8_lossy(data.to_vec().as_slice()).to_string())
    .filter(|value| !value.is_empty())
    .or_else(|| unsafe {
        board
            .stringForType(ns_string!("public.utf8-plain-text"))
            .map(|value| value.to_string())
    });
    Some(Cargo { files, text, types })
}

fn path_from_file_url(value: &str) -> Option<PathBuf> {
    let rest = value.strip_prefix("file://")?;
    let path = rest.split('?').next().unwrap_or(rest);
    let decoded = percent_decode(path);
    let candidate = PathBuf::from(decoded);
    candidate.is_file().then_some(candidate)
}

fn percent_decode(value: &str) -> String {
    let bytes = value.as_bytes();
    let mut out: Vec<u8> = Vec::with_capacity(bytes.len());
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index] == b'%' && index + 2 < bytes.len() {
            let hex = std::str::from_utf8(&bytes[index + 1..index + 3]).ok();
            if let Some(byte) = hex.and_then(|value| u8::from_str_radix(value, 16).ok()) {
                out.push(byte);
                index += 3;
                continue;
            }
        }
        out.push(bytes[index]);
        index += 1;
    }
    String::from_utf8_lossy(&out).to_string()
}

#[cfg(test)]
mod tests {
    use super::{is_concealed, path_from_file_url, percent_decode};

    #[test]
    fn password_managers_are_never_recorded() {
        assert!(is_concealed(&["org.nspasteboard.ConcealedType".into()]));
        assert!(is_concealed(&["public.utf8-plain-text".into(), "org.nspasteboard.TransientType".into()]));
        assert!(!is_concealed(&["public.utf8-plain-text".into()]));
    }

    #[test]
    fn a_file_url_becomes_a_path_only_when_the_file_is_there() {
        assert_eq!(percent_decode("/tmp/a%20b.pdf"), "/tmp/a b.pdf");
        assert_eq!(path_from_file_url("https://example.com"), None);
        assert_eq!(path_from_file_url("file:///definitely/not/here.pdf"), None);
    }
}
