export const WORKFLOWS_EN: Record<string, string> = {
  "先恢复不可用的站点，再开始第一次。": "Restore the unavailable stations before starting the first run.",
  "模板转换": "Template transform",
  "工作流程": "Workflows",
  "工作流程请求失败": "Workflow request failed",
  "还没有站": "No stations yet",
  "还没有工作流程": "No workflows yet",
  "把已有插件按顺序串起来，定好上一步的结果怎样交给下一步。每走一次都会留下这一次自己的内容。": "Chain existing plugins in order and decide how each step's result is handed to the next. Every run keeps its own content.",
  "手动": "Manual",
  "用这个例子新建": "Start from this example",
  "{count} 次": "{count} runs",
  "{count} 次进行中": "{count} in progress",
  "还没走过": "Not run yet",
  "加入第一站": "Add the first station",
  "也可以把下面的插件拖到这里": "Or drag a plugin here",
  "流程顺序": "Workflow order",
  "在开头加入插件": "Add a plugin at the start",
  "往前挪": "Move earlier",
  "往后挪": "Move later",
  "拿掉这一站": "Remove this station",
  "未接上": "Not connected",
  "在 {a} 和 {b} 之间加入插件": "Add a plugin between {a} and {b}",
  "在这里加入插件": "Add a plugin here",
  "在末尾加入插件": "Add a plugin at the end",
  "已走完": "Finished",
  "已结束 · 停在第 {n} 步": "Ended · stopped at step {n}",
  "第 {n}/{total} 步 · {plugin}": "Step {n}/{total} · {plugin}",
  "拖到链上，或点一下加到末尾": "Drag onto the chain, or click to add at the end",
  "返回流程列表": "Back to workflows",
  "流程名称": "Workflow name",
  "已保存": "Saved",
  "删除流程": "Delete workflow",
  "顺序与交接": "Order and handoffs",
  "插件是站，两站之间是衔接。点衔接换方式；点 + 或把插件拖到两站中间来加入。": "Plugins are stations; between two stations is a handoff. Click a handoff to change it; click + or drag a plugin between two stations to add it.",
  "{count} 段还没接上：": "{count} handoffs not connected: ",
  "可以加入的插件": "Plugins you can add",
  "插件": "Plugins",
  "走过的每一次": "Runs",
  "至少要有两站才能开始": "Needs at least two stations to start",
  "开始一次": "Start a run",
  "还没走过。开始一次时，先在 {plugin} 里选这一次的内容。": "Not run yet. When you start a run, pick its content in {plugin} first.",
  "先把至少两站排好，再开始第一次。": "Arrange at least two stations before the first run.",
  "正在保存…": "Saving…",
  "加入到 {a} 和 {b} 之间": "Add between {a} and {b}",
  "加在 {a} 后面": "Add after {a}",
  "加在 {a} 前面": "Add before {a}",
  "可用：{标题} {正文} {来源} {链接} {日期}。标题规则留空时沿用上一步的标题。": "Available: {标题} (title) {正文} (body) {来源} (source) {链接} (link) {日期} (date). An empty title rule keeps the previous title.",
  "打开模型设置": "Open model settings",
  "走到这里时会停下来，人看完上一步的内容，改好要交的标题和正文，再决定交不交。": "The run stops here. A person reads the previous step, edits the title and body to hand over, and decides whether to hand it over.",
  "这一段的交接": "This handoff",
  "交接方式": "Handoff type",
  "已接上": "Connected",
  "未接上：{reason}": "Not connected: {reason}",
  "正在读取…": "Loading…",
  "开始": "Start",
  "在 {plugin} 里新建一份": "Create a new one in {plugin}",
  "这一次的名字": "Name for this run",
  "{plugin} 里还没有可以开始的内容。": "Nothing in {plugin} to start from yet.",
  "这一次从 {plugin} 里的一条内容开始。每一次的内容互不相串。": "This run starts from one item in {plugin}. Runs never share content.",
  "先选这一次从哪条内容开始": "Pick the item this run starts from",
  "{kind} · 已交 {time}": "{kind} · handed over {time}",
  "手动 · 等你交": "Manual · waiting for you",
  "{kind} · 等你继续": "{kind} · waiting to continue",
  "{kind} · 未接上": "{kind} · not connected",
  "还没走到": "Not reached",
  "第 {n} 步": "Step {n}",
  "{plugin} 里这一次的内容": "This run in {plugin}",
  "还没走到这一步": "Not at this step yet",
  "前一步交过来后，这里就是 {plugin} 里这一次的内容。": "Once the previous step hands over, this shows this run in {plugin}.",
  "回到这条流程": "Back to this workflow",
  "结束这一次": "End this run",
  "这一次的步骤": "Steps of this run",
  "AI 整理后交给了 {next}": "AI organised it and handed it to {next}",
  "按规则交给了 {next}": "Handed to {next} by rule",
  "你手动交给了 {next}": "You handed it to {next}",
  "去 {next} 看这一次": "See this run in {next}",
  "这是最后一站，这一次已经走完。": "This is the last station; the run is finished.",
  "这一次在这里结束了，后面的站没有继续。": "This run ended here; later stations were not continued.",
  "手动交给 {next}": "Hand to {next} manually",
  "看完再决定交不交、交什么。改好的内容会交过去。": "Read it, then decide whether and what to hand over. The edited content is what arrives.",
  "标题": "Title",
  "正文": "Body",
  "先不交": "Not now",
  "交给 {next}": "Hand to {next}",
  "下一段 {kind} → {next} 还没接上：{reason}": "Next handoff {kind} → {next} is not connected: {reason}",
  "去配置": "Configure",
  "看内容并交给 {next}": "Review and hand to {next}",
  "AI 整理后交给 {next}": "Let AI organise and hand to {next}",
  "按规则交给 {next}": "Hand to {next} by rule",
  "下一段：{kind}交给 {next}": "Next: {kind} hand to {next}",
  "人看完后": "after a person reviews,",
  "AI 整理后": "AI organises and",
  "按规则": "by rule",
  "AI 正在整理…": "AI is organising…",
  "正在交接…": "Handing over…",
  "已交给 {next}": "Handed to {next}",
  "把这条消息整理成一页说明：先写一句结论，再分成背景、要点和待确认的问题，保留原文链接。": "Turn this message into a one-page brief: one-line conclusion first, then background, key points and open questions; keep the original link.",
  "把消息写成一页": "Turn a message into a page",
  "新的流程": "New workflow",
  "删除「{title}」后它不再出现在列表里。已经走过的每一次，以及交到各插件里的内容，都会保留。": "“{title}” will leave the list. Past runs, and what they handed to each plugin, stay.",
  "删除": "Delete",
  "新建流程": "New workflow",
  "正在读取流程…": "Loading workflows…",
  "编辑": "Edit",
  "关闭": "Close",
  "取消": "Cancel",
  "标题规则": "Title rule",
  "正文规则": "Body rule",
  "要整理成什么": "What to organise it into",
  "例如：来源：{来源}\n链接：{链接}\n\n{正文}": "e.g. Source: {来源}\nLink: {链接}\n\n{正文}",
  "例如：整理成一页说明，分成背景、要点和待确认的问题，保留原文链接。": "e.g. A one-page brief with background, key points and open questions; keep the original link.",
  "还没写交接规则": "no handoff rule yet",
  "还没写 AI 要整理成什么": "no instruction for AI yet",
  "还没有可用的文字模型": "no text model available",
  "暂不能串进流程": "Can't join a workflow yet",
  "按定好的规则，把上一步的结果变成下一步能直接用的内容，中间不再问人。": "Turns the previous result into what the next step can use, by a fixed rule, without asking anyone.",
  "AI 读上一步的结果，整理成下一步能接着用的内容。整理出的内容会留在这一次的记录里。": "AI reads the previous result and organises it for the next step. What it produced stays in this run's record.",
  "人看完这一步，自己决定交不交、交什么过去。": "A person reviews this step and decides whether and what to hand over.",
  "工作流程交接": "Workflow handoff",
  "其余 {count} 个插件暂不能串进流程": "{count} other plugins can't join a workflow yet",
  "Inbox · 工作流程": "Inbox · Workflow",
  "工作流程交过来": "Handed over by a workflow",
  "{plugin} · 第 {n} 站": "{plugin} · station {n}",
  "拖动或用 {mod} ← → 调顺序，Delete 拿掉": "Drag or use {mod} ← → to reorder; Delete removes it",
  "回到「{title}」": "Back to “{title}”",
  "回到「{title}」继续": "Back to “{title}” and continue",
  "点选插入": "Insert",
  "插入到正文规则": "Insert into the body rule",
  "标题规则留空时沿用上一步的标题。": "An empty title rule keeps the previous title.",
  "筛选…": "Filter…",
  "交过去": "hand over",
  "结束这一次？": "End this run?",
  "后面的站不会再继续。已经交出去的内容都会留在各自的插件里。": "Later stations won't continue. Everything already handed over stays in its plugin.",
  "AI 整理出的内容": "What AI produced",
  "交过去的内容": "What was handed over",
  "这段交接的要求": "Instruction for this handoff",
  "规则": "Rule",
  "撤销": "Undo",
  "已撤回这次改动": "Change undone",
  "已拿掉 {plugin}": "Removed {plugin}",
  "{count} 段交接变回了手动": "{count} handoffs went back to manual",
};
