import { renderReuseChoices } from "./ui.js";

// Source-mode tsx preserves nested function names with this pure helper; tsc output needs no helper.
export const WORK_REUSE_CLIENT = `const __name = value => value; const renderReuseChoices = ${renderReuseChoices.toString()};` + String.raw`
  let reuseChoices=null,reuseContext=null,reuseDraftKey='';
  const selectedReuse=f=>({artifacts:f.getAll('reuse-artifact').map(i=>({reference:reuseChoices.artifacts[Number(i)].reference,reason:String(f.get('reuse-reason')||'').trim()})),methodIds:f.getAll('reuse-method')});
  function saveReuseDraft(){if(!dialogBody.querySelector('.alc-reuse')||!reuseDraftKey)return;try{sessionStorage.setItem(reuseDraftKey,JSON.stringify(selectedReuse(new FormData(form))));}catch{}}
  form.addEventListener('input',saveReuseDraft);form.addEventListener('change',saveReuseDraft);
  function restoreReuseDraft(){try{const saved=JSON.parse(sessionStorage.getItem(reuseDraftKey)||'null');if(!saved)return;form.querySelectorAll('[name=reuse-artifact]').forEach(e=>{const ref=reuseChoices.artifacts[Number(e.value)].reference;e.checked=saved.artifacts.some(a=>a.reference.artifact_id===ref.artifact_id&&a.reference.version===ref.version)});form.querySelectorAll('[name=reuse-method]').forEach(e=>e.checked=saved.methodIds.includes(e.value));form.elements['reuse-reason'].value=saved.artifacts[0]?.reason||'';}catch{}}
  async function assessReuse(){const selected=selectedReuse(new FormData(form)),slot=dialogBody.querySelector('[data-reuse-assessment]');if(!slot)return;
    slot.textContent=L('正在检查适用性…');const contextSnapshot=JSON.stringify(reuseContext);
    try{const r=await api('/reuse/assess',{...reuseContext,references:selected.artifacts.map(a=>a.reference),methodIds:selected.methodIds,...(form.elements.model?.value&&form.elements.model.value!=='auto'?{modelId:form.elements.model.value}:{})});
      if(!slot.isConnected||contextSnapshot!==JSON.stringify(reuseContext))return;
      const labels=new Map([...reuseChoices.artifacts.map(a=>[a.reference.artifact_id+'@'+a.reference.version,a.title]),...reuseChoices.methods.map(m=>['method:'+m.id+'@'+m.version,m.methodChange])]);
      slot.innerHTML=r.recommendations.map(item=>'<section class="alc-claim"><h3>'+esc(labels.get(item.key)||L('所选内容'))+'</h3>'+paragraphs(L({applicable:'适用',needs_review:'核对后使用',not_applicable:'不适用'}[item.suitability]))+paragraphs(item.reason)+section('适用条件',item.applicableWhen)+section('失效条件',item.invalidWhen)+section('仍需重核',item.recheck)+'</section>').join('')+paragraphs(L('建议尚未采用，请保留适用的选择后确认研究计划。'));
    }catch(e){if(slot.isConnected)slot.textContent=e.message+' '+L('尚未采用。可以重试，或手动选择后继续。');}
  }
  async function startPrepared(plan,chosen){show('确认开始研究',paragraphs(plan.scopeSummary)+section('研究模型',runtime.models.find(m=>m.id===plan.modelId)?.label||L('使用可用模型'))+section('调用上限',String(plan.budget.limit))+section('已选择成果',plan.reuse?.artifacts.map(a=>(a.contentUnavailable?L('内容已隐藏'):(a.title||L('已保存成果')))+' · v'+a.reference.version+'：'+a.reason)||[])+section('已选择方法',plan.reuse?.methods.map(m=>m.methodChange+' · v'+m.version)||[])+paragraphs(L('目前只保存了计划。开始研究后，实际使用的版本会单独记录。')),'开始研究',async()=>{
    await api('/ideas/'+enc(chosen.id)+'/lenses/'+plan.key.lens+'/runs',{planId:plan.id});closeAfterSubmit();await load();if(sameCurrent(chosen))await open(chosen,false);
  });}
  async function reuseReceipt(planId){const r=await api('/reuse/receipts/'+enc(planId));if(!r.receipt){show('本次采用记录',paragraphs(L('已选择不等于已使用。本次还没有完成交叉核对，因此没有实际采用记录。')),'关闭',()=>closeAfterSubmit());return;}
    const receipt=r.receipt;show('本次采用记录', (receipt.artifacts.some(a=>a.contentUnavailable)?paragraphs(L('部分来源当前不可读取，相关内容已隐藏；实际使用及来源关系记录仍然保留。')):'')+section('实际使用方法',receipt.methods.map(m=>m.methodChange+' · v'+m.version))+section('实际使用成果',receipt.artifacts.map(a=>(a.contentUnavailable?L('内容已隐藏'):(a.title||L('已保存成果')))+' · v'+a.reference.version))+paragraphs(receipt.relationState==='pending'?L('研究已使用这些内容，来源关系尚待补写。重试只补关系，不重新调用模型。'):L('采用记录已保存。'))+(receipt.relationState==='pending'?button('重试来源关系','reuse-reconcile',false,'data-plan="'+esc(planId)+'"'):'')+field('本次重新解释了什么','explanation',{area:true,value:receipt.feedback?.explanation||''})+field('本次仍需准备什么','preparation',{area:true,value:receipt.feedback?.preparation||''})+field('本次纠正了什么','corrections',{area:true,value:receipt.feedback?.corrections||''})+field('结果与仍有的局限','result',{area:true,required:true,value:receipt.feedback?.result||''}),'保存实际记录',async f=>{await api('/reuse/feedback',{planId,explanation:f.get('explanation'),preparation:f.get('preparation'),corrections:f.get('corrections'),result:f.get('result')});closeAfterSubmit();notice(L('已保存本次实际记录。'));});
  }
  async function pendingMethods(){const r=await api('/action-proposals/pending');show('继续待确认方法',r.proposals.length?r.proposals.map(p=>'<section class="alc-claim">'+paragraphs(p.summary)+p.diff.map(d=>section(d.field,d.after)).join('')+paragraphs(p.memoryImpact)+button('确认保存方法','reuse-apply-proposal',false,'data-id="'+esc(p.id)+'"')+button('不采用','reuse-reject-proposal',false,'data-id="'+esc(p.id)+'"')+'</section>').join(''):paragraphs(L('没有待确认的方法。')),'关闭',()=>closeAfterSubmit());}
  async function revisePlaybook(id){const selected=memory.playbook.find(r=>r.id===id);if(!selected)return;show('修改研究方法',paragraphs(L('保存后形成新版本；已经使用过的版本保持原样。'))+field('以后具体怎样研究或判断','method',{area:true,required:true,max:2000,value:selected.methodChange})+field('适用示例（每行一条）','positive',{area:true,value:selected.positiveExamples.join('\n')})+field('不适用示例（每行一条）','negative',{area:true,value:selected.negativeExamples.join('\n')}),'确认保存新版本',async f=>{await api('/memory/playbook/'+enc(id)+'/revise',{expectedVersion:selected.version,methodChange:f.get('method'),positiveExamples:lines(f.get('positive')),negativeExamples:lines(f.get('negative'))});closeAfterSubmit();await open({kind:'settings'},false);});}
`;
