import {
  Activity,
  AlertTriangle,
  Archive,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  AppWindow,
  BadgeCheck,
  Ban,
  Bell,
  Bookmark,
  BookOpen,
  Boxes,
  Braces,
  Bug,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleDot,
  CircleHelp,
  CirclePlay,
  CircleX,
  ClipboardCheck,
  Clock3,
  Cloud,
  Columns3,
  Copy,
  Database,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileCheck2,
  FileCode2,
  FileInput,
  FileOutput,
  FileText,
  Filter,
  Fingerprint,
  Flag,
  Folder,
  FolderOpen,
  FolderTree,
  GitBranch,
  GitCompareArrows,
  Globe,
  GripVertical,
  Hash,
  History,
  House,
  Image,
  Inbox,
  Info,
  Kanban,
  KeyRound,
  Layers3,
  LayoutGrid,
  Library,
  Lightbulb,
  Link2,
  List,
  ListChecks,
  ListOrdered,
  LockKeyhole,
  LogOut,
  Mail,
  Maximize2,
  MessageSquare,
  Minus,
  Monitor,
  Moon,
  Network,
  Package,
  PanelLeft,
  PanelRight,
  Paperclip,
  Pause,
  Pilcrow,
  Pencil,
  Pin,
  PinOff,
  Play,
  Plus,
  RefreshCw,
  Redo2,
  Rss,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  SquareTerminal,
  Star,
  Sun,
  Tag,
  Target,
  Timer,
  Trash2,
  Undo2,
  Upload,
  UserRound,
  UsersRound,
  WandSparkles,
  Workflow,
  X,
  Zap,
  type IconNode,
} from "lucide";

const ICONS = {
  accepted: BadgeCheck,
  activity: Activity,
  alert: AlertTriangle,
  archive: Archive,
  arrow: ArrowRight,
  back: ArrowLeft,
  bell: Bell,
  blocked: CircleX,
  board: Kanban,
  book: BookOpen,
  bookmark: Bookmark,
  brand: Boxes,
  bug: Bug,
  calendar: Calendar,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle-alert": CircleAlert,
  circle: Circle,
  claim: Fingerprint,
  clipboard: ClipboardCheck,
  clock: Clock3,
  cloud: Cloud,
  code: Braces,
  columns: Columns3,
  completed: CheckCircle2,
  copy: Copy,
  database: Database,
  dot: CircleDot,
  download: Download,
  edit: Pencil,
  evidence: FileCheck2,
  external: ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  file: FileCode2,
  filter: Filter,
  flag: Flag,
  folder: Folder,
  "folder-open": FolderOpen,
  "folder-tree": FolderTree,
  "git-branch": GitBranch,
  "git-compare": GitCompareArrows,
  frame: AppWindow,
  globe: Globe,
  grid: LayoutGrid,
  grip: GripVertical,
  hash: Hash,
  history: History,
  home: House,
  idea: Lightbulb,
  image: Image,
  impact: Layers3,
  inbox: Inbox,
  info: Info,
  input: FileInput,
  key: KeyRound,
  library: Library,
  link: Link2,
  list: ListChecks,
  "list-ordered": ListOrdered,
  lock: LockKeyhole,
  logout: LogOut,
  mail: Mail,
  maximize: Maximize2,
  message: MessageSquare,
  minus: Minus,
  moon: Moon,
  more: Ellipsis,
  network: Network,
  note: FileText,
  output: FileOutput,
  package: Package,
  panel: PanelRight,
  paperclip: Paperclip,
  pause: Pause,
  pin: Pin,
  "pin-off": PinOff,
  play: Play,
  plus: Plus,
  question: CircleHelp,
  ready: CirclePlay,
  redo: Redo2,
  refresh: RefreshCw,
  rejected: Ban,
  review: UsersRound,
  risk: AlertTriangle,
  rows: List,
  rss: Rss,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share2,
  shield: ShieldCheck,
  sidebar: PanelLeft,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  switch: ArrowLeftRight,
  system: Monitor,
  tag: Tag,
  target: Target,
  terminal: SquareTerminal,
  text: Pilcrow,
  timer: Timer,
  trash: Trash2,
  tree: GitBranch,
  tune: SlidersHorizontal,
  undo: Undo2,
  upload: Upload,
  user: UserRound,
  waiting: Clock3,
  wand: WandSparkles,
  workflow: Workflow,
  x: X,
  zap: Zap,
} satisfies Record<string, IconNode>;

export type MolisWorkIcon = keyof typeof ICONS;

export const ICON_LIBRARY: ReadonlyArray<{ id: string; label: string; icons: readonly MolisWorkIcon[] }> = [
  {
    id: "chrome",
    label: "栏",
    icons: [
      "home", "search", "settings", "more", "sidebar", "panel", "frame", "columns", "rows", "list", "list-ordered", "text",
      "board", "grid", "maximize", "grip", "x", "chevron-up", "chevron-down", "chevron-left", "chevron-right",
      "back", "arrow",
    ],
  },
  {
    id: "action",
    label: "动作",
    icons: [
      "plus", "minus", "check", "edit", "save", "copy", "share", "send", "undo", "redo",
      "download", "upload", "external", "filter", "pin", "pin-off", "play", "pause", "refresh", "trash",
      "eye", "eye-off", "logout",
    ],
  },
  {
    id: "object",
    label: "对象",
    icons: [
      "inbox", "mail", "calendar", "bookmark", "flag", "star", "tag", "hash", "link", "paperclip",
      "file", "note", "folder", "folder-open", "folder-tree", "image", "book", "library", "database", "code", "terminal",
      "message", "user", "review", "target", "tree", "git-branch", "git-compare", "workflow", "network", "globe", "rss", "cloud",
      "package", "key", "lock", "shield", "brand", "claim", "clipboard", "evidence", "impact", "input",
      "output", "history", "archive", "system", "sun", "moon", "tune", "switch",
    ],
  },
  {
    id: "status",
    label: "状态",
    icons: [
      "info", "alert", "circle-alert", "question", "clock", "waiting", "ready", "activity",
      "bell", "sparkles", "wand", "zap", "timer", "bug", "idea", "circle", "dot", "accepted", "completed",
      "blocked", "rejected", "risk",
    ],
  },
];

function escapeAttribute(value: string | number | undefined): string {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll('"', "&quot;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

function renderNode([tag, attributes]: IconNode[number]): string {
  const attrs = Object.entries(attributes)
    .filter(([, value]) => value !== undefined)
    .map(([name, value]) => `${name}="${escapeAttribute(value)}"`)
    .join(" ");
  return `<${tag}${attrs ? ` ${attrs}` : ""}></${tag}>`;
}

export function renderIconSprite(): string {
  const symbols = Object.entries(ICONS)
    .map(
      ([name, node]) =>
        `<symbol id="icon-${name}" viewBox="0 0 24 24">${node.map(renderNode).join("")}</symbol>`,
    )
    .join("");
  return `<svg class="icon-sprite" aria-hidden="true">${symbols}</svg>`;
}

export function icon(name: MolisWorkIcon, className = ""): string {
  return `<svg${className ? ` class="${escapeAttribute(className)}"` : ""} aria-hidden="true"><use href="#icon-${name}"></use></svg>`;
}

export function listedIconNames(): MolisWorkIcon[] {
  return [...new Set(ICON_LIBRARY.flatMap((group) => group.icons))];
}

export function registeredIconNames(): MolisWorkIcon[] {
  return Object.keys(ICONS) as MolisWorkIcon[];
}
