import {RECORD_CLIENT_FACTORY_SCRIPT} from './record-client.js';
import {builderIcons,builderMark} from './visuals.js';
export const BUILDER_CLIENT_FACTORY_SCRIPT=String.raw`(host)=>{
 const root=document.querySelector('[data-builder]');if(!root)return;
 const icons=${JSON.stringify(builderIcons)},mark=${JSON.stringify(builderMark)};
 const $=selector=>root.querySelector(selector),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const route=host.route||((p)=>p),base=route('/api/plugins/io.molis.work.plugin-builder');
 root.style.setProperty('--pb-atlas','url("'+base+'/assets/inspiration-atlas.png")');
 let current=null,selection=null,state=null,busy=false,timer=null,renderedId=null,chatKey='',trying=false,loading=false,selectedNode=null,lastPointerKey='',replay=null,replayTimer=null,placement=null,placementTimer=null;
 const api=async(path,method='GET',body,query)=>{const url=new URL(base+path,location.origin);if(query)Object.entries(query).forEach(([k,v])=>{if(v)url.searchParams.set(k,v);});const response=await fetch(url,{method,cache:'no-store',headers:method==='GET'?{}:(globalThis.molisWorkControlHeaders?.()||host.headers?.()||{'content-type':'application/json'}),...(method==='GET'?{}:{body:JSON.stringify(body??{})})});const result=await response.json();if(!response.ok)throw new Error(result.error||'请求失败');return result;};
 const error=message=>{const el=$('[data-pb-error]');el.textContent=message||'';el.hidden=!message;};
 const active=()=>current&&['clarifying','building'].includes(current.phase);
 const config=()=>{const pair=$('[data-pb-model]').value.split('\n');return {workspace_id:$('[data-pb-workspace]').value,provider_id:pair[0],model_id:pair[1]};};
 const settings=()=>{$('[data-pb-settings-panel]').hidden=false;};
 const schedule=()=>{clearTimeout(timer);if(active()&&!document.hidden&&!root.closest('[data-work-surface]')?.hidden)timer=setTimeout(advance,900);};
 const nodeArea=n=>!n?'':['heading','form','actions'].includes(n.kind)?'head':['search','filter'].includes(n.kind)?'query':'body';
 const speaker=(label,ai)=>'<div class="pb-speaker '+(ai?'ai':'')+'"><span>'+icons[ai?'sparkles':'user']+'</span>'+label+'</div>';
 const empty=()=>{records.clear();$('[data-pb-preview]').innerHTML='<div class="pb-canvas-empty"><div class="pb-empty-mark">'+mark+'</div><h2>让一个想法，长成工具。</h2><p>从你想完成的事开始。<br>一起确定使用方式，再看着它逐步成形。</p><button class="pb-button" data-pb-starter="inspiration">体验灵感库示例 '+icons.arrow+'</button><small>可编辑示例 · 不调用模型</small></div>';$('[data-pb-chat]').innerHTML='<article class="pb-message">'+speaker('Molis AI',true)+'<p>你希望这个插件帮你完成什么？告诉我使用场景，以及你希望留下什么结果。</p></article>';$('[data-pb-title]').textContent='你的新插件';};
 const records=(${RECORD_CLIENT_FACTORY_SCRIPT})({root:$('[data-pb-preview]'),request:(method,body,query)=>api('/builds/'+current.id+'/records',method,body,query),onInspect:id=>inspect(id),onLayout:layout=>action('layout',{layout}),onChange:()=>requestAnimationFrame(positionAgents),onPlace:placeElement});
 const thumb=c=>'<div class="pb-mini '+esc(c.layout)+'"><div class="pb-mini-head"><b>'+esc(c.title)+'</b><i></i></div><div class="pb-mini-items">'+Array.from({length:4},(_,j)=>'<div class="pb-mini-item"><i class="pb-mini-cover '+(current?.example?'sample':'')+'" style="background-position:'+(j%2?'100%':'0')+' '+(j>1?'100%':'0')+'"></i><div><span></span><span></span></div></div>').join('')+'</div></div>';
 const action=async(name,extra={})=>{if(!current||busy)return false;let succeeded=false;stopReplay();busy=true;error('');render();try{const result=await api('/builds/'+current.id+'/action','POST',{action:name,revision:current.revision,...config(),...extra});current=result.build;succeeded=true;if(result.release){await loadState();$('[data-pb-connected]').innerHTML='<a href="'+esc(route('/plugins/'+result.release.pluginId))+'" target="_blank" rel="noopener">已发布 · 独立打开 '+icons.external+'</a>';}}catch(e){error(e.message);try{current=(await api('/builds/'+current.id)).build;}catch{}}finally{busy=false;render();schedule();}return succeeded;};
 const advance=async()=>{if(busy||!active())return;busy=true;try{const id=current.id,result=await api('/builds/'+id+'/action','POST',{action:'advance'});if(current?.id===id)current=result.build;}catch(e){error(e.message);}finally{busy=false;render();schedule();}};
 const stateText=d=>({draft:'等待你的补充',clarifying:'主线设计 · Prologue 正在工作',choosing:'比较方案，选择你的使用方式',building:d.active?.stage==='behavior'?'功能 Agent 正在连接数据与行为':'UI Agent 正在装配界面',paused:'已暂停 · 内容已保留',ready:'界面与功能已接通',failed:'这一轮需要处理'})[d.phase];
 function renderChat(d){
  const key=JSON.stringify([d.revision,selection,busy,replay!==null]);if(key===chatKey)return;chatKey=key;const chat=$('[data-pb-chat]'),scroll=chat.scrollTop;
  const firstReply=d.messages.find(m=>m.role==='assistant');const selected=d.candidates.find(c=>c.id===selection)||d.design;
  let html='<article class="pb-message user">'+speaker('我',false)+'<p>'+esc(d.brief)+'</p></article><article class="pb-message">'+speaker('Molis AI',true)+'<p>'+esc(firstReply?.text||'我会先理清使用过程，再给出几种可以直接比较的方案。')+'</p></article>';
  if(selected)html+='<details class="pb-reasoning" open><summary>需求解析与设计依据 '+icons.chevron+'</summary><p>'+esc(d.example?'先收集，再整理，随时找回。':selected.description)+'</p><small>'+esc(d.example?'轻量录入 · 本地保存 · 按主题浏览':selected.journey.join(' → '))+'</small></details>';
  if(d.questions.length)html+='<div class="pb-questions">'+d.questions.map(q=>'<p>'+esc(q)+'</p>').join('')+'</div>';
  if(d.candidates.length)html+='<h3>选择一个适合你的使用方式</h3><div class="pb-candidates">'+[...d.candidates].sort((a,b)=>['list','table','cards'].indexOf(a.layout)-['list','table','cards'].indexOf(b.layout)).map(c=>'<button class="pb-candidate" data-pb-candidate="'+esc(c.id)+'" aria-pressed="'+(d.phase==='choosing'?selection===c.id:d.example?d.design?.layout===c.layout:d.design?.id===c.id)+'" title="'+esc(c.rationale)+'">'+thumb(c)+'<strong>'+({cards:'灵感',list:'阅读',table:'整理'})[c.layout]+'</strong></button>').join('')+'</div>'+(d.phase==='choosing'||selection&&selection!==d.design?.id&&!d.example?'<div class="pb-choose-actions"><button class="pb-button pb-primary" data-pb-confirm '+(!selection||busy?'disabled':'')+'>采用方案并构建 '+icons.arrow+'</button>'+(state?.selectionAvailable?'<label><input type="checkbox" data-pb-jev> Jev 选择集合零件</label>':'')+'</div>':'');
  if(d.design)html+='<details class="pb-design"><summary><span>主线已确定 <small>v'+d.revision+'</small><span class="pb-journey">'+esc(d.example?'收集 → 分类 → 回看':d.design.journey.join(' → '))+'</span></span>'+icons.chevron+'</summary><ul>'+d.design.acceptance.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>'+(d.selection?'<small>'+esc(d.selection.source==='jev'?d.selection.model+' · '+d.selection.elapsedMs+'ms':d.selection.reason)+'</small>':'')+'</details>';
  const uiText=replay!==null?'回放已保存的界面':d.pendingNodes.length?'放入'+d.pendingNodes[0].label:d.phase==='ready'?'界面装配完成':d.nodes.length?'检查'+d.nodes.at(-1).label:'等待界面方案';
  const fnText=d.behavior?'数据与操作已接通':d.active?.stage==='behavior'?'连接保存与数据行为':'等待主线设计';
  if(d.design)html+='<section class="pb-agent-note">'+speaker('Molis AI',true)+'<p>'+esc(replay!==null?'这是示例装配回放，不会启动模型或改写数据。':d.phase==='ready'?'已经可以用了。亲手试试，再把它保存为自己的插件。':'开始搭建。你可以看着它成形。')+'</p><div class="pb-agent-status"><div><i class="pb-agent-dot"></i><b>UI Agent</b><span>'+esc(uiText)+'</span></div><div><i class="pb-agent-dot"></i><b>功能 Agent</b><span>'+esc(fnText)+'</span></div></div></section>';
  html+='<div class="pb-playback">'+(active()?'<button data-pb-action="pause">'+icons.pause+'暂停</button>':'')+(d.active?'<button data-pb-action="stop">停止本轮</button>':'')+(['paused','failed'].includes(d.phase)?'<button data-pb-action="resume">'+icons.play+'继续构建</button>':'')+(d.example&&d.phase==='ready'?'<button data-pb-replay>'+icons[replay!==null?'pause':'play']+(replay!==null?'停止示例回放':'回放示例装配')+'</button>':'')+(d.history.length&&!d.active?'<button data-pb-action="undo" aria-label="撤销">'+icons.undo+'</button>':'')+'</div>';
  const moreMessages=d.messages.filter(m=>m.role==='user').slice(1);html+=moreMessages.map(m=>'<article class="pb-message user">'+speaker('我',false)+'<p>'+esc(m.text)+'</p></article>').join('');
  chat.innerHTML=html;chat.scrollTop=scroll;
 }
 function render(){
  if(!current)return;const d=current;if(renderedId!==d.id){records.clear();renderedId=d.id;chatKey='';selection=null;trying=false;selectedNode=null;error('');$('[data-pb-connected]').textContent='';}
  root.classList.toggle('pb-trying',trying);$('[data-pb-title]').textContent=d.title;$('[data-pb-badge]').textContent=replay!==null?'示例回放':d.example?'示例草稿':'草稿';$('[data-pb-status]').textContent=replay!==null?'示例装配回放 · 不调用模型':stateText(d);
  $('[data-pb-build]').classList.toggle('selected',!trying);$('[data-pb-try]').classList.toggle('selected',trying);$('[data-pb-build]').setAttribute('aria-pressed',String(!trying));$('[data-pb-try]').setAttribute('aria-pressed',String(trying));$('[data-pb-try]').disabled=!d.design;
  const publish=$('[data-pb-action="publish"]');publish.hidden=d.phase!=='ready'||Boolean(d.active);publish.disabled=busy||replay!==null;
  $('[data-pb-send]').disabled=busy||Boolean(d.active);$('[data-pb-send]').setAttribute('aria-label',d.design?'发送修改':'开始设计');
  renderChat(d);
  if(d.design){records.update(d.design,d.nodes,d.behavior);records.setMode(trying?'try':'building');}
  $('[data-pb-layout]').disabled=busy||Boolean(d.active);if(d.design)$('[data-pb-layout]').value=d.design.layout;
  $('[data-pb-runs]').innerHTML=(d.runs||[]).map(r=>'<div><strong>'+esc(({design:'主线设计',ui:'UI Agent',behavior:'功能 Agent'})[r.stage])+'</strong> · '+esc(r.phase)+'<small>'+esc(r.model_id)+' · '+esc(r.run_id||'等待运行标识')+'</small></div>').join('')||'此草稿还没有 Prologue 运行记录。';
  if(!$('[data-pb-connected]').querySelector('a'))$('[data-pb-connected]').textContent=d.example?'示例内容 · 预览与正式数据分开':d.behavior?'预览数据保存在本机':'功能待连接 · 输入会保留';
  $('.pb-shelf').hidden=trying||!d.design;
  if(d.error)error(d.error);requestAnimationFrame(positionAgents);
 }
 function inspect(id){if(!current?.design||trying)return;selectedNode=id||null;const panel=$('[data-pb-inspector-panel]');panel.hidden=false;
  const chosen=current.nodes.find(n=>n.id===selectedNode),nodes=chosen?[chosen]:current.nodes;const locked=busy||Boolean(current.active)||current.pendingNodes.length>0;
  $('[data-pb-inspector]').innerHTML='<p class="pb-hint">同一区域内可调整顺序，记录会保留。</p>'+nodes.map(n=>{const i=current.nodes.indexOf(n);return '<div class="pb-inspector-row"><label>'+esc(n.kind)+'<input aria-label="零件标签" data-pb-node-label="'+esc(n.id)+'" value="'+esc(n.label)+'" '+(locked?'disabled':'')+'></label><button data-pb-node-up="'+esc(n.id)+'" '+(nodeArea(current.nodes[i-1])!==nodeArea(n)||locked?'disabled':'')+' aria-label="上移零件">'+icons.arrow+'</button><button data-pb-node-down="'+esc(n.id)+'" '+(nodeArea(current.nodes[i+1])!==nodeArea(n)||locked?'disabled':'')+' aria-label="下移零件">'+icons.arrow+'</button></div>';}).join('');
  $('[data-pb-context]').hidden=!chosen;$('[data-pb-context]').textContent=chosen?'正在看 · '+chosen.label:'';positionAgents();
 }
 function finishPlacement(){clearTimeout(placementTimer);if(placement){const element=placement.element;element.classList.remove('pb-awaiting-placement');element.removeAttribute('aria-busy');element.inert=false;element.classList.add('pb-just-placed');placement=null;}}
 function placeElement(element,label){
  if((!active()&&replay===null)||trying||matchMedia('(prefers-reduced-motion:reduce)').matches)return;
  finishPlacement();placement={element,label};element.classList.add('pb-awaiting-placement');element.setAttribute('aria-busy','true');element.inert=true;
  requestAnimationFrame(()=>{if(placement?.element!==element)return;positionAgents();placementTimer=setTimeout(()=>{if(placement?.element!==element)return;finishPlacement();positionAgents();},650);});
 }
 function positionAgents(){
  if(!current?.design){root.querySelectorAll('[data-pb-pointer],[data-pb-selection]').forEach(e=>e.hidden=true);return;}const canvas=$('.pb-canvas'),bounds=canvas.getBoundingClientRect(),preview=$('[data-pb-preview]');
  const running=active()||replay!==null;const targetId=selectedNode||placement?.element.closest('[data-node-id]')?.dataset.nodeId||(current.nodes.at(-1)?.id);const logicalNode=[...preview.querySelectorAll('[data-node-id]')].find(n=>n.dataset.nodeId===targetId);let node=placement?.element||logicalNode;
  if(!placement&&(replay!==null||logicalNode?.dataset.kind==='collection'))node=preview.querySelector('.pb-record:last-of-type')||node;
  const outline=$('[data-pb-selection]');outline.hidden=trying||!node||(!running&&!selectedNode);
  if(!outline.hidden){const b=node.getBoundingClientRect();outline.style.transform='translate('+(b.left-bounds.left-5)+'px,'+(b.top-bounds.top-5)+'px)';outline.style.width=(b.width+10)+'px';outline.style.height=(b.height+10)+'px';if(b.bottom<bounds.top||b.top>bounds.bottom)outline.hidden=true;}
  const fnNode=preview.querySelector('[data-record-add]')||preview.querySelector('[data-record-export]');
  const key=current.revision+':'+replay+':'+targetId;
  for(const kind of ['ui','behavior']){const el=$('[data-pb-pointer="'+kind+'"]'),target=kind==='ui'?node:fnNode;el.hidden=trying||!running||!target||(kind==='behavior'&&!current.behavior&&current.active?.stage!=='behavior');if(el.hidden)continue;const b=target.getBoundingClientRect();if(b.bottom<bounds.top||b.top>bounds.bottom){el.hidden=true;continue;}const x=kind==='ui'?b.right-bounds.left+6:b.right-bounds.left-14;const y=kind==='ui'?b.top-bounds.top+12:b.bottom-bounds.top-3;el.style.transform='translate('+Math.max(4,Math.min(bounds.width-98,x))+'px,'+Math.max(0,Math.min(bounds.height-63,y))+'px)';el.querySelector('small').textContent=kind==='ui'?placement?'放置'+placement.label:replay!==null?'回放素材卡片':'装配'+(current.nodes.at(-1)?.label||'界面'):current.behavior?'保存已接通':'连接保存';if(key!==lastPointerKey){el.classList.remove('clicking');requestAnimationFrame(()=>el.classList.add('clicking'));}}
  lastPointerKey=key;root.querySelectorAll('[data-pb-part]').forEach(el=>el.classList.toggle('selected',(logicalNode?.dataset.kind==='collection'&&el.dataset.pbPart===(current.design.layout==='table'?'list':current.design.layout))||(logicalNode?.dataset.kind==='form'&&el.dataset.pbPart==='input')));
 }
 function stopReplay(){finishPlacement();clearTimeout(replayTimer);if(replay!==null){replay=null;records.setVisibleCount(Infinity);chatKey='';}}
 function playExample(){if(replay!==null){stopReplay();render();return;}trying=false;selectedNode=null;replay=0;records.setVisibleCount(0);render();const next=()=>{if(replay===null)return;replay++;records.setVisibleCount(replay);chatKey='';render();if(replay<4)replayTimer=setTimeout(next,900);else replayTimer=setTimeout(()=>{stopReplay();render();},2200);};replayTimer=setTimeout(next,600);}
 const loadState=async()=>{state=await api('/state');const workspace=$('[data-pb-workspace]'),model=$('[data-pb-model]'),w=workspace.value,m=model.value;workspace.innerHTML='<option value="">选择工作区</option>'+state.workspaces.map(x=>'<option value="'+esc(x.workspace_id)+'">'+esc(x.label)+'</option>').join('');model.innerHTML='<option value="">选择模型</option>'+state.models.map(x=>'<option value="'+esc(x.provider_id+'\n'+x.model_id)+'">'+esc(x.label)+'</option>').join('');if(w)workspace.value=w;else if(state.workspaces.length===1)workspace.selectedIndex=1;if(m)model.value=m;else if(state.models.length===1)model.selectedIndex=1;
  $('[data-pb-config-hint]').textContent=!state.runtimeAvailable?'Prologue 尚未装配，请检查运行环境。':!state.models.length?'先在模型设置中配置一个模型，再开始真实构建。可先体验灵感库示例。':!state.workspaces.length?'先将工作区关联到当前项目，再开始设计。':'配置已就绪。';updateModelLabel();};
 const updateModelLabel=()=>{$('[data-pb-model-label]').textContent=$('[data-pb-model]').value?'Prologue · '+$('[data-pb-model]').selectedOptions[0].textContent:'Prologue · 设置工作区与模型';};
 const openBuild=async id=>{stopReplay();clearTimeout(timer);current=(await api('/builds/'+id)).build;render();schedule();};
 const library=async()=>{await loadState();const versions=new Map(await Promise.all(state.builds.map(async b=>[b.id,(await api('/builds/'+b.id)).versions])));$('[data-pb-library-panel]').hidden=false;$('[data-pb-library-list]').innerHTML=state.builds.length?state.builds.map(b=>{const release=state.releases.find(r=>r.buildId===b.id);return '<article class="pb-library-entry"><div><strong>'+esc(b.title)+'</strong><small>'+esc(b.brief.slice(0,100))+'</small></div><button class="pb-button" data-pb-open="'+esc(b.id)+'">继续编辑</button>'+(release?'<a href="'+esc(route('/plugins/'+release.pluginId))+'" target="_blank" rel="noopener">打开 v'+release.version+' '+icons.external+'</a><label>使用版本<select aria-label="使用版本" data-pb-version="'+esc(b.id)+'">'+versions.get(b.id).map(v=>'<option value="'+v.version+'" '+(v.version===release.version?'selected':'')+'>v'+v.version+'</option>').join('')+'</select></label>':'<small>未发布</small>')+'</article>';}).join(''):'<p>还没有插件。写下一句需求，开始第一个。</p>';};
 root.addEventListener('click',async event=>{const el=event.target.closest('button,[data-pb-home]');if(!el)return;try{
  if(el.matches('[data-pb-home]')){event.preventDefault();await library();return;}
  if(el.matches('[data-pb-settings]')){settings();return;}if(el.matches('[data-pb-settings-close]')){$('[data-pb-settings-panel]').hidden=true;return;}
  if(el.matches('[data-pb-library]')){await library();return;}if(el.matches('[data-pb-library-close]')){$('[data-pb-library-panel]').hidden=true;return;}
  if(el.dataset.pbOpen){$('[data-pb-library-panel]').hidden=true;await openBuild(el.dataset.pbOpen);return;}
  if(el.matches('[data-pb-new]')){stopReplay();current=null;renderedId=null;selectedNode=null;clearTimeout(timer);error('');$('[data-pb-compose]').reset();$('[data-pb-action="publish"]').hidden=true;$('.pb-shelf').hidden=true;$('[data-pb-inspector-panel]').hidden=true;root.querySelectorAll('[data-pb-pointer],[data-pb-selection]').forEach(e=>e.hidden=true);$('[data-pb-connected]').textContent='';empty();root.classList.add('pb-chat-open');$('[data-pb-compose] textarea').focus();return;}
  if(el.dataset.pbStarter){if(busy)return;busy=true;try{current=(await api('/builds','POST',{starter:el.dataset.pbStarter})).build;renderedId=null;render();}finally{busy=false;render();}return;}
  if(el.matches('[data-pb-chat-close]')){root.classList.remove('pb-chat-open');$('[data-pb-chat-toggle]').focus();return;}if(el.matches('[data-pb-chat-toggle]')){root.classList.toggle('pb-chat-open');return;}
  if(el.dataset.pbCandidate){const candidate=current.candidates.find(c=>c.id===el.dataset.pbCandidate);if(!candidate)return;if(current.example){await action('layout',{layout:candidate.layout});selection=null;return;}selection=candidate.id;chatKey='';render();if(current.phase==='choosing')records.update(candidate,[{id:'candidate-heading',kind:'heading',label:'标题'},{id:'candidate-form',kind:'form',label:'录入'},{id:'candidate-collection',kind:'collection',label:'集合'}],null);return;}
  if(el.matches('[data-pb-confirm]')){if(!config().model_id){settings();throw new Error('选择模型后开始构建。');}const chosen=await action('choose',{candidateId:selection,selection:$('[data-pb-jev]')?.checked?'jev':'manual'});selection=null;if(chosen)await action('resume');root.classList.remove('pb-chat-open');return;}
  if(el.dataset.pbAction){await action(el.dataset.pbAction);return;}
  if(el.matches('[data-pb-try],[data-pb-build]')){stopReplay();trying=el.hasAttribute('data-pb-try');selectedNode=null;$('[data-pb-inspector-panel]').hidden=true;$('[data-pb-context]').hidden=true;render();return;}
  if(el.matches('[data-pb-replay]')){playExample();return;}
  if(el.matches('[data-pb-inspector-close]')){$('[data-pb-inspector-panel]').hidden=true;selectedNode=null;$('[data-pb-context]').hidden=true;positionAgents();return;}
  if(el.matches('[data-pb-inspect-all]')){inspect();return;}
  if(el.dataset.pbPart){const kind=({frame:'heading',text:'heading',input:'form',plus:'actions',list:'collection',cards:'collection'})[el.dataset.pbPart];const node=current?.nodes.find(n=>n.kind===kind);if(node)inspect(node.id);else error('这个零件还未装配，完成当前构建后即可检查。');return;}
  if(el.dataset.pbNodeUp||el.dataset.pbNodeDown){await action('node',{nodeId:el.dataset.pbNodeUp||el.dataset.pbNodeDown,direction:el.dataset.pbNodeUp?-1:1});inspect(selectedNode);return;}
 }catch(e){error(e.message);}});
 root.addEventListener('change',async event=>{const el=event.target;try{if(el.matches('[data-pb-model],[data-pb-workspace]')){updateModelLabel();return;}if(el.dataset.pbNodeLabel){await action('node',{nodeId:el.dataset.pbNodeLabel,label:el.value});return;}if(el.matches('[data-pb-layout]')){await action('layout',{layout:el.value});return;}if(el.dataset.pbVersion){const d=(await api('/builds/'+el.dataset.pbVersion)).build;await api('/builds/'+d.id+'/action','POST',{action:'activate',revision:d.revision,version:Number(el.value)});await library();}}catch(e){error(e.message);$('[data-pb-library-panel]').hidden=true;}});
 $('[data-pb-compose]').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const input=event.target.querySelector('textarea'),message=input.value.trim();if(!message)return;error('');try{
  if(!config().workspace_id||!config().model_id){settings();throw new Error('先选择已授权工作区和模型，你写下的需求会保留。');}
  if(!current)current=(await api('/builds','POST',{brief:message})).build;else if(!await action('message',{message}))return;input.value='';render();await action('design');
 }catch(e){error(e.message);}});
 $('[data-pb-compose] textarea').addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key==='Enter'&&!event.isComposing){event.preventDefault();$('[data-pb-compose]').requestSubmit();}});
 $('.pb-canvas-scroll').addEventListener('scroll',positionAgents,{passive:true});new ResizeObserver(positionAgents).observe($('.pb-canvas'));
 root.addEventListener('keydown',event=>{if(event.key==='Escape'){root.classList.remove('pb-chat-open');$('[data-pb-settings-panel]').hidden=true;$('[data-pb-inspector-panel]').hidden=true;selectedNode=null;positionAgents();}});
 const initialize=async()=>{if(loading)return;loading=true;try{await loadState();const requested=new URL(location.href).searchParams.get('build');if(requested)await openBuild(requested);else if(state.builds.length)await openBuild(state.builds[0].id);else empty();}catch(e){error(e.message);}finally{loading=false;}};
 const surface=root.closest('[data-work-surface]');if(!surface?.hidden)void initialize();if(surface)new MutationObserver(()=>{if(!surface.hidden&&!state)void initialize();else if(!surface.hidden)schedule();else clearTimeout(timer);}).observe(surface,{attributes:true,attributeFilter:['hidden','class']});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTimeout(timer);else schedule();});
}`;
