import type { AgentManifest, AgentPromptText } from '@molis-ai/molis-work-contracts/platform/plugin-agent';
const schema = `Design = {id,title,description,journey:string[],acceptance:string[],fields:[{id,label,type:"text"|"url"|"number"|"tags"|"boolean",required:boolean}],calculations:[{id,label,expression:Expr}],layout:"cards"|"list"|"table",allowImport:boolean,allowExport:boolean,presentation?:{title?:string,description?:string,image?:string,metadata?:string,link?:string,tags?:string,addLabel?:string}}.
Optional presentation maps visual roles to existing input field IDs, never literal content: title/description/metadata require text or url fields; image/link require url fields; tags requires a tags field. addLabel is the only literal, a nonempty add-button label up to 30 characters. Omit presentation to keep the default first-field presentation. Use image binding only when the requested records include image URLs; never invent fetched material or external data.
Expr = {op:"literal",value:string|number|boolean} | {op:"field",id:string} | {op:"add"|"subtract"|"multiply"|"divide"|"concat"|"equal"|"gt",left:Expr,right:Expr} | {op:"if",condition:Expr,then:Expr,else:Expr}. No arbitrary code. IDs are lowercase ASCII identifiers, unique and stable. Only these properties are allowed. Expressions may reference fields or other calculated fields without cycles, depth <=8.`;
export const builderPrompts: AgentPromptText[] = [
  {prompt_id:'builder-base',version:1,layer:'base',body:`You design functional local data plugins for Molis Work. Return only a complete JSON value, no markdown or explanation outside JSON. Use the user's language for labels. Do not pretend external accounts, networking, collaboration or arbitrary code execution exist. Supported: schema-driven records, search, tag filters, CRUD, CSV import/export, derived fields and numeric totals. If the task needs unsupported capabilities explain them in a clarification question. Never substitute a sample materials app for the requested task. Preserve existing field IDs/types when revising a published design. ${schema}`},
  {prompt_id:'builder-design',version:1,layer:'role',body:`Analyze the requested user journey. If essential information is missing return {questions:string[],summary:string}, with 1-3 concise questions. Otherwise return {summary:string,candidates:[...]} with 2-3 Design objects each with an extra rationale:string. Candidates must differ meaningfully in workflow/layout; each must meet the user's required behaviors. Keep fields focused (max 16), design evidence succinct, and include concrete acceptance checks. Do not add unsupported properties such as default or options.`},
  {prompt_id:'builder-ui',version:1,layer:'role',body:`Build the selected design with an ordered array of UI parts: [{id,kind,label}]. Allowed kind: heading, form, search, filter, collection, actions, summary. Include heading, form, collection, actions exactly once, search for browsing, filter only with tags fields, summary only when numbers/calculations are useful. Each part appears at most once. Use no HTML, CSS or code. The selected design and component layout are authoritative.`},
  {prompt_id:'builder-behavior',version:1,layer:'role',body:`Connect the selected design's real operations. Return {calculations:[{id,label,expression:Expr}],allowImport:boolean,allowExport:boolean}. Honor the selected fields and requirements. Derive exactly the requested custom computations (e.g. quantity * price, conditional prioritization), keeping calculation IDs and labels from the selected design. Keep calculations empty when unnecessary. You generate the program, the Host validates and interprets it. Never claim validation or persistence has already occurred.`},
];
export const builderAgentManifest: AgentManifest = {
 roles: ['design','ui','behavior'].map(role=>({role_id:role,version:1,name:{design:'主线设计',ui:'UI Agent',behavior:'功能 Agent'}[role]!,execution:'read-only',prompts:['builder-base',`builder-${role}`],host_tools:[]})),
 prompts: builderPrompts.map(({body:_body,...prompt})=>prompt),
};
