import type {UiContribution} from '@molis-ai/molis-work-contracts/platform/ui';
import {BUILDER_PLUGIN_ID,BUILDER_UI_ID} from './manifest.js';
import {builderIcons as i,builderMark,builderPointer} from './visuals.js';
export const builderUiContribution:UiContribution={descriptor:{contribution_id:BUILDER_UI_ID,plugin_id:BUILDER_PLUGIN_ID,kind:'primary-page',navigation_id:'plugin-builder',label:'插件创作工作台',surfaces:[{surface_id:'directory',target_slot_id:'workbench.directory',format:'declarative-html'},{surface_id:'workbench',target_slot_id:'workbench.main',format:'declarative-html'}],slots:[]},render:request=>request.surface==='directory'?'':renderBuilder()};
export function renderBuilder(){return `<section class="desktop-work-surface pb-surface" data-work-surface="plugin-builder" data-work-surface-label="插件创作工作台" hidden>
<div class="pb-shell" data-builder>
<header class="pb-top"><a class="pb-brand" href="#" data-pb-home>${builderMark}<strong>Molis</strong></a><span class="pb-top-divider">/</span><span class="pb-top-title">插件 Builder</span><nav><button data-pb-library>我的插件 ${i.chevron}</button><span class="pb-separator"></span><button class="pb-icon" data-pb-new title="新建插件" aria-label="新建插件">${i.plus}</button><button class="pb-icon" data-pb-settings title="工作区、模型与运行记录" aria-label="构建设置">${i.settings}</button></nav></header>
<aside class="pb-sidebar"><header class="pb-sidebar-heading"><h2>一起把想法做出来</h2><button class="pb-mobile pb-icon" data-pb-chat-close aria-label="回到画布">${i.close}</button></header><div class="pb-chat" data-pb-chat></div>
<div class="pb-composer-wrap"><div class="pb-context" data-pb-context hidden></div><div class="pb-attachment" data-pb-attachment hidden></div><form class="pb-compose" data-pb-compose><button type="button" class="pb-attach" data-pb-attach title="附上已有内容（CSV 或文字）" aria-label="附上已有内容">${i.paperclip}</button><input type="file" data-pb-file accept=".csv,.tsv,.txt,.md,.json,text/csv,text/plain,text/markdown,application/json" hidden><label class="pb-sr" for="pb-prompt">插件需求或修改意见</label><textarea id="pb-prompt" rows="1" maxlength="12000" placeholder="描述你想做的插件…"></textarea><button class="pb-send" type="submit" data-pb-send aria-label="发送需求">${i.arrow}</button></form><button class="pb-model-note" data-pb-settings><span data-pb-model-label>Prologue · 选择工作区与模型</span>${i.chevron}</button></div></aside>
<section class="pb-work"><header class="pb-toolbar"><div class="pb-project-title"><button class="pb-mobile pb-icon" data-pb-chat-toggle aria-label="设计对话">${i.message}</button>${i.cards}<strong data-pb-title>你的新插件</strong><span class="pb-draft" data-pb-badge>草稿</span></div><div class="pb-mode" role="group" aria-label="画布模式"><button class="selected" data-pb-build aria-pressed="true">构建</button><button data-pb-try aria-pressed="false">试用</button></div><div class="pb-toolbar-actions"><button class="pb-button" data-pb-action="publish" hidden>${i.external}发布插件</button><button class="pb-icon" data-pb-inspect-all aria-label="主线与界面零件">${i.more}</button></div></header>
<div class="pb-error" role="alert" data-pb-error hidden></div>
<div class="pb-canvas"><div class="pb-canvas-scroll"><div class="pb-artboard" data-pb-preview></div></div>
<div class="pb-agent-layer" aria-hidden="true"><div class="pb-target-hint" data-pb-hint hidden></div><div class="pb-drop-line" data-pb-drop hidden></div><div class="pb-selection" data-pb-selection hidden><i></i><i></i><i></i><i></i></div><div class="pb-pointer ui" data-pb-pointer="ui" hidden>${builderPointer}<div><strong>UI Agent</strong><small>放入界面零件</small><span class="pb-dots"><i></i><i></i><i></i></span></div><i></i></div><div class="pb-pointer fn" data-pb-pointer="behavior" hidden>${builderPointer}<div><strong>功能 Agent</strong><small>接入数据与行为</small><span class="pb-dots"><i></i><i></i><i></i></span></div><i></i></div></div>
<div class="pb-shelf" aria-label="规格板：可用的界面零件" hidden></div>
<aside class="pb-inspector" data-pb-inspector-panel hidden><header><strong>界面零件</strong><button class="pb-icon" data-pb-inspector-close aria-label="关闭检查器">${i.close}</button></header><div data-pb-inspector></div><label data-pb-layout-wrap>集合布局<select data-pb-layout aria-label="集合布局"><option value="cards">卡片</option><option value="list">列表</option><option value="table">表格</option></select></label></aside>
</div><footer class="pb-bottom"><span data-pb-status>从一个想法开始</span><span data-pb-connected></span></footer></section>
<aside class="pb-settings" data-pb-settings-panel hidden><header><h2>构建设置</h2><button class="pb-icon" data-pb-settings-close aria-label="关闭设置">${i.close}</button></header><p>需求与设计交给所选模型，插件数据留在本机。</p><label>已授权工作区<select data-pb-workspace aria-label="已授权工作区"></select></label><label>执行模型<select data-pb-model aria-label="执行模型"></select></label><p data-pb-config-hint></p><details><summary>Prologue 运行记录</summary><div data-pb-runs>开始构建后显示。</div></details></aside>
<div class="pb-library" data-pb-library-panel hidden><header><div><h2>我的插件</h2><p>从想法到日常真正用得上的工具。</p></div><button class="pb-button" data-pb-library-close>返回创作</button></header><div data-pb-library-list></div></div>
<dialog class="pb-publish-dialog" data-pb-publish-dialog aria-labelledby="pb-publish-title"><h2 id="pb-publish-title">说明新版本如何接续数据</h2><p>选择对上一发布的声明。直接兼容表示无需转换即可读取；需要校验的数据会在你手动升级时逐条检查，通过后才切换。创作台不会自动迁移数据。</p><label><input type="radio" name="pb-compatibility" value="compatible" data-pb-compatibility> 直接兼容上一发布</label><label><input type="radio" name="pb-compatibility" value="validate" data-pb-compatibility> 升级时校验已有数据</label><footer><button class="pb-button" type="button" data-pb-publish-cancel>取消</button><button class="pb-button pb-primary" type="button" data-pb-publish-confirm disabled>确认并发布候选版本</button></footer></dialog>
</div></section>`;}
