export const FUNCTIONS_EN: Record<string, string> = {
  "仅列出插件已声明的工具和页面动作。": "Only declared plugin tools and page actions are listed.",
  "重新加载": "Reload",
  "新事项来时，建议整理成稿、先核查或处理状态": "Suggest drafting, verification or status changes for new items",
  "配置 TypeSafe API Key": "Configure TypeSafe API Key",
  "新建判断": "New judgment",
  "还没有判断": "No judgments yet",
  "点「新建判断」。": "Click New judgment.",
  "返回列表": "Back",
  "函数": "Function",
  "判断": "Judgment",
  "名称": "Name",
  "函数 key": "Function key",
  "发布后不能改。": "Locked after publish.",
  "说明": "Instructions",
  "怎么判断": "How to judge",
  "选项": "Options",
  "可选动作": "Actions",
  "添加": "Add",
  "试一段": "Try this",
  "试跑": "Preview",
  "发布 v1": "Publish v1",
  "未命名函数": "Untitled",
  "草稿": "Draft",
  "已选出": "Picked",
  "需要复核": "Needs review",
  "可选": "Optional",
  "去掉选项": "Remove option",
  "Choice 至少需要两个选项": "A Choice needs at least two options",
  "Functions 请求失败": "Request failed",
  "保存失败": "Could not save",
  "试跑用 TypeSafe 的 Jev。": "Preview runs on TypeSafe's Jev.",
  "TypeSafe API Key": "TypeSafe API Key",
  "来自 TYPESAFE_API_KEY。": "From TYPESAFE_API_KEY.",
  "已保存。": "Saved.",
  "还没填。": "Not set.",
  "保存": "Save",
  "清除": "Clear",
  "保存后不再显示。": "Hidden after save.",
  "Inbox、首页、Feed 显示哪个按钮。": "Which button Inbox, Home, or Feed should show.",
  "删除草稿": "Delete draft",
  "样例": "Samples",
  "存为样例": "Save as sample",
  "关闭": "Close",
  "成不成立": "Yes or no",
  "选动作": "Pick an action",
  "打分": "Score",
  "成立时": "When true",
  "不成立时": "When false",
  "档位": "Levels",
  "档位说明": "Level",
  "去掉档位": "Remove level",
  "Score 至少需要两个档位": "A Score needs at least two levels",
  "成立概率": "Probability",
  "分类结果": "Class",
  "可能计费。": "May be billed.",
  "已发布。": "Published.",
  "载入": "Load",
  "去掉样例": "Remove sample",
  "确定删除这个草稿？": "Delete this draft?",
  "模型概率不是正确率。": "Probability is not accuracy.",
  "判断完成": "Judged",
  "用在哪": "Used in",
  "首页卡底": "Home dock",
  "Feed 捕捉规则": "Feed capture rules",
  "Inbox 下一步": "Inbox next step",
  "还没有说明": "No instructions yet",
  "试过": "Tried",
  "看什么": "Looks at",
  "首页、Inbox、Feed 要用 Choice。": "Home, Inbox, and Feed need Choice.",
  "先选「用在哪」。": "Pick Used in first.",
  "Feed 消息": "Feed item",
  "Inbox": "Inbox",
  "来源出错": "Source error",
  "首页事件": "Home event",
  "Session": "Session",
  "Agent": "Agent",
  "首页": "Home",
  "点开事件时，亮哪些按钮": "Which buttons to show when an event opens",
  "发布后打开": "Turn on after publish",
  "亮哪些按钮": "Which buttons to show",
  "新事项来时，显示「做完了」还是「忽略」": "Done or Dismiss when an item arrives",
  "显示「做完了」还是「忽略」": "Done or Dismiss",
  "Feed": "Feed",
  "这条消息该进 Inbox、存资料、升格还是忽略": "Inbox, save, promote, or dismiss this message",
  "去任务捕捉规则里选": "Pick it in the task's capture rules",
  "亮哪条去向": "Which destination to show",
  "给 Agent 选动作": "Pick an action for the agent",
  "发布后可用": "Ready after publish",
  "系统": "System",
  "插件": "Plugin",
  "MCP": "MCP",
  "看": "Read",
  "写": "Write",
  "还没选": "None",
  "先发布。": "Publish first.",
  "先打开项目。": "Open a project first.",
  "Inbox 在用。": "Inbox is using this.",
  "首页在用。": "Home is using this.",
  "正在用": "Using",
  "正在用另一个。": "Using another one.",
  "换成这个": "Use this",
  "用在 Inbox": "Use in Inbox",
  "用在首页": "Use on Home",
  "停用": "Deactivate",
  "没读到": "Could not read",
  "没打开": "Could not turn on",
  "去 Feed 任务里选。": "Pick it in a Feed task.",
  "发布后可用。": "Ready after publish.",
  "给 Agent": "For the agent",
  "这段判断看哪些对象，可以不选。": "What this judgment looks at. Optional.",
  "函数可以单独存在，不必绑现场。": "The function can stand alone. Binding is optional.",
  "先不落地": "Not used yet",
  "只写判断，稍后才绑。": "Write the judgment first, bind later.",
  "对到现场按钮": "Map to a button",
  "还没对上": "Not mapped",
  "对上之后才能用在这里。": "Map every option before using it here.",
  "从动作库加入": "Add from actions",
  "加入": "Add",
  "选项是这道判断的答案，不必等于现场按钮。": "Options are this judgment's answers, not necessarily the on-site buttons.",
  "这些动作跟着「看什么」和「用在哪」更新。": "These actions follow Looks at and Used in.",
  "勾选的对象在这里没有对应动作。": "The selected objects have no actions here.",
  "Score 不能绑 Inbox、首页、Feed。": "Score cannot bind to Inbox, Home, or Feed.",
  "成立": "True",
  "不成立": "False",
  "选项 key": "Option key",
  "上一步": "Previous",
  "下一步：判断规则": "Next: judgment rules",
  "下一步：试跑与启用": "Next: test and activate",
  "不选时显示该用途的全部动作；选择对象只筛选建议动作，不会自动读取数据。": "Leave empty to show all actions for this use. This filters suggestions; it does not read data.",
  "什么情况下选择这个结果？": "When should this result be chosen?",
  "从插件能力中添加结果": "Add results from plugin capabilities",
  "使用状态": "Usage status",
  "例如：优先跟进与当前项目相关、需要我采取行动的消息；广告和重复内容可以忽略。": "For example: follow up on messages related to this project that need my action; ignore ads and duplicates.",
  "例如：把紧急程度分为低、中、高。Score": "For example: rate urgency as low, medium or high. Score",
  "例如：筛选值得跟进的消息": "For example: find messages worth following up",
  "例如：跟进、保存还是忽略。Choice": "For example: follow up, save or ignore. Choice",
  "例如：这份材料是否足够。Noul": "For example: is this material sufficient? Noul",
  "供 Agent 和接口调用，已自动生成；发布后不能改。": "Generated for agent and API calls. Locked after publishing.",
  "先写规则、试跑，暂不接入页面。": "Write and test rules without connecting a page yet.",
  "先试一段，再投入使用": "Test your judgment before using it",
  "先选择用途或判断对象，即可查看相关能力。": "Choose a use or subject to see relevant capabilities.",
  "写清判断依据，再定义可能的结果。草稿会自动保存。": "Explain how to judge, then define the possible results. Drafts save automatically.",
  "函数设置步骤": "Function setup steps",
  "判断对象": "Judgment subjects",
  "判断是或否": "Decide yes or no",
  "判断结果用于推荐页面动作。发布后还需要在当前项目启用。": "Results suggest page actions. Activate in this project after publishing.",
  "判断规则": "Judgment rules",
  "判断说明": "Judgment instructions",
  "发布与启用": "Publish and activate",
  "发布会锁定名称、规则和用途。确认试跑符合预期后再发布；发布不会自动启用页面判断。": "Publishing locks the name, rules and use. Check a test result first. Publishing does not activate page judgments.",
  "发布后，Agent 可以按函数 key 请求判断。": "After publishing, an agent can request a judgment using the function key.",
  "发布后，到 Feed 任务的捕捉规则中选择此函数；具体处理由该规则决定。": "After publishing, select this function in a Feed task's capture rules. The rule determines what happens next.",
  "只读": "Read only",
  "可先保存和试跑，不必绑定任何页面。发布后也可通过接口调用。": "Save and test without binding a page. Published functions can also be called through the API.",
  "告诉 AI 怎么判断": "Tell AI how to judge",
  "在哪里使用结果": "Where to use the result",
  "已保存": "Saved",
  "已保存的样例": "Saved samples",
  "已发布 · 规则只读": "Published · read-only rules",
  "已发布，可通过 Functions 调用工具按函数 key 请求判断。": "Published. Use the Functions invoke tool with the function key to request a judgment.",
  "已按用途提供动作。请补充每个动作的选择条件；切换用途会更新默认动作，自定义结果会保留。": "Actions are suggested for this use. Describe when to choose each. Changing the use updates default actions and keeps custom results.",
  "所选对象没有足够的适用动作。请返回选择用途，调整判断对象，或自定义结果。": "There are not enough actions for these subjects. Adjust subjects in the first step or define custom results.",
  "执行时修改数据": "Changes data when executed",
  "把重复的判断写成规则，试跑后用在页面或交给 Agent。点「新建判断」开始。": "Turn recurring decisions into rules, test them, then use them in pages or with an agent. Start with New judgment.",
  "按等级评分": "Rate on a scale",
  "搜索插件、动作或用途": "Search plugins, actions or uses",
  "搜索能力": "Search capabilities",
  "是非": "Yes / no",
  "是非判断：返回成立的概率，例如材料是否足够。": "Yes / no: returns the probability of a statement, such as whether material is sufficient.",
  "有更改，等待保存…": "Changes waiting to save…",
  "未保存 · 请修正后重试": "Not saved · fix the issue and retry",
  "标识": "Key",
  "正在保存…": "Saving…",
  "正在试跑…": "Testing…",
  "正在请求判断，通常需要几秒。": "Requesting a judgment. This usually takes a few seconds.",
  "每个结果都需要对应一个动作，才能在所选页面启用。": "Map every result to an action before activating it on this page.",
  "没有匹配的能力，试试其他关键词。": "No matching capabilities. Try a different search.",
  "没有可添加的动作：可能已加入全部结果，或所选对象不适用于此用途。": "No actions to add. They may already be included, or the selected subjects may not apply here.",
  "独立使用": "Standalone",
  "独立使用：未绑定页面。": "Standalone: no page is bound.",
  "等级评分：按你定义的档位返回分数，例如紧急程度。": "Rating: returns a score on your scale, such as urgency.",
  "粘贴一条真实场景中的消息或材料，看看判断是否符合预期。": "Paste a message or material from a real scenario to check the judgment.",
  "结果": "Result",
  "结果对应的页面动作": "Map results to page actions",
  "结果标识": "Result key",
  "结果选择：从你定义的结果中选出一个，例如跟进、保存或忽略。": "Choice: picks one of your results, such as follow up, save or ignore.",
  "至少保留两个结果，说明各自在什么情况下被选中。": "Keep at least two results and explain when each should be chosen.",
  "草稿尚未生效。发布后将在这里显示启用入口。": "This draft is not active. Activation will be available here after publishing.",
  "草稿自动保存": "Drafts save automatically",
  "规则已锁定，可以继续试跑，并查看或调整使用状态。": "Rules are locked. You can still test and manage usage.",
  "让 AI 帮你做哪种判断？": "What should AI help you decide?",
  "评分": "Rating",
  "评分用于独立试跑或 Agent 调用；页面按钮需要选择或是非判断。": "Ratings work standalone or with agents. Page actions require a choice or yes / no judgment.",
  "试跑与启用": "Test and activate",
  "试跑内容": "Test input",
  "试跑只返回判断结果，不执行选出的动作。TypeSafe 可能收取调用费用。": "Tests return a judgment without executing the selected action. TypeSafe may charge for the call.",
  "请选择对应动作": "Choose a matching action",
  "返回哪些结果": "Possible results",
  "返回建议给 Agent；不会自动执行工具。实际调用取决于工具启用状态和权限。": "Returns a suggestion to the agent without running tools. Calls depend on tool enablement and permissions.",
  "还有结果未对应页面动作，请补齐后再发布。": "Some results are not mapped to page actions. Complete the mapping before publishing.",
  "这里只选择判断可能返回的动作，不会执行。Agent 调用还需启用对应工具并满足权限。": "Choose actions the judgment may return; nothing runs here. Agents need the corresponding tools enabled and permitted.",
  "选择": "Choice",
  "选择一个结果": "Choose one result",
  "选择此结果的条件": "When to choose this result",
  "选择用途": "Choose a use",
  "选择用途后，再写判断规则。也可以先做一个独立函数。": "Choose where to use the result, then write the rules. You can also start with a standalone function.",
  "限定判断对象（可选）": "Limit judgment subjects (optional)",
  "高级：调用标识": "Advanced: invocation key",
};
