/** Shelf workbench client: select, extract, ingest, DropAgent command bar. */
export const SHELF_CLIENT_FACTORY_SCRIPT = `(host) => {
  const { translate: L } = host;
  const directory = document.querySelector("[data-shelf=directory]");
  const workbench = document.querySelector("[data-shelf=workbench]");
  if (!directory || !workbench) return;
  const stage = workbench.querySelector("[data-shelf-stage]");
  const preview = workbench.querySelector("[data-shelf-preview]");
  const bar = workbench.querySelector("[data-shelf-bar]");
  const fileInput = directory.querySelector("[data-shelf-file]");
  const search = directory.querySelector("[data-shelf-search]");
  const CLIP_PREVIEW = 3;
  let snapshot = { materials: [], results: [], clipboard: [], recipes: [], current_clip_id: null };
  let selected = null;
  let selectedClip = null;
  let clipSelection = new Set();
  let clipExpanded = false;
  let compare = false;
  let compareSourceId = null;
  let editing = false;
  let editTimer = 0;
  let arranging = false;
  let hiddenActs = new Set();
  let lastBarKind = "empty";
  let stickyHint = "";
  const fileUrl = (id) => "/api/shelf/items/" + encodeURIComponent(id) + "/file";
  const TEXT_EDIT = { txt:1, md:1, markdown:1, json:1, swift:1, py:1, js:1, ts:1, mjs:1, css:1, yaml:1, yml:1, xml:1, toml:1, ini:1, rs:1, go:1, rb:1, sh:1, zsh:1, c:1, h:1, cc:1, cpp:1, m:1, mm:1, csv:1, log:1 };
  const isEditable = (item) => {
    if (!item) return false;
    if (item.kind === "pdf" || item.kind === "image" || item.kind === "folder" || item.kind === "url" || item.kind === "website") return false;
    const ext = String(item.name || "").split(".").pop()?.toLowerCase() || "";
    if (ext === "html" || ext === "htm") return false;
    if (item.kind === "markdown" || item.kind === "text") return true;
    return Boolean(TEXT_EDIT[ext]);
  };
  const isConcealed = (types) => types.some((type) => /org\\.nspasteboard\\.(concealedtype|autogeneratedtype|transienttype)/i.test(String(type)));

  const post = async (path, body) => {
    const headers = typeof molisWorkControlHeaders === "function" ? molisWorkControlHeaders() : { "content-type": "application/json" };
    const response = await fetch(path, { method: "POST", headers, body: JSON.stringify(body || {}) });
    const payload = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(payload.error || L("Shelf 请求失败"));
    return payload;
  };

  const cap = (kind) => kind === "pdf" ? "PDF" : kind === "markdown" ? "MD" : kind === "image" ? "IMG" : kind === "website" ? "WEB" : kind === "url" ? "URL" : "FILE";
  const tone = (kind, group) => group === "clipboard" ? (kind === "url" ? "blue" : "slate") : kind === "pdf" ? "clay" : kind === "image" ? "plum" : kind === "url" || kind === "website" ? "blue" : kind === "markdown" || kind === "text" ? "slate" : "ochre";
  const items = () => [...(snapshot.materials || []), ...(snapshot.results || [])];
  const stageBusy = () => stage.classList.contains("is-confirm") || stage.classList.contains("is-run") || stage.classList.contains("is-fail");

  const paintLists = () => {
    const query = (search?.value || "").trim().toLowerCase();
    const busyId = () => stageBusy() && selected && !selectedClip ? selected.item_id : "";
    const fill = (group, entries, countTotal) => {
      const list = directory.querySelector('[data-shelf-list="' + group + '"]');
      if (!list) return;
      const visible = entries.filter((item) => !query || String(item.name || item.title || "").toLowerCase().includes(query));
      if (!visible.length) {
        list.innerHTML = '<li class="shelf-empty-line" data-shelf-empty>' + escapeText(group === "clipboard" ? L("剪贴板是空的") : group === "results" ? L("还没有生成结果") : L("还没有材料")) + "</li>";
      } else {
        list.replaceChildren(...visible.map((item) => {
          const node = document.createElement("template");
          node.innerHTML = group === "clipboard" ? clipHtml(item) : itemHtml(item, selected?.item_id === item.item_id, busyId() === item.item_id);
          return node.content.firstElementChild;
        }));
      }
      const count = directory.querySelector('[data-shelf-count="' + group + '"]');
      if (count) count.textContent = String(countTotal ?? entries.length);
    };
    const clips = snapshot.clipboard || [];
    const shown = clipExpanded || clips.length <= CLIP_PREVIEW ? clips : clips.slice(0, CLIP_PREVIEW);
    fill("materials", snapshot.materials || []);
    fill("results", snapshot.results || []);
    fill("clipboard", shown, clips.length);
    const resultsWrap = directory.querySelector("[data-shelf-results]");
    if (resultsWrap) resultsWrap.hidden = (snapshot.results || []).length === 0;
    const more = directory.querySelector("[data-shelf-clip-more]");
    if (more) {
      more.hidden = clips.length <= CLIP_PREVIEW;
      more.textContent = clipExpanded ? L("显示最近 3 条") : L("显示全部");
    }
    const hint = directory.querySelector("[data-shelf-clip-hint]");
    if (hint) hint.hidden = clips.length === 0;
  };

  const itemHtml = (item, on, locked) => {
    const lock = locked ? ' aria-disabled="true"' : "";
    return '<li class="shelf-row' + (on ? " is-on" : "") + '" data-shelf-item="' + escapeAttr(item.item_id) + '" data-shelf-kind="' + escapeAttr(item.kind) + '" data-shelf-group="' + escapeAttr(item.group) + '" data-shelf-name="' + escapeAttr(item.name) + '" role="option" aria-selected="' + String(on) + '" draggable="true">' +
      '<span class="shelf-glyph tone-' + tone(item.kind, item.group) + '">' + glyphSvg(item.kind) + "</span>" +
      '<span class="shelf-name">' + escapeText(item.name) + "</span>" +
      '<span class="shelf-cap">' + cap(item.kind) + "</span>" +
      '<span class="shelf-ops"><span class="shelf-op" role="button" tabindex="0" data-shelf-row-action="copy" aria-label="' + L("复制") + '">' + opSvg("copy") + '</span><span class="shelf-op" role="button" tabindex="0" data-shelf-row-action="hide" aria-label="' + L("隐藏（列表拿掉，副本还在）") + '" title="' + L("隐藏（列表拿掉，副本还在）") + '"' + lock + '>' + opSvg("hide") + '</span><span class="shelf-op is-danger" role="button" tabindex="0" data-shelf-row-action="delete" aria-label="' + L("删除副本") + '" title="' + L("删除副本") + '"' + lock + '>' + opSvg("trash") + "</span></span></li>";
  };
  const clipHtml = (clip) => {
    const kind = clip.kind === "url" ? "url" : "text";
    const on = clipSelection.has(clip.clip_id);
    const current = snapshot.current_clip_id === clip.clip_id;
    return '<li class="shelf-row' + (on ? " is-on" : "") + '" data-shelf-clip="' + escapeAttr(clip.clip_id) + '" data-shelf-kind="' + kind + '" data-shelf-group="clipboard" data-shelf-name="' + escapeAttr(clip.title) + '" role="option" aria-selected="' + String(on) + '">' +
      '<span class="shelf-glyph tone-' + tone(kind, "clipboard") + '">' + glyphSvg(kind) + "</span>" +
      '<span class="shelf-name">' + escapeText(clip.title) + "</span>" +
      (current ? '<span class="shelf-now" data-shelf-current>' + escapeText(L("当前")) + "</span>" : "") +
      '<span class="shelf-ops"><span class="shelf-op" role="button" tabindex="0" data-shelf-row-action="copy" aria-label="' + L("复制") + '">' + opSvg("copy") + '</span><span class="shelf-op" role="button" tabindex="0" data-shelf-row-action="join" aria-label="' + L("加入材料") + '">' + opSvg("down") + '</span><span class="shelf-op is-danger" role="button" tabindex="0" data-shelf-row-action="delete" aria-label="' + L("删除记录") + '" title="' + L("删除记录") + '">' + opSvg("trash") + "</span></span></li>";
  };
  const glyphSvg = (kind) => {
    if (kind === "image") return '<svg viewBox="0 0 24 24"><rect x="4" y="5" width="16" height="14" rx="2"/><circle cx="9" cy="10" r="1.5"/><path d="m4 16 4-4 3 3 3-4 6 5"/></svg>';
    if (kind === "url") return '<svg viewBox="0 0 24 24"><path d="M10 13a5 5 0 0 0 7 0l2-2a5 5 0 0 0-7-7l-1 1"/><path d="M14 11a5 5 0 0 0-7 0l-2 2a5 5 0 0 0 7 7l1-1"/></svg>';
    if (kind === "website") return '<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a14 14 0 0 1 0 18M12 3a14 14 0 0 0 0 18"/></svg>';
    if (kind === "markdown") return '<svg viewBox="0 0 24 24"><path d="M7 3h7l5 5v13a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z"/><path d="M14 3v6h6M8 13h8M8 17h5"/></svg>';
    if (kind === "text") return '<svg viewBox="0 0 24 24"><rect x="7" y="4" width="10" height="16" rx="2"/><path d="M9 8h6M9 12h4"/></svg>';
    return '<svg viewBox="0 0 24 24"><path d="M7 3h7l5 5v13a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z"/><path d="M14 3v6h6"/></svg>';
  };
  const opSvg = (name) => {
    const map = { copy: "copy", hide: "x", down: "download", trash: "trash" };
    return '<svg aria-hidden="true"><use href="#icon-' + (map[name] || "file") + '"></use></svg>';
  };

  const welcome = () => '<div class="shelf-welcome"><h2>' + L("材料放进来，结果拿出去") + "</h2><p>" + L("先放下，再决定要不要跑。原件不动。没有 Agent 也可以先提取 PDF 里的字。") + '</p><div class="shelf-cta"><span class="shelf-primary" role="button" tabindex="0" data-shelf-sample>' + L("试用示例 PDF") + '</span><span class="shelf-paper" role="button" tabindex="0" data-shelf-pick>' + L("选择我的文件") + "</span></div></div>";
  const idle = () => '<div class="shelf-idle"><p style="font-size:17px;font-weight: 400;color:var(--da-text)">' + L("选择一份材料") + "</p><p>" + L("在这里预览，使用下方指令处理副本。") + "</p></div>";
  const docHtml = (kicker, title, body) => '<div class="shelf-preview-inner shelf-doc"><p class="shelf-kicker">' + escapeText(kicker) + '</p><h1 class="shelf-title">' + escapeText(title) + "</h1>" + String(body || "").split(/\\n+/).map((line) => "<p>" + escapeText(line) + "</p>").join("") + "</div>";
  const previewPane = (item, kicker) => {
    if (!item) {
      return '<div class="shelf-preview-inner shelf-doc"><p class="shelf-kicker">' + escapeText(kicker || L("原文")) + '</p><p class="muted">' + escapeText(L("原材料已不在工作区，无法对照。")) + "</p></div>";
    }
    const label = kicker || item.name;
    if (item.kind === "pdf") {
      return '<div class="shelf-preview-inner"><p class="shelf-kicker">' + escapeText(label) + '</p><iframe class="shelf-pdf-frame" title="' + escapeAttr(item.name) + '" src="' + fileUrl(item.item_id) + '"></iframe>' + (item.preview_text ? '<div class="shelf-doc" style="margin-top:24px"><p class="muted">' + escapeText(item.preview_text) + "</p></div>" : "") + "</div>";
    }
    if (item.kind === "image") {
      return '<div class="shelf-preview-inner"><p class="shelf-kicker">' + escapeText(label) + '</p><img class="shelf-image" alt="" src="' + fileUrl(item.item_id) + '"></div>';
    }
    return docHtml(label, String(item.name || "").replace(/\\.[^.]+$/, ""), item.preview_text || "");
  };
  const comparisonSources = () => {
    const id = selected?.source_item_id;
    if (!id) return [];
    return items().filter((item) => item.item_id === id);
  };
  const syncStage = () => {
    const comparing = Boolean(compare && selected?.group === "result");
    const busy = stageBusy();
    stage.classList.toggle("is-result", Boolean(selected?.group === "result"));
    stage.classList.toggle("is-compare", comparing);
    stage.classList.toggle("is-item", Boolean(selected && !selectedClip));
    const compareBtn = workbench.querySelector("[data-shelf-compare]");
    if (compareBtn) {
      compareBtn.classList.toggle("is-on", comparing);
      compareBtn.setAttribute("aria-pressed", comparing ? "true" : "false");
    }
    const chrome = workbench.querySelector("[data-shelf-chrome]");
    const title = workbench.querySelector("[data-shelf-chrome-title]");
    const tag = workbench.querySelector("[data-shelf-chrome-tag]");
    const editBtn = workbench.querySelector("[data-shelf-edit]");
    if (chrome) chrome.hidden = !(selected && !selectedClip);
    if (title) title.textContent = selected && !selectedClip ? selected.name : "";
    if (tag) {
      const group = selected?.group === "result" ? L("结果") : L("材料");
      tag.textContent = selected && !selectedClip ? group + " · " + cap(selected.kind) : "";
    }
    if (editBtn) {
      const allow = Boolean(selected && !selectedClip && isEditable(selected) && !busy);
      editBtn.hidden = !allow;
      editBtn.textContent = editing ? L("完成编辑") : L("编辑副本");
      editBtn.classList.toggle("is-on", editing);
      editBtn.setAttribute("aria-pressed", editing ? "true" : "false");
    }
  };
  const editorHtml = (item) => {
    const ext = String(item.name || "").split(".").pop()?.toLowerCase() || "";
    const code = ext !== "md" && ext !== "txt" && ext !== "markdown";
    return '<div class="shelf-editor-wrap"><p class="shelf-edit-hint">' + escapeText(L("正在编辑副本。原文件保持不变。")) + '</p><textarea class="shelf-editor' + (code ? " is-code" : "") + '" data-shelf-editor spellcheck="false">' + escapeText(item.preview_text || "") + "</textarea></div>";
  };

  const paintPreview = () => {
    stage.classList.remove("is-confirm", "is-run", "is-fail");
    const line = workbench.querySelector("[data-shelf-run-line]");
    if (line) line.hidden = true;
    syncStage();
    if (compare && selected?.group === "result") {
      const sources = comparisonSources();
      if (!compareSourceId || !sources.some((item) => item.item_id === compareSourceId)) {
        compareSourceId = sources[0]?.item_id ?? null;
      }
      const source = sources.find((item) => item.item_id === compareSourceId) || null;
      const nav = sources.length > 1
        ? '<div class="shelf-compare-nav">' + sources.map((item) => '<button type="button" class="shelf-source' + (item.item_id === source?.item_id ? " is-on" : "") + '" data-shelf-source="' + escapeAttr(item.item_id) + '">' + escapeText(item.name) + "</button>").join("") + "</div>"
        : "";
      preview.innerHTML = '<div class="shelf-compare" data-shelf-compare-layout>' +
        '<div data-shelf-compare-pane="source">' + nav + previewPane(source, L("原文") + (source ? " · " + source.name : "")) + "</div>" +
        '<div class="shelf-rule"></div>' +
        '<div data-shelf-compare-pane="result">' + (editing ? editorHtml(selected) : previewPane(selected, L("结果") + " · " + selected.name)) + "</div>" +
        "</div>";
      renderBar("result");
      focusEditor();
      return;
    }
    if (selectedClip) {
      preview.innerHTML = docHtml(L("点选只预览"), selectedClip.title, selectedClip.body) +
        '<p class="shelf-clip-foot">' + escapeText(L("仅预览历史记录 · 加入材料后可运行指令")) + "</p>";
      renderBar("clipboard");
      return;
    }
    if (!selected) {
      preview.innerHTML = (snapshot.materials || []).length ? idle() : welcome();
      renderBar((snapshot.materials || []).length ? "none" : "empty");
      return;
    }
    preview.innerHTML = editing && isEditable(selected) ? editorHtml(selected) : previewPane(selected);
    renderBar(selected.group === "result" ? "result" : selected.kind);
    focusEditor();
  };

  const showPreview = () => {
    compare = false;
    compareSourceId = null;
    paintPreview();
  };

  const focusEditor = () => {
    const editor = preview.querySelector("[data-shelf-editor]");
    if (!editor) return;
    editor.focus();
    const end = editor.value.length;
    editor.setSelectionRange(end, end);
  };
  const saveCopy = async (text) => {
    if (!selected) return;
    const payload = await post("/api/shelf/items/" + encodeURIComponent(selected.item_id) + "/edit", { text });
    snapshot = payload.snapshot;
    selected = items().find((item) => item.item_id === selected.item_id) || payload.item || selected;
  };
  const flushEdit = async () => {
    if (editTimer) { clearTimeout(editTimer); editTimer = 0; }
    if (!editing || !selected) return;
    const editor = preview.querySelector("[data-shelf-editor]");
    if (editor) await saveCopy(editor.value);
  };
  const stopEdit = async () => {
    await flushEdit();
    editing = false;
    paintPreview();
  };
  const startEdit = () => {
    if (!selected || !isEditable(selected)) return;
    if (stageBusy()) return;
    editing = true;
    paintPreview();
  };

  const recipeSvg = (id) => {
    const icon = id === "extract" ? "file" : id === "use" || id === "join" ? "download" : id === "talk" ? "message" : id === "pick" ? "plus" : "list";
    const tone = id === "extract" ? "clay" : id === "use" || id === "join" ? "ochre" : id === "talk" ? "plum" : "slate";
    return '<svg class="tone-' + tone + '" aria-hidden="true"><use href="#icon-' + icon + '"></use></svg>';
  };
  const agentMissing = () => (snapshot.recipes || []).some((item) => item.recipe !== "extract_text" && item.available === false);
  const renderBar = (kind) => {
    lastBarKind = kind;
    const hint = workbench.querySelector("[data-shelf-bar-hint]");
    if (hint) {
      if (stickyHint) {
        hint.hidden = false;
        hint.textContent = stickyHint;
      } else {
        hint.hidden = !(kind === "pdf" || kind === "text" || kind === "markdown" || kind === "image" || kind === "url" || kind === "website") || !agentMissing();
      }
    }
    if (kind === "empty") {
      bar.innerHTML = actButton(L("新建"), "pick", true);
      return;
    }
    const extract = (snapshot.recipes || []).find((item) => item.recipe === "extract_text");
    const extractOn = extract && extract.available !== false;
    const canExtract = (kind === "pdf" || kind === "text" || kind === "markdown") && extractOn;
    const recipes = [];
    if (canExtract && !hiddenActs.has("extract")) {
      recipes.push(actChip("extract", extract.label || L("提取文字"), true));
    } else if (arranging && canExtract && hiddenActs.has("extract")) {
      recipes.push('<span class="shelf-act" role="button" tabindex="0" data-shelf-restore-act="extract">' + recipeSvg("extract") + escapeText(L("加回动作栏")) + "</span>");
    }
    if (kind === "result") recipes.push(actButton(L("用作材料"), "use", true));
    if (kind === "clipboard") {
      const count = Math.max(clipSelection.size, selectedClip ? 1 : 0);
      recipes.push(actButton(count > 1 ? L("加入材料") + " · " + count : L("加入材料"), "join", true));
    }
    bar.innerHTML = '<div class="shelf-bar-scroll">' + recipes.join("") + '</div>' +
      '<span class="shelf-act-rule" data-shelf-act-rule aria-hidden="true"></span>' +
      actButton(L("对话"), "talk", true, L("打开终端会话。不会生成新文件。发给终端请用轮盘。")) +
      moreButton();
  };
  const fillConfirm = () => {
    if (!selected) return;
    const pdf = selected.kind === "pdf";
    const outName = pdf ? "pdf.md" : "extract.md";
    const title = pdf ? L("提取 PDF 文字") : L("提取文字");
    const setText = (selector, value) => {
      const node = workbench.querySelector(selector);
      if (node) node.textContent = value;
    };
    setText("[data-shelf-confirm-title]", title);
    setText("[data-shelf-confirm-out]", pdf ? L("将生成 pdf.md。原文件保持不变。") : L("将生成 extract.md。原文件保持不变。"));
    setText('[data-shelf-fact="action"]', title + " → " + outName);
    setText('[data-shelf-fact="read"]', L("任务副本") + " work/" + selected.name);
    setText('[data-shelf-fact="write"]', "output/" + outName);
  };
  const actButton = (label, id, enabled, title) => {
    return '<span class="shelf-act' + (id === "talk" && stage.classList.contains("is-talk") ? " is-on" : "") + '" role="button" tabindex="' + (enabled ? "0" : "-1") + '" data-shelf-act="' + id + '"' + (enabled ? "" : ' aria-disabled="true"') + (title ? ' title="' + escapeAttr(title) + '"' : "") + ">" + recipeSvg(id) + escapeText(label) + "</span>";
  };
  const actChip = (id, label, enabled) => {
    const hide = arranging
      ? '<span class="shelf-act-hide" role="button" tabindex="0" data-shelf-hide-act="' + id + '" title="' + escapeAttr(L("从栏上拿掉")) + '">' + opSvg("hide") + "</span>"
      : "";
    const grip = arranging ? '<span class="shelf-act-grip" aria-hidden="true"></span>' : "";
    return '<span class="shelf-act-wrap">' + grip + actButton(label, id, enabled) + hide + "</span>";
  };
  const moreButton = () => {
    return '<span class="shelf-more"><span class="shelf-act" role="button" tabindex="0" data-shelf-more title="' + escapeAttr(L("管理动作")) + '" aria-haspopup="menu">···</span><div class="shelf-more-menu" data-shelf-more-menu hidden><span class="shelf-more-item" role="menuitem" tabindex="0" data-shelf-arrange>' + escapeText(arranging ? L("完成整理") : L("整理动作")) + '</span><span class="shelf-more-item" role="menuitem" tabindex="0" data-shelf-pick>' + escapeText(L("新建")) + "</span></div></span>";
  };

  const applySnapshot = (next, selectId) => {
    snapshot = next;
    if (selectId) {
      editing = false;
      selectedClip = null;
      clipSelection = new Set();
      selected = items().find((item) => item.item_id === selectId) || null;
      compare = false;
      compareSourceId = null;
    } else {
      if (selected) selected = items().find((item) => item.item_id === selected.item_id) || null;
      if (selectedClip) selectedClip = (snapshot.clipboard || []).find((clip) => clip.clip_id === selectedClip.clip_id) || null;
      clipSelection = new Set([...clipSelection].filter((id) => (snapshot.clipboard || []).some((clip) => clip.clip_id === id)));
      if (selectedClip && !clipSelection.has(selectedClip.clip_id)) clipSelection.add(selectedClip.clip_id);
      if (!selected || selected.group !== "result") {
        compare = false;
        compareSourceId = null;
      }
    }
    paintLists();
    paintPreview();
  };

  const load = async (selectId) => {
    const response = await fetch("/api/shelf", { cache: "no-store" });
    if (!response.ok) throw new Error(L("无法读取置物架"));
    applySnapshot(await response.json(), selectId);
  };

  const admitFiles = async (files) => {
    let lastId = "";
    for (const file of files) {
      const bytes = new Uint8Array(await file.arrayBuffer());
      const payload = await post("/api/shelf/items", { filename: file.name, mime: file.type, bytes_base64: bufferToBase64(bytes) });
      lastId = payload.item?.item_id || lastId;
      snapshot = payload.snapshot;
    }
    applySnapshot(snapshot, lastId);
  };

  const selectItem = async (id) => {
    stickyHint = "";
    await flushEdit();
    editing = false;
    selectedClip = null;
    clipSelection = new Set();
    selected = items().find((item) => item.item_id === id) || null;
    compare = false;
    compareSourceId = null;
    paintLists();
    paintPreview();
  };

  const selectClip = (clipId, command) => {
    void flushEdit();
    editing = false;
    selected = null;
    compare = false;
    compareSourceId = null;
    if (command) {
      if (clipSelection.has(clipId)) clipSelection.delete(clipId);
      else clipSelection.add(clipId);
      selectedClip = (snapshot.clipboard || []).find((clip) => clip.clip_id === clipId) || selectedClip;
      if (selectedClip && !clipSelection.has(selectedClip.clip_id)) {
        selectedClip = (snapshot.clipboard || []).find((clip) => clipSelection.has(clip.clip_id)) || null;
      }
      if (!clipSelection.size) selectedClip = null;
    } else if (selectedClip?.clip_id === clipId && clipSelection.size <= 1) {
      selectedClip = null;
      clipSelection = new Set();
    } else {
      selectedClip = (snapshot.clipboard || []).find((clip) => clip.clip_id === clipId) || null;
      clipSelection = selectedClip ? new Set([selectedClip.clip_id]) : new Set();
    }
    paintLists();
    paintPreview();
  };

  const makeClipCurrent = async (clipId) => {
    const clip = (snapshot.clipboard || []).find((item) => item.clip_id === clipId);
    if (!clip) return;
    try { await navigator.clipboard.writeText(clip.body); } catch {}
    const payload = await post("/api/shelf/clipboard", { text: clip.body });
    selected = null;
    selectedClip = payload.clip || (payload.snapshot.clipboard || []).find((item) => item.clip_id === clipId) || clip;
    clipSelection = selectedClip ? new Set([selectedClip.clip_id]) : new Set();
    applySnapshot(payload.snapshot);
  };

  const copyShelfItem = async (id, name) => {
    const item = items().find((entry) => entry.item_id === id);
    if (item && (item.kind === "markdown" || item.kind === "text" || item.kind === "url" || item.kind === "website")) {
      const text = item.preview_text || await (await fetch(fileUrl(id))).text();
      try { await navigator.clipboard.writeText(text); } catch {}
      return;
    }
    const link = document.createElement("a");
    link.href = fileUrl(id);
    link.download = name;
    link.click();
  };

  const joinClips = async (ids) => {
    let lastId = "";
    let next = snapshot;
    for (const id of ids) {
      const payload = await post("/api/shelf/clipboard/" + encodeURIComponent(id) + "/material");
      lastId = payload.item?.item_id || lastId;
      next = payload.snapshot;
    }
    selectedClip = null;
    clipSelection = new Set();
    applySnapshot(next, lastId);
  };

  directory.addEventListener("click", async (event) => {
    if (event.target.closest("[data-shelf-clip-more]")) {
      event.preventDefault();
      clipExpanded = !clipExpanded;
      paintLists();
      return;
    }
    const action = event.target.closest("[data-shelf-row-action]");
    const row = event.target.closest("[data-shelf-item], [data-shelf-clip]");
    if (action && row) {
      event.preventDefault();
      event.stopPropagation();
      if (action.getAttribute("aria-disabled") === "true") return;
      const id = row.dataset.shelfItem || row.dataset.shelfClip;
      try {
        if (action.dataset.shelfRowAction === "hide" && row.dataset.shelfItem) applySnapshot((await post("/api/shelf/items/" + encodeURIComponent(id) + "/hide")).snapshot);
        else if (action.dataset.shelfRowAction === "delete" && row.dataset.shelfItem) applySnapshot((await post("/api/shelf/items/" + encodeURIComponent(id) + "/delete")).snapshot);
        else if (action.dataset.shelfRowAction === "delete" && row.dataset.shelfClip) {
          applySnapshot((await post("/api/shelf/clipboard/" + encodeURIComponent(id) + "/delete")).snapshot);
        } else if (action.dataset.shelfRowAction === "join" && row.dataset.shelfClip) {
          const group = clipSelection.has(id) && clipSelection.size > 1 ? [...clipSelection] : [id];
          await joinClips(group);
        } else if (action.dataset.shelfRowAction === "copy") {
          const name = row.dataset.shelfName || "";
          if (row.dataset.shelfItem) await copyShelfItem(id, name);
          else await makeClipCurrent(id);
        }
      } catch (error) { preview.innerHTML = docHtml("Shelf", L("无法读取置物架"), error.message); }
      return;
    }
    if (row?.dataset.shelfItem) await selectItem(row.dataset.shelfItem);
    if (row?.dataset.shelfClip) {
      if (event.detail > 1) return;
      selectClip(row.dataset.shelfClip, event.metaKey || event.ctrlKey);
    }
  });
  directory.addEventListener("dblclick", async (event) => {
    const row = event.target.closest("[data-shelf-clip]");
    if (!row?.dataset.shelfClip || event.target.closest("[data-shelf-row-action]")) return;
    event.preventDefault();
    try { await makeClipCurrent(row.dataset.shelfClip); } catch (error) {
      preview.innerHTML = docHtml("Shelf", L("无法读取置物架"), error.message);
    }
  });
  directory.addEventListener("input", () => paintLists());
  directory.querySelectorAll("[data-shelf-fold]").forEach((button) => button.addEventListener("click", () => {
    button.classList.toggle("is-shut");
    const list = directory.querySelector('[data-shelf-list="' + button.dataset.shelfFold + '"]');
    if (list) list.hidden = button.classList.contains("is-shut");
    if (button.dataset.shelfFold === "clipboard") {
      const extra = directory.querySelectorAll("[data-shelf-clip-hint], [data-shelf-clip-more]");
      extra.forEach((node) => { if (!node.hidden) node.style.display = list?.hidden ? "none" : ""; });
    }
  }));

  const activatePaper = (event) => {
    if (event.key !== "Enter" && event.key !== " ") return;
    const control = event.target.closest("[role=button]");
    if (!control) return;
    event.preventDefault();
    control.click();
  };
  workbench.addEventListener("keydown", activatePaper);
  directory.addEventListener("keydown", activatePaper);
  workbench.addEventListener("click", async (event) => {
    const sourceBtn = event.target.closest("[data-shelf-source]");
    if (sourceBtn && compare) {
      compareSourceId = sourceBtn.dataset.shelfSource;
      paintPreview();
      return;
    }
    const moreMenu = workbench.querySelector("[data-shelf-more-menu]");
    if (moreMenu && !event.target.closest(".shelf-more")) moreMenu.hidden = true;
    if (event.target.closest("[data-shelf-more]") && !event.target.closest("[data-shelf-more-menu]")) {
      if (moreMenu) moreMenu.hidden = !moreMenu.hidden;
      return;
    }
    if (event.target.closest("[data-shelf-arrange]")) {
      arranging = !arranging;
      renderBar(lastBarKind);
      return;
    }
    const hideAct = event.target.closest("[data-shelf-hide-act]");
    if (hideAct?.dataset.shelfHideAct) {
      hiddenActs.add(hideAct.dataset.shelfHideAct);
      renderBar(lastBarKind);
      return;
    }
    const restoreAct = event.target.closest("[data-shelf-restore-act]");
    if (restoreAct?.dataset.shelfRestoreAct) {
      hiddenActs.delete(restoreAct.dataset.shelfRestoreAct);
      renderBar(lastBarKind);
      return;
    }
    if (event.target.closest("[data-shelf-pick]") || event.target.closest("[data-shelf-act=pick]")) { fileInput?.click(); return; }
    if (event.target.closest("[data-shelf-sample]")) {
      const payload = await post("/api/shelf/sample");
      applySnapshot(payload.snapshot, payload.item.item_id);
      return;
    }
    const act = event.target.closest("[data-shelf-act]");
    if (act?.getAttribute("aria-disabled") === "true") return;
    if (act?.dataset.shelfAct === "extract" && selected) {
      if (editing) await stopEdit();
      fillConfirm();
      stage.classList.add("is-confirm");
      paintLists();
      return;
    }
    if (act?.dataset.shelfAct === "talk") {
      stage.classList.toggle("is-talk");
      renderBar(lastBarKind);
      return;
    }
    if (act?.dataset.shelfAct === "use" && selected) {
      const payload = await post("/api/shelf/items/" + encodeURIComponent(selected.item_id) + "/use-material");
      applySnapshot(payload.snapshot, payload.item.item_id);
      return;
    }
    if (act?.dataset.shelfAct === "join") {
      const ids = clipSelection.size ? [...clipSelection] : (selectedClip ? [selectedClip.clip_id] : []);
      if (ids.length) await joinClips(ids);
    }
  });
  workbench.querySelector("[data-shelf-run]")?.addEventListener("click", async () => {
    if (!selected) return;
    stage.classList.remove("is-fail");
    stage.classList.add("is-run");
    paintLists();
    const line = workbench.querySelector("[data-shelf-run-line]");
    if (line) {
      line.hidden = false;
      line.textContent = L("正在从副本抽取可选中文字…");
    }
    try {
      const payload = await post("/api/shelf/jobs", { recipe: "extract_text", item_id: selected.item_id });
      applySnapshot(payload.snapshot, payload.result?.item_id);
    } catch (error) {
      stage.classList.remove("is-run");
      stage.classList.add("is-fail");
      if (line) { line.hidden = false; line.textContent = error.message; }
      paintLists();
    }
  });
  workbench.querySelector("[data-shelf-back]")?.addEventListener("click", () => paintPreview());
  workbench.querySelector("[data-shelf-fold-talk]")?.addEventListener("click", () => {
    stage.classList.remove("is-talk");
    renderBar(lastBarKind);
  });
  workbench.querySelector("[data-shelf-compare]")?.addEventListener("click", async () => {
    if (!selected || selected.group !== "result") return;
    await flushEdit();
    compare = !compare;
    if (compare) compareSourceId = selected.source_item_id;
    else compareSourceId = null;
    paintPreview();
  });
  workbench.querySelector("[data-shelf-edit]")?.addEventListener("click", async () => {
    if (editing) await stopEdit();
    else startEdit();
  });
  preview.addEventListener("input", (event) => {
    if (!event.target.closest("[data-shelf-editor]") || !editing) return;
    const text = event.target.value;
    if (editTimer) clearTimeout(editTimer);
    editTimer = setTimeout(() => { saveCopy(text).catch(() => {}); }, 400);
  });
  workbench.querySelector("[data-shelf-copy-file]")?.addEventListener("click", () => {
    if (!selected) return;
    const link = document.createElement("a");
    link.href = fileUrl(selected.item_id); link.download = selected.name; link.click();
  });
  workbench.querySelector("[data-shelf-use-material]")?.addEventListener("click", async () => {
    if (!selected) return;
    const payload = await post("/api/shelf/items/" + encodeURIComponent(selected.item_id) + "/use-material");
    applySnapshot(payload.snapshot, payload.item.item_id);
  });
  fileInput?.addEventListener("change", async () => {
    const files = [...(fileInput.files || [])];
    fileInput.value = "";
    if (files.length) await admitFiles(files);
  });

  const isExternalFileDrag = (event) => {
    const types = [...(event.dataTransfer?.types || [])];
    if (types.includes("application/x-molis-shelf")) return false;
    return types.includes("Files");
  };
  const insideShelfDrop = (node) => Boolean(node && node.closest && node.closest("[data-shelf], [data-plugin-section=shelf]"));
  const markDrop = (on) => {
    workbench.classList.toggle("is-drop", on);
    stage.classList.toggle("is-drop", on);
    directory.classList.toggle("is-drop", on);
    document.querySelectorAll("[data-shelf-drop]").forEach((node) => node.setAttribute("aria-hidden", on ? "false" : "true"));
  };
  directory.addEventListener("dragstart", (event) => {
    const row = event.target.closest("[data-shelf-item]");
    if (!row || !event.dataTransfer) return;
    event.dataTransfer.setData("application/x-molis-shelf", row.dataset.shelfItem || "1");
    event.dataTransfer.effectAllowed = "copy";
  });
  document.addEventListener("dragenter", (event) => {
    if (document.body.dataset.desktopSurface !== "shelf") return;
    if (!isExternalFileDrag(event) || !insideShelfDrop(event.target)) return;
    event.preventDefault();
    markDrop(true);
  });
  document.addEventListener("dragover", (event) => {
    if (document.body.dataset.desktopSurface !== "shelf") return;
    if (!isExternalFileDrag(event) || !insideShelfDrop(event.target)) return;
    event.preventDefault();
    event.dataTransfer.dropEffect = "copy";
  });
  document.addEventListener("dragleave", (event) => {
    if (document.body.dataset.desktopSurface !== "shelf") return;
    if (insideShelfDrop(event.relatedTarget)) return;
    if (!insideShelfDrop(event.target)) return;
    markDrop(false);
  });
  document.addEventListener("drop", async (event) => {
    if (document.body.dataset.desktopSurface !== "shelf") return;
    if (!isExternalFileDrag(event) || !insideShelfDrop(event.target)) return;
    event.preventDefault();
    markDrop(false);
    const files = [...(event.dataTransfer?.files || [])];
    if (files.length) await admitFiles(files);
  });

  document.addEventListener("paste", async (event) => {
    if (document.body.dataset.desktopSurface !== "shelf") return;
    if (event.target.closest("input, textarea, [contenteditable=true]")) return;
    const data = event.clipboardData;
    if (!data) return;
    const types = [...data.types];
    if (isConcealed(types)) return;
    event.preventDefault();
    try {
      if (data.files?.length) {
        await admitFiles([...data.files]);
        return;
      }
      const text = (data.getData("text/plain") || data.getData("text/uri-list") || "").trim();
      if (!text || /^file:/i.test(text)) return;
      const recorded = await post("/api/shelf/clipboard", { text, types });
      snapshot = recorded.snapshot;
      const admitted = await post("/api/shelf/items", { text });
      applySnapshot(admitted.snapshot, admitted.item.item_id);
    } catch (error) {
      preview.innerHTML = docHtml("Shelf", L("无法读取置物架"), error.message);
    }
  });

  document.addEventListener("keydown", async (event) => {
    if (document.body.dataset.desktopSurface !== "shelf") return;
    if (event.key === "Escape" && editing) {
      event.preventDefault();
      await stopEdit();
      return;
    }
    if (event.target.closest("input, textarea, [contenteditable=true]")) return;
    if (event.key !== "Backspace" && event.key !== "Delete") return;
    event.preventDefault();
    try {
      if (clipSelection.size) {
        let next = snapshot;
        for (const id of [...clipSelection]) {
          next = (await post("/api/shelf/clipboard/" + encodeURIComponent(id) + "/delete")).snapshot;
        }
        selectedClip = null;
        clipSelection = new Set();
        applySnapshot(next);
      } else if (selected) {
        if (stageBusy()) return;
        applySnapshot((await post("/api/shelf/items/" + encodeURIComponent(selected.item_id) + "/hide")).snapshot);
      }
    } catch (error) {
      preview.innerHTML = docHtml("Shelf", L("无法读取置物架"), error.message);
    }
  });

  const boot = () => { if (document.body.dataset.desktopSurface === "shelf") load().catch(() => {}); };
  document.addEventListener("molis-work:surface", boot);
  window.addEventListener("molis-shelf-notice", (event) => {
    stickyHint = event.detail && event.detail.message ? String(event.detail.message) : "";
    paintPreview();
  });
  window.addEventListener("molis-shelf-refresh", () => { load().catch(() => {}); });
  new MutationObserver(boot).observe(document.body, { attributes: true, attributeFilter: ["data-desktop-surface"] });
  boot();

  function escapeText(value) {
    return String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
  }
  function escapeAttr(value) { return escapeText(value).replaceAll('"', "&quot;"); }
  function bufferToBase64(bytes) {
    let binary = "";
    const chunk = 0x8000;
    for (let index = 0; index < bytes.length; index += chunk) binary += String.fromCharCode(...bytes.subarray(index, index + chunk));
    return btoa(binary);
  }
}`;
