/** Shelf application copy; Workbench supplies the request locale. */
export const SHELF_EN: Record<string, string> = {
  "搜索材料": "Search materials",
  "材料": "Materials",
  "生成结果": "Results",
  "剪贴板历史": "Clipboard history",
  "还没有材料": "No materials yet",
  "还没有生成结果": "No results yet",
  "剪贴板是空的": "Clipboard is empty",
  "复制": "Copy",
  "隐藏": "Hide",
  "隐藏（列表拿掉，副本还在）": "Hide from list, keep the copy",
  "删除副本": "Delete copy",
  "删除记录": "Delete entry",
  "当前": "Current",
  "显示全部": "Show all",
  "显示最近 3 条": "Show last 3",
  "单击选择，双击复制为当前。⌘V 仍直接上架当前剪贴板。": "Click to select, double-click to make it current. ⌘V still shelves the current clipboard.",
  "仅预览历史记录 · 加入材料后可运行指令": "Previewing a saved clip · Add it to materials to run actions",
  "选择一条剪贴板记录": "Select a clipboard entry",
  "原材料已不在工作区，无法对照。": "The source material is no longer in this workspace.",
  "原文": "Source",
  "结果": "Result",
  "文件或图片已丢失，可以删除这条记录后重新复制。": "The file or image is missing. Delete this clip and copy it again.",
  "加入材料": "Add to materials",
  "对照原文": "Compare original",
  "复制文件": "Copy file",
  "编辑副本": "Edit copy",
  "完成编辑": "Done editing",
  "正在编辑副本。原文件保持不变。": "Editing a copy. The original stays unchanged.",
  "用作材料": "Use as material",
  "提取文字": "Extract text",
  "总结文件": "Summarize",
  "提取结构化信息": "Extract structure",
  "翻译并保留格式": "Translate and keep layout",
  "转换为 Markdown": "Convert to Markdown",
  "敏感信息脱敏": "Redact sensitive data",
  "整合多份材料": "Combine materials",
  "对话": "Chat",
  "整理": "Arrange",
  "整理动作": "Arrange actions",
  "完成整理": "Done arranging",
  "管理动作": "Manage actions",
  "从栏上拿掉": "Remove from bar",
  "加回动作栏": "Add back to bar",
  "新建": "New",
  "打开终端会话。不会生成新文件。发给终端请用轮盘。": "Open the terminal session. This does not create a new file. Send files from the wheel.",
  "总结、翻译等动作需要本机 Agent。图片与 PDF 可直接提取文字。": "Connect a local agent for summaries and translation. Images and PDFs can extract text now.",
  "将生成 pdf.md。原文件保持不变。": "Creates pdf.md. Your original file stays unchanged.",
  "将生成 extract.md。原文件保持不变。": "Creates extract.md. Your original file stays unchanged.",
  "提取 PDF 文字": "Extract PDF text",
  "开始提取": "Start extraction",
  "返回": "Back",
  "收起": "Collapse",
  "发给终端请拖到轮盘": "To send to a terminal, drop on the wheel",
  "材料放进来，结果拿出去": "Put materials in. Take results out.",
  "先放下，再决定要不要跑。原件不动。没有 Agent 也可以先提取 PDF 里的字。": "Set it down first, then decide whether to run. Originals stay put. You can extract PDF text without an Agent.",
  "试用示例 PDF": "Try the sample PDF",
  "选择我的文件": "Choose my file",
  "选择一份材料": "Choose a material",
  "在这里预览，使用下方指令处理副本。": "Preview here, then use the commands below on the copy.",
  "动作": "Action",
  "读取": "Read",
  "写入": "Write",
  "网络": "Network",
  "隔离": "Isolation",
  "关": "Off",
  "本机抽字，不调用 Agent": "Local text extract, no Agent",
  "提取 PDF 文字 → pdf.md": "Extract PDF text → pdf.md",
  "任务副本": "Job copy",
  "正在从副本抽取可选中文字…": "Extracting selectable text from the copy…",
  "发给终端不是副本沙箱": "Sending to the terminal is not the copy sandbox",
  "材料不会写回原路径。": "Materials are not written back to the original path.",
  "发给当前终端，不会生成新文件": "Send to the current terminal. This does not create a new file.",
  "点选只预览": "Selecting only previews",
  "加入材料后才能跑动作。⌘V 仍直接上架当前剪贴板。": "Add it as a material before running actions. ⌘V still shelves the current clipboard.",
  "个人置物架：先上架，再处理副本。": "Personal shelf: ingest first, then work on copies.",
  "把文件放到置物架": "Put files on the shelf",
  "把文件放到置物架，处理副本，原件不动。": "Put files on the shelf, work on copies, and leave originals untouched.",
  "无法读取置物架": "Could not read the shelf",
  "这些设置只改变 Shelf 在这台设备上的工作方式。": "These settings only change how Shelf works on this device.",
  "拖放轮盘": "Drop wheel",
  "从 Finder 拖到菜单栏时出现动作轮盘。关闭后不再出轮盘，不会开关 Shelf 面板，也不会改 Goal 胶囊。": "Shows the action wheel when dragging from Finder onto the menu bar. Turning it off hides the wheel. It does not open or close the Shelf panel or change the Goal capsule.",
  "快捷键": "Shortcuts",
  "打开 / 关闭 Shelf": "Open / close Shelf",
  "置前主窗口并打开 Shelf。若已在 Shelf 且窗口在前，则隐藏主窗口。": "Bring the main window forward and open Shelf. If Shelf is already frontmost, hide the main window.",
  "抓当前页": "Capture current page",
  "把 Safari、Chrome 或 Edge 放到最前面，抓成钢蓝地球标的网站材料。不装浏览器扩展。": "Bring Safari, Chrome, or Edge to the front and capture it as a steel-blue globe website. No browser extension.",
  "加入前台选中文件": "Add frontmost selected files",
  "优先读 Finder 选中的本地文件。浏览器在最前时请用抓页。": "Reads the Finder selection first. If a browser is frontmost, capture the page instead.",
  "点右边的键再按下新组合。全局快捷键必须带 ⌃ ⌥ ⇧ 或 ⌘。": "Click a shortcut, then press the new keys. Global shortcuts must include Control, Option, Shift, or Command.",
  "按下…": "Press…",
  "默认": "Default",
  "这个组合被占用。": "This shortcut is already in use.",
  "全局快捷键必须带 ⌃ ⌥ ⇧ 或 ⌘。": "Global shortcuts must include Control, Option, Shift, or Command.",
  "快捷键无效": "This shortcut is invalid.",
  "请提供要保存的设置": "Provide the settings to save.",
  "Shelf": "Shelf",
  "无法保存 Shelf 设置": "Could not save Shelf settings",
  "Shelf 请求失败": "Shelf request failed",
};
