/** Shelf application copy; Workbench supplies the request locale. */
export const SHELF_EN: Record<string, string> = {
  "搜索材料": "Search materials",
  "返回材料列表": "Back to material list",
  "材料": "Materials",
  "生成结果": "Results",
  "剪贴板历史": "Clipboard history",
  "剪贴板": "Clipboard",
  "还没有材料": "No materials yet",
  "还没有生成结果": "No results yet",
  "剪贴板是空的": "Clipboard is empty",
  "复制": "Copy",
  "隐藏": "Hide",
  "隐藏（列表拿掉，副本还在）": "Hide from list, keep the copy",
  "删除副本": "Delete copy",
  "删除记录": "Delete entry",
  "当前": "Current",
  "显示全部": "Show all",
  "显示最近 3 条": "Show last 3",
  "单击选择，双击复制为当前。⌘V 仍直接上架当前剪贴板。": "Click to select, double-click to make it current. ⌘V still shelves the current clipboard.",
  "仅预览历史记录 · 加入材料后可运行指令": "Previewing a saved clip · Add it to materials to run actions",
  "选择一条剪贴板记录": "Select a clipboard entry",
  "原材料已不在工作区，无法对照。": "The source material is no longer in this workspace.",
  "原文": "Source",
  "结果": "Result",
  "文件或图片已丢失，可以删除这条记录后重新复制。": "The file or image is missing. Delete this clip and copy it again.",
  "加入材料": "Add to materials",
  "对照原文": "Compare original",
  "复制文件": "Copy file",
  "编辑副本": "Edit copy",
  "完成编辑": "Done editing",
  "正在编辑副本。原文件保持不变。": "Editing a copy. The original stays unchanged.",
  "用作材料": "Use as material",
  "提取文字": "Extract text",
  "总结": "Summarize",
  "提取": "Extract",
  "翻译": "Translate",
  "脱敏": "Redact",
  "转 MD": "To MD",
  "整合": "Combine",
  "提炼重点，生成摘要": "Turn key points into a summary.",
  "提取要点、待办或结构化数据": "Extract key points, tasks, or structured data.",
  "在本机提取 PDF 中可选择的文字": "Extract selectable PDF text on your Mac.",
  "译为指定语言，尽量保留格式": "Translate while preserving formatting where possible.",
  "移除联系方式、证件等敏感信息": "Remove contact details, IDs, and other sensitive data.",
  "生成可编辑的 Markdown 文件": "Create an editable Markdown file.",
  "将多份材料整理为一份文档": "Combine several files into one document.",
  "篇幅": "Length",
  "抽取": "Extract",
  "译成": "Into",
  "范围": "Scope",
  "版式": "Layout",
  "源语言自动识别": "Source language detected automatically",
  "短 · 200 字": "Short · 200 words",
  "中 · 500 字": "Medium · 500 words",
  "长 · 1000 字": "Long · 1000 words",
  "提纲": "Outline",
  "要点": "Key points",
  "待办": "Tasks",
  "引用与数据": "Quotes and figures",
  "全量 JSON": "Full JSON",
  "中文": "Chinese",
  "联系方式": "Contact details",
  "金额证件": "Amounts and IDs",
  "全套": "Everything",
  "保结构": "Keep structure",
  "只要正文": "Body only",
  "带目录": "With contents",
  "一页": "One page",
  "完整一份": "Full document",
  "在副本里跑，写出新的 Markdown": "Run on a copy and write a new Markdown file",
  "权限与连接": "Permissions",
  "快捷动作": "Actions",
  "使用指南": "Guide",
  "Agent 与存储": "Agent & storage",
  "按需要开启功能。暂存文件和本机文字提取无需这些权限。": "Enable features when you need them. Staging and on-device extraction work without these permissions.",
  "管理动作，设置动作栏的内容与顺序。": "Manage actions and arrange the action bar.",
  "设置打开面板、添加文件和抓取网页的快捷键。": "Set shortcuts for the panel, selected files, and page capture.",
  "了解材料导入、文件处理和结果导出。": "Learn how to add files, run actions, and export results.",
  "选择本机 Agent，以及材料副本和结果的存放位置。": "Choose your local agent and where copies and results are stored.",
  "设置主题、语言和拖放显示。": "Set the theme, language, and drop wheel visibility.",
  "Shelf 设置": "Shelf settings",
  "未发现终端 Agent。暂存、预览、拖出和本机文字提取仍然可用。": "No terminal agent found. Staging, preview, drag-out, and on-device extraction still work.",
  "没有无界面执行入口，动作不能跑。": "has no headless entry, so recipes cannot run.",
  "可跑动作": "Can run actions",
  "已装 · 只能对话": "Installed · chat only",
  "未装": "Not installed",
  "安装说明": "How to install",
  "系统权限": "System permissions",
  "辅助功能：加入前台选中文件时需要。": "Accessibility: needed to add the files selected in the front app.",
  "辅助功能：已授权。": "Accessibility: granted.",
  "辅助功能：还没授权。加入前台选中文件时系统会询问。": "Accessibility: not granted yet. macOS asks the first time you add front-app files.",
  "Finder 自动化：抓前台选中文件时系统会询问一次。": "Finder automation: macOS asks once when you add the Finder selection.",
  "已装浏览器：抓当前页支持 Safari、Chrome，Edge 尽力而为。": "Browsers: page capture supports Safari and Chrome; Edge is best effort.",
  "已装浏览器：": "Browsers: ",
  "没找到 Safari、Chrome 或 Edge。": "No Safari, Chrome, or Edge found.",
  "这些权限按需授予。不授权也能上架、预览、拖出和本机抽字。": "Grant these when you need them. Staging, preview, drag-out, and on-device extraction work without them.",
  "动作栏": "Action bar",
  "拖动或用上下键换序。拿掉的动作还能加回来。": "Drag or use the arrows to reorder. Removed actions can come back.",
  "我的动作": "My actions",
  "一句话说明要做什么。它在任务副本里跑，产出「原名-动作.md」。不开放任意 Shell。": "One line about what to do. It runs on the job copy and writes “name-action.md”. No arbitrary shell.",
  "上移": "Move up",
  "下移": "Move down",
  "在栏上": "On the bar",
  "已隐藏": "Hidden",
  "编辑": "Edit",
  "名称": "Name",
  "说明": "Instruction",
  "例如：抽联系人": "For example: extract contacts",
  "把材料里的联系人写成一张表。": "List every contact in the material as a table.",
  "适用材料": "Works with",
  "保存动作": "Save action",
  "清空": "Clear",
  "全局": "Global",
  "面板内": "In the panel",
  "点右边的键再按下新键。面板内的键可以不带修饰键。": "Click the key on the right, then press a new one. In-panel keys may be bare.",
  "退出编辑 / 收起": "Leave editing",
  "在预览里按它退出编辑副本。": "Press it in the preview to stop editing the copy.",
  "把剪贴板上架": "Shelve the clipboard",
  "直接把当前剪贴板加进材料。": "Add the current clipboard straight to materials.",
  "复制选中": "Copy the selection",
  "复制选中的材料或结果。": "Copy the selected material or result.",
  "隐藏 / 删除记录": "Hide / delete entry",
  "隐藏当前材料或结果；剪贴板焦点下删除所选历史。": "Hide the current material or result; with the clipboard focused, delete the selected entries.",
  "上一条 / 下一条": "Previous / next",
  "目录里用方向键走。这一条不可改。": "Arrow keys walk the directory. This one is fixed.",
  "再试一次示例 PDF": "Try the sample PDF again",
  "会在材料里放一份可抽字的示例 PDF，不需要 Agent、授权或联网。": "Puts a text-bearing sample PDF in materials. No agent, permission, or network needed.",
  "示例已放回材料": "The sample is back in materials",
  "能做什么": "What it can do",
  "拖到哪里": "Where to drop",
  "菜单栏图标、拖放轮盘，或打开的 Shelf 工作面任意处。": "The menu bar icon, the drop wheel, or anywhere on an open Shelf surface.",
  "收什么": "What it takes",
  "文件、文件夹、PDF、图片、文字与 Markdown、链接、抓下来的网页，以及多份材料一起。": "Files, folders, PDFs, images, text and Markdown, links, captured pages, and several at once.",
  "读什么": "What it reads",
  "动作只读任务目录里的副本，Prompt 不写原路径，也不跟符号链接。": "Actions read only the copy in the job folder. The prompt carries no original path and no symlinks.",
  "写到哪": "Where it writes",
  "结果写进任务目录的 output/，再作为新文件进结果组。原件从不被改。": "Results go to the job folder's output/, then join Results as new files. Originals are never changed.",
  "拖出去是什么": "What drags out",
  "系统认的文件、文字、图片和链接。接不住会弹回，架子上的还在。默认复制，不是移动。": "Standard file, text, image, and URL payloads. A refusal springs back and the shelf keeps its copy. Copy, never move.",
  "不联网": "No network",
  "本机文字提取不调用 Agent、不上网。联网与否在确认页写明。": "On-device extraction calls no agent and no network. The confirmation says whether a run goes online.",
  "本机 Agent": "Local agent",
  "自动": "Automatic",
  "按安装顺序挑一个": "Picks the first one installed",
  "只能对话": "Chat only",
  "快捷动作和 CLI Recipe 都跟这一个。没有无界面执行入口的 Agent 仍可对话。": "Shortcut actions and CLI recipes follow this one. An agent without a headless entry can still chat.",
  "自定义 Runtime": "Custom runtime",
  "可执行文件": "Executable",
  "类型": "Kind",
  "终端会话（TUI）": "Terminal session (TUI)",
  "无界面（CLI）": "Headless (CLI)",
  "例如：公司内部 CLI": "For example: our internal CLI",
  "添加": "Add",
  "存放位置": "Where it lives",
  "材料副本、任务目录和结果都在这里。删除副本只动这里，原件不动。": "Copies, job folders, and results live here. Deleting a copy touches only this, never the original.",
  "主题与语言跟 Molis 的外观设置。": "Theme and language follow Molis appearance settings.",
  "提取图片文字": "Extract image text",
  "本机识别，不发送": "On-device, not sent",
  "本机识别，不发送。": "On-device recognition, not sent.",
  "正在本机识别图片里的文字…": "Reading the text in this image on your Mac…",
  "这台机器还没有本机文字识别": "This Mac has no on-device text recognition yet",
  "语言": "Language",
  "中英": "Chinese + English",
  "English": "English",
  "{agent} · 发给终端不是副本沙箱": "{agent} · sent to the terminal, not to a copy sandbox",
  "文件夹": "Folder",
  "正在读这份文件…": "Reading this file…",
  "{count} 个文件。点左边展开，选一份看内容。": "{count} files. Expand on the left and pick one to read.",
  "剪贴板：在别处复制会自动记进历史。": "Clipboard: copying anywhere else records an entry here.",
  "剪贴板：这台 Mac 不让后台程序读剪贴板。打开 Shelf 面板按 ⌘V 仍可把当前剪贴板上架。": "Clipboard: this Mac does not let a background app read the clipboard. Open the Shelf panel and press ⌘V to shelve what you copied.",
  "未发现终端 Agent。文件已留在架子上。": "No terminal agent found. The files stayed on the shelf.",
  "添加本机文件": "Add this file",
  "添加材料": "Add files",
  "更多": "More",
  "粘贴当前剪贴板": "Paste current clipboard",
  "多选材料": "Select multiple files",
  "结束多选": "Finish selecting",
  "副本工作区": "Working copies",
  "⌘V 粘贴当前": "⌘V pastes current",
  "已选 {count} 份材料": "{count} files selected",
  "取消": "Cancel",
  "失败": "Failed",
  "这次动作没成": "This action did not finish",
  "任务失败": "The job failed",
  "材料还在架子上。原文件没有被改动。": "The materials are still on the shelf. Your original file was not touched.",
  "Agent": "Agent",
  "1 份材料的副本": "Copies of 1 material",
  "{count} 份材料": "{count} materials",
  "{count} 份材料的副本": "Copies of {count} materials",
  "将生成 {name}。原文件保持不变。": "Creates {name}. Your original file stays unchanged.",
  "仅任务目录": "Job folder only",
  "未确认仅任务目录": "Job-folder limit unconfirmed",
  "无执行入口": "No exec entry",
  "未确认": "Unconfirmed",
  "开": "On",
  "关": "Off",
  "本机提取，不发送": "On-device extraction, not sent",
  "本机提取，不发送。": "On-device extraction, not sent.",
  "Workspace Sandbox：Agent 只能写任务工作区": "Workspace Sandbox: the agent can only write the job workspace",
  "未确认工作区限制，仍在副本目录跑": "Workspace limit unconfirmed; still runs in the copy folder",
  "在终端执行，不是副本沙箱": "Runs in the terminal, not a copy sandbox",
  "未发现 Agent": "No agent found",
  "{agent} 在任务副本里跑。": "{agent} runs in a job copy.",
  "{agent} 没有无界面执行入口，动作不能跑。": "{agent} has no headless entry, so recipes cannot run.",
  "未发现终端 Agent。": "No terminal agent found.",
  "{agent} 正在副本里跑「{recipe}」…": "{agent} is running “{recipe}” on the copy…",
  "「{name}」至少要两份材料": "“{name}” needs at least two items",
  "开始处理": "Run action",
  "返回材料重试": "Back to materials, then retry",
  "总结文件": "Summarize",
  "提取结构化信息": "Extract structure",
  "翻译并保留格式": "Translate and keep layout",
  "转换为 Markdown": "Convert to Markdown",
  "敏感信息脱敏": "Redact sensitive data",
  "整合多份材料": "Combine materials",
  "对话": "Chat",
  "整理": "Arrange",
  "整理动作": "Arrange actions",
  "完成整理": "Done arranging",
  "管理动作": "Manage actions",
  "从栏上拿掉": "Remove from bar",
  "加回动作栏": "Add back to bar",
  "新建": "New",
  "打开终端会话。不会生成新文件。发给终端请用轮盘。": "Open the terminal session. This does not create a new file. Send files from the wheel.",
  "总结、翻译等动作需要本机 Agent。图片与 PDF 可直接提取文字。": "Connect a local agent for summaries and translation. Images and PDFs can extract text now.",
  "将生成 pdf.md。原文件保持不变。": "Creates pdf.md. Your original file stays unchanged.",
  "将生成 extract.md。原文件保持不变。": "Creates extract.md. Your original file stays unchanged.",
  "提取 PDF 文字": "Extract PDF text",
  "开始提取": "Start extraction",
  "返回": "Back",
  "收起": "Collapse",
  "发给终端请拖到轮盘": "To send to a terminal, drop on the wheel",
  "材料放进来，结果拿出去": "Put materials in. Take results out.",
  "先放下，再决定要不要跑。原件不动。没有 Agent 也可以先提取 PDF 里的字。": "Set it down first, then decide whether to run. Originals stay put. You can extract PDF text without an Agent.",
  "试用示例 PDF": "Try the sample PDF",
  "选择我的文件": "Choose my file",
  "选择一份材料": "Choose a material",
  "在这里预览，使用下方指令处理副本。": "Preview here, then use the commands below on the copy.",
  "动作": "Action",
  "读取": "Read",
  "写入": "Write",
  "网络": "Network",
  "隔离": "Isolation",
  "本机抽字，不调用 Agent": "Local text extract, no Agent",
  "任务副本": "Job copy",
  "正在从副本抽取可选中文字…": "Extracting selectable text from the copy…",
  "发给终端不是副本沙箱": "Sending to the terminal is not the copy sandbox",
  "材料不会写回原路径。": "Materials are not written back to the original path.",
  "发给当前终端，不会生成新文件": "Send to the current terminal. This does not create a new file.",
  "点选只预览": "Selecting only previews",
  "加入材料后才能跑动作。⌘V 仍直接上架当前剪贴板。": "Add it as a material before running actions. ⌘V still shelves the current clipboard.",
  "个人置物架：先上架，再处理副本。": "Personal shelf: ingest first, then work on copies.",
  "把文件放到置物架": "Put files on the shelf",
  "把文件放到置物架，处理副本，原件不动。": "Put files on the shelf, work on copies, and leave originals untouched.",
  "无法读取置物架": "Could not read the shelf",
  "这些设置只改变 Shelf 在这台设备上的工作方式。": "These settings only change how Shelf works on this device.",
  "拖放轮盘": "Drop wheel",
  "从 Finder 拖到菜单栏时出现动作轮盘。关闭后不再出轮盘，不会开关 Shelf 面板，也不会改 Goal 胶囊。": "Shows the action wheel when dragging from Finder onto the menu bar. Turning it off hides the wheel. It does not open or close the Shelf panel or change the Goal capsule.",
  "快捷键": "Shortcuts",
  "打开 / 关闭 Shelf": "Open / close Shelf",
  "置前主窗口并打开 Shelf。若已在 Shelf 且窗口在前，则隐藏主窗口。": "Bring the main window forward and open Shelf. If Shelf is already frontmost, hide the main window.",
  "抓当前页": "Capture current page",
  "把 Safari、Chrome 或 Edge 放到最前面，抓成钢蓝地球标的网站材料。不装浏览器扩展。": "Bring Safari, Chrome, or Edge to the front and capture it as a steel-blue globe website. No browser extension.",
  "加入前台选中文件": "Add frontmost selected files",
  "优先读 Finder 选中的本地文件。浏览器在最前时请用抓页。": "Reads the Finder selection first. If a browser is frontmost, capture the page instead.",
  "点右边的键再按下新组合。全局快捷键必须带 ⌃ ⌥ ⇧ 或 ⌘。": "Click a shortcut, then press the new keys. Global shortcuts must include Control, Option, Shift, or Command.",
  "按下…": "Press…",
  "默认": "Default",
  "这个组合被占用。": "This shortcut is already in use.",
  "全局快捷键必须带 ⌃ ⌥ ⇧ 或 ⌘。": "Global shortcuts must include Control, Option, Shift, or Command.",
  "快捷键无效": "This shortcut is invalid.",
  "请提供要保存的设置": "Provide the settings to save.",
  "Shelf": "Shelf",
  "无法保存 Shelf 设置": "Could not save Shelf settings",
  "Shelf 请求失败": "Shelf request failed",
};
