export const FUNCTIONS_EN: Record<string, string> = {
  "新建函数": "New function",
  "新建判断": "New judgment",
  "还没有判断函数": "No functions yet",
  "选 Noul、Choice 或 Score，用真实输入试跑，再发布给 Agent 调用。": "Pick Noul, Choice, or Score, preview with real input, then publish so the agent can call it.",
  "写一道题：看哪类内容、在哪个现场或给 Agent 挑哪几件已登记的动作。试跑后发布，再到 Inbox、首页或 Feed 规则里打开开关。": "Write one question: what to look at, which event or the agent to pick from registered actions. Preview, publish, then turn it on in Inbox, Home, or a Feed rule.",
  "返回函数列表": "Back to function list",
  "函数": "Function",
  "判断": "Judgment",
  "名称": "Name",
  "函数 key": "Function key",
  "发布后不能改。给调用方看的稳定名字。": "Frozen after publish. The stable name callers use.",
  "判断说明": "Instructions",
  "选项": "Options",
  "会在这些动作里挑": "Pick from these actions",
  "添加": "Add",
  "试跑输入": "Preview input",
  "试跑": "Preview",
  "发布 v1": "Publish v1",
  "未命名函数": "Untitled function",
  "草稿": "Draft",
  "已选出": "Selected",
  "需要复核": "Needs review",
  "选项说明": "Why this action",
  "去掉选项": "Remove option",
  "Choice 至少需要两个选项": "A Choice needs at least two options",
  "Functions 请求失败": "Functions request failed",
  "保存失败": "Could not save",
  "TypeSafe 的 Jev 用来跑这些判断。Key 留在这台机器，保存后页面不会再显示明文。": "TypeSafe's Jev runs these judgments. The key stays on this machine and is never shown again after save.",
  "TypeSafe API Key": "TypeSafe API Key",
  "由环境变量 TYPESAFE_API_KEY 提供，输入框不可改。": "Provided by TYPESAFE_API_KEY. The field is read-only.",
  "已配置。页面不会再显示明文。": "Configured. This page will not show the secret again.",
  "还没有 Key。没有它也能写草稿，试跑时会停住。": "No key yet. You can still edit drafts; preview will stop.",
  "保存": "Save",
  "清除": "Clear",
  "保存只记下已配置，不会向 TypeSafe 发探测。试跑成功才算连通。": "Save only marks the key as configured. It does not probe TypeSafe. A successful preview is the connectivity proof.",
  "把一段输入交给 Jev，得到一个有版本的判断。": "Hand Jev some input and get a versioned judgment.",
  "删除草稿": "Delete draft",
  "样例": "Samples",
  "保存当前输入": "Save current input",
  "关闭": "Close",
  "一函数一题。试跑成功后再发布，Agent 才能调用。": "One question per function. Preview successfully, then publish so the agent can call it.",
  "Choice 能接到首页事件、Inbox、Feed，或给 Agent 从 MCP 和插件动作里挑。Noul 和 Score 只给 Agent 用。": "Choice can attach to home events, Inbox, Feed, or let the agent pick from MCP and plugin actions. Noul and Score are agent-only.",
  "这是否成立": "Does this hold?",
  "属于哪一类": "Which class is this?",
  "从已登记动作里挑一件": "Pick one registered action",
  "在有序档位上打分": "Score on ordered levels",
  "是的标准（可选）": "When it is true (optional)",
  "否的标准（可选）": "When it is false (optional)",
  "档位": "Levels",
  "档位说明": "Level description",
  "去掉档位": "Remove level",
  "Score 至少需要两个档位": "A Score needs at least two levels",
  "成立概率": "Probability it holds",
  "分类结果": "Classification",
  "正在请求 TypeSafe，可能计费。": "Sending to TypeSafe. This may be billed.",
  "已发布，配置不能再改。": "Published. Configuration is frozen.",
  "载入": "Load",
  "去掉样例": "Remove sample",
  "确定删除这个草稿？": "Delete this draft?",
  "模型概率不是正确率。": "Model probability is not accuracy.",
  "判断完成": "Judged",
  "被用在哪": "Used in",
  "首页卡底": "Home dock",
  "Feed 捕捉规则": "Feed capture rules",
  "Inbox 下一步": "Inbox next step",
  "还没有说明": "No instructions yet",
  "试过": "Previewed",
  "这是一道系统判断。看一类内容，在一个事件现场或给 Agent 挑已登记的动作。写的动作不会自动执行。": "This is a system judgment. It looks at one kind of object and picks a registered action for an event or the agent. Write actions are never auto-run.",
  "来源": "Looks at",
  "这道题看什么对象。": "What object this question looks at.",
  "去向": "Goes to",
  "判断结果用在哪。开关仍在现场，这里只选定去向。": "Where the answer is used. The on/off switch stays at the site; this only picks the destination.",
  "现场判断要用 Choice。Noul 和 Score 只给 Agent 用。": "Site judgments need Choice. Noul and Score are agent-only.",
  "何时": "When",
  "哪里配": "Where",
  "效果": "Effect",
  "勾选已登记动作。系统/插件动作能接到现场按钮；MCP 写工具只建议，不会自动执行。": "Check registered actions. System and plugin actions can become site buttons. MCP write tools are suggestions only and never auto-run.",
  "Feed 消息": "Feed item",
  "Inbox": "Inbox",
  "来源故障": "Source fault",
  "首页事件": "Home event",
  "Session": "Session",
  "Agent 调用": "Agent call",
  "首页出现这条事件、点开详情时": "When this home event appears and its detail opens",
  "首页详情里的「卡底判断」": "Home detail, dock judgment",
  "只挑亮一两个按钮。写操作不会自动执行。": "Highlights one or two buttons. Write actions are not auto-run.",
  "Inbox 落地": "Inbox arrival",
  "Inbox 条目被创建时": "When an Inbox entry is created",
  "Inbox 列表的「下一步判断」": "Inbox list, next-step judgment",
  "只改「做完了 / 忽略」谁出现，不自动改状态。": "Only changes whether Done / Dismiss appear. It does not change status by itself.",
  "Feed 捕捉": "Feed capture",
  "捕捉规则命中一条 Feed 消息时": "When a capture rule hits a Feed item",
  "Feed 任务的捕捉规则": "Feed task capture rules",
  "只改「加入 Inbox」是否出现，不自动写入。": "Only changes whether Add to Inbox appears. It does not write by itself.",
  "给 Agent 调用": "For the agent",
  "Agent 调用 molis_work_v1_functions_invoke 时": "When the agent calls molis_work_v1_functions_invoke",
  "发布后即可，不用现场开关": "After publish. No site switch.",
  "返回挑中的动作。MCP 写工具不会因为判断结果自动执行。": "Returns the picked action. MCP write tools do not run because of the judgment.",
  "系统": "System",
  "插件": "Plugin",
  "MCP": "MCP",
  "看": "Read",
  "写": "Write",
  "判断只建议": "Suggestion only",
  "未选去向": "No destination yet",
  "还没接到现场。发布后到这里选它：": "Not attached yet. After publish, pick it here:",
  "发布后 Agent 就能调用，不用再去 Inbox 或首页开开关。": "After publish the agent can call it. No Inbox or Home switch.",
  "未接线，给 Agent 用": "Not wired to a button; for the agent",
};
