export const FUNCTIONS_EN: Record<string, string> = {
  "新建函数": "New function",
  "还没有判断函数": "No functions yet",
  "写一条 Choice：给一段输入，从你定的选项里选出一项。试跑成功后再发布 v1。": "Write a Choice: given some input, pick one of the options you defined. Preview successfully, then publish v1.",
  "返回函数列表": "Back to function list",
  "函数": "Function",
  "名称": "Name",
  "函数 key": "Function key",
  "发布后不能改。给调用方看的稳定名字。": "Frozen after publish. The stable name callers use.",
  "判断说明": "Instructions",
  "选项": "Options",
  "添加选项": "Add option",
  "试跑输入": "Preview input",
  "试跑": "Preview",
  "发布 v1": "Publish v1",
  "未命名函数": "Untitled function",
  "草稿": "Draft",
  "已选出": "Selected",
  "需要复核": "Needs review",
  "选项说明": "Option description",
  "去掉选项": "Remove option",
  "Choice 至少需要两个选项": "A Choice needs at least two options",
  "Functions 请求失败": "Functions request failed",
  "保存失败": "Could not save",
  "TypeSafe 的 Jev 用来跑这些判断。Key 留在这台机器，保存后页面不会再显示明文。": "TypeSafe's Jev runs these judgments. The key stays on this machine and is never shown again after save.",
  "TypeSafe API Key": "TypeSafe API Key",
  "由环境变量 TYPESAFE_API_KEY 提供，输入框不可改。": "Provided by TYPESAFE_API_KEY. The field is read-only.",
  "已配置。页面不会再显示明文。": "Configured. This page will not show the secret again.",
  "还没有 Key。没有它也能写草稿，试跑时会停住。": "No key yet. You can still edit drafts; preview will stop.",
  "保存": "Save",
  "清除": "Clear",
  "保存只记下已配置，不会向 TypeSafe 发探测。试跑成功才算连通。": "Save only marks the key as configured. It does not probe TypeSafe. A successful preview is the connectivity proof.",
  "把一段输入交给 Jev，得到一个有版本的判断。": "Hand Jev some input and get a versioned judgment.",
};
