export const FUNCTIONS_EN: Record<string, string> = {
  "新建判断": "New judgment",
  "还没有判断": "No judgments yet",
  "点「新建判断」。": "Click New judgment.",
  "返回列表": "Back",
  "函数": "Function",
  "判断": "Judgment",
  "名称": "Name",
  "函数 key": "Function key",
  "发布后不能改。": "Locked after publish.",
  "说明": "Instructions",
  "怎么判断": "How to judge",
  "选项": "Options",
  "可选动作": "Actions",
  "添加": "Add",
  "试一段": "Try this",
  "试跑": "Preview",
  "发布 v1": "Publish v1",
  "未命名函数": "Untitled",
  "草稿": "Draft",
  "已选出": "Picked",
  "需要复核": "Needs review",
  "可选": "Optional",
  "去掉选项": "Remove option",
  "Choice 至少需要两个选项": "A Choice needs at least two options",
  "Functions 请求失败": "Request failed",
  "保存失败": "Could not save",
  "试跑用 TypeSafe 的 Jev。": "Preview runs on TypeSafe's Jev.",
  "TypeSafe API Key": "TypeSafe API Key",
  "来自 TYPESAFE_API_KEY。": "From TYPESAFE_API_KEY.",
  "已保存。": "Saved.",
  "还没填。": "Not set.",
  "保存": "Save",
  "清除": "Clear",
  "保存后不再显示。": "Hidden after save.",
  "Inbox、首页、Feed 显示哪个按钮。": "Which button Inbox, Home, or Feed should show.",
  "删除草稿": "Delete draft",
  "样例": "Samples",
  "存为样例": "Save as sample",
  "关闭": "Close",
  "成不成立": "Yes or no",
  "选动作": "Pick an action",
  "打分": "Score",
  "成立时": "When true",
  "不成立时": "When false",
  "档位": "Levels",
  "档位说明": "Level",
  "去掉档位": "Remove level",
  "Score 至少需要两个档位": "A Score needs at least two levels",
  "成立概率": "Probability",
  "分类结果": "Class",
  "可能计费。": "May be billed.",
  "已发布。": "Published.",
  "载入": "Load",
  "去掉样例": "Remove sample",
  "确定删除这个草稿？": "Delete this draft?",
  "模型概率不是正确率。": "Probability is not accuracy.",
  "判断完成": "Judged",
  "用在哪": "Used in",
  "首页卡底": "Home dock",
  "Feed 捕捉规则": "Feed capture rules",
  "Inbox 下一步": "Inbox next step",
  "还没有说明": "No instructions yet",
  "试过": "Tried",
  "看什么": "Looks at",
  "首页、Inbox、Feed 要用 Choice。": "Home, Inbox, and Feed need Choice.",
  "先选「用在哪」。": "Pick Used in first.",
  "Feed 消息": "Feed item",
  "Inbox": "Inbox",
  "来源出错": "Source error",
  "首页事件": "Home event",
  "Session": "Session",
  "Agent": "Agent",
  "首页": "Home",
  "点开事件时，亮哪些按钮": "Which buttons to show when an event opens",
  "发布后打开": "Turn on after publish",
  "亮哪些按钮": "Which buttons to show",
  "新事项来时，显示「做完了」还是「忽略」": "Done or Dismiss when an item arrives",
  "显示「做完了」还是「忽略」": "Done or Dismiss",
  "Feed": "Feed",
  "要不要出现「加入 Inbox」": "Whether Add to Inbox shows",
  "去任务捕捉规则里选": "Pick it in the task's capture rules",
  "「加入 Inbox」出不出现": "Whether Add to Inbox shows",
  "给 Agent 选动作": "Pick an action for the agent",
  "发布后可用": "Ready after publish",
  "系统": "System",
  "插件": "Plugin",
  "MCP": "MCP",
  "看": "Read",
  "写": "Write",
  "还没选": "None",
  "先发布。": "Publish first.",
  "先打开项目。": "Open a project first.",
  "Inbox 在用。": "Inbox is using this.",
  "首页在用。": "Home is using this.",
  "正在用": "Using",
  "正在用另一个。": "Using another one.",
  "换成这个": "Use this",
  "用在 Inbox": "Use in Inbox",
  "用在首页": "Use on Home",
  "停用": "Deactivate",
  "没读到": "Could not read",
  "没打开": "Could not turn on",
  "去 Feed 任务里选。": "Pick it in a Feed task.",
  "发布后可用。": "Ready after publish.",
  "给 Agent": "For the agent",
};
