#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

/**
 * Who answers for each workspace package, written once and rendered twice: the "归属" column of docs/SSOT-MATRIX.md and
 * .github/CODEOWNERS. `workspace-packages.mjs` puts the result on every entry as `owner`, and `checkPackageOwners` (called
 * by `checkWorkspacePackages`, so by `pnpm boundary:check` and CI) fails when either file differs from what the rules
 * below produce.
 *
 * The decision (specs/repository-anti-corruption/spec.md §1, 2026-10-02 and 2026-10-07): a role plus accounts per row;
 * LEAD answers for everything, CODING_REVIEWER also for Coding, Agent Host, Jelly, Shelf and Diff. CODEOWNERS only asks
 * for review; branch protection is not changed here.
 *
 * To change an owner, edit the rules in this file and run `node scripts/package-owners.mjs --write`.
 * `node scripts/package-owners.mjs` without arguments checks without writing.
 */
export const LEAD = "@yijunw0212";
export const CODING_REVIEWER = "@jingxusandra-gif";

export const OWNER_COLUMN = "归属";
/** The 归属 cell of a row that names no workspace package (a package not built yet). */
export const NO_OWNER = "—";
export const CODEOWNERS_FILE = ".github/CODEOWNERS";
export const SSOT_FILE = "docs/SSOT-MATRIX.md";

const ROLE_BY_KIND = {
  app: "应用",
  foundation: "平台包",
  module: "Module",
  horizontal: "横向服务",
  "native-plugin": "内置插件",
  "integration-plugin": "官方集成",
  tooling: "工具",
};

/** The shared core named in docs/prompts/repository-anti-corruption.md §4.7: contracts, kernel, action service, Agent Host, shell. */
const SHARED_CORE = new Set([
  "packages/contracts",
  "packages/kernel",
  "apps/local-host", // the action service on the host side, and the composition root
  "apps/workbench", // the shell
  "horizontal/agent-host",
]);

const ALSO_REVIEWED_BY_CODING_REVIEWER = new Set([
  "plugins/native/coding",
  "horizontal/agent-host",
  "plugins/native/jelly",
  "modules/shelf",
  "plugins/native/shelf",
  "plugins/native/diff",
]);

/** The gate script, its CI helper, the gate numbers and the CI workflow: LEAD only, whatever pattern is added above them. */
export const GATE_PATHS = [
  "scripts/check-health-gates.mjs",
  "scripts/ci-health-base.mjs",
  "scripts/check-secrets.mjs",
  "tooling/gates/",
  ".github/workflows/",
];

export function packageOwner(packagePath, kind) {
  const role = SHARED_CORE.has(packagePath) ? "共享核心" : ROLE_BY_KIND[kind];
  if (!role) throw new Error(`no owner role for package kind "${kind}" (${packagePath})`);
  const handles = ALSO_REVIEWED_BY_CODING_REVIEWER.has(packagePath) ? [LEAD, CODING_REVIEWER] : [LEAD];
  return { role, handles };
}

export function ownerCell(owner) {
  return `${owner.role}：${owner.handles.join("、")}`;
}

const ownerOf = (item) => item.owner ?? packageOwner(item.path, item.kind);

export function renderCodeowners(packages) {
  const reviewed = packages
    .filter((item) => ownerOf(item).handles.some((handle) => handle !== LEAD))
    .sort((left, right) => left.path.localeCompare(right.path));
  return [
    "# Generated by scripts/package-owners.mjs: edit the rules there, then run `node scripts/package-owners.mjs --write`.",
    "# `pnpm boundary:check` fails when this file differs from what the rules produce.",
    "#",
    "# Review is requested from these accounts, not required: branch protection and the merge queue are unchanged",
    "# (specs/repository-anti-corruption/spec.md §1, 2026-10-02 and 2026-10-07). The role of each package is in the 归属",
    "# column of docs/SSOT-MATRIX.md. The last matching line wins.",
    "",
    `* ${LEAD}`,
    "",
    `# Also reviewed by ${CODING_REVIEWER}`,
    ...reviewed.map((item) => `/${item.path}/ ${ownerOf(item).handles.join(" ")}`),
    "",
    "# The gates and the CI workflow stay with the lead alone",
    ...GATE_PATHS.map((gatePath) => `/${gatePath} ${LEAD}`),
    "",
  ].join("\n");
}

const FIRST_TABLE_HEADER = "| 目标 package |";

function splitCells(line) {
  return line.slice(1, line.lastIndexOf("|")).split(/(?<!\\)\|/u).map((cell) => cell.trim());
}

function pathsNamedIn(cell) {
  return [...cell.matchAll(/`([^`]+)`/gu)].map((match) => match[1]);
}

function owningPackage(namedPath, packages) {
  const owning = packages
    .filter((item) => namedPath === item.path || namedPath.startsWith(`${item.path}/`))
    .sort((left, right) => right.path.length - left.path.length);
  return owning[0];
}

function expectedCell(firstCell, packages) {
  const named = pathsNamedIn(firstCell)[0];
  const item = named ? owningPackage(named, packages) : undefined;
  return item ? ownerCell(ownerOf(item)) : NO_OWNER;
}

/** Calls `visit(line, index, kind)` for the header, separator and rows of every package table; kind is "header", "separator" or "row". */
function eachTableLine(lines, visit) {
  let inTable = false;
  lines.forEach((line, index) => {
    if (line.startsWith(FIRST_TABLE_HEADER)) { inTable = true; visit(line, index, "header"); return; }
    if (!inTable) return;
    if (!line.startsWith("|")) { inTable = false; return; }
    visit(line, index, line.startsWith("| ---") ? "separator" : "row");
  });
}

/** The SSOT text with the 归属 column set on every package table row; running it on its own output changes nothing. */
export function renderSsot(text, packages) {
  const lines = text.split("\n");
  eachTableLine(lines, (line, index, kind) => {
    const cells = splitCells(line);
    const hasColumn = kind === "header" ? cells.at(-1) === OWNER_COLUMN : cells.length === 6;
    const base = line.trimEnd();
    if (kind === "header") lines[index] = hasColumn ? base : `${base} ${OWNER_COLUMN} |`;
    else if (kind === "separator") lines[index] = cells.length === 6 ? base : `${base} --- |`;
    else {
      const cell = expectedCell(cells[0], packages);
      lines[index] = hasColumn ? base.replace(/\|[^|]*\|$/u, `| ${cell} |`) : `${base} ${cell} |`;
    }
  });
  return lines.join("\n");
}

/** Errors for a SSOT text and CODEOWNERS text that do not match the rules; pure, so tests can feed it altered copies. */
export function ownerErrors({ codeowners, ssot, packages }) {
  const errors = [];
  if (codeowners !== renderCodeowners(packages)) {
    errors.push(`${CODEOWNERS_FILE} differs from the owner rules in scripts/package-owners.mjs; run "node scripts/package-owners.mjs --write"`);
  }

  const lines = ssot.split("\n");
  const rowsByPath = new Map();
  let headers = 0;
  eachTableLine(lines, (line, index, kind) => {
    const cells = splitCells(line);
    const where = `${SSOT_FILE}:${index + 1}`;
    if (kind === "header") {
      headers++;
      if (cells.at(-1) !== OWNER_COLUMN) errors.push(`${where}: package table has no "${OWNER_COLUMN}" column`);
      return;
    }
    if (kind === "separator") return;
    const named = pathsNamedIn(cells[0]);
    if (named.length !== 1) errors.push(`${where}: the first cell must name exactly one path in backticks, found ${named.length} (${cells[0]})`);
    else rowsByPath.set(named[0], (rowsByPath.get(named[0]) ?? 0) + 1);
    if (cells.length !== 6) errors.push(`${where}: row has ${cells.length} cells, expected 6 (the last is "${OWNER_COLUMN}")`);
    else {
      const expected = expectedCell(cells[0], packages);
      if (cells[5] !== expected) errors.push(`${where}: ${OWNER_COLUMN} of ${cells[0]} is "${cells[5]}", the rules give "${expected}"`);
    }
  });
  if (headers === 0) errors.push(`${SSOT_FILE}: no package table found`);
  for (const item of packages) {
    const count = rowsByPath.get(item.path) ?? 0;
    if (count !== 1) errors.push(`${SSOT_FILE}: package ${item.path} must have exactly one row, found ${count}`);
  }
  return errors;
}

/** Everything `pnpm boundary:check` verifies about ownership; reads the two generated files and the paths the rules name. */
export function checkPackageOwners(repositoryRoot, packages) {
  const errors = [];
  const read = (file) => {
    const absolute = path.join(repositoryRoot, file);
    if (fs.existsSync(absolute)) return fs.readFileSync(absolute, "utf8");
    errors.push(`${file}: missing`);
    return undefined;
  };
  const codeowners = read(CODEOWNERS_FILE);
  const ssot = read(SSOT_FILE);
  if (codeowners === undefined || ssot === undefined) return errors;
  errors.push(...ownerErrors({ codeowners, ssot, packages }));
  for (const gatePath of GATE_PATHS) {
    if (!fs.existsSync(path.join(repositoryRoot, gatePath))) errors.push(`${CODEOWNERS_FILE}: gate path ${gatePath} does not exist`);
  }
  return errors;
}

async function main() {
  const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
  // Imported once this module has finished evaluating (no top-level await): workspace-packages.mjs imports this file for `packageOwner`.
  const { WORKSPACE_PACKAGES } = await import("./workspace-packages.mjs");
  if (process.argv.includes("--write")) {
    const ssotFile = path.join(repositoryRoot, SSOT_FILE);
    const ssot = fs.readFileSync(ssotFile, "utf8");
    const nextSsot = renderSsot(ssot, WORKSPACE_PACKAGES);
    if (nextSsot !== ssot) fs.writeFileSync(ssotFile, nextSsot);
    const codeownersFile = path.join(repositoryRoot, CODEOWNERS_FILE);
    fs.mkdirSync(path.dirname(codeownersFile), { recursive: true });
    fs.writeFileSync(codeownersFile, renderCodeowners(WORKSPACE_PACKAGES));
  }
  const errors = checkPackageOwners(repositoryRoot, WORKSPACE_PACKAGES);
  for (const error of errors) console.error(error);
  if (errors.length > 0) process.exitCode = 1;
  else console.log(`owners ok: ${WORKSPACE_PACKAGES.length} packages, ${CODEOWNERS_FILE} and ${SSOT_FILE} match the rules`);
}

const invokedPath = process.argv[1] ? pathToFileURL(path.resolve(process.argv[1])).href : null;
if (invokedPath === import.meta.url) {
  main().catch((error) => { console.error(error); process.exitCode = 1; });
}
