/** Explicit export allowlist copied from the stable producer codes below, not a runtime pattern.
 * New producer codes require review here; do not turn arbitrary strings or remediation text into facts. */
export const REASON_CODES = [...new Set([
  // Shared action validation and protected tree approval.
  'actions.input_invalid', 'goal_tree_proposal.untrusted_actor',
  // Native Goal Tree submission/decision rejection literals, not operation-event names.
  'goal_tree_proposal.items_required', 'goal_tree_proposal.summary_required',
  'goal_tree_proposal.actor_required', 'goal_tree_proposal.id_required', 'goal_tree_proposal.not_found',
  'goal_tree_proposal.base_cursor_invalid', 'goal_tree_proposal.baseline_changed',
  'goal_tree_proposal.item_id_duplicate', 'goal_tree_proposal.payload_unknown',
  'goal_tree_proposal.item_payload_invalid', 'goal_tree_proposal.item_operation_invalid',
  'goal_tree_proposal.goal_title_required', 'goal_tree_proposal.payload_shape_invalid',
  'goal_tree_proposal.user_authority_required', 'goal_tree_proposal.user_actor_required',
  'goal_tree_proposal.authority_source_invalid', 'goal_tree_proposal.conversation_ref_required',
  'goal_tree_proposal.message_ref_required', 'goal_tree_proposal.prompted_proposal_id_required',
  'goal_tree_proposal.decision_not_pending', 'goal_tree_proposal.decision_item_closed',
  'goal_tree_proposal.decision_item_not_found', 'goal_tree_proposal.decisions_required',
  'goal_tree_proposal.whole_confirmation_ambiguous', 'goal_tree_proposal.whole_confirmation_conflict',
  'goal_tree_proposal.whole_confirmation_mixed', 'goal_tree_proposal.whole_confirmation_requires_pristine_proposal',
  'goal_tree_proposal.kind_retired', 'goal_tree_proposal.use_event_agree',
  // Current event application/state producer literals; reviewed export allowlist, never runtime patterns.
  "event.not_found",
  "event_agreement.change_mismatch",
  "event_agreement.duplicate_revision",
  "event_agreement.expected_agreement_version_required",
  "event_agreement.invalid_change",
  "event_agreement.no_changes",
  "event_agreement.revision_empty",
  "event_agreement.stale_config_version",
  "event_agreement.unauthorized_change",
  "event_closure.blocking_concern",
  "event_closure.blocking_risk",
  "event_closure.cancelled",
  "event_closure.denied_action",
  "event_closure.human_approval_required",
  "event_closure.human_decision_required",
  "event_closure.invalid_kind",
  "event_closure.missing_agreement",
  "event_closure.missing_result",
  "event_closure.open_dependency",
  "event_closure.pending_decision",
  "event_closure.requirement_unsupported",
  "event_closure.stale_version",
  "event_concern.accept_requires_user_decision",
  "event_concern.cross_goal_reference",
  "event_concern.evidence_not_subsequent",
  "event_concern.evidence_required",
  "event_concern.not_found",
  "event_concern.scope_required",
  "event_config.cannot_rewrite_type",
  "event_config.cross_goal_requirement",
  "event_config.default_requirement_not_found",
  "event_config.duplicate_field_id",
  "event_config.duplicate_planning",
  "event_config.duplicate_requirement",
  "event_config.duplicate_type_id",
  "event_config.executable_content",
  "event_config.fields_required",
  "event_config.invalid_field",
  "event_config.invalid_field_source",
  "event_config.invalid_human_decision_required",
  "event_config.invalid_planning",
  "event_config.invalid_requirement",
  "event_config.invalid_requirement_source",
  "event_config.invalid_source",
  "event_config.invalid_text",
  "event_config.invalid_type_id",
  "event_config.invalid_type_version",
  "event_config.no_changes",
  "event_config.planning_not_found",
  "event_config.planning_requirement_conflict",
  "event_config.planning_type_conflict",
  "event_config.planning_version_unavailable",
  "event_config.requirement_exists",
  "event_config.requirement_not_found",
  "event_config.reserved_field",
  "event_config.type_version_gap",
  "event_config.unsupported_field_format",
  "event_config.unsupported_property",
  "event_config.unsupported_semantic_family",
  "event_config.version_conflict",
  "event_decision.change_mismatch",
  "event_decision.conclusion_required",
  "event_decision.cross_goal_reference",
  "event_decision.duplicate_option",
  "event_decision.effect_conflict",
  "event_decision.effect_scope_mismatch",
  "event_decision.effect_widened",
  "event_decision.invalid_effect",
  "event_decision.invalid_options",
  "event_decision.invalid_purpose",
  "event_decision.missing_proposed_change",
  "event_decision.not_found",
  "event_decision.option_not_found",
  "event_decision.request_not_found",
  "event_decision.scope_expanded",
  "event_decision.scope_required",
  "event_decision.stale_commitment",
  "event_decision.superseded",
  "event_decision.unexpected_proposed_change",
  "event_decision.untrusted_actor",
  "event_http.invalid_version",
  "event_http.unexpected_field",
  "event_list.invalid_cursor",
  "event_list.invalid_limit",
  "event_progress.cursor_not_on_goal",
  "event_progress.future_cursor",
  "event_progress.invalid_cursor",
  "event_progress.summary_required",
  "event_report.cross_goal_reference",
  "event_report.duplicate_requirement",
  "event_report.empty_batch",
  "event_report.forged_authority",
  "event_report.incompatible_requirement",
  "event_report.invalid_actor_kind",
  "event_report.invalid_field_value",
  "event_report.invalid_judgments",
  "event_report.invalid_payload",
  "event_report.invalid_progress",
  "event_report.invalid_verdict",
  "event_report.missing_required_field",
  "event_report.requirement_not_found",
  "event_report.title_required",
  "event_report.type_required",
  "event_report.unknown_field",
  "event_report.unknown_progress_field",
  "event_requirement.not_current",
  "event_resume.already_open",
  "event_resume.not_resumable",
  "event_state.not_owner",
  "event_type.not_found",
  "event_type.version_not_found",
  "goal.archived",
  "goal.not_found",
  "goal.priority_invalid",
  "goal.title_required",
  "goal.trashed",
  "goal_list.invalid_cursor",
  "goal_list.invalid_limit",
  "goal_list.invalid_status",
  "mcp.unexpected_field",
  // plugins/native/goals/src/goal-eligibility.ts
  'claim.already_active',
  'contract_proposal.user_decision_required',
  'dependency.not_valid',
  'dependency.unsatisfied',
  'goal.acceptance_missing',
  'goal.already_satisfied',
  'goal.archived',
  'goal.clarification_not_needed',
  'goal.invalidated',
  'goal.needs_revalidation',
  'goal.not_accepted',
  'goal.not_closed_leaf',
  'goal.not_found',
  'goal.revalidation_not_needed',
  'goal.trashed',
  'goal_tree_proposal.user_decision_required',
  'policy.capability_missing',
  'policy.goal_mode_required',
  'review.execution_not_completed',
  'review.not_pending',
  'risk.blocks_claim',
  // plugins/native/goals/src/action-projection.ts
  'action.auto_release_repair',
  'action.candidate_decision_required',
  'action.completion_reconciliation_required',
  'action.compound_children_missing',
  'action.compound_coverage_missing',
  'action.contract_decision_required',
  'action.contract_revision_conflict',
  'action.contract_rework_required',
  'action.coverage_revision_stale',
  'action.evidence_incomplete',
  'action.goal_invalidated',
  'action.human_obligation_missing',
  'action.human_review_required',
  'action.leaf_has_children',
  'action.rewire_decision_required',
  'action.rework_requested',
  'action.risk_acceptance_required',
  'action.risk_mitigation_required',
  'action.run_blocked',
  'action.run_missing',
  'wait.child_goal',
  'wait.dependency',
  // plugins/native/goals/src/execution-validation-claim-commands.ts
  'lease.duration_exceeds_policy',
  'lease.duration_invalid',
  // plugins/native/goals/src/execution-validation-run-commands.ts

  // plugins/native/goals/src/execution-validation-verification-commands.ts

  // plugins/native/goals/src/work-state-queries.ts
  'candidate.user_decision_required',
  'evidence.criterion_uncovered',
  'goal.compound_child_not_trusted',
  'goal.compound_children_missing',
  'goal.contract_coverage_incomplete',
  'goal.execution_finished_rework_required',
  'goal.invalidated',
  'goal.ready_to_complete',
  'policy.review_pending',
  'review.user_approval_required',
  'rewire.user_confirmation_required',
  'risk.blocks_completion',
  'run.blocked',
  'run.missing',
  // modules/execution/src/lifecycle.ts
  'claim.lease_expired',
  'claim.not_active',
  'claim.not_found',
  'claim.not_owner',
  'contract.revision_stale',
  'lease.duration_exceeds_policy',
  'lease.duration_invalid',
  'run.already_active',
  'run.block_reason_required',
  'run.claim_expired',
  'run.claim_inactive',
  'run.not_found',
  'run.not_owner',
  'run.role_invalid',
  'run.transition_invalid',
  // modules/goals/src/lifecycle-reasons.ts
  'dependency.not_valid',
  'dependency.unsatisfied',
  'risk.blocks_completion',
  // Stable errorType throws in the three execution-validation command producers above.
  'action.id_required',
  'action.not_available',
  'action.role_mismatch',
  'action.token_stale',
  'claim.lease_expired',
  'claim.not_active',
  'claim.not_found',
  'claim.not_owner',
  'contract.revision_stale',
  'evidence.actor_invalid',
  'evidence.criterion_invalid',
  'evidence.run_invalid',
  'goal.not_found',
  'goal.rework_active_claim',
  'goal.rework_completed_run_required',
  'goal.rework_criterion_invalid',
  'goal.rework_criterion_required',
  'goal.rework_evidence_required',
  'goal.rework_not_at_completion_gate',
  'goal.rework_reason_required',
  'goal.rework_state_invalid',
  'goal.trashed',
  'review.attention_token_stale',
  'review.dialogue_provenance_required',
  'review.dialogue_target_ambiguous',
  'review.evidence_not_effective',
  'review.evidence_stale_after_rework',
  'review.evidence_wrong_goal',
  'review.execution_not_completed',
  'review.independence_failed',
  'review.obligation_closed',
  'review.obligation_not_found',
  'review.reasoning_required',
  'review.rework_pending',
  'review.user_authority_required',
  'run.claim_expired',
  'run.not_found',
  'run.not_owner',
  'board.not_found', 'kernel.capability_missing', 'request.idempotency_key_reused',
])] as readonly string[];
export const RECOVERY_ACTIONS = ['select_goal','retry_claim_renew_as_owner'] as const;
