// Interaction slice only: in-memory illustrative rows, no user Home, credentials or service calls.
import { createServer } from 'node:http';
import { renderMcpAccess, renderMcpAccessRows, type McpAccessModel } from '../../../apps/workbench/src/mcp-access.js';
import { MCP_ACCESS_CLIENT_SCRIPT } from '../../../apps/workbench/src/scripts/mcp-access.js';
import { renderMolisWorkSettingsStylesheet } from '../../../tests/workbench-renderer-fixture.js';
const escapeHtml=(v:unknown)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const p={escapeHtml,L:(s:string,v?:Record<string,string|number>)=>s.replace('{count}',String(v?.count??''))};
const model:McpAccessModel={client_id:'runtime:codex',project_id:'demo',clients:[{id:'runtime:codex',title:'Codex'},{id:'runtime:claude-code',title:'Claude Code'}],query:'',filter:'',entries:[
{capability_id:'pages.list',provider_id:'io.molis.work.pages',version:1,title:'查看项目文稿',provider_title:'文稿',description:'读取当前项目的文稿列表，不修改内容。',kind:'query',permissions:['pages:read'],status:'enabled',can_enable:false,can_revoke:true},
{capability_id:'alchemist.direction.create',provider_id:'io.molis.work.alchemist',version:1,title:'新建研究方向',provider_title:'炼金术士',description:'保存一个待探索的方向，后续可发起候选生成与研究。',kind:'operation',permissions:['alchemist:write'],status:'ungranted',can_enable:true,can_revoke:false},
{capability_id:'research.run',provider_id:'research',version:2,title:'研究市场机会',provider_title:'研究服务',description:'收集公开来源并整理研究材料。',kind:'operation',permissions:['research:write','model:invoke'],status:'unavailable',reason:'所选服务连接已失效，请在服务连接中重新配置。',can_enable:false,can_revoke:true},
{capability_id:'old.classifier',provider_id:'old.plugin',version:1,title:'旧版消息分类',provider_title:'原插件',description:'原授权仍保留，可以撤销。',kind:'judgment',permissions:['functions:invoke'],status:'missing',reason:'找不到原能力、版本或提供方。',can_enable:false,can_revoke:true}
]};
const server=createServer((req,res)=>{const url=new URL(req.url??'/','http://127.0.0.1');const current={...model,query:url.searchParams.get('q')??'',filter:url.searchParams.get('filter')??''};
if(url.pathname.startsWith('/api/')){res.setHeader('content-type','application/json');res.end(JSON.stringify({html:renderMcpAccessRows(current,p)}));return;}
res.setHeader('content-type','text/html; charset=utf-8');res.end(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${renderMolisWorkSettingsStylesheet()}body{margin:0}.settings-shell{height:100dvh}.settings-content{overflow:auto}</style></head><body class="capabilities-page"><div class="settings-shell"><nav class="settings-navigation"><div class="settings-nav-body"><a><span></span><span>能力库</span></a><a><span></span><span>服务连接</span></a><a aria-current="page"><span></span><span>对外接入</span></a><a><span></span><span>调用记录</span></a></div></nav><main class="settings-content"><section class="settings-document"><header class="settings-heading"><h1>对外接入</h1><p>选择客户端，决定它可以读取什么、执行哪些操作。</p></header><p role="status">交互预览 · 示例数据，不会执行真实操作</p>${renderMcpAccess(current,[{project_id:'demo',display_name:'产品研究'}],false,p)}</section></main></div><script>const L=s=>s;document.addEventListener('click',event=>{const button=event.target.closest('[data-mcp-grant]');if(!button)return;event.stopPropagation();const enabled=button.dataset.grantEnabled==='true';button.textContent=enabled?'撤销授权':'授权';button.dataset.grantEnabled=String(!enabled);button.closest('[data-grant-row]').querySelector('.mcp-access-state').textContent=enabled?'已授权':'已撤销';const feedback=document.querySelector('[data-mcp-access-feedback]');feedback.hidden=false;feedback.textContent='交互预览 · 未保存真实授权';},true);${MCP_ACCESS_CLIENT_SCRIPT}</script></body></html>`);});
server.listen(0,'127.0.0.1',()=>console.log((server.address() as any).port));
process.on('SIGTERM',()=>server.close());
