export const PAGES_EN: Record<string, string> = {
  "新建文档": "New page",
  "新建文件夹": "New folder",
  "从模板新建": "New from template",
  "搜索文档": "Search pages",
  "还没有文档": "No pages yet",
  "先建一篇，在纸面上写。刷新之后还在。": "Create a page and write on the paper. It stays after refresh.",
  "内容属于当前项目，保存在这台电脑。": "These stay with the current project on this computer.",
  "没有匹配的文档": "No matching pages",
  "挂到 Goal": "Link to Goal",
  "不挂 Goal": "Not linked",
  "抽取": "Extract",
  "Promote": "Promote",
  "块备注": "Block note",
  "评论": "Comment",
  "写作": "Write",
  "候选": "Draft",
  "未接模型": "No model connected",
  "正在处理": "Working",
  "写作失败": "Could not write",
  "翻译": "Translation",
  "引用文档": "Linked page",
  "文档引用": "Page mention",
  "任务卡": "Task card",
  "待办": "To do",
  "进行中": "Doing",
  "完成": "Done",
  "日程卡": "Event card",
  "日期": "Date",
  "月历": "Calendar",
  "本篇事件": "Events in this page",
  "选择文档": "Choose a page",
  "任务": "Task",
  "日程": "Event",
  "没有日期": "No date",
  "标题": "Title",
  "描述": "Description",
  "状态": "Status",
  "截止日期": "Due date",
  "输入 / 插入块，或直接写": "Type / to insert a block, or just write",
  "备注": "Note",
  "返回文档列表": "Back to page list",
  "文档": "Page",
  "文件夹": "Folder",
  "收藏": "Favorite",
  "取消收藏": "Unfavorite",
  "导出 HTML": "Export HTML",
  "删除": "Delete",
  "取消": "Cancel",
  "确定": "OK",
  "无标题": "Untitled",
  "已保存": "Saved",
  "保存失败": "Could not save",
  "文档请求失败": "Page request failed",
  "缺少项目": "Project is missing",
  "要删除这篇文档吗？删除后无法恢复。": "Delete this page? This cannot be undone.",
  "要删除这个文件夹吗？里面的文档会回到未分类。": "Delete this folder? Pages inside move to Unfiled.",
  "编辑器内核未加载": "The editor kernel did not load",
  "文件夹名称": "Folder name",
  "未分类": "Unfiled",
  "在此新建": "New in folder",
  "重命名文件夹": "Rename folder",
  "删除文件夹": "Delete folder",
  "会议纪要": "Meeting notes",
  "信息、出席、议程、结论、行动项": "Info, attendees, agenda, decisions, actions",
  "周报": "Weekly update",
  "完成、进行中、下周、风险": "Done, in progress, next week, risks",
  "项目计划": "Project plan",
  "目标、团队、里程碑、范围": "Goal, team, milestones, scope",
  "PRD": "PRD",
  "背景、用户故事、验收": "Background, stories, acceptance",
  "迭代回顾": "Sprint retro",
  "做得好、改进、行动": "Went well, improve, actions",
  "用户访谈": "User interview",
  "问题、洞察、原话": "Questions, insights, quotes",
  "OKR": "OKR",
  "目标与关键结果": "Objectives and key results",
  "复盘": "Postmortem",
  "经过、根因、改进": "What happened, causes, fixes",
  "技术方案": "Technical design",
  "架构、取舍、计划": "Architecture, tradeoffs, plan",
  "竞品分析": "Competitor notes",
  "插入块": "Insert block",
  "上移": "Move up",
  "下移": "Move down",
  "段落": "Paragraph",
  "正文": "Body",
  "标题 1": "Heading 1",
  "标题 2": "Heading 2",
  "标题 3": "Heading 3",
  "无序列表": "Bulleted list",
  "有序列表": "Numbered list",
  "清单": "Checklist",
  "提示块": "Callout",
  "代码": "Code",
  "表": "Table",
  "两列表": "Two columns",
  "折叠": "Toggle",
  "分隔线": "Divider",
  "目录": "Table of contents",
  "按标题生成": "From headings",
  "Callout": "Callout",
  "Toggle": "Toggle",
  "还没有标题": "No headings yet",
};
