export const PAGES_EN: Record<string, string> = {
  "导入": "Import",
  "关闭": "Close",
  "导入已有文档": "Import existing documents",
  "导入文档": "Import documents",
  "把已有文档带进 Pages，导入后可继续编辑。": "Bring existing documents into Pages and keep editing them.",
  "文档来自": "Source",
  "飞书 / Lark": "Feishu / Lark",
  "Word、语雀及其他工具": "Word, Yuque and other tools",
  "选择文件，或拖到这里": "Choose files or drop them here",
  "支持多选，总计不超过 10 MB；每次最多 100 篇。": "Choose multiple files, up to 10 MB total and 100 documents per import.",
  "选择要导入的文件": "Choose files to import",
  "图片和附件会转为链接或文字说明；评论、权限和历史版本不导入。": "Images and attachments become links or text labels. Comments, permissions and version history are not imported.",
  "全选": "Select all",
  "导入到": "Import into",
  "导入所选文档": "Import selected documents",
  "打开文档": "Open document",
  "在 Notion 的页面菜单中导出为 Markdown & CSV 或 HTML，可包含子页面；直接选择下载的 ZIP。": "In Notion's page menu, export as Markdown & CSV or HTML with subpages, then choose the downloaded ZIP.",
  "在飞书文档菜单中下载为 Word（.docx）或 Markdown，再选择导出的文件。": "In the Feishu document menu, download as Word (.docx) or Markdown, then choose the exported file.",
  "从原工具导出为 Word（.docx）、Markdown、HTML 或纯文本；CSV 会导入为文档中的表格。": "Export as Word (.docx), Markdown, HTML or plain text. CSV files become tables inside documents.",
  "项目已切换，请在目标项目重新打开导入。": "The project changed. Reopen import in the target project.",
  "导入失败，请检查文件后重试。": "Import failed. Check your files and try again.",
  "预览正文": "Preview content",
  "已解析文档，请选择要导入的内容并检查转换提示。": "Documents are ready. Select what to import and review any conversion notes.",
  "文件读取失败": "Could not read the file",
  "正在读取并解析文件…": "Reading and converting files…",
  "请选择不超过 100 个文件，总大小不超过 10 MB。": "Choose at most 100 files, up to 10 MB total.",
  "正在导入文档…": "Importing documents…",
  "已导入": "Imported",
  "篇文档": "documents",
  "可重试此批导入，不会重复创建文档。": "Retry this import safely without creating duplicate documents.",
  "新建文档": "New page",
  "新建文件夹": "New folder",
  "从模板新建": "New from template",
  "更多新建": "More create options",
  "加粗": "Bold",
  "斜体": "Italic",
  "下划线": "Underline",
  "删除线": "Strikethrough",
  "搜索文档": "Search pages",
  "还没有文档": "No pages yet",
  "先建一篇，在纸面上写。刷新之后还在。": "Create a page and write on the paper. It stays after refresh.",
  "内容属于当前项目，保存在这台电脑。": "These stay with the current project on this computer.",
  "没有匹配的文档": "No matching pages",
  "挂到 Goal": "Link to Goal",
  "不挂 Goal": "Not linked",
  "抽取": "Extract",
  "Promote": "Promote",
  "存成 Artifact": "Save as Artifact",
  "再存一版": "Save another version",
  "已存成 Artifact": "Saved as an Artifact",
  "块备注": "Block note",
  "评论": "Comment",
  "写作": "Write",
  "候选": "Draft",
  "未接模型": "No model connected",
  "正在处理": "Working",
  "写作失败": "Could not write",
  "翻译": "Translation",
  "引用文档": "Linked page",
  "文档引用": "Page mention",
  "任务卡": "Task card",
  "待办": "To do",
  "进行中": "Doing",
  "完成": "Done",
  "日程卡": "Event card",
  "日期": "Date",
  "月历": "Calendar",
  "本篇事件": "Events in this page",
  "选择文档": "Choose a page",
  "任务": "Task",
  "日程": "Event",
  "没有日期": "No date",
  "标题": "Title",
  "描述": "Description",
  "状态": "Status",
  "截止日期": "Due date",
  "输入 / 插入块，或直接写": "Type / to insert a block, or just write",
  "备注": "Note",
  "返回文档列表": "Back to page list",
  "文档": "Page",
  "文件夹": "Folder",
  "更多": "More",
  "收藏": "Favorite",
  "取消收藏": "Unfavorite",
  "导出 HTML": "Export HTML",
  "删除": "Delete",
  "取消": "Cancel",
  "确定": "OK",
  "无标题": "Untitled",
  "已保存": "Saved",
  "保存失败": "Could not save",
  "文档请求失败": "Page request failed",
  "缺少项目": "Project is missing",
  "要删除这篇文档吗？删除后无法恢复。": "Delete this page? This cannot be undone.",
  "要删除这个文件夹吗？里面的文档会回到未分类。": "Delete this folder? Pages inside move to Unfiled.",
  "编辑器内核未加载": "The editor kernel did not load",
  "文件夹名称": "Folder name",
  "未分类": "Unfiled",
  "在此新建": "New in folder",
  "移到文件夹": "Move to folder",
  "重命名文件夹": "Rename folder",
  "删除文件夹": "Delete folder",
  "会议纪要": "Meeting notes",
  "信息、出席、议程、结论、行动项": "Info, attendees, agenda, decisions, actions",
  "周报": "Weekly update",
  "完成、进行中、下周、风险": "Done, in progress, next week, risks",
  "项目计划": "Project plan",
  "目标、团队、里程碑、范围": "Goal, team, milestones, scope",
  "PRD": "PRD",
  "背景、用户故事、验收": "Background, stories, acceptance",
  "迭代回顾": "Sprint retro",
  "做得好、改进、行动": "Went well, improve, actions",
  "用户访谈": "User interview",
  "问题、洞察、原话": "Questions, insights, quotes",
  "OKR": "OKR",
  "目标与关键结果": "Objectives and key results",
  "复盘": "Postmortem",
  "经过、根因、改进": "What happened, causes, fixes",
  "技术方案": "Technical design",
  "架构、取舍、计划": "Architecture, tradeoffs, plan",
  "竞品分析": "Competitor notes",
  "块操作": "Block actions",
  "拖动以排序或缩进": "Drag to reorder or nest",
  "转换为": "Turn into",
  "复制": "Duplicate",
  "返回": "Back",
  "链接": "Link",
  "移除链接": "Remove link",
  "换图标或颜色": "Change icon or colour",
  "图标": "Icon",
  "提示": "Note",
  "想法": "Idea",
  "注意": "Heads up",
  "风险": "Risk",
  "重点": "Key point",
  "标记": "Flag",
  "目标": "Goal",
  "疑问": "Question",
  "参考": "Reference",
  "行动": "Action",
  "钉住": "Pinned",
  "代码语言": "Code language",
  "复制代码": "Copy code",
  "纯文本": "Plain text",
  "列表项": "List item",
  "待办事项": "To-do",
  "想强调的话": "Something worth calling out",
  "折叠起来的内容": "Hidden inside the toggle",
  "颜色": "Color",
  "文字颜色": "Text color",
  "背景色": "Background",
  "默认": "Default",
  "灰": "Gray",
  "棕": "Brown",
  "橙": "Orange",
  "黄": "Yellow",
  "绿": "Green",
  "蓝": "Blue",
  "紫": "Purple",
  "粉": "Pink",
  "红": "Red",
  "没有匹配的块": "No matching blocks",
  "基础": "Basic",
  "卡片": "Cards",
  "圆点": "Bullets",
  "等宽": "Monospace",
  "横线": "Line",
  "在此插入": "Insert here",
  "插入块": "Insert block",
  "上移": "Move up",
  "下移": "Move down",
  "段落": "Paragraph",
  "正文": "Body",
  "标题 1": "Heading 1",
  "标题 2": "Heading 2",
  "标题 3": "Heading 3",
  "无序列表": "Bulleted list",
  "有序列表": "Numbered list",
  "清单": "Checklist",
  "提示块": "Callout",
  "代码": "Code",
  "表": "Table",
  "两列表": "Two columns",
  "折叠": "Toggle",
  "分隔线": "Divider",
  "引用": "Quote",
  "摘一句": "A line worth keeping",
  "加一行": "Add row",
  "加一列": "Add column",
  "删行": "Delete row",
  "删列": "Delete column",
  "目录": "Table of contents",
  "按标题生成": "From headings",
  "Callout": "Callout",
  "Toggle": "Toggle",
  "还没有标题": "No headings yet",
};
