export const PPT_EN: Record<string, string> = {
  "列表暂时读不到": "The list could not be read",
  "请稍后重试": "Try again in a moment",
  "重试": "Retry",
  "重新读取": "Reload",
  "恢复发布": "Resume publishing",
  "保存中": "Saving",
  "尚未保存": "Unsaved",
  "处理中": "Working",
  "已保存": "Saved",
  "重新读取会丢弃未保存的编辑。继续吗？": "Reloading discards unsaved edits. Continue?",
  "演示稿已在别处修改，当前输入已保留。请复制需要保留的内容，再重新读取。": "This deck changed elsewhere. Your input is preserved. Copy anything you need, then reload.",
  "上次 Artifact 发布尚未完成。恢复使用上次固定内容，后续编辑可另存一版。": "The previous Artifact publication is incomplete. Resume its saved snapshot; later edits can be published as another version.",
  "新建演示稿": "New deck",
  "删除这一页": "Remove slide",
  "上移": "Move up",
  "下移": "Move down",
  "还没有演示稿": "No decks yet",
  "先建一份，再加幻灯片。预览区按页展示，可以导出 JSON。": "Create a deck, add slides, preview them, then export JSON.",
  "内容属于当前项目，保存在这台电脑。": "These stay with the current project on this computer.",
  "返回演示稿列表": "Back to deck list",
  "演示稿": "Presentation",
  "导出 JSON": "Export JSON",
  "删除": "Delete",
  "存成 Artifact": "Save as Artifact",
  "再存一版": "Save another version",
  "已存成 Artifact": "Saved as an Artifact",
  "取消": "Cancel",
  "标题": "Title",
  "说明": "Description",
  "可选": "Optional",
  "主题色": "Accent",
  "背景": "Background",
  "文字": "Text",
  "幻灯片": "Slides",
  "加一页": "Add slide",
  "页标题": "Slide title",
  "要点": "Bullets",
  "每行一条": "One bullet per line",
  "备注": "Notes",
  "讲者备注": "Speaker notes",
  "未命名一页": "Untitled slide",
  "还没有要点": "No bullets yet",
  "页": "slides",
  "演示稿请求失败": "Presentation request failed",
  "保存失败": "Could not save",
  "缺少项目": "Missing project",
  "至少保留一页": "Keep at least one slide",
  "写幻灯片大纲，预览并导出 JSON。": "Write slide outlines, preview them, and export JSON.",
  "删除这份演示稿？": "Delete this deck?",
  "已导出": "Exported",
  "还没有说明": "No description yet",
  "放映": "Present",
  "←/→ 翻页 · N 讲者备注 · Esc 退出": "←/→ to change slides · N for speaker notes · Esc to exit",
  "上次固定版本还没存完。恢复会使用上次的固定内容，之后的编辑可以再存一版。": "The last fixed version wasn't finished saving. Resuming uses that saved content; you can save another version of later edits.",
  "再存一个固定版本": "Save another fixed version",
  "存为固定版本": "Save as fixed version",
  "第 {version} 版 · 放在这个位置的成果（Artifacts）里；继续编辑不会改变这一版": "Version {version} · kept in this location's Artifacts; further edits won't change it",
  "PowerPoint · {count} 页，含讲者备注": "PowerPoint · {count} slides, with speaker notes",
  "数据文件，不是演示文稿": "Data file, not a presentation",
  "先建一份，再加幻灯片。写好后可以直接放映，也能导出 PowerPoint 文件。": "Create a deck, then add slides. When it's ready, present it here or export a PowerPoint file.",
  "全屏放映，方向键翻页，N 显示讲者备注，Esc 退出": "Present full screen: arrow keys change slides, N shows speaker notes, Esc exits",
  "导出": "Export",
  "PowerPoint 文件（.pptx）": "PowerPoint file (.pptx)",
  "打印或存为 PDF": "Print or save as PDF",
  "导出数据（JSON，不是演示文稿）": "Export data (JSON, not a presentation)",
  "把当前内容存成不会再变的一版，放进这个位置的成果（Artifacts）": "Save the current content as a version that won't change, in this location's Artifacts",
  "继续保存上次固定版本": "Finish saving the last fixed version",
};
