export const PPT_EN: Record<string, string> = {
  "新建演示稿": "New deck",
  "还没有演示稿": "No decks yet",
  "先建一份，再加幻灯片。预览区按页展示，可以导出 JSON。": "Create a deck, add slides, preview them, then export JSON.",
  "内容属于当前项目，保存在这台电脑。": "These stay with the current project on this computer.",
  "返回演示稿列表": "Back to deck list",
  "演示稿": "Presentation",
  "导出 JSON": "Export JSON",
  "删除": "Delete",
  "取消": "Cancel",
  "标题": "Title",
  "说明": "Description",
  "可选": "Optional",
  "主题色": "Accent",
  "背景": "Background",
  "文字": "Text",
  "幻灯片": "Slides",
  "加一页": "Add slide",
  "页标题": "Slide title",
  "要点": "Bullets",
  "每行一条": "One bullet per line",
  "备注": "Notes",
  "讲者备注": "Speaker notes",
  "未命名一页": "Untitled slide",
  "还没有要点": "No bullets yet",
  "页": "slides",
  "演示稿请求失败": "Presentation request failed",
  "保存失败": "Could not save",
  "缺少项目": "Missing project",
  "至少保留一页": "Keep at least one slide",
  "写幻灯片大纲，预览并导出 JSON。": "Write slide outlines, preview them, and export JSON.",
  "删除这份演示稿？": "Delete this deck?",
  "已导出": "Exported",
  "还没有说明": "No description yet",
};
