import type { Clock, IdFactory } from "../../domain/kernel/identity.js";
import type { RuntimeModel } from "../../domain/kernel/ports.js";
import type { SqliteActivityRepository } from "../db/activity-repository.js";
import type { SqliteCalibrationRepository } from "../db/calibration-repository.js";
import type { SqliteConversationRepository } from "../db/conversation-repository.js";
import type { SqliteDecisionRepository } from "../db/decision-repository.js";
import type { SqliteDirectionRepository } from "../db/direction-repository.js";
import type { SqliteExplorationRepository } from "../db/exploration-repository.js";
import type { SqliteIdeaRepository } from "../db/idea-repository.js";
import type { SqliteMemoryRepository } from "../db/memory-repository.js";
import type { SqlitePulseRepository } from "../db/pulse-repository.js";
import type { SqliteResearchRepository } from "../db/research-repository.js";
import type { SqliteJobRunner } from "../jobs/sqlite-job-runner.js";
import type { RuntimeSelector } from "../runtime/runtime-selector.js";
import type { LocalSecurityOptions } from "../security/local-session.js";
import type { createCalibrationMemoryService } from "../services/calibration-memory.js";
import type { CancelLensRun } from "../services/cancel-lens-run.js";
import type { CreateExploration } from "../services/create-exploration.js";
import type { CreateResearchPlan } from "../services/create-research-plan.js";
import type { DecisionWorkspaceService } from "../services/decision-workspace.js";
import type { GetResearchWorkspace } from "../services/get-research-workspace.js";
import type { IdeaCardActions } from "../services/idea-card-actions.js";
import type { OpportunityActions } from "../services/opportunity-actions.js";
import type { StartLensRun } from "../services/start-lens-run.js";
import type { StartPulseRun } from "../services/start-pulse-run.js";
import type { WorkspaceExportService } from "../services/workspace-export.js";

import type { WorkReuseService } from "../../../work-reuse/service.js";

export interface ApiDependencies {
  workReuse: WorkReuseService;
  workspaceId: string;
  actorId: string;
  workspaceName?: string;
  actorName?: string;
  clock: Clock;
  idFactory: IdFactory;
  activity: SqliteActivityRepository;
  calibration: SqliteCalibrationRepository;
  directions: SqliteDirectionRepository;
  conversations: SqliteConversationRepository;
  decisions: SqliteDecisionRepository;
  explorations: SqliteExplorationRepository;
  ideas: SqliteIdeaRepository;
  memory: SqliteMemoryRepository;
  pulse: SqlitePulseRepository;
  research: SqliteResearchRepository;
  jobs: SqliteJobRunner;
  ideaCardActions: IdeaCardActions;
  createExploration: CreateExploration;
  listRuntimeModels(): Promise<readonly RuntimeModel[]>;
  createResearchPlan: CreateResearchPlan;
  startLensRun: StartLensRun;
  cancelLensRun: CancelLensRun;
  getResearchWorkspace: GetResearchWorkspace;
  decisionWorkspace: DecisionWorkspaceService;
  startPulseRun: StartPulseRun;
  opportunityActions: OpportunityActions;
  calibrationMemory: ReturnType<typeof createCalibrationMemoryService>;
  runtimeSettings: RuntimeSelector;
  workspaceExport: WorkspaceExportService;
  localSecurity?: LocalSecurityOptions;
}
