export const FEED_EN: Record<string, string> = {
  "管理 AI 连接": "Manage AI connection",
  "返回消息": "Back to messages",
  "AI 会按这段描述判断消息；试跑使用已配置的 Functions 服务。": "AI evaluates messages using this description and your configured Functions service.",
  "AI 判断还未连接。请在 Connectors 配置 TypeSafe，并在 Functions 选择该连接；当前输入已保留。": "AI is not connected. Add TypeSafe in Connectors, then select it in Functions. Your input is saved.",
  "GitHub 仓库": "GitHub repository",
  "{count} 条消息": "{count} messages",
  "{count} 项": "{count} items",
  "什么样的消息值得关注？": "Which messages deserve attention?",
  "仅建议，手动处理": "Suggest for manual review",
  "使用已发布的判断规则，仍可在这里预览结果。": "Reuse a published rule and preview its results here.",
  "例如：bug": "e.g. bug",
  "例如：用户反馈无法登录、付款失败或数据丢失；忽略日常通知和推广。": "e.g. Reports of login problems, failed payments, or lost data. Ignore routine updates and promotions.",
  "例如：需要跟进的产品反馈": "e.g. Product feedback to follow up",
  "保存后请立即拉取验证。": "Pull messages after saving to verify the source.",
  "保存来源资料": "Save source details",
  "保留的消息": "Saved messages",
  "先描述你想捕捉什么消息。": "Describe the messages you want to capture first.",
  "全部消息": "All messages",
  "关注的内容，在这里汇集。": "Updates from the sources you follow.",
  "关键词": "Keyword",
  "列表更新失败，当前输入已保留，请重试。": "Could not refresh the list. Your input is saved; please retry.",
  "判断": "Evaluation",
  "匹配方式": "Match by",
  "告诉 Feed 什么值得关注，先看看会捕捉哪些消息。": "Describe what matters, then preview which messages match.",
  "填写一个关键词，再预览匹配结果。": "Enter a keyword to preview matching messages.",
  "处理已有消息": "Apply to existing messages",
  "复用规则": "Reuse a rule",
  "对最近 20 条消息运行当前规则": "Run current rules on the latest 20 messages",
  "将当前已启用规则应用到最近 20 条消息，可能写入 Inbox。": "Apply enabled rules to the latest 20 messages. This may add items to Inbox.",
  "已有捕捉规则": "Capture rules",
  "我的来源": "My sources",
  "所有来源的最新内容": "Latest updates from all sources",
  "手动加入 Inbox": "Add to Inbox manually",
  "拉取计划单独保存，修改后从下次拉取起生效。": "Save the pull schedule separately. Changes apply to the next pull.",
  "按完整关键词匹配标题、摘要、标签和正文。": "Match this phrase in the title, summary, tags, or body.",
  "搜索消息": "Search messages",
  "新增捕捉规则": "New capture rule",
  "无法更新 Feed 列表": "Could not refresh Feed",
  "最近 {count} 条消息的预览": "Preview of the latest {count} messages",
  "来源工作区": "Source workspace",
  "来源捕捉规则": "Source capture rule",
  "来源设置": "Source settings",
  "没有符合当前条件的消息": "No messages match these filters",
  "消息": "Messages",
  "消息包含": "Message contains",
  "添加一个来源，开始收集消息": "Add a source to start collecting messages",
  "添加真实来源后，即可试跑和保存规则。": "Add a source to preview and save rules.",
  "用自然语言描述": "Describe in words",
  "研究来源 id": "Research source ID",
  "符合条件的消息会保存精确版本，你可以决定是否自动加入 Inbox。": "Matching messages are saved as exact versions. Choose whether to add them to Inbox automatically.",
  "筛选后自动入 Inbox": "Automatically add matches to Inbox",
  "规则已启用，将处理新消息和更新。": "Rule enabled for new and updated messages.",
  "规则操作失败，输入已保留，请重试。": "The rule could not be processed. Your input is saved; please retry.",
  "请先用当前描述预览，再保存并启用。": "Preview your current description before saving and enabling the rule.",
  "请选择一条已发布规则。": "Choose a published rule.",
  "读取已发布研究，保留原始链接、版本和使用限制。私有仓库使用本机 Git 登录。": "Read published research with original links, versions, and usage limits. Private repositories use local Git credentials.",
  "还没有可预览的消息。先拉取来源内容，再试一次。": "No messages to preview yet. Pull this source, then try again.",
  "还没有捕捉规则。在下方直接添加，无需离开 Feed。": "No capture rules yet. Add one below, right here in Feed.",
  "还没有消息，拉取后会出现在这里": "Messages will appear here after the first pull",
  "这个任务已不可用，请刷新后查看。": "This source is no longer available. Refresh to continue.",
  "这里展示模拟运行记录，不会启动后台任务。": "These are sample runs. No background task will start.",
  "选择来源": "Choose a source",
  "预览不会入箱；启用后只处理新消息和更新。": "Preview leaves Inbox unchanged. Enabled rules apply to new and updated messages.",
  "预览完成，未改变消息或 Inbox。": "Preview complete. Messages and Inbox are unchanged.",
  "预览最近消息": "Preview recent messages",
  "正在预览最近的消息…": "Previewing recent messages…",
  "正在保存规则…": "Saving rule…",
  "匹配": "Matches",
  "不匹配": "Does not match",
  "还没有来源": "No sources yet",
  "这个来源还没有消息": "No messages from this source yet",
  "选择你想关注的内容来源。": "Choose a source to follow.",
  "添加后可设置拉取计划与捕捉规则。": "After adding a source, set its pull schedule and capture rules.",
  "在这里写规则、预览，再决定哪些消息进入 Inbox。": "Write and preview rules here, then choose which messages reach Inbox.",
  "管理来源内容、拉取频率和连接状态。": "Manage source details, pull frequency, and connection status.",
  "来源资料已保存": "Source details saved",
  "保存并启用": "Save and enable",
  "使用的账号连接": "Account connection",
  "正在读取账号连接…": "Loading account connections…",
  "账号授权由 Connectors 统一管理，这里选择要使用的连接。": "Connectors manages authorization. Choose the connection to use here.",
  "无法读取账号连接，请重试。": "Could not load account connections. Please retry.",
  "原连接已不可用，请重新选择或前往 Connectors": "The previous connection is unavailable. Choose another or open Connectors.",
  "请选择账号连接": "Choose an account connection",
  "更换账号会创建独立来源并暂停旧来源，原消息会保留。": "Switching accounts creates a separate source and pauses the old one. Existing messages are kept.",
  "还没有账号连接，请先在 Connectors 添加。": "No account connections yet. Add one in Connectors first.",
  "暂停来源": "Pause source",
  "恢复来源": "Resume source",
  "移除来源": "Remove source",
  "该来源的全部新消息": "All new messages from this source",
  "来源资料已保存。": "Source details saved."
};
