/** English for the Todo surface; Chinese strings are the keys. Placeholders ({title}, {count}, {view}, {y}, {m}, {d}) stay as written. */
export const TODO_EN: Readonly<Record<string, string>> = {
  "待办": "Todo",
  "待办视图": "Todo views",
  "搜索待办": "Search todos",
  "也显示其他项目的待办": "Also show other projects' todos",
  "所有项目": "All projects",
  "记下一件事": "Write down a todo",
  "记下一件事，例如：周四前给王总回电话": "Write down a todo, e.g. call Wang back by Thursday",
  "放在": "Put in",
  "记下": "Add",
  "撤销": "Undo",
  "批量处理": "Batch changes",
  "完成": "Complete",
  "推后一天": "Push back a day",
  "安排到今天": "Plan for today",
  "取消安排": "Unplan",
  "移到": "Move to",
  "归档": "Archive",
  "取消选择": "Clear selection",
  "返回待办列表": "Back to todos",
  "更多操作": "More actions",
  "更多": "More",
  "重新读取": "Reload",
  "删除": "Delete",
  "要做什么": "What to do",
  "状态": "Status",
  "在等谁": "Waiting on",
  "例如：小李": "e.g. Li",
  "等什么": "Waiting for",
  "例如：确认预算": "e.g. budget sign-off",
  "打算哪天跟进": "Follow up on",
  "截止日期": "Due date",
  "最晚什么时候必须完成": "Latest date it must be done",
  "截止时间": "Due time",
  "可不填，不填就是全天": "Optional; empty means all day",
  "计划处理日期": "Planned date",
  "你打算哪天做": "The day you plan to do it",
  "提醒时间": "Reminder",
  "什么时候提醒你": "When to remind you",
  "提醒只在 Molis Work 打开时出现；关着应用时不会按时提醒，打开后会补一条。": "Reminders appear only while Molis Work is open. While it is closed nothing fires on time; you get one catch-up reminder when you open it.",
  "重要": "Important",
  "说明": "Notes",
  "补充细节、背景、下一步": "Details, background, next step",
  "来源与形成原因": "Source and why it is a todo",
  "关联": "Links",
  "选一件待办": "Choose a todo",
  "关系": "Relation",
  "要等它先完成": "Waits for it",
  "它在等这件": "It waits for this",
  "相关": "Related",
  "修改记录": "History",
  "取消": "Cancel",
  "待处理": "To do",
  "进行中": "In progress",
  "等待他人": "Waiting on others",
  "已完成": "Done",
  "已取消": "Cancelled",
  "个人": "Personal",
  "这个项目": "This project",
  "暂未归类": "Not placed yet",
  "已逾期": "Overdue",
  "今天截止": "Due today",
  "计划日已过": "Planned day passed",
  "很久没动": "Untouched for a while",
  "今天没有要处理的事": "Nothing for today",
  "有截止日期、计划今天做或正在做的事会出现在这里。": "Todos due today, planned for today or in progress show up here.",
  "没有在等别人的事": "Not waiting on anyone",
  "把一件事的状态改成“等待他人”，写上等谁、等什么。": "Set a todo to “Waiting on others” and note who and what you are waiting for.",
  "每件事都有安排了": "Everything is scheduled",
  "没有日期的新事项会先放在这里，有空时再安排。": "New todos without a date land here until you schedule them.",
  "未来 7 天没有截止的事": "Nothing due in the next 7 days",
  "有截止日期的事会按日期出现在这里。": "Todos with a due date appear here by date.",
  "还没有待办": "No todos yet",
  "在上面记下一件事，例如“周四前给王总回电话”。": "Write one down above, e.g. “call Wang back by Thursday”.",
  "还没有完成的事": "Nothing completed yet",
  "完成或取消的事会留在这里，可以重新打开。": "Completed or cancelled todos stay here and can be reopened.",
  "没有找到": "No matches",
  "换个词，或者到“全部”里看看。": "Try other words, or look in “All”.",
  "周日": "Sun",
  "周一": "Mon",
  "周二": "Tue",
  "周三": "Wed",
  "周四": "Thu",
  "周五": "Fri",
  "周六": "Sat",
  "待办请求失败": "The todo request failed",
  "今天": "Today",
  "明天": "Tomorrow",
  "昨天": "Yesterday",
  "{m}月{d}日": "{m}/{d}",
  "{y}年{m}月{d}日": "{m}/{d}/{y}",
  "帮我推进这件事": "Help me move this forward",
  "帮我推进这件待办": "Help me move this todo forward",
  "拆成几步": "Break it into steps",
  "把这件待办拆成几个可以直接做的步骤": "Break this todo into steps I can do right away",
  "整理材料里要做的事": "Find todos in materials",
  "帮我整理这些材料里需要我做的事": "Find what I need to do in these materials",
  "看看有没有遗漏": "Check for missed todos",
  "看看最近有没有遗漏的待办": "Check whether I missed any todos recently",
  "其他项目": "Other projects",
  "截止": "Due",
  "计划": "Planned",
  "提醒": "Remind",
  "原文：": "As written: ",
  "不按这个日期": "Ignore this date",
  "关着应用时不会按时提醒": "No reminder fires while the app is closed",
  "等待中": "Waiting",
  "未安排": "Unscheduled",
  "即将到期": "Upcoming",
  "全部": "All",
  "，在“{view}”里": " (in “{view}”)",
  "已记下「{title}」": "Added “{title}”",
  "没记下，请再试一次": "Not added. Please try again",
  "找到 {count} 件": "{count} found",
  "{count} 件已逾期": "{count} overdue",
  "{count} 件今天截止": "{count} due today",
  "，其中 {count} 件还在等别人": ", {count} of them still waiting on others",
  "{count} 件计划今天做或正在做": "{count} planned for today or in progress",
  "在等 {count} 件事": "Waiting on {count}",
  "，{count} 件到了约定的跟进日": ", {count} reached the agreed follow-up day",
  "{count} 件还没有日期，有空时安排一下": "{count} without a date; schedule them when you can",
  "未来 7 天有 {count} 件截止": "{count} due in the next 7 days",
  "计划日已过，重新安排一下": "Planned day passed; reschedule",
  "在等": "Waiting on",
  "跟进": " follow-up",
  "选中「{title}」": "Select “{title}”",
  "重新打开「{title}」": "Reopen “{title}”",
  "完成「{title}」": "Complete “{title}”",
  "已选 {count} 件": "{count} selected",
  "保存中": "Saving",
  "尚未保存": "Not saved yet",
  "手动": "Manual",
  "材料": "Material",
  "助理": "Assistant",
  "开始使用时": "Getting started",
  "拆分自": "Split from",
  "合并自": "Merged from",
  "已完成的动作": "Done",
  "草稿": "Draft",
  "助理工作": "Assistant work",
  "在等这件": "Waits for this",
  "还没有关联。": "No links yet.",
  "去掉这项关联": "Remove this link",
  "标题": "Title",
  "计划日期": "Planned date",
  "归属": "Placement",
  "等待": "Waiting",
  "你": "You",
  "其他入口": "Another client",
  "创建": " created it",
  "改为": " set it to ",
  "取回": "Restore",
  "关联了「{title}」": " linked “{title}”",
  "去掉了一项关联": " removed a link",
  "撤销了一次修改": " undid a change",
  "改了": " changed",
  "（已撤销）": " (undone)",
  "撤销创建": "Undo create",
  "完成或取消后才能归档": "Only completed or cancelled todos can be archived",
  "标题不能是空的": "The title cannot be empty",
  "这件待办已在别处修改，你的输入还在。复制需要保留的内容后点“更多 → 重新读取”。": "This todo changed elsewhere. Your input is kept; copy what you need, then choose More → Reload.",
  "已完成「{title}」": "Completed “{title}”",
  "已重新打开「{title}」": "Reopened “{title}”",
  "「{title}」已改为": "“{title}” is now ",
  "已撤销": "Undone",
  "已完成 {count} 件": "Completed {count}",
  "已把 {count} 件推后一天": "Pushed {count} back a day",
  "已把 {count} 件安排到今天": "Planned {count} for today",
  "已取消 {count} 件的计划日期": "Cleared the planned date of {count}",
  "已归档 {count} 件": "Archived {count}",
  "已把 {count} 件移到": "Moved {count} to ",
  "已移到": "Moved to ",
  "已撤销创建": "Creation undone",
  "先选一件待办": "Choose a todo first",
  "已归档": "Archived",
  "已取回": "Restored",
  "重新读取会丢掉还没保存的输入。继续吗？": "Reloading discards unsaved input. Continue?",
  "永久删除「{title}」？删除后不能撤销，修改记录也会一起删掉。": "Delete “{title}” permanently? This cannot be undone, and its history goes with it.",
  "已删除「{title}」": "Deleted “{title}”",
  "助理刚改过这件待办；你还有没保存的输入，保存时会提示冲突，不会覆盖。": "The Assistant just changed this todo. You have unsaved input; saving will report the conflict instead of overwriting.",
  "待办没打开，请刷新再试": "Todo did not open. Refresh and try again",
  "到了时间的提醒": "Reminders due",
  "错过了 {count} 条提醒（当时应用没打开）": "{count} reminders missed while the app was closed",
  "错过：": "Missed: ",
  "15 分钟后": "In 15 minutes",
  "1 小时后": "In 1 hour",
  "今晚 20:00": "Tonight 20:00",
  "明早 9:00": "Tomorrow 9:00",
  "稍后": "Later",
  "知道了": "Got it",
  "关闭提醒": "Turn off reminder",
  "会在 {time} 再提醒「{title}」": "Will remind “{title}” again {time}",
  "已关闭「{title}」的提醒": "Reminder for “{title}” turned off",
};
